### ISSUE TITLE
`ls **/*` command is not streaming

### ISSUE THREAD

**Issue by wmstack** [nushell/nushell#6174] opened 2022-07-28 22:13 UTC
### Describe the bug

The command above does not stream a table of output to autoview, but the user must keep waiting around until the table is fully complete. That is a downgrade from a shell like bash, where you don't have to wait for all the data to finish loading before you can read it.

### How to reproduce

1. Open a relatively large directory
2. Open Nushell and type `ls **/*`
3. You have to wait for a period of time before you see anything

### Expected behavior

I expected the `ls **/*` command to stream output as advertised in the README. However, it doesn't stream output for large files and the user is stuck without even a progress bar.

### Screenshots

![image](https://user-images.githubusercontent.com/58462210/181645833-49e9074d-878e-4888-b739-5d06d1ded7c0.png)

It almost feels frozen for a long time. It should output a table that keeps updating, rather than this lazy stream. Also if you pipe to `fzf`, you have to wait for the stream to complete before you see any file.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-28 23:20:39 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |                                          |

### Additional context

This isn't scalable. If the user happens to be in the home directory, it could take longer than a minute for anything to appear at all. It really takes a disproportionately large period of time.

Autoview should be smart. It should page the table when it finally arrives and should keep it to a consistent width. Commands like `fzf` should recieve a list of increasing size, but shouldn't make you have to wait to start searching.

**Comment by kubouch** [comment] 2022-07-29 07:08
Does it still happen? We reverted the `ls` changes that likely caused this.

**Comment by wmstack** [comment] 2022-07-29 07:10
Yup, I reported it today, and it happened today. `0.66.1` is the latest version right?

**Comment by kubouch** [comment] 2022-07-29 07:10
`0.66.2`, we made another hotfix.

**Comment by wmstack** [comment] 2022-07-29 07:12
Hmm, I wouldn't be able to run it right now, because it would need to trickle down into scoop. I have installed ripgrep as `rg --files` kind of does the streaming as I want anyway. Still, would love some polish on nushell.

**Comment by kubouch** [comment] 2022-07-29 07:25
On my end, running `ls **/*` streams while previously, it did the waiting. So it seems to me the issues is solved.

And yes, `to text` collects the stream.

I'll close this issue then but we can discuss the stream collecting in general in another issue (maybe there is one already).

**Comment by wmstack** [comment] 2022-07-29 07:31
`ls` *is* streaming when I do it from my desktop, but when I do it for the home directory, it is frozen:

![image](https://user-images.githubusercontent.com/58462210/181707486-7385d9c6-e5fb-4149-996d-905be7c56b60.png)

**Comment by wmstack** [comment] 2022-07-29 07:57
@kubouch is there a chance that the starting performance for large directories such as the home directory might be improved?

**Comment by kubouch** [comment] 2022-07-29 08:05
I'm not sure why you're seeing the 40s pause. For me on Linux, it starts streaming immediately. I'll reopen this until we find a cause of this.

Can you update the version in the issue description to the `0.66.2`?

**Comment by wmstack** [comment] 2022-07-29 08:08
It is odd that `scoop` says I have version `0.66.2` while `version` outputs `0.66.3` :)

**Comment by kubouch** [comment] 2022-07-30 15:57
Yeah, somehow the versions got messed up with the recent hotfixes. 0.67.0 comes 16th of August so that's when the versions should match again, at the latest.

**Comment by rgwood** [comment] 2022-12-09 01:17
FWIW I can't reproduce this (v0.72, Linux, a few different machines).

Nu currently streams in pages of 1000 records each, so maybe it's getting stuck somewhere in your first 1000 files...

**Comment by rgwood** [comment] 2022-12-09 01:46
OK, I can reproduce this on Windows - there is a delay of 5-10s before getting any results from `ls **/*` when called in my home directory. If I profile `nu -c "cd ~; ls **/* | first 20"` in Superluminal, I can see that a tremendous amount of time is spent in `std::sys::windows::fs::metadata`:

![image](https://user-images.githubusercontent.com/26268125/206603806-5a894e5c-a8e4-4750-a64e-5494c0d39644.png)

From what I can tell, Nu is spending that time gathering file metadata for a _lot_ of files instead of just the first 20. This doesn't quite fit my understanding of how Nu's iterators/streams work, so my understanding of them is probably wrong.

**Comment by rgwood** [comment] 2022-12-09 03:08
Alright, my current rough understanding:

- for a pattern like `**/*`, `nu_glob` can look at _many_ files before returning a result
- for each of those files, `nu_glob` needs to check file metadata using `fs::metadata`
- that file metadata call is relatively slow on Windows (as expected)

Not easy to improve without a deep dive into the globbing code. I'm going to leave this here for now.

**Comment by cosineblast** [comment] 2024-12-18 16:49
I can note a smaller-scale version of this problem even on linux. Having more than 90k files in a directory makes so that `ls **/*` takes at least 500 milliseconds to produce any results.

![image](https://github.com/user-attachments/assets/16b93089-f9ab-40a5-a3c0-8dc184814aa4)

Although it takes less than one-second, it is still annoying with things like `fzf`, specially since the cold start scales linearly with the number of files under your home directory.

**Closed** 2024-12-25 13:36 UTC
Labels: delight, polish, performance, streaming, glob-expansion
