### ISSUE TITLE
find NOT returning correct bytes

### ISSUE THREAD

**Issue by st-clair-clarke** [nushell/nushell#6939] opened 2022-10-29 11:48 UTC
### Describe the bug

[1 5 3kb 4 3Mb] | find 5 3kb

...gives the following result  (2.9KiB instead of 3kb)

![image](https://user-images.githubusercontent.com/3227590/198829358-1b1bb623-2f9b-4dd1-8ea9-060d3429e5f6.png)

### How to reproduce

run [`1 5 3kb 4 3Mb] | find 5 3kb` in the console

### Expected behavior

3Kb instead of 2.9KiB

### Screenshots

![image](https://user-images.githubusercontent.com/3227590/198829489-affeb20b-4316-493e-86de-3f26c0590af2.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0                                    |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:13:36 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by webbedspace** [comment] 2022-10-29 11:58
I notice this is from the Linux build. Please run `config nu` and report the value of `filesize_format` and `filesize_metric`.

**Comment by st-clair-clarke** [comment] 2022-10-29 12:14
filesize_metric: false
filesize_format: "auto" # b, kb, kib, mb, mib, gb, gib, tb, tib, pb, pib, eb, eib, zb, zib, auto

**Comment by webbedspace** [comment] 2022-10-29 12:21
OK, so, if `filesize_metric` is false, then KB values will be converted to KiB values, which is the Windows standard instead of the ISO standard. The ISO standard is also called "metric" because it goes up in increments of 1000. See the table below. 

![image](https://user-images.githubusercontent.com/83939/198831173-0bc7412d-2870-4f43-9179-c58998db4d1b.png)

**Comment by fdncred** [comment] 2022-10-29 12:29
dupe of https://github.com/nushell/nushell/issues/6533

**Comment by st-clair-clarke** [comment] 2022-10-29 12:36
Is there any current effort to correct this anamoly?

**Closed** 2023-08-09 23:11 UTC
Labels: type-system, inconsistent-behavior
