### ISSUE TITLE
`(ls | sort-by name)` and other subexpressions lose ls_colors

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4501] opened 2022-02-16 19:36 UTC
### Describe the bug

`alias ls = (ls | sort-by name)`
names are not colored with ls_colors

### How to reproduce

see above

### Expected behavior

retain ls_colors

### Configuration

|key|value|
|-|-|
|version|0.59.0|
|branch|main|
|short_commit|b64ac9eb|
|commit_hash|b64ac9eb7b8b32696618092f1144084b51d8a053|
|commit_date|2022-02-16 18:24:45 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.58.1 (db9d1b20b 2022-01-20)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.58.0 (f01b232bc 2022-01-19)|
|pkg_version|0.59.0|
|build_time|2022-02-16 12:33:29 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by jntrnr** [comment] 2022-02-16 19:39
I have a hunch. `(ls | sort-by name)` also loses it, so I suspect subexpression evaluation is to blame.

**Comment by jntrnr** [comment] 2022-02-16 19:41
Yup - `eval_subexpression` returns a PipelineData, which should be fine. The problem is here:

```
                eval_subexpression(engine_state, stack, block, PipelineData::new(expr.span))?
                    .into_value(expr.span),
```

The `.into_value` will convert `PipelineData` into a `Value`, and in doing so will lose the metadata

**Comment by fdncred** [comment] 2022-02-16 19:41
ya, you're right.. sometimes?
![image](https://user-images.githubusercontent.com/343840/154342908-2fb44505-267d-4f15-9c5a-8a921efe4bd4.png)

as an alias
![image](https://user-images.githubusercontent.com/343840/154342955-258c639b-7ec3-4ec5-b90c-1142f9034320.png)

i'm so confused
![image](https://user-images.githubusercontent.com/343840/154343000-683f747b-cb6a-43bf-aba5-61f83aee8150.png)

**Comment by jntrnr** [comment] 2022-02-16 19:42
Is that last image after you aliased `ls`?

**Comment by fdncred** [comment] 2022-02-16 19:43
> Is that last image after you aliased `ls`?

yup - i just put an EDIT above it to explain it.

**Comment by fdncred** [comment] 2022-02-17 11:20
> Yup - `eval_subexpression` returns a PipelineData, which should be fine. The problem is here:
> 
> ```
>                 eval_subexpression(engine_state, stack, block, PipelineData::new(expr.span))?
>                     .into_value(expr.span),
> ```
> 
> The `.into_value` will convert `PipelineData` into a `Value`, and in doing so will lose the metadata

I don't see where there is an available `pipelinedata.metdata` to use around here. The closest I could find would be maybe using `eval_expression_with_input()` which has an input with metadata. Am I missing something?

**Comment by naosense** [comment] 2022-11-08 23:19
What's the status of this issue?

**Comment by fdncred** [comment] 2022-11-09 12:13
> What's the status of this issue?

it's still not fixed

**Comment by naosense** [comment] 2022-11-09 12:39
has any plan for this issue?

**Comment by fdncred** [comment] 2022-11-09 13:36
There are other priorities at the moment. We're always open to people making nushell better with PRs.

**Comment by naosense** [comment] 2022-11-10 01:30
I would like to help, but I'm afraid that this is beyond my current level. looks like it's not simple based on this thread

**Comment by amtoine** [comment] 2023-08-11 07:51
and `ls | sort-by name` does not :thinking:

**Comment by fdncred** [comment] 2023-08-11 11:55
> and `ls | sort-by name` does not 🤔

JT explains why here https://github.com/nushell/nushell/issues/4501#issuecomment-1042095330 - it would be so nice to have this fixed once and for all.

**Comment by izuzak** [comment] 2023-10-08 19:52
👋 I was encouraged in Discord to add a case I hit to this issue. 

- Output of `ls` shows both filenames and dates with color (`name` and `modified` columns)
- Output of `ls | reject ...` shows filenames without color (unexpected), but dates with color (expected)
- Output of `ls | move ...` shows both filenames and dates with color (both expected)

![Image](https://github.com/nushell/nushell/assets/38924/59054e46-c578-4be8-b1b9-77af0f290e83)

**Comment by stroborobo** [comment] 2024-04-12 17:00
Seems like this is fixed in 0.92.

**Comment by fdncred** [comment] 2024-04-12 18:46
> Seems like this is fixed in 0.92.

Not all of it, you can't even do the alias that I originally mentioned anymore. However, nushell has got better about passing metadata around which affects the highlighting.

**Comment by stroborobo** [comment] 2024-04-12 19:13
Fair, the nature of aliases changed since that time (#8123), so does it really matter? I thought this issue was about pipelining in subexpressions loosing color metadata.

I'm just happy it's working now, so thanks <3

**Comment by fdncred** [comment] 2024-04-12 19:34
It's better but it's not complete. I saw one the other day that was still broken and made me think we need to have a `metadata set` command.

**Comment by sholderbach** [comment] 2024-08-15 21:12
I consider this closed by #11160 and some of @IanManske's related efforts (e.g. #12848 ).

Open issues listing specific commands that cause issues if necessary.

**Closed by sholderbach** 2024-08-15 21:12 UTC
Labels: :bug:  bug, pipeline-metadata
