### ISSUE TITLE
Panic on invalid syntax

### ISSUE THREAD

**Issue by marekdedic** [nushell/nushell#454] opened 2019-08-26 12:01 UTC
```shell
/home/user> ls | where type == Directory and acessd < 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShellError { error: CoerceError { left: Tagged { tag: Tag { origin: None, span: Span { start: 33, end: 39 } }, item: "string" }, right: Tagged { tag: Tag { origin: None, span: Span { start: 42, end: 43 } }, item: "int" } }, cause: None }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Followed by a crash of the shell...

I fully realize that the command is invalid (I was playing around with nushell), but I expected an error message, not a panic.

**Comment by marekdedic** [comment] 2019-08-26 12:03
with `RUST_BACKTRACE=full`:
```shell
/home/user> ls | where type == Directory and acessd < 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShellError { error: CoerceError { left: Tagged { tag: Tag { origin: None, span: Span { start: 33, end: 39 } }, item: "string" }, right: Tagged { tag: Tag { origin: None, span: Span { start: 42, end: 43 } }, item: "int" } }, cause: None }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x5624f3d16882 - backtrace::backtrace::libunwind::trace::h0ac7f7550b32014d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x5624f3d16882 - backtrace::backtrace::trace_unsynchronized::h484f421aa64dd633
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x5624f3d16882 - std::sys_common::backtrace::_print::hcee6c7a382e03f01
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5624f3d16882 - std::sys_common::backtrace::print::h0f722630cb440d0d
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5624f3d16882 - std::panicking::default_hook::{{closure}}::haf1afcc8aebb7f00
                               at src/libstd/panicking.rs:200
   5:     0x5624f3d16566 - std::panicking::default_hook::h548c46b20f9036e2
                               at src/libstd/panicking.rs:214
   6:     0x5624f3d16fd5 - std::panicking::rust_panic_with_hook::h2e01ca08bfa50f6c
                               at src/libstd/panicking.rs:477
   7:     0x5624f3d16b72 - std::panicking::continue_panic_fmt::h89ac412ecc105abb
                               at src/libstd/panicking.rs:384
   8:     0x5624f3d16a66 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5624f3d38bca - core::panicking::panic_fmt::hc72bd3ff9f8b21ef
                               at src/libcore/panicking.rs:85
  10:     0x5624f3d38cc7 - core::result::unwrap_failed::h8fe51b7d2d9e1a4f
                               at src/libcore/result.rs:1084
  11:     0x5624f385fce7 - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h8613fef0a3978665
  12:     0x5624f37c5bfd - <futures_util::stream::flatten::Flatten<St> as futures_core::stream::Stream>::poll_next::hbb4fc7c881a90f5e
  13:     0x5624f385ef55 - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h4c18b5503ee8094d
  14:     0x5624f3782b45 - std::future::poll_with_tls_context::h2d7298286dcde6aa
  15:     0x5624f37815ea - nu::cli::cli::{{closure}}::h8e6e7b0dd51451cf
  16:     0x5624f3767c78 - futures_executor::local_pool::block_on::hacc7c2e7bebd447b
  17:     0x5624f376fa0c - nu::main::he63059cf806f3eba
  18:     0x5624f3773b67 - std::rt::lang_start::{{closure}}::h5eb55eb3468f6e02
  19:     0x5624f3d16a03 - std::rt::lang_start_internal::{{closure}}::he0d59d62c6efe2b1
                               at src/libstd/rt.rs:49
  20:     0x5624f3d16a03 - std::panicking::try::do_call::h113a0035ae721173
                               at src/libstd/panicking.rs:296
  21:     0x5624f3d207ea - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  22:     0x5624f3d1758d - std::panicking::try::h8e15018af0cd855a
                               at src/libstd/panicking.rs:275
  23:     0x5624f3d1758d - std::panic::catch_unwind::heaa443b6ed829eda
                               at src/libstd/panic.rs:394
  24:     0x5624f3d1758d - std::rt::lang_start_internal::h8629e458a9174fd0
                               at src/libstd/rt.rs:48
  25:     0x5624f376fb52 - main
  26:     0x7f8b209ac09b - __libc_start_main
  27:     0x5624f375a65a - _start
  28:                0x0 - <unknown>

```

**Comment by Akito13** [comment] 2019-08-26 15:16
https://github.com/nushell/nushell/issues/438

**Comment by jorpic** [comment] 2019-08-27 16:19
I can't reproduce this with the current [HEAD](https://github.com/nushell/nushell/commit/f59b78a7649a11973940d5eef59dfc17e3846efc) (seems it was fixed in https://github.com/nushell/nushell/commit/efd9631a9081a5c1669c4ec1d133c59e0eefecc0) but behavoir is still incorrect.

All good, error message:
```
/home/user/t/nushell(HEAD)> ls | where name == 1 and type == Directory
error: Could not evaluate (CoerceError)
- shell:1:11
1 | ls | where name == 1 and type == Directory
  |            ^^^^^^^^^ could not evaluate
```

This is incorrect, error is silently ignored:

```
/home/user/t/nushell(HEAD)> ls | where type == Directory and name == 1
━━━┯━━━━━━━━┯━━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━┯━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━
 # │ name   │ type      │ readonly │ size   │ accessed       │ modified
───┼────────┼───────────┼──────────┼────────┼────────────────┼───────────────
 0 │ .git   │ Directory │          │ 372 B  │ a day ago      │ 7 minutes ago
 1 │ .azure │ Directory │          │  38 B  │ 41 minutes ago │ 7 minutes ago
 2 │ .cargo │ Directory │          │  12 B  │ 2 hours ago    │ a day ago
 3 │ assets │ Directory │          │  44 B  │ 2 hours ago    │ a day ago
 4 │ docs   │ Directory │          │  26 B  │ 2 hours ago    │ a day ago
 5 │ images │ Directory │          │ 100 B  │ 41 minutes ago │ 7 minutes ago
 6 │ src    │ Directory │          │ 380 B  │ 41 minutes ago │ 7 minutes ago
 7 │ tests  │ Directory │          │ 536 B  │ 7 minutes ago  │ 7 minutes ago
 8 │ target │ Directory │          │  42 B  │ an hour ago    │ a day ago
━━━┷━━━━━━━━┷━━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━┷━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━
```

**Comment by jorpic** [comment] 2019-08-27 19:32
It's not a panic anymore. It's incorrect behavior now.

**Comment by wycats** [comment] 2019-08-29 17:13
Thanks for all your work running this down.

The issue of making boolean and logic work is tracked in https://github.com/nushell/nushell/pull/502, with great progress by @mgattozzi. Closing!

**Closed by wycats** 2019-08-29 17:13 UTC
Labels: bug, parser
