### ISSUE TITLE
Some commands cannot be found when executing scripts

### ISSUE THREAD

**Issue by bugabinga** [nushell/nushell#3892] opened 2021-08-04 10:06 UTC
### Describe the bug

It seems that under some circumstances, nushell cannot find certain plugins.
In my experience these situations are: 
- running scripts via `nu <script>`
- running commands via `nu -c "..."`

The affected commands/plugins seem to be at least :
- sys
- ps
- xpath

### How to reproduce

Test files:

config_with_plugins.toml
```
startup = [
"let OS = (sys).host.name",
"let NAME = (build-string Peter Pan)",
"let SILLY_MEM = (sys | get mem | get free | into int) / (sys | get mem | get total | into int) * 100",
"let BIG_DOG = (ps | sort-by -r mem | first)",
"let BIG_CAT = (du -a | sort-by -r physical | first)",
"let ME = (random uuid)",
"let NOW = (date now)",
"let URL_HELP = (url -h)",
"let TAGS_HELP = (tags -h)",
"let XPATH_HELP = (xpath -h)"
]
```

hello.nu
```
echo "Hi There Traveler!"
echo (char newline)
echo "Welcome Home."
```

Run the following commands with above test files in current directory:

- `nu --config-file .\config_with_plugins.toml .\hello.nu`
```sh
error: Command not found
  ┌─ shell:1:11
  │
1 │ let OS = (sys).host.name
  │           ^^^ command sys not found

error: Command not found
  ┌─ shell:1:18
  │
1 │ let SILLY_MEM = (sys | get mem | get free | into int) / (sys | get mem | get total | into int) * 100
  │                  ^^^ command sys not found

error: Command not found
  ┌─ shell:1:16
  │
1 │ let BIG_DOG = (ps | sort-by -r mem | first)
  │                ^^ command ps not found

error: Command not found
  ┌─ shell:1:19
  │
1 │ let XPATH_HELP = (xpath -h)
  │                   ^^^^^ command xpath not found

Hi There Traveler!
Welcome Home.
```
- `nu --config-file .\config_with_plugins.toml -c "echo $ME"`
```sh
error: Command not found
  ┌─ shell:1:11
  │
1 │ let OS = (sys).host.name
  │           ^^^ command sys not found

error: Command not found
  ┌─ shell:1:18
  │
1 │ let SILLY_MEM = (sys | get mem | get free | into int) / (sys | get mem | get total | into int) * 100
  │                  ^^^ command sys not found

error: Command not found
  ┌─ shell:1:16
  │
1 │ let BIG_DOG = (ps | sort-by -r mem | first)
  │                ^^ command ps not found

error: Command not found
  ┌─ shell:1:19
  │
1 │ let XPATH_HELP = (xpath -h)
  │                   ^^^^^ command xpath not found

a6de4da6-0b3f-4087-8de4-bac34bd77221
```
- `nu --config-file .\config_with_plugins.toml`
```sh
Welcome to Nushell 0.35.0 (type 'help' for more info)
```

As you can see, the first two commands produce errors, while the third does not.

### Expected behavior

I expected all 3 commands to behave like the third.

### Configuration

version | pivot | to md
|Column0|Column1|
|-|-|
|version|0.35.0|
|build_os|windows-x86_64|
|rust_version|rustc 1.54.0 (a178d0322 2021-07-26)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.54.0 (5ae8d74b3 2021-06-22)|
|pkg_version|0.35.0|
|build_time|2021-08-04 10:11:37|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

Nushell was installed via `cargo install nu --features extra`.

**Comment by fdncred** [comment] 2021-08-04 13:57
I think this is because the plugins aren't registered at the time when the `nu -c` commands are executed.

I think this is where `nu -c` commands are executed.
https://github.com/nushell/nushell/blob/575c07c9c413be903dfb1a3748c8dab75c3e4edd/crates/nu-cli/src/app.rs#L190-L196

I think this is where the plugins are registered.
https://github.com/nushell/nushell/blob/575c07c9c413be903dfb1a3748c8dab75c3e4edd/crates/nu-cli/src/app.rs#L256-L258

I'm guessing we can move some things around to make this work but I'm not sure if they're in a particular order or not. Someone can try to move things around to see if it breaks. We just need to make sure all the timing comments are kept at the appropriate locations.

**Comment by fdncred** [comment] 2021-08-04 14:33
I tried swapping the order without much success.
```
c:\cartar\debug\nu --config-file .\config_with_plugins.toml             
error: random unexpected uuid
  ┌─ shell:1:18
  │
1 │ let ME = (random uuid)
  │                  ^^^^ unexpected argument (try random -h)

error: Command not found
  ┌─ shell:1:19
  │
1 │ let XPATH_HELP = (xpath -h)
  │                   ^^^^^ command xpath not found

Welcome to Nushell 0.35.0 (type 'help' for more info)
C:\Users\user\source\repos\forks\nushell(main)>
```
```
c:\cartar\debug\nu --config-file .\config_with_plugins.toml -c "echo me" 
error: Command not found
  ┌─ shell:1:11
  │
1 │ let OS = (sys).host.name
  │           ^^^ command sys not found

error: Command not found
  ┌─ shell:1:18
  │
1 │ let SILLY_MEM = (sys | get mem | get free | into int) / (sys | get mem | get total | into int) * 100
  │                  ^^^ command sys not found

error: Command not found
  ┌─ shell:1:16
  │
1 │ let BIG_DOG = (ps | sort-by -r mem | first)
  │                ^^ command ps not found

error: random unexpected uuid
  ┌─ shell:1:18
  │
1 │ let ME = (random uuid)
  │                  ^^^^ unexpected argument (try random -h)

error: Command not found
  ┌─ shell:1:19
  │
1 │ let XPATH_HELP = (xpath -h)
  │                   ^^^^^ command xpath not found

me
```
```
c:\cartar\debug\nu --config-file .\config_with_plugins.toml .\hello.nu
error: Command not found
  ┌─ shell:1:11
  │
1 │ let OS = (sys).host.name
  │           ^^^ command sys not found

error: Command not found
  ┌─ shell:1:18
  │
1 │ let SILLY_MEM = (sys | get mem | get free | into int) / (sys | get mem | get total | into int) * 100
  │                  ^^^ command sys not found

error: Command not found
  ┌─ shell:1:16
  │
1 │ let BIG_DOG = (ps | sort-by -r mem | first)
  │                ^^ command ps not found

error: random unexpected uuid
  ┌─ shell:1:18
  │
1 │ let ME = (random uuid)
  │                  ^^^^ unexpected argument (try random -h)

error: Command not found
  ┌─ shell:1:19
  │
1 │ let XPATH_HELP = (xpath -h)
  │                   ^^^^^ command xpath not found

Hi There Traveler!
Welcome Home.
```
so, i'm not sure how to make this work.

**Comment by andrasio** [comment] 2021-08-04 15:04
@bugabinga Sorry about that.

As a workaround. Try on `startup` in the first entry to add something like `nu plugin --load /path/to/plugins`.

**Comment by fdncred** [comment] 2021-08-04 15:18
oof - i forgot to compile with `--features=extra` so in my tests it wouldn't have found the plugins because they didn't exist. let me retry.

**Comment by fdncred** [comment] 2021-08-04 15:27
ok, my idea of reordering didn't make any difference even after i recompiled with --features=extra but @andrasio 's idea seemed to work for me, at least it didn't give any error messages.
```toml
startup = [
"nu plugin --load c:\\cartar\\debug",
"let OS = (sys).host.name",
"let NAME = (build-string Peter Pan)",
"let SILLY_MEM = (sys | get mem | get free | into int) / (sys | get mem | get total | into int) * 100",
"let BIG_DOG = (ps | sort-by -r mem | first)",
"let BIG_CAT = (du -a | sort-by -r physical | first)",
"let ME = (random uuid)",
"let NOW = (date now)",
"let URL_HELP = (url -h)",
"let TAGS_HELP = (tags -h)",
"let XPATH_HELP = (xpath -h)",
"build-string 'OS: ' $OS (char nl)"
]
```

**Comment by andrasio** [comment] 2021-08-04 16:13
I suggest the `nu plugin --load /path/to` entry be in the script directly though. If it's in `startup`, when you run `nu` normally, you'd been trying to load the plugins twice. The issue only manifests when using nu to run scripts.

`I don't think we ever supported loading plugins on scripts` 

Whether we should allow it or not it's a different topic (security concerns) that I'm not quite sure about right now.

**Comment by fdncred** [comment] 2021-08-04 21:06
ya @andrasio , i was surprised your original suggestion worked because it's running nu within nu, but it worked somehow. I agree, puttting the load plugin would help the hello.nu script but it wouldn't help the commands in startup.

**Comment by andrasio** [comment] 2021-08-04 21:21
@fdncred It does because `nu plugin` is an internal sub command.

**Comment by bugabinga** [comment] 2021-08-05 10:10
Thank you a lot for looking into this!
I was not aware of `nu plugin`, that is very helpful. 

> I suggest the `nu plugin --load /path/to` entry be in the script directly though. If it's in `startup`, when you run `nu` normally, you'd been trying to load the plugins twice. The issue only manifests when using nu to run scripts.

That will work if plugins are used in the script after the `nu plugin ...` call.
Plugins used in `startup` would still fail.
```sh
∽/nu_playground
>  cat .\config_with_sys_plugin.toml
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .\config_with_sys_plugin.toml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ startup = [ "let OS = (sys).host.name" ]
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

∽/nu_playground
>  cat .\hello_load_plugins.nu
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .\hello_load_plugins.nu
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # in my case, since nu was installed via cargo, the nu plugins in $CARGO_HOME/bin
   2   │ nu plugin --load (build-string $nu.env.CARGO_HOME / bin)
   3   │ echo "Welcome, have a nu ❤ ."
   4   │ echo (char newline)
   5   │ echo "The sys plugin here says your host OS is: "
   6   │ echo (sys).host.name
   7   │ echo (char newline)
   8   │
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

∽/nu_playground
>  nu --config-file .\config_with_sys_plugin.toml .\hello_load_plugins.nu
error: Command not found
  ┌─ shell:1:11
  │
1 │ let OS = (sys).host.name
  │           ^^^ command sys not found

Welcome, have a nu ❤ .
The sys plugin here says your host OS is: Windows

```

Also, don´t forget the case of running `nu --commands`.
If `startup` uses nu plugins, then `nu plugin --load ...` as a workaround in `startup` helps!
```sh
∽/nu_playground
>  nu --config-file .\config_with_sys_plugin.toml --commands "echo ___ $OS ___"
error: Command not found
  ┌─ shell:1:11
  │
1 │ let OS = (sys).host.name
  │           ^^^ command sys not found

error: Variable not in scope
  ┌─ shell:1:10
  │
1 │ echo ___ $OS ___
  │          ^^^ unknown variable: $OS

error: External command failed
   ┌─ shell:48:1
   │
48 │ nu --config-file .\config_with_sys_plugin.toml --commands "echo ___ $OS ___"
   │ ^^ command failed
```

> Whether we should allow it or not it's a different topic (security concerns) that I'm not quite sure about right now.

I do not really understand the security implications in this case, so I do not want to make claims either way.
However, in terms of consistency, I would expect one of two behaviours:

1. Never load nu plugins for scripts/commands (including `startup`). Load them only for interactive nu sessions.
1. Always load nu plugins.

Right now, nu plugins are sometimes loaded before `startup` script (interactive nu session) and sometimes not at all ( `--commands` and scripts).

---

For now, using `nu plugin --load ...` in `startup` is a good workaround for me.
Performance might suffer but I worry more about security.

Should I close this issue?

**Comment by bugabinga** [comment] 2021-08-05 10:24
For those curious about the perf hit:
```sh
∽/nu_playground
  cat .\config_empty.toml
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .\config_empty.toml   <EMPTY>
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

∽/nu_playground
  cat .\config_preload_nu_plugins.toml
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .\config_preload_nu_plugins.toml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ startup = [ "nu plugin --load (build-string $nu.env.CARGO_HOME / bin)"  ]
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

∽/nu_playground
  hyperfine "nu --config-file config_empty.toml" "nu --config-file config_preload_nu_plugins.toml"
Benchmark #1: nu --config-file config_empty.toml
  Time (mean ± σ):     860.6 ms ±   4.4 ms    [User: 4.0 ms, System: 7.6 ms]
  Range (min … max):   854.3 ms … 867.4 ms    10 runs

Benchmark #2: nu --config-file config_preload_nu_plugins.toml
  Time (mean ± σ):      1.015 s ±  0.040 s    [User: 2.7 ms, System: 16.1 ms]
  Range (min … max):    0.965 s …  1.066 s    10 runs

Summary
  'nu --config-file config_empty.toml' ran
    1.18 ± 0.05 times faster than 'nu --config-file config_preload_nu_plugins.toml'

∽/nu_playground
  nu --perf --config-file .\config_empty.toml
commands using -c at launch: 600ns
script file(s) passed in: 694.5µs
plugins registered: 734.109ms
config loaded: 1.2482ms
rustyline configuration: 1.019ms
history load: 704.4µs
load custom prompt: 465.3µs
Welcome to Nushell 0.35.0 (type 'help' for more info)
timing stopped. starting run loop: 774.8µs
C:\Users\okr\nu_playground> exit

∽/nu_playground
  nu --perf --config-file .\config_preload_nu_plugins.toml
commands using -c at launch: 700ns
script file(s) passed in: 713.3µs
plugins registered: 739.1474ms
config loaded: 112.544ms
rustyline configuration: 946µs
history load: 550.4µs
load custom prompt: 474.9µs
Welcome to Nushell 0.35.0 (type 'help' for more info)
timing stopped. starting run loop: 866.6µs
C:\Users\okr\nu_playground> exit
```

**Comment by yourealwaysbe** [comment] 2021-08-09 10:01
I have a similar problem but it is not fixed by loading the plugins in the startup file.

Config file:
```
startup = [
    "nu plugin -l /home/matt/.cargo/bin",
    "def opensql [file] { open $file | from sqlite }",
]
```

When running `nu -c "from -h"` the sqlite plugin is not found during startup, but is listed by `from -h`.

```
> nu -c "from -h"
error: from unexpected sqlite
  ┌─ shell:1:40
  │
1 │ def opensql [file] { open $file | from sqlite }
  │                                        ^^^^^^ unexpected argument (try from -h)

Parse content (string or binary) as a table (input format based on subcommand, like csv, ini, json, toml).

Usage:
  > from <subcommand> {flags} 

Subcommands:
  from bson - Convert from .bson binary into table
  from csv - Parse text as .csv and create table.
  from eml - Parse text as .eml and create table.
  from ics - Parse text as .ics and create table.
  from ini - Parse text as .ini and create table
  from json - Parse text as .json and create table.
  from mp4 - Get meta-data of mp4 file
  from ods - Parse OpenDocument Spreadsheet(.ods) data and create table.
  from sqlite - Convert from sqlite binary into table
  from ssv - Parse text as space-separated values and create a table. The default minimum number of spaces counted as a separator is 2.
  from toml - Parse text as .toml and create table.
  from tsv - Parse text as .tsv and create table.
  from url - Parse url-encoded string as a table.
  from vcf - Parse text as .vcf and create table.
  from xlsx - Parse binary Excel(.xlsx) data and create table.
  from xml - Parse text as .xml and create table.
  from yaml - Parse text as .yaml/.yml and create table.
  from yml - Parse text as .yaml/.yml and create table.

Flags:
  -h, --help: Display this help 
```

Version:

|Column0|Column1|
|-|-|
|version|0.35.0|
|branch|makepkg|
|short_commit|de71cbdd|
|commit_hash|de71cbdd43bc882a90b23de954ddf389e13424ad|
|commit_date|2021-08-07 18:57:32|
|build_os|linux-x86_64|
|rust_version|rustc 1.54.0|
|cargo_version|cargo 1.54.0|
|pkg_version|0.35.0|
|build_time|2021-08-09 10:39:29|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, which, zip|
|installed_plugins|fetch, match, post, ps, sys|

**Comment by fdncred** [comment] 2022-03-06 14:41
if this issue isn't reproducible in 0.59 we should probably close it. do you know how to reproduce the original error?

**Comment by jntrnr** [comment] 2022-03-09 10:28
Agreed - this works differently now and should work as expected once the plugins are registered.

**Closed by jntrnr** 2022-03-09 10:28 UTC
Labels: bug, 0.60

**Comment by adminy** [comment] 2023-10-10 21:16
```
/etc/nixos> clear                                                                                   10/10/23 21:16:35 PM
/nix/store/yi5aswh4a0mb82kbi0afr26j5ilsghjl-bash-interactive-5.2-p15/bin/sh: line 1: clear: command not found
/etc/nixos>                                                                                         10/10/23 21:16:37 PM
```
