### ISSUE TITLE
The size of directories is always 4.0 KiB

### ISSUE THREAD

**Issue by seongs1024** [nushell/nushell#6092] opened 2022-07-21 16:30 UTC
### Describe the bug

```
/home/user〉ls                    07/22/2022 01:14:45 AM
╭───┬────────────────┬──────┬─────────┬────────────╮
│ # │      name      │ type │  size   │  modified  │
├───┼────────────────┼──────┼─────────┼────────────┤
│ 0 │ README.md      │ file │    62 B │ 2 days ago │
│ 1 │ a_directory    │ dir  │ 4.0 KiB │ 2 days ago │
│ 2 │ another_dir    │ dir  │ 4.0 KiB │ 2 days ago │
│ 3 │ the_other_dir  │ dir  │ 4.0 KiB │ 2 days ago │
╰───┴────────────────┴──────┴─────────┴────────────╯ 
```

### How to reproduce

1. `ls`

### Expected behavior

Expected that the size of directories was more than 4.0 KiB

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.65.0                              |
| branch             |                                     | 
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |  
| build_target       | x86_64-unknown-linux-gnu            |  
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27) |                                                                                                                                    | rust_channel       | stable-x86_64-unknown-linux-gnu     |  
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08) |  
| pkg_version        | 0.65.0                              | 
| build_time         | 2022-07-15 01:31:11 +09:00          |
| build_rust_channel | release                             |         
| features           | default, trash, which, zip          |      
| installed_plugins  |                                     |

**Comment by jntrnr** [comment] 2022-07-21 16:33
This is the size reported by the operating system. If you run `ls -l` in Bash, you'll also see the 4k size.

**Comment by fdncred** [comment] 2022-07-21 17:05
more info here. dupe of #4080

**Closed by fdncred** 2022-07-21 17:05 UTC
