### ISSUE TITLE
Can't create a Span whose end < start while trying to auto-complete

### ISSUE THREAD

**Issue by jiripospisil** [nushell/nushell#8188] opened 2023-02-24 08:59 UTC
### Describe the bug

Nushell panics while trying to auto-complete a command.

### How to reproduce

1. Create an alias `alias l = ls -l`
2. Type `l |` and press tab.

```
thread 'main' panicked at 'Can't create a Span whose end < start, start=7, end=3', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/reedline-0.16.0/src/completion/base.rs:18:9
stack backtrace:
   0:        0x109f988ea - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc8ca9f73e36eafbe
   1:        0x1093b2c6a - core::fmt::write::h18f05dbaeab5c517
   2:        0x109f74cbc - std::io::Write::write_fmt::hd185f936516635e5
   3:        0x109f986d0 - std::sys_common::backtrace::print::hae2c1dab158bad7e
   4:        0x109f8ce83 - std::panicking::default_hook::{{closure}}::h1822f7e734921c5c
   5:        0x109f8cc16 - std::panicking::default_hook::hcf24b2925482f4ed
   6:        0x109f8d6a4 - std::panicking::rust_panic_with_hook::hea90e49b67f0dd80
   7:        0x109f98e35 - std::panicking::begin_panic_handler::{{closure}}::h441e09e11630fdf5
   8:        0x109f98a38 - std::sys_common::backtrace::__rust_end_short_backtrace::h5f47c9926b336c66
   9:        0x109f8d002 - _rust_begin_unwind
  10:        0x10a150ee3 - core::panicking::panic_fmt::hb71fe88fbeca9b67
  11:        0x109e27d1d - reedline::completion::base::Span::new::h84d407baea7d6a34
  12:        0x1094d3d09 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::hae30915ca2bf0a9f
  13:        0x109504fa2 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold::hba419194431baf8b
  14:        0x1094c3329 - alloc::vec::Vec<T,A>::extend_trusted::h43dd52aea628fbf5
  15:        0x1094c02d6 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h3908aae5deafa9b0
  16:        0x1094d80d7 - nu_cli::completions::command_completions::CommandCompletion::complete_commands::he883417323f1b313
  17:        0x1094d8d21 - <nu_cli::completions::command_completions::CommandCompletion as nu_cli::completions::base::Completer>::fetch::h7306656b8e4d476f
  18:        0x1094fd013 - nu_cli::completions::completer::NuCompleter::process_completion::h045ac2cd0b17ecb3
  19:        0x1094feae2 - nu_cli::completions::completer::NuCompleter::completion_helper::h5ef6e3fcf8d363a7
  20:        0x1095002e2 - <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete::hcc530748310a5e9e
  21:        0x109e3cd59 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values::h820b770f3965d506
  22:        0x109e378d6 - reedline::engine::Reedline::handle_editor_event::h335d98f8d78de07e
  23:        0x109e373e0 - reedline::engine::Reedline::handle_editor_event::h335d98f8d78de07e
  24:        0x109e35cf1 - reedline::engine::Reedline::read_line::hff2e93dc3a4ec6cb
  25:        0x1094eba07 - nu_cli::repl::evaluate_repl::h30c3cb2ef58c6616
  26:        0x1094bb5b6 - nu::run::run_repl::h02a95985ec485864
  27:        0x1094b7d16 - nu::main::h374ee896b80f789a
  28:        0x1094b8372 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2e5472df8012f276
  29:        0x1094bba36 - std::rt::lang_start::{{closure}}::hae6d78569b0caf03
  30:        0x109f73a58 - std::rt::lang_start_internal::h63aa6976ade06f50
  31:        0x1094b831c - _main
```

### Expected behavior

Auto complete.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.76.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0 (8ecd4f20a 2023-01-10)                               |
| pkg_version        | 0.76.0                                                            |
| build_time         | 2023-02-21 20:46:29 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | database, default, trash, which, zip                              |
| installed_plugins  |                                                                   |

**Comment by kubouch** [comment] 2023-02-24 11:21
I believe it's a duplicate of https://github.com/nushell/nushell/issues/7754 (if not, please reopen). We're working on alias implementation that should prevent this.

**Closed by kubouch** 2023-02-24 11:21 UTC
