### ISSUE TITLE
Replace `is-empty` with `any`

### ISSUE THREAD

**Issue by adamijak** [nushell/nushell#6499] opened 2022-09-06 13:52 UTC
### Related problem

Since `is-empty` and `any` are redundant I think we can use `is-empty` for different 
We should consider this issue before landing v0.68.0 because it is breaking change of #6464 which lands in v0.68.0.

### Describe the solution you'd like

We could change behaviour of `any` and `is-empty` to match following example:
```
> [ ] | any
false
> [ ] | is-empty
true
> [ $nothing "" ] | any
true
> [ $nothing "" ] | is-empty
true
> [ $nothing "some" ] | any
true
> [ $nothing "some" ] | is-empty
false
```
`any` in this example mimics `len > 0`
`is-empty` should detect empty values. For example `$nothing` `""` and ?maybe others?

ping @sholderbach since you were interested in this issue before

**Comment by sholderbach** [comment] 2022-09-06 13:59
Currently `any` and `all` require an explicit predicate that should be tested.

**Comment by adamijak** [comment] 2022-09-06 14:01
> Currently `any` and `all` require an explicit predicate that should be tested.

Yes currently you have to use `any true`.

**Comment by sholderbach** [comment] 2022-09-06 14:33
The behavior of `| any true` is not really doing what I would consider `any` as a boolean summary. 
Example: `[false]`

![grafik](https://user-images.githubusercontent.com/15833959/188660800-312d07b9-8a99-46e2-badd-fe6b6eac6f73.png)

My `any` base case would rather be `| any $it` if we allow different nushell values to evaluate to an implicit conversion to bool

**Comment by hyiltiz** [comment] 2022-09-06 20:46
I like that `any` is currently a functional, and requires an explicit function of type `a -> Bool` to work. `is-empty` is probably a common function of that type, but `is-true` is almost as common. I would hesitate adopting a default.

However, the results of `any?` and `all?` are surprising indeed (see attached).
<img width="556" alt="image" src="https://user-images.githubusercontent.com/3246683/188734456-c4440a54-e992-463e-bbb9-80fe403c4243.png">

I think the confusion is coming from `any?` accepting `true` as a `a -> Bool` predicate, rather than just a `Bool` value. This should probably just throw a syntax error, with a friendly message educating the user to use `any? is-true` instead.

**Comment by sholderbach** [comment] 2022-09-07 08:56
Yes the `Expr::RowCondition` syntax can be somewhat surprising in its implicitness. So the expression is basically a function block that will always return `true` and for `any` the base case is `false` and as soon as the first iteration happens it sees `true` and returns `true`.

Having a `is-true` command to do casting to bool only in an explicit way would be probably nicer than Python/R/C style everything can always be tested for truthiness.
Limitation is that we don't really have first class function/command support at the moment.

In general I would say `is-empty` is here to stay. If everybody is on board, I would close the issue for now. Happy to see future improvements to any (or first class function support :P)

**Comment by hyiltiz** [comment] 2022-09-08 01:41
As demonstrated above, the current behavior of `any? true` `any? false` etc. is surprising, if not a bug. It would be desirable to keep this open until we reach a resolution, maybe?

**Comment by sholderbach** [comment] 2022-09-08 11:33
`... | any false` is objectively useless as it will only return `false`. `... | any true` acts as a lesss descriptive stand in for the inverse of `is-empty` on automatically iterable types like lists and tables but NOT for strings.

We could improve the documentation on what the predicate in `any`, `all` or `where` is. It doesn't act as a value to compare but rather is an expression to be evaluated in the context of each iteration (with name binding for columns) Thus the `RowCondition` is slightly more than just a block without `{}`.

**Comment by webbedspace** [comment] 2022-10-30 13:30
This issue can be closed, right? It's clear what it's asking for is fundamentally a misunderstanding of what these commands do.

**Comment by sholderbach** [comment] 2022-10-30 13:37
Yeah closing it for now. Happy to land PRs that may improve the documentation.

**Closed by sholderbach** 2022-10-30 13:37 UTC
Labels: enhancement
