### ISSUE TITLE
`type` is lying about builtins?

### ISSUE THREAD

**Issue by shreevatsa** [nushell/nushell#10171] opened 2023-08-31 14:32 UTC
### Describe the bug

I tried switching to nushell after reading https://www.jntrnr.com/case-for-nushell/ (and searching online for it, as the page doesn't link to https://www.nushell.sh), and one of the first things I ran into (after installing, and after finding that `nu` and not `nushell` was the command to start it) was that I ran `ps` and it shows every single process running on the system (as my user, I guess?), rather than just the ones started from a terminal (which is the default behaviour of `/bin/ps`). Also `ps aux` didn't work, so I suspected that nushell was using its own `ps` shell builtin (which [it is](https://www.nushell.sh/commands/docs/ps.html)), so I tried to check it:

```
> type ps
ps is /bin/ps
```

— this is a lie! Other things seem to work fine:

```
> type type
type is a shell builtin
> type help
help is a shell builtin
```

Especially when nushell is re-implementing several common shell commands (coreutils?) as shell builtins, I would consider it essential for `type` to be honest about the type of each command, whether when I type the command I'm going to get a shell builtin or something else.

### How to reproduce

1. Type `type ps`

### Expected behavior

I expected nu to say `ps is a shell builtin`. Instead I get `ps is /bin/ps`

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-08-22 21:09:23 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                     |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment] 2023-08-31 14:55
`type` is not a nushell command, so when you call it, you're shelling out into bash and running it. You can see that `type` is not a command with `help type` or `help commands | where name == type` and also `scope commands | where name == type`.

`help ps` will show you that `ps` is a built-in also `which ps` says the same.

**Comment by amtoine** [comment] 2023-08-31 16:49
closing this issue as `type` is not a Nushell command :relieved: 

@shreevatsa 
feel free to reopen if the issue is more deep than this confusing saying from this system `type` command :wink:

**Closed by amtoine** 2023-08-31 16:49 UTC
Labels: needs-triage
