### ISSUE TITLE
`into datetime` not parsed correctly when testing examples

### ISSUE THREAD

**Issue by dandavison** [nushell/nushell#7032] opened 2022-11-06 16:37 UTC
### Describe the bug

`into datetime` is not parsed correctly in the code that automatically tests command examples.

### How to reproduce

Make this change (this assumes that https://github.com/nushell/nushell/pull/7031 has been landed):

```diff
diff --git a/crates/nu-command/src/date/format.rs b/crates/nu-command/src/date/format.rs
index c7032f9f7..034fba0c9 100644
--- a/crates/nu-command/src/date/format.rs
+++ b/crates/nu-command/src/date/format.rs
@@ -86,7 +86,7 @@ impl Command for SubCommand {
             },
             Example {
                 description: "Format a given date using a given format string.",
-                example: r#""2021-10-22 20:00:12 +01:00" | date format "%Y-%m-%d""#,
+                example: r#""2021-10-22 20:00:12 +01:00" | into datetime | date format "%Y-%m-%d""#,
                 result: Some(Value::String {
                     val: "2021-10-22".to_string(),
                     span: Span::test_data(),
```

Then run
```
cargo test -p nu-command date::format::test::test_examples
```

You'll see an error like
```
thread 'date::format::test::test_examples' panicked at
'test parse error in
`"2021-10-22 20:00:12 +01:00" | into datetime | date format "%Y-%m-%d"`:
ExtraPositional("into ", Span { start: 78, end: 86 })',
crates/nu-command/src/example_test.rs:99:17
```

### Expected behavior

The test should pass, since the code works at the REPL:

```
〉"2021-10-22 20:00:12 +01:00" | into datetime | date format "%Y-%m-%d"
2021-10-22
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.1                                          |
| branch             | dev                                             |
| commit_hash        | e7c5abf4efa0f5645fc19a3bd777044e8a0f7136        |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | 1.63.0-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.70.1                                          |
| build_time         | 2022-10-20 09:10:05 -04:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment] 2022-11-07 21:33
The environment in which the `Example`s are run is restricted to the command under test and some meager core commands. 
https://github.com/nushell/nushell/blob/3d8d7787ded739935996b407156174ef9b835b1d/crates/nu-command/src/example_test.rs#L27-L58
I think the original reasoning was that the startup time for individual example tests was atrocious. So sadly for nice looking examples we currently have to disable testing the output.
Even worse, we don't run or try to parse them when setting the expected output to `None` so there is potential for bitrot.

**Comment by hbt** [comment] 2022-11-11 00:36
@dandavison FYI, please note since the signatures are generated from examples and this bug prevents adding examples, some signatures are missing.

e.g `fmt` signature is 
```
Number => Record
```

but should be 
```
Number => Record
Filesize => Record
```

It would be trivial to add an example like `42B | into filesize | fmt` 
and change the signatures to 
```rust
vec![
                (Type::Number, Type::Record(vec![])),
                (Type::Filesize, Type::Record(vec![])),
            ]
```

but we can't until this bug is fixed. 

Otherwise, other tests would fail 
```
thread 'conversions::fmt::test::test_examples' panicked at 'assertion failed: `(left == right)`
  left: `{(Number, Record([]))}`,
 right: `{(Filesize, Record([])), (Number, Record([]))}`: There are entries in the signature type map which do not correspond to any example: "filesize -> record<>"', crates/nu-command/src/example_test.rs:244:13
```

**Comment by dandavison** [comment] 2022-11-11 02:03
@sholderbach what would it take to make `into datetime` and `into filesize` work in the example test? I see `Into` is already present in the working set.

@hbt I think I understand what you said but I'm not quite sure why you addressed it to me. I didn't introduce the bug, I just reported it, no?

**Comment by hbt** [comment] 2022-11-11 11:34
@dandavison Thank you for adding the signatures inputs/outputs type https://github.com/nushell/nushell/pull/6796

I noticed some of the signatures were missing and wanted to fix it and work on the "discovery" feature mentioned in https://github.com/nushell/nushell/issues/6996 to build some form of "data typed ETL pipeline explorer" kinda thing.

I got blocked on the parser failing (*IF that's the bug*) and was too new to the project to figure it out. 

I addressed it to you because maybe the root cause of the bug is beyond the datetime, as I encountered a similar error message when using this example: `42B | into filesize | fmt` 

I posted some code https://github.com/hbt/nushell/commit/1b4f95787475fbcdf18e74c12c62c6c29dfb2f86

Perhaps we are debugging the same thing. 
I won't be digging it into the parser yet though. 

Thanks.

**Comment by dandavison** [comment] 2022-11-11 12:08
Hi @hbt ok cool! Let's work out how to make progress here and make good use of the types. I agree, I think the `into filesize` in https://github.com/hbt/nushell/commit/1b4f95787475fbcdf18e74c12c62c6c29dfb2f86 and `into datetime` issues here are the same thing. But the thing is, `Into` is already present in the "working_set" used in the test https://github.com/nushell/nushell/blob/main/crates/nu-command/src/example_test.rs#L71. (I initially thought that was the problem, but evidently not.) I think @sholderbach will understand what's going on here.

**Comment by sholderbach** [comment] 2022-11-11 12:16
The `Into` and `From` in this list are in and of itself useless in this context as they are the meta commands that will just display the help message referring to the subcommands https://github.com/nushell/nushell/blob/main/crates/nu-command/src/conversions/into/command.rs
We need to pull in the explicit versions to have them available. (Don't fully have the name resolution rules in my head if removing the meta command would cause the subcommands to stop working in this context but I think not cause I remember adding a meta command later.)

**Comment by fdncred** [comment] 2022-11-11 14:36
FWIW, I was able to add these two lines and update the `use` statements and get the tests to work.
```rust
            working_set.add_decl(Box::new(IntoDatetime));
            working_set.add_decl(Box::new(IntoFilesize));
```
cargo test -p nu-command date::format::test::test_examples
this test worked 
```rust
            Example {
                description: "Format a given date-time using the default format (RFC 2822).",
                example: r#"'2021-10-22 20:00:12 +01:00' | into datetime | date format"#,
                result: Some(Value::String {
                    val: "Fri, 22 Oct 2021 20:00:12 +0100".to_string(),
                    span: Span::test_data(),
                }),
            },
```
cargo test -p nu-command conversions::fmt::test::test_examples
this test worked
```rust
            Example {
                description: "Get a record containing multiple formats for filesize 42B",
                example: "42B | into filesize | fmt",
                result: Some(Value::Record {
                    cols: vec![
                        "binary".into(),
                        "debug".into(),
                        "display".into(),
                        "lowerexp".into(),
                        "lowerhex".into(),
                        "octal".into(),
                        "upperexp".into(),
                        "upperhex".into(),
                    ],
                    vals: vec![
                        Value::String {
                            val: "0b101010".to_string(),
                            span: Span::test_data(),
                        },
                        Value::String {
                            val: "42".to_string(),
                            span: Span::test_data(),
                        },
                        Value::String {
                            val: "42".to_string(),
                            span: Span::test_data(),
                        },
                        Value::String {
                            val: "4.2e1".to_string(),
                            span: Span::test_data(),
                        },
                        Value::String {
                            val: "0x2a".to_string(),
                            span: Span::test_data(),
                        },
                        Value::String {
                            val: "0o52".to_string(),
                            span: Span::test_data(),
                        },
                        Value::String {
                            val: "4.2E1".to_string(),
                            span: Span::test_data(),
                        },
                        Value::String {
                            val: "0x2A".to_string(),
                            span: Span::test_data(),
                        },
                    ],
                    span: Span::test_data(),
                }),
            },
```

So, I guess the real question is, do we want to/need to add more items to the Examples test runner. I'm not really sure what the rules are for this. I'd love to be able to test (nearly) any pipeline in Examples without degrading testing performance or running into issues. I'm not sure what the way forward is. Thoughts?

**Comment by dandavison** [comment] 2022-11-11 14:56
How about we refactor so that individual tests can add things to the `working_set` before starting the example test?

**Comment by fdncred** [comment] 2022-11-11 15:31
I'm definitely willing to explore that and see how it goes. The problem is that I don't remember exactly the limitation. @sholderbach mentions that startup time was bad. That may be the case for having everything all in one, but having each example have it's own set of available commands may be a good fix for that.

**Comment by sholderbach** [comment] 2023-08-09 23:00
Closing this one as this is currently not an active issue but tribal knowledge around how the example test runner works.

**Closed by sholderbach** 2023-08-09 23:00 UTC
Labels: tests
