### ISSUE TITLE
How to set envirinment variables inside any logic i.e. scoped block?

### ISSUE THREAD

**Issue by CmdQ** [nushell/nushell#6705] opened 2022-10-11 22:53 UTC
### Question

I'm starting with nushell and I really like the concepts. So I thought I'd bring my start-up scripts over (`env.nu`). Something very simple trips me up completely though: I want to conditionally define environment variables, maybe even in a loop.

That just does not work. For a `for` loop or an `if` you have to have a block. Whatever you `let-env` inside that is gone at the end of the block, even it that conditional was inside of a `dev-env` function.

```
let homebrew = ([
    /opt/homebrew
    /home/linuxbrew/.linuxbrew
] | each { $in | append 'bin' | str join '/' })

for dir in $homebrew {
    if ($dir not-in $env.PATH && ($dir | path exists)) {
        echo prepending
        let-env PATH = ($env.PATH | prepend $dir)
    }
}
```

The “prepending” was printed, but the `PATH` was still the default one.

As a FP fan I totally get and value immutability (along with shadowing), but how am I supposed to achieve my very practical goal here?

**Comment by fdncred** [comment] 2022-10-12 11:33
The key is to do `let-env` on the outside of your loops/conditions. For example:
```
let-env PATH = (if blah else blah)
```
Another way is to create a record and use `load-env`. For example:
```
let paths = (construct key: value records over and over again)
$paths | load-env
```
I'm betting that you can find examples of both of these techniques and perhaps more in the nu_scripts repo. Just search for `let-env` or `load-env`.

**Comment by sholderbach** [comment] 2022-10-12 12:56
Closing as it is generally a duplicate of #6703 and maybe a few other issues.
Any improvements to documentation or suggestions for good syntactic sugar is definitely welcome.

**Closed by sholderbach** 2022-10-12 12:56 UTC
Labels: question
