### ISSUE TITLE
unexpected type mismatch: expected String, found Record([])

### ISSUE THREAD

**Issue by N4tus** [nushell/nushell#8005] opened 2023-02-08 17:04 UTC
### Describe the bug

```py
def provideStr [r: record] {
  "test"
} 

def needStr [str: string] {
  echo $str
}

def run [r: record] {
  needStr (provideStr $r)
}

run {a:b}
```
This script errors with:
```
Error: nu::parser::type_mismatch (link)

  × Type mismatch.
    ╭─[/d/dev/nu/test.nu:9:1]
  9 │ def run [r: record] {
 10 │   needStr (provideStr $r)
    ·           ───────┬───────
    ·                  ╰── expected String, found Record([])
 11 │ }
    ╰────
```

But `provideStr` does return a string. Putting the expression around quotes (`(provideStr $r)` -> `$"(provideStr $r)"`) solves this issue but it looks unnecessary.  
The more curious case is, that `r` has to be a parameter and not a variable. This script runs just fine:
```py
def provideStr [r: record] {
  "test"
} 

def needStr [str: string] {
  echo $str
}

let r = {a:b}
needStr (provideStr $r)
```

### How to reproduce

1. create a file named `test.nu` with the content:
```py
def provideStr [r: record] {
  "test"
} 

def needStr [str: string] {
  echo $str
}

def run [r: record] {
  needStr (provideStr $r)
}

run {a:b}
```
2. run it with `nu test.nu`

### Expected behavior

I expect nu to use the output from `provideStr` as positional parameter for the `needStr` command. 

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.75.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.68.0-nightly (0442fbabe 2023-01-10)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.68.0-nightly (8c460b223 2023-01-04)     |
| pkg_version        | 0.75.0                                          |
| build_time         | 2023-02-08 17:29:13 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by Mehrbod2002** [comment] 2023-02-10 00:28
@sholderbach
Can you assign me for it ?
Just one question  
Is Function define as Closure in Nushell?

**Comment by ysthakur** [comment] 2023-12-26 21:11
I can no longer reproduce this on version 0.88:

![image](https://github.com/nushell/nushell/assets/45539777/07d73a5a-b899-4d3a-a56e-f752b6f06017)

@N4tus Could you check if the issue still occurs for you? Hopefully it got fixed at some point

**Comment by amtoine** [comment] 2023-12-27 09:09
good catch @ysthakur => i can't reproduce either with almost the latest `main` :thinking: 

i'll close this issue for now.
@N4tus, please reopen this thread in case the issue still occurs in the end :innocent:

**Closed by amtoine** 2023-12-27 09:09 UTC
Labels: :bug:  bug, investigate, type-system
