### ISSUE TITLE
`DIRS_LIST` and `DIRS_POSITION` are not being set

### ISSUE THREAD

**Issue by akarel-mb** [nushell/nushell#9265] opened 2023-05-22 19:09 UTC
### Describe the bug

Since upgrading to `0.80.0` from `0.79.0` any command dealing with multiple working directories (e.g. `shells`, `enter`, `g`, `n`, `p`, etc.) results in one of the following errors:

```
Error: nu::shell::column_not_found

  × Cannot find column
    ╭─[dirs:67:1]
 67 │     mut out = []
 68 │     for $p in ($env.DIRS_LIST | enumerate) {
    ·                ──┬─ ────┬────
    ·                  │      ╰── cannot find column 'DIRS_LIST'
    ·                  ╰── value originates here
 69 │         $out = ($out | append [
    ╰────
```

```
Error: nu::shell::column_not_found

  × Cannot find column
     ╭─[dirs:108:1]
 108 │     # see: https://stackoverflow.com/questions/13683563/whats-the-difference-between-mod-and-remainder
 109 │     let pos = ($env.DIRS_POSITION
     ·                ──┬─ ──────┬──────
     ·                  │        ╰── cannot find column 'DIRS_POSITION'
     ·                  ╰── value originates here
 110 │                 + $offset
     ╰────
```

Manually setting `DIRS_LIST` and `DIRS_POSITION` resolves the issue.

Not sure if this is tangentially related to #9229

### How to reproduce

1. Attempt one of the following commands: `enter`, `shells`, `g`

### Expected behavior

`DIRS_LIST` and `DIRS_POSITION` to be set on start/init.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.0                                   |
| branch             |                                          |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-16 22:27:13 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment] 2023-05-22 19:21
We're still working on the stdlib version of the shells commands here https://github.com/nushell/nushell/pull/9234. So, it's not surprising that things are broken.

**Comment by aidalgol** [comment] 2023-05-23 04:39
What should `DIRS_LIST` and `DIRS_POSITION` be set to in `env.nu` as a workaround for now?

**Comment by hustcer** [comment] 2023-05-23 05:29
```shell
let-env DIRS_POSITION = 0
let-env DIRS_LIST = [($env.PWD | path expand)]
```

**Comment by fdncred** [comment] 2023-05-23 11:32
We just landed https://github.com/nushell/nushell/pull/9267 which I think fixes this. Can someone please confirm?

**Comment by amtoine** [comment] 2023-05-23 16:53
i already wasn't able to reproduce this without the PR, let me build and try again... :recycle:

**Comment by amtoine** [comment] 2023-05-23 17:04
no such error on latest `main` :+1:

**Comment by akarel-mb** [comment] 2023-05-23 21:13
Interestingly, if I remove the `env.nu` and `config.nu` files and restart the shell, after being prompted and creating the default env and config files, `DIRS_LSIT` and `DIRS_POSITION` are populated. But upon the next shell restart they are not and I get the above errors.

**Comment by amtoine** [comment] 2023-05-24 16:37
i've just installed the latest revision of Nushell and i still cannot reproduce the error above by doing
1. remove the config files `rm $nu.config-path $nu.env-path`
2. restart a new instance of Nushell
3. accept the creation of the two default config files
4. restart the shell again

 :confused:

**Comment by akarel-mb** [comment] 2023-06-05 15:18
This weekend I upgraded nushell on a different computer (still Windows 11) and received the same error. Maybe the issue is OS related if you are unable to reproduce. I have a linux box with an older version (0.7.7 I think). I'll see if I can get to testing on it later today.

**Comment by akarel-mb** [comment] 2023-06-12 19:46
FYI. Updating to 0.81.0 resolved this issue for me. 🎉

**Comment by fdncred** [comment] 2023-06-12 20:59
great, let's close this then!

**Closed by fdncred** 2023-06-12 20:59 UTC
Labels: priority, std-library
