### ISSUE TITLE
Variables not substituted in `rm`

### ISSUE THREAD

**Issue by thought-police-000** [nushell/nushell#12731] opened 2024-05-02 05:40 UTC
### Question

```
~/databases> const file = ~/Downloads/2930.txt                                                                                                                     05/02/2024 03:31:05 PM
~/databases> ls $file                                                                                                                                              05/02/2024 03:33:40 PM
╭───┬──────────────────────────────┬──────┬──────────┬───────────────╮
│ # │             name             │ type │   size   │   modified    │
├───┼──────────────────────────────┼──────┼──────────┼───────────────┤
│ 0 │ /Users/ph/Downloads/2930.txt │ file │ 456.5 KB │ 6 minutes ago │
╰───┴──────────────────────────────┴──────┴──────────┴───────────────╯
~/databases> rm $file                                                                                                                                              05/02/2024 03:33:43 PM
Error:   × File(s) not found
   ╭─[entry #24:1:1]
 1 │ rm $file
   ·    ──┬──
   ·      ╰── File(s) not found
   ╰────

```
So why isn't the `$file` variable substituted as the first parameter of rm?

**Comment by thought-police-000** [comment] 2024-05-02 05:42
```
~/databases> which rm                                                                                                                                              05/02/2024 03:41:12 PM
╭───┬─────┬──────────────────────────┬──────────╮
│ # │ arg │           path           │ built-in │
├───┼─────┼──────────────────────────┼──────────┤
│ 0 │ rm  │ Nushell built-in command │ true     │
╰───┴─────┴──────────────────────────┴──────────╯
```

**Comment by WindSoilder** [comment] 2024-05-02 07:33
Yeah, nushell won't auto expand `~` if you give variables, to achieve this, you need to use `path expand`:
`rm ($file | path expand)`

**Comment by WindSoilder** [comment] 2024-05-06 08:16
I forget to close the issue, but yeah it's by design.

**Closed** 2024-05-06 08:15 UTC
Labels: question, glob-expansion
