### ISSUE TITLE
can not use ln command in nushell

### ISSUE THREAD

**Issue by lgf-136** [nushell/nushell#8195] opened 2023-02-24 15:13 UTC
### Describe the solution you'd like

can not use ln command in nushell,

**Comment by WindSoilder** [comment] 2023-02-24 15:24
Please provide more information, which version and which os are you using?  I can't reproduce it.

**Comment by WindSoilder** [comment] 2023-02-26 01:00
Closing the issue for now, feel free to re-open it and provide more information

**Closed by WindSoilder** 2023-02-26 01:00 UTC
Labels: enhancement
