### ISSUE TITLE
Setting alias ls  = ( ls | sort-by type ) removes all color from output

### ISSUE THREAD

**Issue by DWTW321** [nushell/nushell#6373] opened 2022-08-20 21:19 UTC
### Describe the bug

If any alias that contains a pipe is created for ls the output stops showing colors.

### How to reproduce

1. Create an alias for ls with a pipe; e.g. `alias ls = ( ls | sort-by type )`
2. Any color, even color explicitly set by the LS_COLORS environment variable, doesn't show.

### Expected behavior

Sort ls output by type and still show colors

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 33674d3a98dd7510a4e4784c079dfdaecfd2e0d6        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-16 20:28:43 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |

**Comment by fdncred** [comment] 2022-08-21 00:30
dupe

**Comment by onthebridgetonowhere** [comment] 2022-08-21 03:31
Duplicate of #4501. No solution exists for the moment.

**Closed** 2022-08-21 11:17 UTC
Labels: bug
