### ISSUE TITLE
Allow short flags of any length in completion definitions

### ISSUE THREAD

**Issue by itzgoldenleonard** [nushell/nushell#8318] opened 2023-03-04 16:29 UTC
### Related problem

I'm trying to write extern completions for ffmpeg, which has some unusual and complicated syntax. Many of the flags look like this `-version`, long flag names but with only 1 hyphen. There's probably some good reason that they do it this way.

Nu's completion engine doesnt support this. If I try it throws a `nu::parser::parse_mismatch` error that says "expected short flag". This means that you can't write functional completions for commands that use this syntax.

### Describe the solution you'd like

Allow short flags (flags that only start with 1 hyphen) to have any length

### Describe alternatives you've considered

There doesn't currently seem to be any way to get this to work

### Additional context and details

ffmpeg-completions.nu:
```nu
# Hyper fast Audio and Video encoder
export extern "ffmpeg" [
    -version             #Show version
]
```

Throws this error:
```
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
    ╭─[./ffmpeg/ffmpeg-completions.nu:22:1]
 1  │ export extern "ffmpeg" [
 2  │     -version                                             # Show version
    ·     ────┬───
    ·         ╰── expected short flag
 3  │ ]
    ╰────
```

**Comment by sholderbach** [comment] 2023-03-04 19:51
That has been a long-standing issue. Our parser tries to assign special semantics to the shortflags which is at odds with the wider world that also has single dash long flags.
We need to further separate the behavior of nu internal commands and external commands in that parse stage to fully support them in the extern definitions if I understand the current technical state.

(have to look for the related issues to consolidate the discussion)

**Comment by sholderbach** [comment] 2024-07-21 14:38
Closing as duplicate of #5959

**Closed by sholderbach** 2024-07-21 14:38 UTC
Labels: enhancement, parser, completions
