### ISSUE TITLE
register -e capnp is trying to register nu and is freezing the terminal

### ISSUE THREAD

**Issue by stormasm** [nushell/nushell#4277] opened 2022-02-06 20:43 UTC
_I believe this only happens if you try and run the register command inside a directory with the actual plugin file like /target/debug_

To reproduce

```rust
cd /target/debug
register -e capnp n
```

If you run the register command somewhere else you will PROBABLY not see this...

For some reason @fdncred and I are able to reproduce this issue...

[discord conversation](https://discord.com/channels/601130461678272522/683070703716925568/939967740935012353)

_it looks to me like register is trying to register nu and is failing because it's not a plugin. i launched another tab and with ps and noticed that nu launch /path/to/nu so i killed that pid and then the prompt was responding again._

**Comment by stormasm** [comment] 2022-02-17 21:12
@fdncred I just reproduced and got the same behavior I was seeing before, it is not fixed unfortunately.  It still freezes my terminal...

You have to cd /target/debug and then

```rust
register -e capnp n
```

**Comment by stormasm** [comment] 2022-02-17 21:15
3768 ttys000    3:02.97 /Users/ma/j/tmp17/nushell/target/debug/nu

3768 ttys000    3:15.66 /Users/ma/j/tmp17/nushell/target/debug/nu

3768 ttys000    3:29.13 /Users/ma/j/tmp17/nushell/target/debug/nu

**Comment by fdncred** [comment] 2022-02-17 21:44
ya, i cd'd to my target\debug folder on windows which is in c:\cartar\debug and didn't have the issue. must be linux/mac specific.

**Comment by stormasm** [comment] 2022-02-18 03:33
yes, so basically as I think you might have pointed out a week or so ago.  It appears to be running the nu program in that directory.  It seems like a bug to me that it would start to read or run the program prior to the user hitting return...

maybe @jntrnr can give me a pointer as to where that code might be where it starts reading the file and maybe we can just say --- do not read it if its nu or something along those lines ?

Just a guess ---- or maybe we should not read at all until the user hits return...

**Comment by fdncred** [comment] 2022-03-06 15:10
@stormasm can you still reproduce this? I can't any longer.

**Comment by stormasm** [comment] 2022-03-06 19:20
@fdncred yes ! it is still happening / you have to go to the target/debug directory first and then type the command...  

How to reproduce:
1) cd target/debug
2) type this part : register -e capnp
3) wait 10 seconds
4) type the n

And it dies / I just did it again....

It is a bit finicky as once I kill the process,
it starts working (now)...

So to reproduce I have to get out of nushell
and then come in again to reproduce...

You have to start from fresh...  This is a bizarre one !

Now when I kill the process it works and does not kill the actual
process nushell is running in --- as it comes back...

So it must be some zombie process that is hanging it up...
Its almost like the spawned process off of nushell is where the problem lies,
not sure....

**Comment by fdncred** [comment] 2022-03-15 19:09
i tried this on windows and couldn't reproduce.

then i tried to do `register -e capnp nu.ex` and the press `e` and it's like you did a ctrl-c. it just goes to the next line.

it definitely still happens in wsl/linux though and gets in a weird state. this screenshot was after i hit ctrl-c a bunch of times and it finally came back.
![image](https://user-images.githubusercontent.com/343840/158452918-d7324866-2054-42b1-93eb-20aed4cf512b.png)

but then i try to do an `ls` and the terminal is totally whacked.
![image](https://user-images.githubusercontent.com/343840/158453069-08216591-0a86-4dae-8631-ffb1b4e1d587.png)

a `clsterm` won't even fix it - which is my def of the reset-the-terminal-clear-everything command.

**Comment by fdncred** [comment] 2022-03-15 19:21
on windows, it appeared to fail in a different way, but what i just found out is that each time i tried with that `nu.exe` part, it was launching a new nushell.

**Comment by stormasm** [comment] 2022-03-15 19:39
@fdncred correct !
And on my mac....
If I kill that process that it is trying to launch.
Then I get back the original prompt where it was launching from...
And everything is OK again...

**Comment by tmccombs** [comment] 2022-04-13 06:18
On my archlinux install when I start to type:

```
register -e json /usr/bin/nu_
```
when trying to register nu_plugin_query, then it will hang for a couple of seconds then I get a panic:

```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
                   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                   ```
                   
                   
With a full bcktrace I have:
```
register -e json /usr/bin/nuthread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
                                          stack backtrace:
                                                             0:     0x556a532c0984 - <unknown>
                                                                                                 1:     0x556a5260e74c - <unknown>
                           2:     0x556a532b8211 - <unknown>
                                                               3:     0x556a532c3325 - <unknown>
                                                                                                   4:     0x556a532c3096 - <unknown>
                             5:     0x556a532c39f5 - <unknown>
                                                                 6:     0x556a532c3714 - <unknown>
                                                                                                     7:     0x556a532c0e84 - <unknown>
                               8:     0x556a532c346d - <unknown>
                                                                   9:     0x556a521b0b23 - <unknown>
                                                                                                      10:     0x556a532b72bb - <unknown>
                                11:     0x556a527204c8 - <unknown>
                                                                    12:     0x556a526d9a58 - <unknown>
                                                                                                        13:     0x556a526e663e - <unknown>
                                  14:     0x556a526ebcb7 - <unknown>
                                                                      15:     0x556a532c017d - <unknown>
                                                                                                          16:     0x556a526db6b8 - <unknown>
                                    17:     0x7f34a73d8310 - __libc_start_call_main
                                                                                     18:     0x7f34a73d83c1 - __libc_start_main@GLIBC_2.2.5
                                   19:     0x556a521eb4b5 - <unknown>
                                                                       20:                0x0 - <unknown>
                                                                      
```

**Comment by fdncred** [comment] 2022-04-13 13:19
here's a debug version of rust_backtrace = full for anyone who wants to jump in and figure this out.
```
register -e json ./target/debug/nu
Broken pipe (os error 32)


thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
stack backtrace:
0:0x5618355ed86d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
1:0x5618355ed86d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2:0x5618355ed86d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
3:0x5618355ed86d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
4:0x561835619e7c - core::fmt::write::he803f0f418caf762 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
5:0x5618355e3fb8 - std::io::Write::write_fmt::h70bc45872f37e7bb at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
6:0x5618355f0147 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
7:0x5618355f0147 - std::sys_common::backtrace::print::h359300b4a7fccf65 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
8:0x5618355f0147 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
9:0x5618355efe10 - std::panicking::default_hook::h03ca0f22e1d2d25e at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
10:0x561831081823 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h073bf443feddd205 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1867:9
11:0x56183107eb9a - nu::main::{{closure}}::hbc08808457f20d89 at /home/fdncred/src/forks/nushell/src/main.rs:44:9
12:0x5618355f08d4 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
13:0x5618355f0587 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
14:0x5618355edd34 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
15:0x5618355f0299 - rust_begin_unwind at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
16:0x56183104c1f3 - core::panicking::panic_fmt::he1bbc7336d49a357 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
17:0x5618355e31a2 - std::io::stdio::print_to::hc260703c9b30a410 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/stdio.rs:1164:9
18:0x5618355e31a2 - std::io::stdio::_print::hcbc8e5359e4501b6 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/stdio.rs:1176:5
19:0x561834b9fe51 - nu_cli::repl::evaluate_repl::hffbf0b7fb1908db0 at /home/fdncred/src/forks/nushell/crates/nu-cli/src/repl.rs:338:21
20:0x5618310924ac - nu::main::h55f3655aceb36c4e at /home/fdncred/src/forks/nushell/src/main.rs:262:21
21:0x56183104d38b - core::ops::function::FnOnce::call_once::h2c782055c5f7df00 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
22:0x5618310899fe - std::sys_common::backtrace::__rust_begin_short_backtrace::h1dffe0103ebd973a at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
23:0x561831096001 - std::rt::lang_start::{{closure}}::h8836a148e0b4f57d at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bd
24:0x5618355ecf51 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13 
25:0x5618355ecf51 - std::panicking::try::do_call::h7bc9dc436daeb8c7 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40 
26:0x5618355ecf51 - std::panicking::try::h653d68a27ff5f175 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
27:0x5618355ecf51 - std::panic::catch_unwind::h9d739f9f59895e68 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
28:0x5618355ecf51 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
29:0x5618355ecf51 - std::panicking::try::do_call::hfb39d6df61a2e69f at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
30:0x5618355ecf51 - std::panicking::try::h13e2d225134958ac at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
31:0x5618355ecf51 - std::panic::catch_unwind::h3bd49b5a5dfb1a50 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
32:0x5618355ecf51 - std::rt::lang_start_internal::h2ba92edce36c035e at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
33:0x561831095fd0 - std::rt::lang_start::h204789f0d91196eb at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:17
34:0x561831095d1c - main
35:0x7f20fef86d90 - __libc_start_call_main at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
36:0x7f20fef86e40 - __libc_start_main_impl at ./csu/../csu/libc-start.c:392:3
37:0x56183104ca75 - _start
38:0x0 - <unknown>
```

**Comment by WindSoilder** [comment] 2022-09-24 10:32
Maybe it's already resolved by https://github.com/nushell/nushell/pull/6479?

**Comment by fdncred** [comment] 2022-09-26 01:13
yup. this should be fixed.

**Closed by fdncred** 2022-09-26 01:13 UTC
Labels: :bug:  bug
