### ISSUE TITLE
rm cannot remove broken symlink

### ISSUE THREAD

**Issue by sheepduke** [nushell/nushell#3977] opened 2021-08-30 14:15 UTC
### Describe the bug

If the target file is deleted first, `rm <symlink>` will fail instead of removing the broken symbolic link file. 

### How to reproduce
```
/home/sheep/temp> touch test.txt
/home/sheep/temp> ln -s test.txt test-link
/home/sheep/temp> rm test.txt
deleted /home/sheep/temp/test.txt
/home/sheep/temp> rm test-link
error: No valid paths
  ┌─ shell:5:1
  │
5 │ rm test-link
  │ ^^ no valid paths
```

### Expected behavior

Remove `test-link` in example above.

### Configuration

  |key|value|
|-|-|
|version|0.36.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.54.0 (a178d0322 2021-07-26)|
|cargo_version|cargo 1.54.0 (5ae8d74b3 2021-06-22)|
|pkg_version|0.36.0|
|build_time|2021-08-30 22:07:49 +08:00|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, which, zip|
|installed_plugins|fetch, match, post, ps, sys|

**Comment by kubouch** [comment] 2021-08-30 20:27
I'm pretty sure it's because it calls `canonicalize()` which fails on a broken symlink so it reports an error. There should be another attempt with just `nu_path::expand_path()` which does not traverse symlinks.

**Comment by TommasoBianchi** [comment] 2021-09-05 15:20
@kubouch I did a bit of digging based on your suggestion, but to me it doesn't seem that `canonicalize()` is the issue: as far as I can tell, it even seems to not be involved in the `rm` implementation at all.

I think the issue might be related to the `glob` crate always following symlinks (see https://github.com/rust-lang-nursery/glob/issues/62), even broken ones. Not sure what can be done about that, though, other than fixing it upstream or interacting directly with the filesystem with something like `std::fs::symlink_metadata()` (this would be painful to do in my opinion to keep supporting globs).

**Comment by rileysu** [comment] 2021-09-16 08:13
From my testing I can confirm the above. It seems glob doesn't return anything when provided with the path of the broken symlink.

**Comment by b-butler** [comment] 2022-05-10 14:50
Given that is has been some months since https://github.com/rust-lang-nursery/glob/pull/105 has been opened without any response by the developers of `glob`, it seems that that a fix on their end might not get merged. Do maintainers/developers hear have an idea on what would be best? Using the external command `^rm` works of course and that could be documented on `rm`'s documentation page.

**Comment by herlon214** [comment] 2022-05-13 19:05
I patched `nu-glob` and tested, looks like it worked fined.
Raised the PR, if someone wants to test.

**Closed** 2022-05-14 00:56 UTC
Labels: bug, good first issue

**Comment by hustcer** [comment] 2022-05-14 01:07
> I patched `nu-glob` and tested, looks like it worked fined. Raised the PR, if someone wants to test.

@herlon214 I'm wondering if this issue https://github.com/nushell/nushell/issues/5526 was caused by `nu-glob` too?

**Comment by herlon214** [comment] 2022-05-14 15:39
@hustcer good question, i'm gonna try to reproduce https://github.com/nushell/nushell/issues/5526 now that the `nu-glob` fix was merged.

**Comment by herlon214** [comment] 2022-05-14 17:42
@hustcer just tested here, and the issue for https://github.com/nushell/nushell/issues/5526 is still happening =(
