### ISSUE TITLE
'ls | find term' doubles the output in the 'name' column

### ISSUE THREAD

**Issue by brancoliticus** [nushell/nushell#6539] opened 2022-09-11 13:51 UTC
### Describe the bug

Read the title and see the screenshot.

### How to reproduce

Run the command 'ls | find term' to trigger the buggy doubling of output.

### Expected behavior

No doubling of output in the 'name' column.

### Screenshots

![doubling_of_output_in_name_column](https://user-images.githubusercontent.com/1506027/189530400-edc95772-b4e9-4ff3-b0fd-a5aca1a2e44d.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-09 20:08:05 +03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Installed on Ubuntu 20.04 with 'cargo install nu --features=extra'.

**Comment by fdncred** [comment] 2022-09-11 19:31
dupe of #6498

**Closed by fdncred** 2022-09-11 19:31 UTC
Labels: :bug:  bug, good first issue
