### ISSUE TITLE
Defining a variable in a string results in error "expected valid variable name" despite being valid

### ISSUE THREAD

**Issue by noahbald** [nushell/nushell#13015] opened 2024-05-31 01:51 UTC
### Describe the bug

When declaring an empty string in a `.nu` file, using that later in a string literal results in an error.

### How to reproduce

1. Consider the following file
```nu
mut $dont_forget = ""
if $nu.os-info.family == "windows" {
    $dont_forget = `- Install Visual Studio C++
`
}
echo $`Don't forget to
- Update your chezmoi.toml email
- Set up ssh keys \(https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent\)
($dont_forget)- To smile :\)`
```

2. Run `nu ./file.nu`

### Expected behavior

I expect nu to output `""` into the string literal

### Screenshots

![Uploading image.png…]()

### Configuration

```
| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.0                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 0                                                          |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | macos-aarch64                                              |
| build_target       | aarch64-apple-darwin                                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) (Homebrew)             |
| cargo_version      | cargo 1.77.2                                               |
| build_time         | 2024-04-30 22:51:13 +00:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                            |
```

**Comment by ptazithos** [comment] 2024-05-31 02:29
> String interpolation uses `$""`  and  `$''` as ways to wrap interpolated text.

Ref: https://www.nushell.sh/book/working_with_strings.html#string-interpolation

I guess replacing the backtick string with a single or double quoted string may help.
```
echo $"Don't forget to
- Update your chezmoi.toml email
- Set up ssh keys \(https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent\)
($dont_forget)- To smile :\)"
```

**Comment by noahbald** [comment] 2024-05-31 05:58
Ah okay, I’d hoped we’d be able to use backticks to the same effect.
Perhaps this could be a feature request instead 😅

**Comment by sholderbach** [comment] 2024-07-11 13:45
Thanks for helping out @ptazithos 

Will close this as a duplicate of #13012

**Comment by sholderbach** [comment] 2024-07-11 13:46
On a second thought the error message is horrible, if we don't get to implementing #13012 we should at least improve it.

**Closed by sholderbach** 2024-07-11 13:45 UTC
Labels: needs-triage
