### ISSUE TITLE
Passthrough of boolean flags

### ISSUE THREAD

**Issue by gutenye** [nushell/nushell#12590] opened 2024-04-20 02:24 UTC
### Related problem

If I want to pass flags to a command, I must use many `if`s. This is not feasible if you have lots of flags.

For example, I created a custom command with some flags, and passed them to another command. I have to write like this

```sh
def custom-http-get [
  --full (-f)
  --raw (-r)
] {
  if $full and $raw {
    http get http://localhost --full --raw
  } else if $full {
    http get http://localhost --full
  } else if $raw {
    http get http://localhost --raw
  }
}
```

### Describe the solution you'd like

Able to store flags in a variable

```sh
let flags = [--full --raw]
http get http://localhost --$flags
```

Current it says `unexpected spread argument, To spread arguments, the command needs to define a multi-positional parameter in its signature, such as ...rest`

**Comment by fdncred** [comment] 2024-04-20 02:26
Have you tried `def custom [...rest] {}` or `def --wrapped custom [...rest] {}`?

**Comment by gutenye** [comment] 2024-04-20 02:30
They don't work.

1. `def custom [...rest] {}`: it does not collect the flags
2. `def --wrapped custom [...rest] {}`: it does no work with custom command.

```sh
def --wrapped custom [...rest] {
  run-external cmd ...$rest   # works
  custom-cmd ...$rest  # error, unexpected spread argument
}
```

**Comment by kubouch** [comment] 2024-04-20 07:18
You can pass variables to flags: `http get --full=$full --raw=$raw`.

**Comment by gutenye** [comment] 2024-04-20 08:48
@kubouch Thanks, it works great for bool flags. But when it comes to flag with argument and builtin command, it does not work anymore.

```sh
def cmd [
  url: string
  --user: string
] {
  http get $url --user=$user
}
cmd http://localhost   # error: can't convert nothing to string, expect it works
```

**Comment by kubouch** [comment] 2024-04-20 09:33
I'll close this since the original issue was about boolean flags, but I created a new one about named flags: https://github.com/nushell/nushell/issues/12592

**Closed by kubouch** 2024-04-20 09:33 UTC
Labels: enhancement, needs-design, type-system

**Comment by kubouch** [comment] 2024-08-30 05:21
We added the ability to pass booleans to flags with `=`:
```
http get http://localhost --full=$full --raw=$raw
```

**Comment by chtenb** [comment] 2024-08-30 08:17
Am I correct to observe that it doesn't work for external commands?

```nu
def "gst" [
  --verbose(-v)                                       # be verbose
  --short(-s)                                         # show status concisely
  --branch(-b)                                        # show branch information
  --show-stash                                        # show stash information
] {
  git status --verbose=$verbose --short=$short --branch=$branch --show-stash=$show_stash
}
```

```
> gst                                      08/30/2024 10:15:44 AM
Error: nu::shell::cant_convert

  × Can't convert to string.
    ╭─[\custom-completions\git-completions.nu:19:22]
 18 │ ] {
 19 │ git status --verbose=$verbose --short=$short --branch=$branch --show-stash=$show_stash
    ·                      ────┬───
    ·                          ╰── can't convert bool to string
 20 │ }
    ╰────
```

**Comment by kubouch** [comment] 2024-08-30 09:56
Apparently. Arguments to externals are just strings, so you need to construct those manually if you have non-string values like booleans. IMO, that works as intended, though I'd expect `extern 'git status' [--short]`, then `git status --short=false` to not pass the flag.

**Comment by chtenb** [comment] 2024-08-30 10:04
Actually, I had it defined like:

```
export extern "git status" [
  --verbose(-v)                                       # be verbose
  --short(-s)                                         # show status concisely
  --branch(-b)                                        # show branch information
  --show-stash                                        # show stash information
]
```

via the git-completions from nu_scripts. If I remove that, the error simply becomes:

```
> gst                                                                      
error: option `verbose' takes no value
```

I'll create a separate issue for this, to not pollute this thread further.
