### ISSUE TITLE
tilde expands to a relative path

### ISSUE THREAD

**Issue by dvc94ch** [nushell/nushell#5315] opened 2022-04-24 16:41 UTC
### Describe the bug

Tilde can't be used in PATH variables

### How to reproduce

This doesn't work:
```
let-env PATH = ($env.PATH | prepend '~/.cargo/bin')
which SOME_BINARY_IN_CARGO_BIN
```

### Expected behavior

This does:
```
let-env PATH = ($env.PATH | prepend '/home/dvc/.cargo/bin')
which SOME_BINARY_IN_CARGO_BIN
```

### Configuration

```
❯ version | transpose key value | to md --pretty
| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.61.0                                    |
| branch             |                                           |
| tag                |                                           |
| short_commit       | 3783c19d                                  |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880  |
| commit_date        | 2022-04-12 20:38:15 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.60.0 (Arch Linux rust 1:1.60.0-1) |
| cargo_version      | cargo 1.60.0                              |
| pkg_version        | 0.61.0                                    |
| build_time         | 2022-04-12 23:20:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |
```

**Comment by rgwood** [comment] 2022-04-24 20:31
Please fill in the Configuration info with the contents of `version | transpose key value | to md --pretty`, as requested in the issue template.

**Comment by uasi** [comment] 2022-04-26 10:46
duplicate of https://github.com/nushell/nushell/issues/4855

**Closed** 2022-04-26 10:52 UTC
