### ISSUE TITLE
Nushell thread panics if a variable  is passed to a custom command that contains a recursive call to itself.

### ISSUE THREAD

**Issue by edhowland** [nushell/nushell#11351] opened 2023-12-16 21:35 UTC
### Describe the bug

In the REPL of Nushell, if you try to send any variable to a custom command
that uses recursion to call itself, the Nushell executable will  thread panic as
soon as you type enough of the custom command's name to make it disticnt.
However, if you pass the exact same value as a literal it works normally.
This does not happen if you embed the custom command inside a Nu script or if you
call nu with using the '-c' flag.

Attempting to fool Nu by disguising the variable in a direct call to a simple
closure it will still panic. Also, if you create another custom command
that refers to the global variable and returns it, the Nu reader still panics.
Local variables that are then returned work normally. Only global variables
that are passed to bad custom command cause Nu to panic.

### How to reproduce

1. Create a custom command that accepts input., and recursively calls itself with that input.
2. Create a variable that contains some value of any type.
  * I used a simple int.
3. In the REPL of Nu, try and  type a pipeline passing the dereference of that variable to the custom command.
4. As soon as you type enough of the command's name that it is distinct, nu thread panics.

Here is a sample command that will trigger the panic:

```nu
# This command does nothing but countdown to 0 and returns false.
def px [n=0] {
  let l = $in
  if $n == 0 { return false } else {
    $l | px ($n - 1)
  }
}
```

Sammple session in the REPL

```nu

minerva issues.nushell >>  > source px.nu
minerva issues.nushell >>  > 1 | px 3
false
minerva issues.nushell >>  > let x = 1
minerva issues.nushell >>  > $x | pthread 'main' panicked at 'Attempt to mutate a block that is in the permanent (immutable) state', /Users/edhowland/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-protocol-0.85.0/src/engine/engine_state.rs:1789:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ 
```

... back in Bash.

Note the following working steps

```bash


mini issues.nushellnu -c "source px.nu; let x = 1; $x | px 3"
false
```

Or running from a .nu script:

```nu
# t-px.nu: Attempt to trigger the panic from a script
source px.nu

let x = 1
$x | px 3
```

Then run it:

```nu


These examples all work as intended.

This only triggers the panic with global variables.
Local variables in a block or  in another custom command or closure will not
trigger the panic.

```nu

minerva issues.nushell >>  > source px.nu
minerva issues.nushell >>  > if true {
::: let x = 1
::: $x
::: } | px 3
false
minerva issues.nushell >>  > do {|y| $y } 2 | px 3
false
minerva issues.nushell >>  > def foo [] {
::: let z = 1
::: $z
::: }
minerva issues.nushell >>  > foo | px 3
```

false

```


But, using a global variable in the above examples will trigger the panic.


```nu

minerva issues.nushell >>  > open foo.nu
source px.nu
let x = 1
def foo [] {
  $x
}
minerva issues.nushell >>  > source foo.nu
minerva issues.nushell >>  > foo | pthread 'main' panicked at 'Attempt to mutate a block that is in the permanent (immutable) state', /Users/edhowland/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-protocol-0.85.0/src/engine/engine_state.rs:1789:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Or with a simple closure: (also works with blocks:

```nu
minerva issues.nushell >>  > source px.nu
minerva issues.nushell >>  > let x = 1
minerva issues.nushell >>  > do {|| $x } | pthread 'main' panicked at 'Attempt to mutate a block that is in the permanent (immutable) state', /Users/edhowland/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-protocol-0.85.0/src/engine/engine_state.rs:1789:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

you should be able to write a custom command in Nu that takes input from a pipeline
and uses recursion to perform its job. This does work properly in most
cases if the input to the command is either a local variable, from some earlier
command that fetches/opens/generates output to feed to the command.
You should be able to experiment with that command within the command line
environment and if you use a literal value it works ok. You should be bale
to store that literal value in a global variable so you do not have to retype
it every time and then just dereference the global variable and pass it to the pipeline
input. This latter use of a global variable triggers the hard panic.

### Screenshots

minerva issues.nushell >>  > source px.nu
minerva issues.nushell >>  > let x = 1
minerva issues.nushell >>  > $x | pthread 'main' panicked at 'Attempt to mutate a block that is in the permanent (immutable) state', /Users/edhowland/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-protocol-0.85.0/src/engine/engine_state.rs:1789:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ 

### Configuration

| key                | value                                   |
| ------------------ | --------------------------------------- |
| version            | 0.85.0                                  |
| branch             |                                         |
| commit_hash        |                                         |
| build_os           | macos-aarch64                           |
| build_target       | aarch64-apple-darwin                    |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23)     |
| rust_channel       | stable-aarch64-apple-darwin             |
| cargo_version      | cargo 1.72.0 (103a7ff2e 2023-08-15)     |
| build_time         | 2023-10-02 09:52:38 -04:00              |
| build_rust_channel | release                                 |
| allocator          | mimalloc                                |
| features           | default, sqlite, trash, which, zip      |
| installed_plugins  | query, query json, query web, query xml |
| key                | value                                   |
| ------------------ | --------------------------------------- |
| version            | 0.85.0                                  |
| branch             |                                         |
| commit_hash        |                                         |
| build_os           | macos-aarch64                           |
| build_target       | aarch64-apple-darwin                    |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23)     |
| rust_channel       | stable-aarch64-apple-darwin             |
| cargo_version      | cargo 1.72.0 (103a7ff2e 2023-08-15)     |
| build_time         | 2023-10-02 09:52:38 -04:00              |
| build_rust_channel | release                                 |
| allocator          | mimalloc                                |
| features           | default, sqlite, trash, which, zip      |
| installed_plugins  | query, query json, query web, query xml |

### Additional context

Tried to get the backtrace as suggested by setting RUST_BACKTRACE=1 but I think that to do that I need to compile nu in debug mode first not in release mode.

**Comment by edhowland** [comment] 2023-12-16 21:48
Forgot to add the fact the version used above is 0.85.0 on MacOS Ventura. The exact problem occurs on Ubuntu Linux 18.04 with Nu version 0.86.0. And on Debian Linux 11 with Nu version 0.87.1. Locally I cannot yet run those vlater versions cause I haven't changed my config and env startup scripts. My custom prompt makes the examples above very hard to read. But if you get a copy of the 'px.nu' in one of the above markdown code fences, and save it to your drive, you should be able to replicate the symptons yourself in even the nightly release, or so I believe.

**Comment by KAAtheWiseGit** [comment] 2023-12-17 11:17
Can confirm on 0.88.0 and on the latest HEAD.

Weirdly enough, it doesn't crash on other names of the command.  `long-command` `long command`, `a`, `aa`, `aaa`, all those names work as expected.

The backtrace is

```
thread 'main' panicked at 'Attempt to mutate a block that is in the permanent (immutable) state', crates/nu-protocol/src/engine/state_working_set.rs:740:13M
stack backtrace:
   0:     0x562c316edb91 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc6521fe9c6439251
   1:     0x562c3172204f - core::fmt::write::hf4e3b21d20138ec6
   2:     0x562c316e7cf7 - std::io::Write::write_fmt::hbec7ded648513a9c
   3:     0x562c316ed9a5 - std::sys_common::backtrace::print::heac539adf76c494b
   4:     0x562c316ef4b3 - std::panicking::default_hook::{{closure}}::h067566546210da2d
   5:     0x562c316ef244 - std::panicking::default_hook::hb2a65fd1b950e4b8
   6:     0x562c2f4c3023 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h15ef02e1a1e93f0c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
   7:     0x562c2e645a72 - nu::main::{{closure}}::h580b8217f6857101
                               at /home/kaathewise/fork/nushell/src/main.rs:59:9
   8:     0x562c316efbae - std::panicking::rust_panic_with_hook::ha7310490fe1853fa
   9:     0x562c316ef8f1 - std::panicking::begin_panic_handler::{{closure}}::hb02409407690e3f6
  10:     0x562c316edff6 - std::sys_common::backtrace::__rust_end_short_backtrace::hed68c847dd04dbce
  11:     0x562c316ef682 - rust_begin_unwind
  12:     0x562c2e630f53 - core::panicking::panic_fmt::hab9d9e42e4c9bd67
  13:     0x562c30f2b64d - nu_protocol::engine::state_working_set::StateWorkingSet::get_block_mut::h119e63ca4b2856ee
                               at /home/kaathewise/fork/nushell/crates/nu-protocol/src/engine/state_working_set.rs:740:13
  14:     0x562c2fe09c6d - nu_parser::parser::parse::h77d3aebb6397f47a
                               at /home/kaathewise/fork/nushell/crates/nu-parser/src/parser.rs:6196:25
  15:     0x562c2fa7232d - <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight::h290c93990e16cddf
                               at /home/kaathewise/fork/nushell/crates/nu-cli/src/syntax_highlight.rs:23:21
  16:     0x562c2fbb87b1 - reedline::engine::Reedline::buffer_paint::ha9c1943f03954e7f
                               at /home/kaathewise/.local/state/cargo/git/checkouts/reedline-e42026a78d91c510/a4bfaa5/src/engine.rs:1641:45
  17:     0x562c2fbb64ab - reedline::engine::Reedline::repaint::h367ee4b1a9a06fe1
                               at /home/kaathewise/.local/state/cargo/git/checkouts/reedline-e42026a78d91c510/a4bfaa5/src/engine.rs:1455:13
  18:     0x562c2fbaf95c - reedline::engine::Reedline::read_line_helper::hdb95df712018a40e
                               at /home/kaathewise/.local/state/cargo/git/checkouts/reedline-e42026a78d91c510/a4bfaa5/src/engine.rs:761:29
  19:     0x562c2fbaed16 - reedline::engine::Reedline::read_line::h71a9da9cbf49b91f
                               at /home/kaathewise/.local/state/cargo/git/checkouts/reedline-e42026a78d91c510/a4bfaa5/src/engine.rs:616:22
  20:     0x562c2f9ffb88 - nu_cli::repl::evaluate_repl::h1d0c20a8570ac810
                               at /home/kaathewise/fork/nushell/crates/nu-cli/src/repl.rs:443:13
  21:     0x562c2e65f426 - nu::run::run_repl::ha46c804f3f92b8dd
                               at /home/kaathewise/fork/nushell/src/run.rs:273:19
  22:     0x562c2e650356 - nu::main::h86579df446725db7
                               at /home/kaathewise/fork/nushell/src/main.rs:347:9
  23:     0x562c2e63f4bb - core::ops::function::FnOnce::call_once::h46a7fbe0622adb90
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
  24:     0x562c2e64d13e - std::sys_common::backtrace::__rust_begin_short_backtrace::hd16422e431dc4292
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:135:18
  25:     0x562c2e645831 - std::rt::lang_start::{{closure}}::h93e39a24bf7c9032
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/rt.rs:166:18
  26:     0x562c316dd7b2 - std::rt::lang_start_internal::h9c9c1bf82ae402f9
  27:     0x562c2e64580a - std::rt::lang_start::h18cf1547bba61b82
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/rt.rs:165:17
  28:     0x562c2e65221e - main
  29:     0x7fc0dbde8aad - <unknown>
```

**Comment by KAAtheWiseGit** [comment] 2023-12-17 13:26
It is `get_block_mut` from `state_working_set`, which complains it was given a non-permanent block.  The difference between the give id and the number of the permanent ones is always nine, regardless of the number of previously executed instructions.

And this is what the call site says:

```
        // In theory, we should only be updating captures where we have new information
        // the only place where this is possible would be blocks that are newly created
        // by our working set delta. If we ever tried to modify the permanent state, we'd
        // panic (again, in theory, this shouldn't be possible)
```

This might be an issue with the variable usage in the closures, but that doesn't explain why changing the name fixes it.

**Comment by edhowland** [comment] 2023-12-17 20:38
Can you elaborate what you mean re: the closure? Since this only happens to me in the interactive env, I thought it was triggered in the auto suggestions part. (Which I sorely want to turn off permantely :( . And can you give some example of where  changing the name causes it not  to fail? In my testing, I made several similar names to 'px' like py, pyx and then renamed the command to 'pyyx'. Typing 'px', 'py', 'pyx' did not trigger the panic. As soon as I typed the x in 'pyyx', it triggered. Very strange bug.

**Comment by edhowland** [comment] 2023-12-17 20:52
Tried to turn off hinting with config.nu: 
    use_ansi_coloring: false. It still panics at the same place. So, not related to hints. Or so it seems to me.

**Comment by KAAtheWiseGit** [comment] 2023-12-17 21:24
@edhowland the issue is parsing.  The logic (`crates/nu-parser/src/parser.rs`, function `parse`) tries to fetch a block, which is permanent.  I don't know what "permanent" means in this context, TLDR is that this is an issue with the guts of the parser.

**Comment by sholderbach** [comment] 2024-02-14 16:58
How does this code behave after https://github.com/nushell/nushell/pull/11729 ?

**Comment by KAAtheWiseGit** [comment] 2024-02-15 18:34
@sholderbach still panics

**Comment by edhowland** [comment] 2024-02-15 21:08
Just tested on 0.90.2 (as cloned from main branch on GH). Still panics as described in the first comment here. Using the simple 'px' recursive countdown custom command that takes input from a pipe. If a literal int is passed, it works OK. If you use a global variable set to the exact same value as the literal, it hard panics. But only in the REPL.
If you run a Nushell script with the same commands, it works OK.. It also works if you execute it with the '-c "source px.nu;let i = 12; $i | px".

**Comment by lilyball** [comment] 2024-03-14 00:41
I've hit this same panic, but when executing a Nu script rather than at the REPL. In my case, the custom command is shadowing a built-in one, with an alias created to the built-in command first. If I rename the command to any other built-in command it still crashes as long as I retarget the alias too, but if I rename the command without retargeting the alias then it doesn't crash, or if I remove the recursive call then it doesn't crash. At the REPL if I `source` or `use` the file there's no immediate panic, but it panics under the same conditions as the original reproduction (even when invoked as a subcommand in the `use` case).

```nu
alias "orig update" = update

# Update a column to have a new value if it exists.
#
# If the column exists with the value `null` it will be skipped.
export def "update" [
    field: cell-path # The name of the column to maybe update.
    value: any # The new value to give the cell(s), or a closure to create the value.
]: [record -> record, table -> table, list<any> -> list<any>] {
    let input = $in
    match ($input | describe | str replace --regex '<.*' '') {
        record => {
            if ($input | get -i $field) != null {
                $input | orig update $field $value
            } else { $input }
        }
        table|list => {
            $input | each {|| update $field $value }
        }
        _ => { $input | orig update $field $value }
    }
}
```

**Comment by WindSoilder** [comment] 2024-04-12 01:48
Tried to look into it, and found it doesn't work with `$in`, panic can happened if we have a recursive call.

Here is a smaller reproducable example:
```nu
def px [] { if true { 3 } else { px } }
let x = 1
$x | px
```

When type final `x` in repl, nushel panic.

**Comment by texastoland** [comment] 2024-04-12 02:11
@WindSoilder That's a solid minimal example 🙌🏼 Can you get a stack trace too? I can try debugging next week.

**Comment by WindSoilder** [comment] 2024-04-12 02:41
@texastoland Oh sorry...I just created a pr to try to fix it.

The stack trace is similar to https://github.com/nushell/nushell/issues/11351#issuecomment-1859142098, starts with highlight function.

**Comment by texastoland** [comment] 2024-04-12 02:46
> Oh sorry...I just created a pr to try to fix it.

Not sorry at all this rocks 👏🏼 Anyone else in the thread should test their example against #12491. I'll try mine too!

**Comment by edhowland** [comment] 2024-04-16 17:50
This issue is probably closed by PR12491. Not sure  re: comment by lilyball above. If every one agrees, I can close the issue as resolved.

**Comment by WindSoilder** [comment] 2024-04-17 01:16
Hi, @edhowland You don't need to close it manually.  It will be closed automatically once the pr is merged.

**Closed** 2024-04-22 22:10 UTC
Labels: panic, recursion
