### ISSUE TITLE
Environment variable 'PATH' not found Windows 10

### ISSUE THREAD

**Issue by wavesinaroom** [nushell/nushell#14628] opened 2024-12-19 02:35 UTC
### Question

Hi everyone!

I was happily working with nushell for a while until I had to add Windows OpenSSH optional feature. Since then, I've not been able to run commands from `PATH` such as `hx` which runs helix code editor. 

Nushell complains with `Error: nu::shell::env_variable_not_found` and that made me double-check `$env.Path` but all paths were there, same with `$env.PATH`. My next step was to uninstall nushell on re-install it but that didn't work nor uninstalling, deleting config stored in `C:\Users\user\AppData\Roaming\nushell` and reinstall everything from scratch. I'm sure that my terminal emulator doesn't have anything to do with this because I ran nushell from Windows Command Prompt and Powershell ending up with the same results and my `hx` command runs helix without a problem.

I'm a new user and barely understand the inner workings of the shell. I had a look to the documentation and the issues in this repository but I couldn't find a hint or an answer that would help me out sorting out this issue.

Can anyone lend me a hand with a hint please? 

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.100.0                                  |
| major              | 0                                        |
| minor              | 100                                      |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | 1.80.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-11-13 03:41:33 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

```nushell
~\dev\rust\poker_squares> hx                                                        18/12/24 22:13:38
Error: nu::shell::env_variable_not_found

  × Environment variable 'PATH' not found
   ╭─[entry #22:1:1]
 1 │ hx
   · ─┬
   ·  ╰── environment variable not found
   ╰────

~\dev\rust\poker_squares> $env.Path                                               1 18/12/24 22:13:49
C:\Program Files\Rio\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files (x86)\Lua\5.1;C:\Program Files (x86)\Lua\5.1\clibs;C:\Program Files (x86)\glab;C:\Program Files\LLVM\bin;C:\Program Files (x86)\LLVM\bin;C:\Windows\System32\OpenSSH\;C:\Users\juank\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\juank\AppData\Local\Programs\Python\Python312\;C:\Users\juank\AppData\Local\Programs\Python\Python313\;C:\Users\juank\AppData\Local\Microsoft\WindowsApps;C:\Users\juank\AppData\Roaming\cabal\bin;C:\tools\ghc-9.8.1\bin;C:\tools\msys64;C:\Users\juank\AppData\Local\Muse Hub\lib;C:\Users\juank\AppData\Local\Programs\Python\Python313\Scripts;C:\Users\juank\.bin;C:\Users\juank\.cargo\bin;C:\Users\juank\AppData\Local\Programs\nu\bin\
~\dev\rust\poker_squares> $env.PATH                                                 18/12/24 22:13:55
C:\Program Files\Rio\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files (x86)\Lua\5.1;C:\Program Files (x86)\Lua\5.1\clibs;C:\Program Files (x86)\glab;C:\Program Files\LLVM\bin;C:\Program Files (x86)\LLVM\bin;C:\Windows\System32\OpenSSH\;C:\Users\juank\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\juank\AppData\Local\Programs\Python\Python312\;C:\Users\juank\AppData\Local\Programs\Python\Python313\;C:\Users\juank\AppData\Local\Microsoft\WindowsApps;C:\Users\juank\AppData\Roaming\cabal\bin;C:\tools\ghc-9.8.1\bin;C:\tools\msys64;C:\Users\juank\AppData\Local\Muse Hub\lib;C:\Users\juank\AppData\Local\Programs\Python\Python313\Scripts;C:\Users\juank\.bin;C:\Users\juank\.cargo\bin;C:\Users\juank\AppData\Local\Programs\nu\bin\
```

**Comment by NotTheDr01ds** [comment] 2024-12-19 02:47
Can you edit your question to include the output of:

```
version | transpose key value | to md --pretty | clip.exe
```

**Comment by wavesinaroom** [comment] 2024-12-19 03:04
Sure @NotTheDr01ds! I've already edited the screenshot to included the output you wanted to see. Thanks for taking time!

**Comment by NotTheDr01ds** [comment] 2024-12-19 03:08
Ah, that's having an issue also.  Try it with just:

```
version | transpose key value | to md --pretty
```

Copy that into your question if you would - It will be valid Markdown, so just copy it from the terminal and paste it into your message, rather than as a screenshot.  Thanks!

**Comment by wavesinaroom** [comment] 2024-12-19 03:16
Sorry about the screenshot @NotTheDr01ds, first time asking here on github

**Comment by NotTheDr01ds** [comment] 2024-12-19 03:28
@wavesinaroom No worries - And thanks!

On the bright side, you've confirmed it's not the bug I was worried it might be.  But it does seem to be some sort of `ENV_CONVERSIONS` issue.  Normally, your path should look like a Nushell list.  Yours is appearing as a string.  And normally Nushell tries to convert the path *list* back to a string before calling an external command.

But in this case, it's already a string, so the code to convert from a list to a string is failing (that's my running theory, anyway).

Just "thinking out loud" here. :-)

Hmm - Try the following from PowerShell:

```powershell
Get-ChildItem Env: | Where-Object { $_.Name -like "PATH" }
```

What's the case that is returned?  `Path` or `PATH`?  Or something else?

Thanks!

**Comment by NotTheDr01ds** [comment] 2024-12-19 03:33
I'm probably going to doze off in a bit for the night, but there's a chance that the issue you are seeing is fixed in the latest release.  I know that there have been some PRs to work on case insensitivity.  And there have been a few around `ENV_CONVERSIONS` as well.  However, there's still at least one bug that I know about in `ENV_CONVERSIONS`, but it *should* be "masked" by other code at the moment.

You *might* try installing the latest nightly release from [here](https://github.com/nushell/nightly) to see if it fixes it.

**Comment by wavesinaroom** [comment] 2024-12-19 03:34
Alright, what I got from your answers is that Nushell needs to make conversions under the hood to display the output as a table (one of its key feature) but that doesn't stop there. Nushell also needs conversions to run commands, that's interesting.

Oddly we don't get `Path` or `PATH` but `path`. I heard that Windows path is not case sensitive if I'm not mistaken but again I'm just starting to learn Nushell and Windows after some time gravitating around linux.

This is the output for the Powershell command you wanted me to run

```
Name                           Value
----                           -----
path                           C:\Program Files\Rio\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Inte...
```

**Comment by wavesinaroom** [comment] 2024-12-19 03:35
Sure @NotTheDr01ds! Have a good sleep. Thanks again for taking time to help me out!

**Comment by WindSoilder** [comment] 2024-12-19 03:36
> cc: @WindSoilder Does this look anything like what you were experiencing?

Nope, I figure out the issue is because of [conda.nu](https://github.com/nushell/nu_scripts/blob/main/modules/virtual_environments/conda.nu)

**Comment by NotTheDr01ds** [comment] 2024-12-19 03:45
> This is the output for the Powershell command you wanted me to run

Ah - That's likely the problem.

I wonder why installing the optional OpenSSH feature changed that on you - Or perhaps it was something else.

I'm not sure how to get Windows to switch that back to `Path` (which would be the normal Windows case), but I do ***think*** the Nightly has the fix you need.

**Comment by NotTheDr01ds** [comment] 2024-12-19 03:47
@wavesinaroom 

> what I got from your answers is that Nushell needs

And yes, that was an excellent summary of my late night "thinking out loud" :-)

**Comment by fdncred** [comment] 2024-12-19 03:47
> I'm not sure how to get Windows to switch that back to Path

You have to make sure the registry is Path under HKCU and HKLM

**Comment by wavesinaroom** [comment] 2024-12-20 03:12
@NotTheDr01ds, @fdncred thanks a lot for giving me hints to troubleshoot this issue! I found how to switch back `path` into `Path`. Here's the steps to follow

* Open `Edit the system environment variables` Control Panel option from the start menu
* Click on the `Environment variables` button at the bottom of the dialogue just beneath the `Start-up and Recovery sections`
* Click on the `path` (which causes the problem) and then `Edit` button in the `System variables` section. That will open a new dialogue with a long list of paths
* Click on `Edit text...` button, it will open a warning pop up, click on `Ok`
* Lastly change the `Variable name` field to `Path`

Hope this could be useful for anyone with name issues with system variable names. The key aspect is to check the system variable section not the user one

Have a good one folks! 

Thanks for your time!

**Closed** 2024-12-20 03:12 UTC
Labels: question
