### ISSUE TITLE
Freeze when executing `^ps -ef | table`

### ISSUE THREAD

**Issue by sandwoodK** [nushell/nushell#6679] opened 2022-10-08 20:34 UTC
### Describe the bug

```
nushell〉^ps -ef | table
```

freeze. No possibility of stopping that with CTRL-D or CTRL-C

### How to reproduce

1. Start nushell
2. > ^ps -ef | table

Tested several time . get same freeze.
Same freeze with ^ps -au | table 
or with ^ps au  | table 
or ^ps ef  | table

### Expected behavior

no freeze.
Some error message if this command does not make sense ? 

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:53:42 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment] 2022-10-08 21:24
You're right that it shouldn't hang but `^ps -ef | table` won't do anything anyway. You might be trying to do something like `^ps -ef | detect columns`

**Comment by nibon7** [comment] 2022-10-09 07:36
I think it is caused by external commands and sync channels.
See #5625 #6594

**Comment by fdncred** [comment] 2022-10-09 11:42
I think we should just land #5197 which fixes these issues at the sacrifice of #4986

**Comment by WindSoilder** [comment] 2022-10-10 14:02
I think this issue is resolved in latest main

**Comment by sholderbach** [comment] 2022-10-10 14:21
Thanks for tackling that @WindSoilder

**Closed by sholderbach** 2022-10-10 14:21 UTC
Labels: :bug:  bug, external-commands
