### ISSUE TITLE
Possible Incorrect Parsing of Path Environment Variable

### ISSUE THREAD

**Issue by neur1n** [nushell/nushell#7741] opened 2023-01-13 06:13 UTC
### Describe the bug

As the documentation says, nushell is using different path environment variables i.e. `PATH` on Linux/Unix and `Path` on Windows. However it acts like both are parsed in my configuration. I'm not able to describe it clearly with texts so let's skip to the reproducing part.

### How to reproduce

I have a Windows 10 machine, with:
1. Both `Path` and `PATH` are appended with some paths in `env.nu`.
2. `Mambaforge` installed in D:\ProgramFiles\Mambaforge, which is similar to Conda.
3. `python.exe` of version 3.10.6 located in D:\ProgramFiles\Mambaforge, which is the Python of the `base` environment.
4. `D:\ProgramFiles\Mambaforge` is not in `$env.Path` nor `$env.PATH` when nushell starts up, which means if I type `python --version` an error message saying "'python.exe' is not recognized as an internal or external command, operable program or batch file" shows up.
5. Use the [conda module](https://github.com/nushell/nu_scripts/blob/main/virtual_environments/conda.nu) to activate the `base` environment, which means `D:\ProgramFiles\Mambaforge` is in `$env.Path` but not in `$env.PATH` now.
6. Check the results of typing `python --version` multiple times:
![image](https://user-images.githubusercontent.com/17579247/212248823-4835812f-f1d0-426e-a726-24386979d892.png)

As shown in the screenshot, `python.exe` seems to be found occasionally. If I modify the conda module to make it update bot `$env.Path` and `$env.PATH` while activating an environment, such behavior is gone:
![image](https://user-images.githubusercontent.com/17579247/212249211-72dc41c6-0cb2-481f-bfef-6bef7ed441fc.png)

It seems that if both `$env.Path` and `$env.PATH` are set, they are required to be configured identically to make things work properly. I'm pretty sure about this since such issue with the conda module didn't show up before I set both `$env.Path` and `$env.PATH` in `env.nu`, but I need to set them both so that my configuration works on different platforms.

Such issue also occurs with other binary tools (e.g. rg, fd), but Python and Conda should be a good example.

### Expected behavior

Setting `$env.PATH` should not affect things on Windows, and setting `$env.Path` should not affect things on Linux/Uinx.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.0                                   |
| branch             |                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.0                                   |
| build_time         | 2023-01-10 20:35:16 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by ChrisDenton** [comment] 2023-01-13 07:10
Note that in the real Windows environment, the key names are case insensitive. Therefore "Path" and "PATH" are exactly the same. You can test this in powershell or cmd (e.g. by getting "pAtH").

**Comment by Neur1n** [comment] 2023-01-13 07:16
> Note that in the real Windows environment, the key names are case insensitive. Therefore "Path" and "PATH" are exactly the same. You can test this in powershell or cmd (e.g. by getting "pAtH").

So, are they being parsed in turn if multiple path variables exist?

**Comment by kubouch** [comment] 2023-01-13 07:51
What happens if you delete "PATH" completely (remove it from env.nu altogether)?

**Comment by Neur1n** [comment] 2023-01-13 08:04
> What happens if you delete "PATH" completely (remove it from env.nu altogether)?

Then everything works properly, just like that before I added PATH to my configuration.

**Comment by fdncred** [comment] 2023-01-13 13:05
offtopic: @Neur1n you should be able to get back into our Discord server again.

**Comment by Neur1n** [comment] 2023-01-13 15:52
> offtopic: @Neur1n you should be able to get back into our Discord server again.

Thank you.

**Comment by Neur1n** [comment] 2023-01-13 15:55
> Note that in the real Windows environment, the key names are case insensitive. Therefore "Path" and "PATH" are exactly the same. You can test this in powershell or cmd (e.g. by getting "pAtH").

I have another two questions:
1. If "PATH" can be recognized by Windows, is it possible to use "PATH" for all OSs?
2. Which part of Nushell's source code is handling the path variable? I'm interested in it.

Thanks.

**Comment by ChrisDenton** [comment] 2023-01-13 17:36
Ok well, there are two things to be mindful of here. What the Rust stdlib does (which is a relatively thin wrapper around the OS APIs) and what nushell does (i.e. manage its own environment variables).

So starting with the Rust stdlib:
* You can use `Path`, `PATH`, `pAtH`, etc to access the same value when using [`std::env::var`](https://doc.rust-lang.org/std/env/fn.var.html) or [`std::env::set_var`](https://doc.rust-lang.org/std/env/fn.set_var.html).
* Setting `Path` and then `PATH` is equivalent to setting `Path` and then `Path` again. I.e. the last value wins.
* [`std::env::vars`](https://doc.rust-lang.org/std/env/fn.vars.html) returns all environment variables. The keys are in the original case (i.e. if `Path` was set first then it'll be `Path` even if `PATH` was used later). If you do an exact match then obviously it'll only match the exact same case.
* Using [`std::process::Command::envs`](https://doc.rust-lang.org/std/process/struct.Command.html#method.envs) is equivalent to the `set_var` case. `Path` and `PATH` are treated the same so whichever value ends up being set last wins.

I'm not familiar enough with nushell's code to be confident here but as far as I understand it, nu keeps track of its own environment variables in a `Hashmap`. This is necessary because it can have different contexts. The "real" Windows environment is not necessarily the same as the current nushell context. IMHO, the problem is that nushell does not consider environment keys equal if they have different casing. I.e. `Path`, `PATH` and `pAtH` are all considered different. There does however seem to be some special case code to specifically handle `Path` and `PATH`. See https://github.com/nushell/nushell/blob/3dd21c635a66b4585914432e36d03fc8bba59019/crates/nu-engine/src/env.rs#L63-L65

Also see https://github.com/nushell/nushell/blob/main/crates/nu-command/src/system/run_external.rs for how commands are run.

**Comment by fdncred** [comment] 2023-01-13 17:46
It would be nice to standardize this mess once and for all. It's a constant source of papercuts to users. At one time I had pwsh returning Path and cmd returning PATH or vice versa and things were super confusing on Windows. I haven't seen that for a year or so. I'm not sure if Microsoft fixed something or my system just started behaving.

I'd vote for always making path uppercase on all systems.

**Comment by Neur1n** [comment] 2023-01-14 05:58
@ChrisDenton @fdncred @kubouch Thank you all!

It may be closed if it is a known issue instead of a bug.

**Comment by YizhePKU** [comment] 2024-05-02 05:57
I think we can close this now because #12701? Let me know if there're still issues.

**Comment by fdncred** [comment] 2024-05-02 11:47
Sounds good. Thanks.

**Closed as completed by fdncred** 2024-05-02 11:47 UTC

**Comment by colececil** [comment] 2025-02-24 04:40
> I think we can close this now because [#12701](https://github.com/nushell/nushell/pull/12701)? Let me know if there're still issues.

@yizhepku, I believe I am running into this same issue when setting `PATH` using `load-env`. I am running on Windows 11 with Nushell v0.102.0.

Most of the time, it works as expected, like so:
```
~> $env.path | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
~> $env.PATH | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
~> load-env {PATH: []}
~> $env.path | first 5
╭────────────╮
│ empty list │
╰────────────╯
~> $env.PATH | first 5
╭────────────╮
│ empty list │
╰────────────╯
```

However, in occasional Nushell sessions I'll get this:
```
~> $env.path | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
~> $env.PATH | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
~> load-env {PATH: []}
~> $env.path | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
~> $env.PATH | first 5
╭────────────╮
│ empty list │
╰────────────╯
```

The issue seems session-dependent. In other words, if I get a Nushell session where it's not working, it seems to consistently not work:
```
~> load-env {PATH: []}
~> $env.path | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
~> $env.PATH | first 5
╭────────────╮
│ empty list │
╰────────────╯
~> load-env {PATH: []}
~> $env.path | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
~> load-env {PATH: []}
~> $env.path | first 5
╭───┬──────────────────────────╮
│ 0 │ C:\Python39\Scripts\     │
│ 1 │ C:\Python39\             │
│ 2 │ C:\WINDOWS\system32      │
│ 3 │ C:\WINDOWS               │
│ 4 │ C:\WINDOWS\System32\Wbem │
╰───┴──────────────────────────╯
```

When this issue happens, only the version of `PATH` with the case matching what was given in `load-env` is updated. So in the examples above `PATH` gets updated by `load-env`, but not `path`, `Path`, `PaTh`, etc. This is a problem for me because Nushell is not finding executables in a directory this is only in the all-caps `PATH` but not in the others.

**Comment by fdncred** [comment] 2025-02-24 12:48
I'm guessing this is because Windows like it to be written `Path` so setting `PATH` is an entirely different env var. It looks to me like our case-insensitive path changes are only for retrieval and not assignment. It would be good to fix this but until that happens, it's probably best to use `Path`.

**Comment by colececil** [comment] 2025-02-24 13:52
Thanks for the suggested workaround, @fdncred. If I use `Path`, will this work across platforms? 

And should we open a separate issue to track this case?

**Comment by fdncred** [comment] 2025-02-24 14:03
>  If I use Path, will this work across platforms?

probably not

> And should we open a separate issue to track this case?

probably so

**Comment by colececil** [comment] 2025-02-24 16:20
😅
Fortunately, in my case, the environment variables being passed in to `load-env` are produced dynamically by an application, so we should be able to have it decide between `PATH` or `Path` based on the OS.

I'll go ahead and create a separate GitHub Issue for this. Thanks!

**Comment by fdncred** [comment] 2025-02-24 17:40
You can do something like this.
```nushell
let pathvar = if "PATH" in $env { "PATH" } else { "Path" }
load-env {
    $pathvar: (
        $env | get $pathvar |
        split row (char esep) |
        prepend 'C:\Apps\Just' |
        prepend 'c:\Apps\carapace' |
        prepend 'C:\Users\dschroeder\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin' |
        prepend 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin'
    )
}
```
