### ISSUE TITLE
nushell sometimes panic

### ISSUE THREAD

**Issue by chen244** [nushell/nushell#4751] opened 2022-03-06 13:53 UTC
### Describe the bug

https://asciinema.org/a/pgmei3pr33rzteFpSzCIHiTVd

When I tab after ./C it panic

### How to reproduce

1. Enter into the nushell folder and cargo run
2. input "open ./C"
3. then Tab
4. It panic

My Environment is Archlinux,

### Expected behavior

Not panic

### Screenshots

https://asciinema.org/a/pgmei3pr33rzteFpSzCIHiTVd

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.59.1                                      |
| branch             | main                                        |
| short_commit       | 69fd7771                                    |
| commit_hash        | 69fd77712014d54d3ef24cdec5f9252ac03cf83b    |
| commit_date        | 2022-03-06 00:55:37 +00:00                  |
| build_os           | linux-x86_64                                |
| rust_version       | rustc 1.61.0-nightly (c274e4969 2022-03-05) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.61.0-nightly (3d6970d 2022-02-28)   |
| pkg_version        | 0.59.1                                      |
| build_time         | 2022-03-06 12:37:11 +08:00                  |
| build_rust_channel | debug                                       |
| features           | default, which                              |
| installed_plugins  |                                             |

**Comment by kubouch** [comment] 2022-03-06 14:59
I could not reproduce it. However, when I type `open ./C<tab>`, the `C` will get deleted when the menu pops up.

**Comment by chen244** [comment] 2022-03-06 15:06
> 

It seems it will happened in the fold of mine, In other fold it won't happened

**Comment by chen244** [comment] 2022-03-06 15:06
> I could not reproduce it. However, when I type `open ./C<tab>`, the `C` will get deleted when the menu pops up.

It seems it will happened in the fold of mine, In other fold it won't happened

**Comment by chen244** [comment] 2022-03-06 15:09
After export RUST_BACKTRACE=1
```
/home/cht/git/nushell〉open ./Cthread 'main' panicked at 'attempt to subtract with overflow', /home/cht/.cargo/git/checkouts/reedline-e42026a78d91c510/7c5f20d/src/engine.rs:609:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/panicking.rs:48:5
   3: reedline::engine::Reedline::handle_editor_event
             at /home/cht/.cargo/git/checkouts/reedline-e42026a78d91c510/7c5f20d/src/engine.rs:609:47
   4: reedline::engine::Reedline::handle_editor_event
             at /home/cht/.cargo/git/checkouts/reedline-e42026a78d91c510/7c5f20d/src/engine.rs:882:27
   5: reedline::engine::Reedline::handle_event
             at /home/cht/.cargo/git/checkouts/reedline-e42026a78d91c510/7c5f20d/src/engine.rs:469:13
   6: reedline::engine::Reedline::read_line_helper
             at /home/cht/.cargo/git/checkouts/reedline-e42026a78d91c510/7c5f20d/src/engine.rs:446:23
   7: reedline::engine::Reedline::read_line
             at /home/cht/.cargo/git/checkouts/reedline-e42026a78d91c510/7c5f20d/src/engine.rs:348:22
   8: nu::repl::evaluate
             at ./src/repl.rs:242:21
   9: nu::main
             at ./src/main.rs:215:31
  10: core::ops::function::FnOnce::call_once
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by chen244** [comment] 2022-03-06 15:15
I remove the crates fold, It not panic again

**Comment by chen244** [comment] 2022-03-06 15:21
https://asciinema.org/a/TRyNHb4jRBispfFKbnGehV6ru

Haha

**Comment by chen244** [comment] 2022-03-06 15:25
https://asciinema.org/a/jC9CfXWBxlWDqvqk0tZiaCYld
I fond it will happened when meed uppercase and lowercase at the same time. Any char is ok.

**Comment by jntrnr** [comment] 2022-03-08 01:49
I can reproduce this with the steps above. Thanks!

To reproduce on macOS, open up the latest main in the nushell source directory and do the same steps: `open ./C<tab>`

**Comment by jntrnr** [comment] 2022-03-09 09:44
fixed by https://github.com/nushell/nushell/pull/4779

**Closed by jntrnr** 2022-03-09 09:44 UTC
Labels: bug, 0.60
