### ISSUE TITLE
`input` command should stop at any byte of until_bytes 

### ISSUE THREAD

**Issue by utouto97** [nushell/nushell#10197] opened 2023-09-03 04:43 UTC
### Related problem

https://github.com/nushell/nushell/pull/10150#discussion_r1312357688

The currrent "input" command checks **only first byte** of until_bytes.

### Describe the solution you'd like

"input" command should stop at any byte of until_bytes string.

**Comment by amtoine** [comment] 2023-09-03 08:28
@utouto97 
can you give an example command involving `input`, the associated user input and the unexpected output? not sure i see what the issue is here :innocent:

**Comment by fdncred** [comment] 2023-09-03 12:22
I think what @utouto97 means is that, you should be able to say do
```nushell
let user_input = (input --bytes-until ABC)
```
and the input only stop when `ABC`, collectively, is seen. Right now, it'll stop when `A` is seen.

**Comment by amtoine** [comment] 2023-09-03 16:13
ooh got it :+1: 

yeah sounds senbible.
i would also understand something like `--bytes-until ["A", "B", "C"]` as saying "until either one of 'A', 'B' or 'C'", but it's not even the current behaviour, it just quits on the first one :thinking:

**Comment by J-Kappes** [comment] 2023-09-05 10:34
I'm currently casting everything to bytes from data that was already String/chars. That doesn't make sense, does it? Might as well compare chars.

**Comment by J-Kappes** [comment] 2023-09-18 09:39
This should be reopened since the PR got reverted, shouldn't it?

**Comment by fdncred** [comment] 2023-09-18 11:59
This revert https://github.com/nushell/nushell/pull/10382 hasn't landed yet, but I'm fine with this staying open.

**Closed** 2023-10-12 15:01 UTC
Labels: enhancement, good first issue
