### ISSUE TITLE
nushell crashed in Windows Terminal when running the `help` command

### ISSUE THREAD

**Issue by Lucretiel** [nushell/nushell#2440] opened 2020-08-27 21:46 UTC
**Describe the bug**
When running the `help` command in nushell, I see the following output, followed by a crash:

```
C:\Users\Lucre> help
Welcome to Nushell.

Here are some tips to help you get started.
  * help commands - list all available commands
  * help <command name> - display help about a particular command

Nushell works on the idea of a "pipeline". Pipelines are commands connected with the '|' character.
Each stage in the pipeline works together to load, parse, and display information to you.

[Examples]

List the files in the current directory, sorted by size:
    ls | sort-by size

Get information about the current system:
    sys | get host

Get the processes on your system actively using CPU:
    ps | where cpu > 0

You can also learn more at https://www.nushell.sh/book/
Error: Io(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })
```

This error seems to only occur in [Windows Terminal](https://github.com/microsoft/terminal), not in the older `powershell.exe` or `cmd.exe`. Additionally, this error only seems to occur with `help`, with no arguments; there is no such issue when running `ls`, `ps`, or `help commands`.

Whatever the problem is, it seems to have something to do with echoing non-table content; I get the same crash behavior when I run `echo hello`, but *not* when I run `echo`, `echo hello world`, or `^echo hello`.

**To Reproduce**
1. Run `help` or `echo hello` in Windows Terminal

**Expected behavior**
The command should complete without the shell crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/1823405/91496852-e1399680-e88a-11ea-8fcd-2f2f4db02483.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10, Version 2004, Build 19041.450
 - Terminal: Windows Terminal 1.2.2381.0
 - Nu version (you can use the `version` command to find out): 0.18.1

**Comment by Lucretiel** [comment] 2020-08-27 21:56
Update: This problem also appears in Alacritty 0.5.0

**Comment by jonathandturner** [comment] 2020-08-28 05:11
We've seen issues like this as part of `rustyline`, the crate we use to do the line editing. Here's one example: https://github.com/kkawakam/rustyline/issues/359

I've filed https://github.com/kkawakam/rustyline/issues/433 as an upstream issue for this one. Hopefully they'll be able to fix it.

**Comment by jonathandturner** [comment] 2020-08-28 19:24
@Lucretiel would you be able to build a debug-version of Nu? If we could see the backtrace when it crashes, we can hand that to the folks working on the `rustyline` crate so they can track down what's happening.

**Comment by Lucretiel** [comment] 2020-08-28 20:49
Sure thing

**Comment by Lucretiel** [comment] 2020-08-28 21:54
This isn't a "crash" in the traditional sense (uncaught panic), so I'm not getting a backtrace. It appears to be a normal debug print of some kind of error condition.

**Comment by jonathandturner** [comment] 2020-08-28 23:35
Interesting. If you change the `?` in that `fn main()` to be `.unwrap()` we might be able to get a full panic and the full backtrace.

Hadn't even thought we might be hiding our backtraces like that before

**Comment by Lucretiel** [comment] 2020-08-29 00:00
Unfortunately, despite replacing every `?` with `.unwrap()` in both `src/main.rs` *and* `nu-cli/src/lib.rs` *and* replacing all the `std::process::exit` calls with `panic!`, I'm still not able to get a backtrace. I can only assume that something deeper in the call tree is calling `process::exit`.

**Comment by jonathandturner** [comment] 2020-08-29 18:47
Not sure what to try next in Nu to see if we can find it.

One alternative thing to try is to build: https://github.com/kkawakam/rustyline and run examples/example and see if you see the same thing. It may take printing out a long bit of text like the help text, which would mean changing the example a bit.

That's really the only thing that comes to mind.

**Comment by Lucretiel** [comment] 2020-08-29 18:50
How confident are we that rustyline is the underlying cause? I'm happy to dig into the nu codebase some more to see if I can find where it calls out to rustyline and see if that's where it's happening.

**Comment by jonathandturner** [comment] 2020-08-29 19:10
I'd say fairly confident. While it's possible it's something else, we've seen this error come from rustyline a number of times in the past.

**Comment by Lucretiel** [comment] 2020-08-30 04:43
Alright, I'll keep looking. I'm fairly sure this is being caused by a process::exit somewhere, so it might be worth trying to replace those paths with errors + returns so that the control flow is less surprising

**Comment by Lucretiel** [comment] 2020-09-01 21:03
Can you assign this to me in github so it stays in my dashboard?

**Comment by jonathandturner** [comment] 2020-09-01 21:16
@Lucretiel done

**Comment by Lucretiel** [comment] 2020-09-02 01:11
Well, I'm still trying to track down the exact failure moment, but my current guess right now is that there are some hardcoded constants on windows that are assuming you're using cmd.exe

**Comment by Lucretiel** [comment] 2020-09-02 18:58
This pull request should fix the crash, though there may still be underlying issues with the actual cursor movement. It's still not clear to me why that call fails in Windows Terminal and Alacritty but not cmd.exe. Maybe an ANSI thing?

**Comment by jonathandturner** [comment] 2020-09-02 19:32
It could be. I run Nu via Windows Terminal directly and haven't seen the issue in a while, but I did see other folks saying they had various ANSI issues with Windows Terminal depending on the version of the terminal they were using.

**Comment by Lucretiel** [comment] 2020-09-02 19:45
What version of windows terminal? Does this issue not reproduce for you?

**Comment by jonathandturner** [comment] 2020-09-02 19:50
```
Windows Terminal
Version: 1.2.2381.0
```

I can't reproduce it here.

**Comment by fdncred** [comment] 2020-09-11 16:52
Thanks for your help on this @Lucretiel

**Comment by jonathandturner** [comment] 2020-09-17 06:04
Should hopefully be fixed by https://github.com/nushell/nushell/pull/2565. If it's not, please reopen so we can investigate further.

**Comment by jonathandturner** [comment] 2020-09-17 06:05
@Lucretiel  - and thanks for the original fix to rustyline!

**Closed by jonathandturner** 2020-09-17 06:04 UTC
