### ISSUE TITLE
version `GLIBC_2.29' not found (required by nu)

### ISSUE THREAD

**Issue by liigo** [nushell/nushell#3825] opened 2021-07-23 03:11 UTC
### Describe the Bug

```
liigo@CW-LIIGO:~$ nu
nu: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by nu)
liigo@CW-LIIGO:~$ ls /lib/x86_64-linux-gnu/ld-*.so
/lib/x86_64-linux-gnu/ld-2.28.so
```

### To Reproduce

just run `nu`

### Expected behavior

nu runs normally

### Additional Context

```
liigo@CW-LIIGO:~$ uname -a
Linux CW-LIIGO 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
```

```
root@debian:~# uname -a
Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

**Comment by fdncred** [comment] 2021-07-23 13:06
Thanks, but this appears to be a dupe of #3737

**Closed by fdncred** 2021-07-23 13:06 UTC
Labels: duplicate
