### ISSUE TITLE
Incompatible types when using `where` command on dates

### ISSUE THREAD

**Issue by Kydlaw** [nushell/nushell#5688] opened 2022-05-30 19:04 UTC
### Describe the bug

I discovered Nushell today and really like the concept (thank you for your amazing work!).
However, I stumble on some kirks while poking around.

Namely, I tried the where clause on files modified in my Temp dir.

I'm obviously doing something wrong, but according to the doc it should have been working I think.

### How to reproduce

0. Configuration
   1. Windows 10 (version 19044)
   2. Windows Terminal
   3. Installed using `winget install nushell`
   4. Followed https://www.nushell.sh/book/installation.html#setting-the-default-shell-windows-terminal
1. `ls | where modified >= (date now) - 2wk` (I also tried `ls | where 'modified' >= (date now) - 2wk`)

Results in (see screenshot):

```
Error: nu::shell::type_mismatch (link)

  × Type mismatch
   ╭─[entry #45:1:1]
 1 │ ls | where modified >= (date now) - 2wk
   ·                     ─┬
   ·                      ╰── needs compatible type
   ╰────
```

### Expected behavior

I expect to have the table of the files modified in the last two weeks.

### Screenshots

![image](https://user-images.githubusercontent.com/26744886/171048152-a48b572f-1ad0-4a69-83fb-9377d3c45872.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             |                                                 |
| commit_hash        | 06cf3fa5ad8c8b1d1351c81ccea59a1f8d588dc9        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.63.0                                          |
| build_time         | 2022-05-25 01:15:47 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment] 2022-05-30 20:18
Thanks for the detailed bug report! I can't reproduce this on `main`; I wonder if it's a bug that was recently fixed.

![image](https://user-images.githubusercontent.com/26268125/171055170-c2a47131-fdaf-401e-92f9-bd202b9ae752.png)

**Comment by fdncred** [comment] 2022-05-30 21:18
Seems ok on Mac.
<img width="835" alt="Screen Shot 2022-05-30 at 4 17 58 PM" src="https://user-images.githubusercontent.com/343840/171060026-85eaadb3-39f3-4c42-a104-19c012b5dfee.png">

**Comment by fdncred** [comment] 2022-05-30 21:21
I'm wondering if this is related to the problem where some files act weird in that you can't get the date. I can't remember the issue but if you don't have permissions weird things happen, although you should have permissions to the temp folder. I'd try the same thing in different folders to see if you get different results. Maybe you can nail down exactly how/why this is happening.

**Comment by Kydlaw** [comment] 2022-05-30 23:12
I tried to run the same command on different dir in Windows, and I think it is a permission issue indeed.

It definitely works on most of them, where I have all permissions.
In WINDOWS/system32, where I have no permission I have the same error as above.
However, I'm supposed to have all permission on AppData/Local/Temp, so it should work?

I think this is just a Windows corner case, sorry for the inconvenience...

**Comment by fdncred** [comment] 2022-05-31 00:15
We may be returning `$nothing` when we can't get information due to permissions and then if we try to compare dates to `$nothing` maybe it pukes. Whatever it is, corner case or not, it needs to work.

**Comment by hustcer** [comment] 2022-05-31 02:35
Closing in favor of https://github.com/nushell/nushell/issues/4975

**Closed by hustcer** 2022-05-31 02:35 UTC
