### ISSUE TITLE
Default parameters don't accept `const` values

### ISSUE THREAD

**Issue by TheLostLambda** [nushell/nushell#13276] opened 2024-06-30 13:43 UTC
### Describe the bug

I've written a bit of code like this:

```nu
const x = 'cool/stuff.txt'

def main [file = $x] {
  # ...
}
```

But got the following error: `Default values should be constant expressions.`, telling me it expected `$x` to be a constant value!

### How to reproduce

1. Write a script containing the code above
2. Attempt to run it

### Expected behavior

The intent was for the above to be the same as:

```nu
def main [file =  'cool/stuff.txt'] {
  # ...
}
```

But I wanted to abstract those defaults into some `const` values since they are currently some very long paths!

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.94.1                                                            |
| major              | 0                                                                 |
| minor              | 94                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (built from a source tarball) |
| cargo_version      | cargo 1.78.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash, which                   |
| installed_plugins  |                                                                   |

### Additional context

The maybe is linked to the ongoing effort at #10239, but I'm not certain — it just felt like something that *should* work, but that didn't!

**Comment by NotTheDr01ds** [comment] 2024-06-30 21:07
I'm not able to reproduce this on 0.95 or 0.94.2.  Given that both `def` and `const` are parser keywords, I don't know why this isn't working for you.

Can you add a `version` in your script to double-check the Nu version that the script is running in?

**Comment by TheLostLambda** [comment] 2024-07-01 10:31
Uh oh! I'm currently stuck on `0.94.1`! I'll try a newer version and see if that works!

**Comment by NotTheDr01ds** [comment] 2024-07-01 13:29
Just for fun, I also tested on 0.89 and it was working there as well.

**Comment by sholderbach** [comment] 2024-07-13 15:56
Closing this one as it seems to work on the latest main.

**Closed by sholderbach** 2024-07-13 15:56 UTC
Labels: needs-triage
