### ISSUE TITLE
Nu adds uneceseray quotes to ints, giving type errors

### ISSUE THREAD

**Issue by FilipAndersson245** [nushell/nushell#5472] opened 2022-05-07 16:32 UTC
### Describe the bug

Nu seems to add quotes to script file inputs when not necessary, making incorrect typings.

the following script does not execute.
```
# foo.nu
def main [a: int] {}
```

### How to reproduce

1. Have a scriptfile with a type limited parameter. example can be seen above.
2. Try to execute the script `nu foo.nu 5`

### Expected behavior

It should not give error upon running.

### Screenshots

![image](https://user-images.githubusercontent.com/17986183/167263278-3f0cedd8-8e59-41c2-98e0-5f17066b90b8.png)
![image](https://user-images.githubusercontent.com/17986183/167263308-3da2de8f-a8f2-42f7-a86d-e59db872cd98.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             | master                                          |
| tag                |                                                 |
| short_commit       | 1cb449b2                                        |
| commit_hash        | 1cb449b2d14bcd77305024716db13a7dbecaede7        |
| commit_date        | 2022-05-07 12:33:33 +00:00                      |
| build_os           | windows-x86_64                                  |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)             |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-07 16:06:29 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

**Comment by merelymyself** [comment] 2022-05-09 15:13
This was happening because of 

https://github.com/nushell/nushell/blob/ae9c0fc138d705a6d1b7f6dacd76165c03d4a031/crates/nu-parser/src/deparse.rs#L1-L14

Not quite sure how to deal with this, while still resolving #5370 and #5371. @uasi , any ideas?

**Comment by uasi** [comment] 2022-05-10 03:52
@merelymyself We have to quote values or not depending on the parameter type. For example, `-10` must not be quoted if and only if the parameter is `int`:

```
〉def main_int [x: int] { echo $x }

〉main_int -10
-10

〉main_int "-10"
Error: nu::parser::parse_mismatch (https://docs.rs/nu-parser/0.62.1/nu_parser/enum.ParseError.html#variant.Expected)

  × Parse mismatch during operation.
   ╭─[entry #3:1:1]
 1 │ main_int "-10"
   ·          ──┬──
   ·            ╰── expected int
   ╰────
```

```
〉def main_string [x: string] { echo $x }

〉main_string -10
Error: nu::parser::unknown_flag (https://docs.rs/nu-parser/0.62.1/nu_parser/enum.ParseError.html#variant.UnknownFlag)

  × The `main_string` command doesn't have flag `-1`.
   ╭─[entry #5:1:1]
 1 │ main_string -10
   ·              ┬
   ·              ╰── unknown flag
   ╰────
  help: use main_string --help for a list of flags

〉main_string "-10"
-10
```

**Comment by merelymyself** [comment] 2022-05-10 04:12
@uasi I tried using `.parse()` to check for this. Should work because unquoted ints translate nicely to strings but not the other way round.

```
/home/gabriel/CodingProjects/nushell〉cat foo.nu                              
def main [a: string] { echo $a }
/home/gabriel/CodingProjects/nushell〉target/debug/nu foo.nu 5                
5
```

**Comment by uasi** [comment] 2022-05-10 05:54
@merelymyself unquoted _negative_ ints don't, though.

```
〉cat foo.nu
def main [a: string] { echo $a }

〉target/debug/nu foo.nu -10
Error: nu::parser::unknown_flag (https://docs.rs/nu-parser/0.62.1/nu_parser/enum.ParseError.html#variant.UnknownFlag)

  × The `main` command doesn't have flag `-1`.
   ╭─[<commandline>:1:1]
 1 │ main -10
   ·       ┬
   ·       ╰── unknown flag
   ╰────
  help: use main --help for a list of flags

〉target/debug/nu foo.nu "-10"
Error: nu::parser::unknown_flag (https://docs.rs/nu-parser/0.62.1/nu_parser/enum.ParseError.html#variant.UnknownFlag)

  × The `main` command doesn't have flag `-1`.
   ╭─[<commandline>:1:1]
 1 │ main -10
   ·       ┬
   ·       ╰── unknown flag
   ╰────
  help: use main --help for a list of flags
```

**Comment by merelymyself** [comment] 2022-05-10 06:26
Good catch, @uasi . Will have to look more into this.

**Comment by uasi** [comment] 2022-05-10 07:53
Let's put things in perspective. Command line arguments are, by design, an array of strings. To convert strings to values of the appropriate type, we quote (or not quote) arguments by `escape_quote_string_*()`, concatenate the results, and evaluate the whole string as a command invocation.

The problem is, it is sometimes impossible to determine what the appropriate type is from a given string alone. Does the string `-10` mean a negative int? If the signature of the main function is `[x: int]`, we can probably say yes. So what if the signature is `[x: any]`? Does the string `[a b]` mean a string or an array of two bare strings? Does `--flag` mean a flag? We can't be sure, because if the signature is `[--flag: bool, x?: string]`, it can either be a flag or a string value to `x`.

**Closed** 2022-06-11 08:52 UTC
Labels: bug
