### ISSUE TITLE
Error calculating file size

### ISSUE THREAD

**Issue by fractal-86** [nushell/nushell#4687] opened 2022-03-01 12:48 UTC
### Describe the bug

I created the file using the fallocate command in Linux and the file size is correct when I use ls -hl in bash.
But in nushell the ls -l command does not show the correct file size

### How to reproduce

![nu](https://user-images.githubusercontent.com/94535450/156171527-b13a9b36-0c2e-4b33-b3ad-200279df6968.png)
![bash](https://user-images.githubusercontent.com/94535450/156171528-9eb63d37-367e-4f28-8567-b47331f975a6.png)
commands most result same 

### Expected behavior

results of commands must be same

**Comment by fdncred** [comment] 2022-03-01 12:50
I wonder if this has to do with this configuration point.
`filesize_format: "auto" # b, kb, kib, mb, mib, gb, gib, tb, tib, pb, pib, eb, eib, zb, zib, auto`

**Comment by jntrnr** [comment] 2022-03-01 12:51
@fdncred - I was wondering if when you set the filesizes to not be in metric if that would also fix it.

**Comment by hustcer** [comment] 2022-03-09 09:53
This may be  caused by `filesize_format ` config, and I will close it, please reopen if you still have issues.

**Closed by hustcer** 2022-03-09 09:53 UTC
