### ISSUE TITLE
Automatic conversion from external command

### ISSUE THREAD

**Issue by sandorex** [nushell/nushell#1432] opened 2020-02-23 18:59 UTC
The idea is simple, some way for an external command to directly output table if its running in nushell (can be checked using `nu` environment variable), which enables applications to support nushell while also supporting regular shell

The solution i thought about is to use an ANSI escape sequence (preferably one that isn't already used) that tells nushell which format the command is outputting so it knows how to parse it

**Comment by thegedge** [comment] 2020-02-23 19:14
Duplicate of https://github.com/nushell/nushell/issues/451

The idea in #451 is to have this (potentially) as part of configuration. One could describe the output format of the external (e.g., `from-ssv --aligned-columns`) and nu would take care of doing that automatically for the user.

Closing. Let me know if that issue won't fully address your use case 🙂

**Closed by thegedge** 2020-02-23 19:14 UTC
