### ISSUE TITLE
subcommand completion broken in 0.75.1

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#8021] opened 2023-02-09 23:11 UTC
### Describe the bug

Before, when typing command + space + tab, I would get a list of the subcommands, but now I only get a list of the files in current directory.

### How to reproduce

Already explained, you can try with `str` command

### Expected behavior

I should get the list of subcommands

### Screenshots

https://user-images.githubusercontent.com/5784951/217959762-27e480ae-00d6-4f40-a735-eefc41274d18.mp4

### Configuration

| key                | value                                                                                                                         |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.75.1                                                                                                                        |
| branch             | main                                                                                                                          |
| commit_hash        | d03665754395980c45f39c4dd317283e7ae6728c                                                                                      |
| build_os           | linux-x86_64                                                                                                                  |
| build_target       | x86_64-unknown-linux-gnu                                                                                                      |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                                                                                           |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                                                                                               |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                                                                                           |
| pkg_version        | 0.75.1                                                                                                                        |
| build_time         | 2023-02-07 12:14:45 -03:00                                                                                                    |
| build_rust_channel | release                                                                                                                       |
| features           | database, dataframe, default, trash, which, zip                                                                               |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, gstat, inc, pnet, query, query json, query web, query xml |

**Comment by WindSoilder** [comment] 2023-02-09 23:15
Hi, it's duplicate of  #7821, so I'll close it for now

**Closed by WindSoilder** 2023-02-09 23:15 UTC
