### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by Escapingbug** [nushell/nushell#824] opened 2019-10-14 06:53 UTC
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\ding6\scoop\persist\rustup\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.40.0-nightly (c27f7568b 2019-10-13)
```

Error message:

```
error[E0369]: binary operation `!=` cannot be applied to type `syn::data::Fields`
   --> C:\Users\ding6\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\enum-util
s-0.1.1\src\attr.rs:345:25
    |
345 |             if v.fields != syn::Fields::Unit {
    |                -------- ^^ ----------------- syn::data::Fields
    |                |
    |                syn::data::Fields
    |
    = note: an implementation of `std::cmp::PartialEq` might be missing for `syn::data::Fields`

error[E0369]: binary operation `!=` cannot be applied to type `syn::data::Fields`
  --> C:\Users\ding6\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\enum-utils
-0.1.1\src\iter.rs:76:29
   |
76 |                 if v.fields != syn::Fields::Unit {
   |                    -------- ^^ ----------------- syn::data::Fields
   |                    |
   |                    syn::data::Fields
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `syn::data::Fields`

error[E0369]: binary operation `!=` cannot be applied to type `syn::data::Fields`
  --> C:\Users\ding6\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\enum-utils
-0.1.1\src\from_str.rs:27:25
   |
27 |             if v.fields != syn::Fields::Unit {
   |                -------- ^^ ----------------- syn::data::Fields
   |                |
   |                syn::data::Fields
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `syn::data::Fields`

error[E0369]: binary operation `!=` cannot be applied to type `syn::data::Fields`
  --> C:\Users\ding6\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\enum-utils
-0.1.1\src\conv.rs:22:21
   |
22 |         if v.fields != syn::Fields::Unit {
   |            -------- ^^ ----------------- syn::data::Fields
   |            |
   |            syn::data::Fields
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `syn::data::Fields`

error[E0369]: binary operation `!=` cannot be applied to type `syn::data::Fields`
  --> C:\Users\ding6\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\enum-utils
-0.1.1\src\conv.rs:83:21
   |
83 |         if v.fields != syn::Fields::Unit {
   |            -------- ^^ ----------------- syn::data::Fields
   |            |
   |            syn::data::Fields
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `syn::data::Fields`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0369`.
error: could not compile `enum-utils`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.3.0`, intermediate artifacts can be found at `C:\Users\ding6\AppData
\Local\Temp\cargo-installJl5Eau`
```

I understand that this error is from enum-utils, but still I have no workable plan to fix it.

**Comment by jonathandturner** [comment] 2019-10-14 07:21
This is a duplicate of #811. It should be fixed in the latest master.

**Closed by jonathandturner** 2019-10-14 07:21 UTC
