### ISSUE TITLE
nushell expands items in PATH causing issues in transactional/atomic operating systems relying on symlinks

### ISSUE THREAD

**Issue by yuuyins** [nushell/nushell#6239] opened 2022-08-05 18:05 UTC
### Describe the bug

nushell expands paths in `PATH`. This in an issue for operating systems that implement transaction/atomicity through symlinks, since the older expanded paths from older \"system generations\" might not exist when in a new \"system generation\". So system is neither able to find paths in PATH nor binaries.

### How to reproduce

1.  Install NixOS <https://nixos.org/download.html>

2.  Install home-manager on NixOS <https://nix-community.github.io/home-manager/index.html#ch-nix-flakes>

3.  Enable nushell home-manager, set it as default shell for your user, and rebuild NixOS/home-manager configuration (it won\'t generate any config).

    ``` nix
    { config, pkgs, ... }:

    {
      home-manager.users.yuu = {
        programs.nushell.enalbe=true;
      };

      users.users.yuu.shell = pkgs.nushell;
    }
    ```

4.  Boot NixOS

5.  Get into tty2 Ctrl+Alt+F2

6.  Login (it will ask to generate config, deny `n`)

    1.  notice we are in nushell and can sudo just fine

        ``` nu
        $env.PATH
        /run/wrappers/bin
        /etc/nixos/bin
        /home/yuu/.config/emacs/bin
        /home/yuu/.local/bin
        /home/yuu/.local/share/flatpak/exports/bin
        /var/lib/flatpak/exports/bin
        /home/yuu/.nix-profile/bin
        /etc/profiles/per-user/yuu/bin
        /nix/var/nix/profiles/default/bin
        /run/current-system/sw/bin
        ```

7.  nu (it will ask to generate config, deny `n`)

    1.  `$env.PATH`

        ``` nu
        $env.PATH
        /run/wrappers/wrappers.iNILe0cMSJ
        /etc/nixos/bin
        /home/yuu/.config/emacs/bin
        /home/yuu/.local/bin
        /home/yuu/.local/share/flatpak/exports/bin
        /var/lib/flatpak/exports/bin
        /nix/store/cs0dihfqdm6cphqph5yqhwlsbn75rbfa-libreoffice-7.1.8.1/bin
        /nix/store/6apfxx1l1k26rxjx4bvmrbl4z0rasmzy-user-environment/bin
        /nix/var/nix/profiles/default/bin
        /nix/store/17r9rhic98i80hfvagd91dc6z7z1589i-system-path/bin
        ```

    2.  now paths in PATH are expanded. `/run/wrappers/wrappers.iNILe0cMSJ` still exists, so we can sudo just fine

8.  `sudo nixos-rebuild switch -L --show-trace --flake "/etc/nixos#myNixOS"`

    1.  `$env.PATH`

        ``` nu
        $env.PATH
        /run/wrappers/wrappers.iNILe0cMSJ
        /etc/nixos/bin
        /home/yuu/.config/emacs/bin
        /home/yuu/.local/bin
        /home/yuu/.local/share/flatpak/exports/bin
        /var/lib/flatpak/exports/bin
        /nix/store/cs0dihfqdm6cphqph5yqhwlsbn75rbfa-libreoffice-7.1.8.1/bin
        /nix/store/6apfxx1l1k26rxjx4bvmrbl4z0rasmzy-user-environment/bin
        /nix/var/nix/profiles/default/bin
        /nix/store/17r9rhic98i80hfvagd91dc6z7z1589i-system-path/bin
        ```

    2.  but now `/run/wrappers/wrappers.iNILe0cMSJ` does not exists anymore, because nixos-rebuild relinks `/run/wrappers/bin` to a newer `/run/wrappers/wrappers.`, and removes the old one `/run/wrappers/wrappers.iNILe0cMSJ`.

9.  sudo

    ``` nu
    sudo: /nix/store/17r9rhic98i80hfvagd91dc6z7z1589i-system-path/bin/sudo must be owned by uid 0 and have the setuid bit set
    ```

### Expected behavior

Do not expand anything in `PATH`; do not change `PATH` at all.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0                                    |
| cargo_version      | cargo 1.62.0                                    |
| pkg_version        | 0.65.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Issue seems to have been introduced in <https://github.com/nushell/nushell/pull/5692>.

-   <https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$0NvdUG7Nm4alrm_C5T6u0vUzqSck3y0X0VlHne4EKlY?via=nixos.org&via=matrix.org&via=tchncs.de>
-   <https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$v7IItXpduS29K2s203GbVGoRkEPPugbXTKhNMISLiFs?via=nixos.org&via=matrix.org&via=tchncs.de>
-   <https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$-AhmfQqrs3_qeSplNfq3QIye5kLS1Zy1oGBfseP_1og?via=nixos.org&via=matrix.org&via=tchncs.de>

**Comment by fdncred** [comment] 2022-08-05 18:32
If that PR #5692 is the problem, just take out that `path expand` part in your own env.nu file.

**Comment by yuuyins** [comment] 2022-08-05 18:42
> If that PR #5692 is the problem, just take out that `path expand` part in your own env.nu file.

i had tried removing that `path expand |` and tried again just in case, but the issue persists.

**Comment by kubouch** [comment] 2022-08-05 18:49
Maybe it's hardcoded, I'm not sure. We probably shouldn't do that and leave it up to the user.

I guess the problem is that it resolves the symlink, right?

**Comment by yuuyins** [comment] 2022-08-05 18:52
> I guess the problem is that it resolves the symlink, right?

yes. It should not resolve/expand symlinks.

**Comment by yuuyins** [comment] 2022-08-06 14:43
@fdncred @kubouch it seems it was really only that `path expand |` indeed, now paths are not expanding anymore. i think before it was still expanding because i already was in an X session under nushell.

**Comment by WindSoilder** [comment] 2022-08-06 15:58
Sorry for that, since it's conflict to  #4855, may be it's better to document about it(especially for your case)?

**Comment by yuuyins** [comment] 2022-08-06 16:39
@WindSoilder in the source code or the nushell book?

**Comment by kubouch** [comment] 2022-08-06 16:42
What we could do is to add a flag to `path expand` to not resolve the symlinks. It would still expand `~` and `..` and such but not the symlinks.

**Comment by kubouch** [comment] 2022-08-06 19:05
@yuuyins Are you sure it gets expanded even if you remove `path expand` from the config? I can't reproduce it. When I remove `path expand`, it doesn't expand the PATH entries. Maybe you forgot to reload the config after changing it?

**Comment by yuuyins** [comment] 2022-08-06 19:21
@kubouch 

> @fdncred @kubouch it seems it was really only that `path expand |` indeed, now paths are not expanding anymore. i think before it was still expanding because i already was in an X session under nushell.

did you see that? initially i think the issue was persisting because i did not logout and login again, so even though i changed the config, it was already expanded by then current nushell + X session. After I logout and login again, the issue is gone for good.

**Comment by kubouch** [comment] 2022-08-06 19:57
I didn't that makes sense. Anyway, I'll close this issue since you can just remove the expands from the config. The anti-symlink flag for `path expand` would still be a good idea, though.

**Closed by kubouch** 2022-08-06 19:57 UTC
Labels: investigate
