### ISSUE TITLE
Recursive delete works not for .git on Windows

### ISSUE THREAD

**Issue by Woomy4680-exe** [nushell/nushell#1862] opened 2020-05-21 08:01 UTC
**Describe the bug**
Hello, on my Windows computer I have NuShell version 0.14.0. When I try to delete folders that contain a .git folder, it's impossible even with the `-r` options. I think the .git folder is the problem because if y try to do `rm -r $name/*`all folders is deleted but .git is not deleted.
**To Reproduce**
1. Clone any git repository 
2. try to use `rm -r $name`
3. 

**Expected behavior**
Add a way to do --force like with bash / other shells.

**Screenshots**
![image](https://user-images.githubusercontent.com/57042741/82537021-ac11ff80-9b49-11ea-8d36-76c18e93fc04.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows):Windows
 - Nu version (you can use the `version` command to find out): 0.14.0
 - Optional features (if any): I use default features

**Comment by filalex77** [comment] 2020-05-21 13:17
Reproduced on Windows 10 Pro (10.0.18363.836).

<details>
<summary>Testing logs</summary>

```
~
❯ mkdir testrepo; cd testrepo; git init
Initialized empty Git repository in C:/Users/brigh/testrepo/.git/

testrepo
❯ echo hello | save file.txt

testrepo
❯ ls
──────────┬───────────
 name     │ file.txt
 type     │ File
 size     │ 5 B
 modified │ 1 sec ago
──────────┴───────────

testrepo
❯ git add .

testrepo
❯ git commit -m 'Initial commit'
[master (root-commit) 509e438] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt

testrepo on 📙 master
❯ cd ..

~
❯ rm -r testrepo
error: Could not delete C:\Users\brigh\testrepo
- shell:1:14
1 | rm -r testrepo
  |       ^^^^^^^^ C:\Users\brigh\testrepo

~
❯ rm -r testrepo\*
error: Could not delete C:\Users\brigh\testrepo\.git
- shell:1:16
1 | rm -r testrepo\*
  |       ^^^^^^^^^^ C:\Users\brigh\testrepo\.git

~
❯ rm -rt testrepo
deleted C:\Users\brigh\testrepo

```

</details>

Seems like with `repo/*` can't delete `.git`, and with `--trash` flag it works.

**Comment by ikopysov** [comment] 2020-05-21 22:52
It seems that's because there were some files flagged as read-only. 
This can be reproduced by creating any file and marking it as "read-only" using the properties of the file.

Full test steps:
Create the file, and make it read-only
```
touch test_file
attrib +R test_file
```

Now try to remove it in nu without flags: `rm test_file`
Result: `Could not delete <file_path>`
Add --trash flag and try again: `rm --trash test_file`
Result `deleted <file_path>`. File successfully deleted and appeared in "Recycle Bin"

So in general respecting the "read-only" flag may be a good idea, but because with different flags it behaves differently, regarding this flag, can be confusing, especially considering that there are no information about it.

**Closed** 2020-07-05 01:03 UTC
Labels: bug, good first issue
