### ISSUE TITLE
Multiple commands?

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#1352] opened 2020-02-06 20:29 UTC
Is there a way to chain two commands? `;` and `&&` do not work. How do I run something like?

```
which foo && echo 'hey'
```

**Comment by thegedge** [comment] 2020-02-06 20:39
Definitely something we'll have to explore. We do have https://github.com/nushell/nushell/issues/740, so I'm going to close this one as a duplicate. I encourage you to subscribe to that issue if you want to keep track of  the progress or make suggestions.

**Comment by thegedge** [comment] 2020-02-06 20:39
Duplicate of https://github.com/nushell/nushell/issues/740

**Closed by thegedge** 2020-02-06 20:39 UTC
Labels: duplicate

**Comment by ryanpcmcquen** [comment] 2020-02-06 20:41
Thanks!
