### ISSUE TITLE
Add wasm build to CI checks

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#2367] opened 2020-08-17 20:04 UTC
As @jonathandturner mentioned on Discord ( https://discordapp.com/channels/601130461678272522/711672795565785169/744991976549777438 ), we should add a wasm build to the CI pipeline, to make sure that keeps building when making changes here (right?).

**Comment by jonathandturner** [comment] 2020-08-17 20:34
Yup. The issue is that we have a `minimal` build that does `--no-default-features`, but that's not sufficient to catch issues with the wasm build. We should have a separate build that is specifically the wasm one. In the future we may want to add wasm-based tests also, but for now just ensuring the wasm build still builds is a good first step.

**Comment by jonathandturner** [comment] 2020-08-18 06:10
We can base what we test off the deploy steps for the demo: https://github.com/nushell/demo/blob/main/.github/workflows/deploy-pages.yml

I think all we need to do is to install wasm-pack and then build a small sample that depends on Nu as a similar way to the demo:

```
nu-cli = {git = "https://github.com/nushell/nushell.git", branch = "main", default-features = false}
nu-errors = {git = "https://github.com/nushell/nushell.git", branch = "main", default-features = false}
nu-protocol = {git = "https://github.com/nushell/nushell.git", branch = "main", default-features = false}
nu-source = {git = "https://github.com/nushell/nushell.git", branch = "main", default-features = false}
```

wasm-pack should build this sample with wasm as the target.

**Comment by jonathandturner** [comment] 2020-08-18 19:35
Fixed by https://github.com/nushell/nushell/pull/2372

**Closed by jonathandturner** 2020-08-18 19:35 UTC
