### ISSUE TITLE
String interpolation for backtick-quoted paths

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12330] opened 2024-03-29 16:20 UTC
### Related problem

With the changes to glob expansion in strings, it's no longer possible to do something like:

```Nushell
ls $'($nu.default-config-dir)/*.nu'
```

Of course, this worked in 0.90.

*Aside: Before stopping here and thinking this is just another question that can be answered with `into glob`, please skip to the "Alternatives I've considered" ;-)).*

It's possible to do:

```Nushell
ls `~/.config/nushell/*.nu`
```

But string interpolation is not possible via $`<string>`.

### Describe the solution you'd like

Enable string interpolation for path strings, so that we can use:

```Nushell
ls $`($nu.default-config-dir)/*.nu`
```

With path strings:

* `~` is always treated as the home director (it no longer is for single-and-double-quoted strings, of course)
* Globs are treated as globs (which, again, they no longer are for single/double-quoted strings)

### Describe alternatives you've considered

As mentioned in #12105 (and elsewhere), the current method for handling this type of situation requires `into glob`:

```Nushell
ls ($'($nu.default-config-dir)/*.nu' | into glob)
```

This works, but is so much more unwieldy, verbose, and user-unfriendly than it use to be.  If you can't tell, I'm not a fan ;-).

Adding an option for backtick/path string interpolation would allow for more ergonomic path/glob handling.

**Comment by kubouch** [comment] 2024-03-29 16:29
The output of a string interpolation is a string, which is not expanded by default. You can do `ls ($'($nu.default-config-dir)/*.nu' | into glob)`.

**Comment by kubouch** [comment] 2024-03-29 16:34
The output of a string interpolation is a string, so that IMO works as intended.

Adding a bareword interpolation could work, I think, but the difference between
```
ls $`($nu.default-config-dir)/*.nu`
```
vs.
```
ls $"($nu.default-config-dir)/*.nu"
```
might not be obvious. It might seem confusing that one expands and the other doesn't.

**Comment by NotTheDr01ds** [comment] 2024-03-29 17:06
> It might seem confusing that one expands and the other doesn't.

Given that a backtick-quoted string is supposed to represent a path, it will hopefully be obvious that the behavior should be different. But also, to be fair, the backtick quoted behavior is *already* different (and should be):

* ``ls `*` ``: Returns a list of all files in the current directory matching the glob pattern `*`
* `ls '*'`: Returns a file or directory literally named `*`

The feature request is just to add string-interpolation so that we can do it dynamically once again (without `into glob`).

**Comment by NotTheDr01ds** [comment] 2024-03-29 17:09
> Adding a bareword interpolation could work

Hmm - What would that look like?

**Comment by kubouch** [comment] 2024-03-29 18:55
Backticks define barewords, not strings. The intention of backticks is to have a similar behavior as if you typed the words without anything (this it not 100% consistent everywhere but that's the intention). So
```nushell
$`...`
```
would be a bareword interpolation, not a string interpolation.

**Comment by NotTheDr01ds** [comment] 2024-03-29 21:41
> Backticks define barewords, not strings

Hmm - Okay.  They *used* to represent paths according to the doc, but I see that's been changed.  I was going on the assumption that `` `<strings>` `` were still paths, especially since they still seem to be behaving that way in some situations.

**Comment by WindSoilder** [comment] 2024-03-30 01:12
Follows the same rules to `backtick-quoted` word, I think we can't assign bareword interpolation to a variable.

**Comment by kubouch** [comment] 2024-03-30 09:37
Yeah. In theory, the following should be identical:
```nushell
let x = git status
let x = `git status`
```
They both should run the command and save the result to `x` (in reality, the backticks seem to be broken in this case). On the other hand, `let x = 'git status'` will save the string to `x`.

**Comment by NotTheDr01ds** [comment] 2024-03-30 16:29
Ok, so somewhere in the past I had read that backticks indicated a path, but that's *not really* the case. 

I probably need to close this as an X/Y problem, but is there any way we can get string interpolation to work with globs short of `into glob`?  It's something we *used* to have - it was nice and clean.  Now we've lost it.

Personally, I'd much rather have to backslash escape `*` when I want a literal * in a string.  But it seems that Nu tends to shy away from this pattern, so it's either all (allow globs in strings, like in 0.90) or nothing (don't allow globs in strings, like in 0.91).

**Comment by kubouch** [comment] 2024-03-31 17:55
We made it stricter to avoid unwanted glob expansion. Now, the rules are more consistent and predictable, you can look up the PR that added `into glob` and related issues for more context, it solved numerous problems. If we auto-expand by default and require `std escape-glob`, we'd have users complaining about that. Can't have both.

**Comment by WindSoilder** [comment] 2024-05-05 23:08
Sorry I think it'd be better to not introducing `bareword interpolation`.  There are some reasons collected from #12548 :
1. Adding runtime interpolation makes backticks more like strings.
2. Nushell will have too much way expand glob if user want to expand variable, it's not good and make user confused which way is better.

So I will close the issue for now.

**Closed by WindSoilder** 2024-05-05 23:08 UTC
Labels: enhancement, quoting/expansion, needs-triage, glob-expansion
