### ISSUE TITLE
`which` returns an empty list for some built-in commands

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6762] opened 2022-10-16 07:16 UTC
### Describe the bug

`which` normally returns a table when given a built-in command's name. However, for some built-in commands, it returns an empty list.

### How to reproduce

```
〉which replace-all
〉which parse
╭───┬───────┬──────────────────────────┬──────────╮
│ # │  arg  │           path           │ built-in │
├───┼───────┼──────────────────────────┼──────────┤
│ 0 │ parse │ Nushell built-in command │ true     │
╰───┴───────┴──────────────────────────┴──────────╯
```
The missing commands are:  agg, agg-groups, all-false, all-true, and, arg-max, arg-min, arg-sort, arg-true, arg-unique, as, as-date, as-datetime, cache, concatenate, contains, count, count-null, cumulative, df-not, drop-duplicates, drop-nulls, dtypes, dummies, explode, expr-not, fill-na, fill-null, filter, filter-with, get-day, get-hour, get-minute, get-month, get-nanosecond, get-ordinal, get-second, get-week, get-weekday, get-year, gstat, inc, is-duplicated, is-in, is-not-null, is-null, is-unique, limit, list, lowercase, max, mean, median, melt, min, n-unique, or, order-by, over, quantile, replace-all, rolling, sample, set, set-with-idx, shape, shift, slice, std, str-lengths, str-slice, strftime, unique, uppercase, value-counts, var, when, with-column, sum, replace, query, join.

### Expected behavior

I expect every command to be listed as "Nushell built-in command" by `which`. I also expect `which` to return $nothing instead of an empty list when it can't find anything.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment] 2022-10-16 10:44
These are dataframe or database commands that are exposed via command overloading and treated not correctly outside their context of a pipeline with the special types for dataframes/database connections

**Comment by fdncred** [comment] 2022-10-16 12:23
Thanks for the report but this is mostly a dupe of #6743. Let's keep this open to consider the returning `$nothing` part. I think we could be more consistent with commands in general on whether we return `$nothing` or empty lists.

**Comment by sholderbach** [comment] 2024-08-02 20:32
Closed by the removal of our old command-overloading system

**Closed by sholderbach** 2024-08-02 20:32 UTC
Labels: command-overloading
