### ISSUE TITLE
sum command panics on rows as input

### ISSUE THREAD

**Issue by rutrum** [nushell/nushell#1787] opened 2020-05-15 02:03 UTC
**Describe the bug**
When piping a row into the sum command, nushell panics.

**To Reproduce**
```
cal | nth 1 | sum
```
This gives the following panic:
```
thread 'main' panicked at 'not implemented: Internal error: can't add non-primitives.', /home/rutrum/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-protocol-0.14.0/src/value.rs:492:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
You can also do a more nonsensical example with the same result:
```
ps | nth 1 | sum
```

**Expected behavior**
Should sum the values of the row if applicable, or throw an error otherwise.

**Configuration (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version 0.14.0

**Comment by DangerFunPants** [comment] 2020-05-17 02:52
Hello! I was considering tackling this issue as a possible first contribution. I have a few questions about the semantics of the `sum` command in more complex cases. For example, in the case mentioned in the issue:
```
cal | nth 1 | sum
```
we presumably expect the output to be the sum of all the dates that comprise the second week of the current month. But what is the expected behaviour in the following case? 
```
cal | first 2 | sum
```
We could output a list where the n_th element of said list is the sum of the n_th row of the input, or we could output the sum of all the values in each of the rows as a scalar. We could also implement the sum function such that it just errors in the case that it is passed multiple rows. 

I think that the most sensical option is the first one that I mentioned given that you could achieve the behavior of the second option by composing multiple invocations of `sum`: 
```
cal | first 2 | sum | sum
```
Apologies if I'm missing something obvious and the questions that I've posed don't make any sense. As I said I'm very new to this code base.

**Comment by thegedge** [comment] 2020-05-17 12:48
Agreed, @DangerFunPants, that the best option is to make sum work on a row-by-row basis (we have lots of commands that do that 🙂).

I've assigned it to you. Let me know if you have any other questions, or join us on Discord (in the `#developing` channel) if you wanna chat in realtime.

**Comment by DangerFunPants** [comment] 2020-05-19 23:42
Duplicate of #1603

**Comment by thegedge** [comment] 2020-05-20 13:31
Ah, good catch, @DangerFunPants.

**Closed by thegedge** 2020-05-20 13:31 UTC
Labels: bug, good first issue, panic
