### ISSUE TITLE
Job control support

### ISSUE THREAD

**Issue by myfreeweb** [nushell/nushell#1796] opened 2020-05-15 13:04 UTC
Looks like there's no job control support currently…

```
% nu
/usr/home/greg> nvim
<Ctrl-Z>
zsh: suspended  nu
%
```

the typical problem of any new shell… [had to deal with this in ion a couple years ago](https://gitlab.redox-os.org/redox-os/ion/issues/29), that code might be helpful

**Comment by thegedge** [comment] 2020-05-15 16:48
Duplicate of https://github.com/nushell/nushell/issues/1329

Definitely a big feature we'll need to implement. We're calling it "background streams", but it should mirror job control features from other shells. We don't call out `Ctrl-Z` sending a foreground process to the background in the above issue, but if it doesn't get implemented as part of the first pass we can open up specific issues for the missing features 🙂

**Closed by thegedge** 2020-05-15 16:48 UTC
Labels: delight, enhancement

**Comment by lparcq** [comment] 2022-01-02 12:24
Until background streams are implemented, a simple alternative would be to start a command in another shell without switching to the shell (start/stop commands on the model of enter/exit).

```
> start mupdf file.pdf
> shells
| # | active | name       | path           |
| 0 | true   | filesystem | /home/user     |
| 1 | false  | external   | mupdf file.pdf |
> stop 1
```
