### ISSUE TITLE
Inconsistent handling of string lists as program arguments

### ISSUE THREAD

**Issue by mpizenberg** [nushell/nushell#10890] opened 2023-10-30 16:41 UTC
### Describe the bug

Hey, so I'm trying to call a program on some files, but depending on how I feed the files, the program behaves differently. Concretely:

```sh
❯ [.gitignore .gitlab-ci.yml]
╭───┬────────────────╮
│ 0 │ .gitignore     │
│ 1 │ .gitlab-ci.yml │
╰───┴────────────────╯
❯ git st | find modified: | parse '{_}   {path}' | get path | take 2
╭───┬────────────────╮
│ 0 │ .gitignore     │
│ 1 │ .gitlab-ci.yml │
╰───┴────────────────╯

❯ dos2unix [.gitignore .gitlab-ci.yml]
dos2unix: converting file .gitignore to Unix format...
dos2unix: converting file .gitlab-ci.yml to Unix format...

❯ dos2unix (git st | find modified: | parse '{_}   {path}' | get path | take 2)
dos2unix: .gitignore: No such file or directory
dos2unix: Skipping .gitignore, not a regular file.
dos2unix: .gitlab-ci.yml: No such file or directory
dos2unix: Skipping .gitlab-ci.yml, not a regular file.
```

### How to reproduce

As in bug description

### Expected behavior

I'd expect the program to treat the arguments the same, which here means applying the `dos2unix` command instead of rejecting the files.

### Configuration

```
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.86.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1) |
| cargo_version      | cargo 1.73.0                                                     |
| build_time         | 2023-10-18 08:45:09 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |
```

**Comment by fdncred** [comment] 2023-10-30 16:45
I've reproduced this as well.

**Comment by fdncred** [comment] 2023-10-30 16:50
ok, I just figured this out. This apparent inconsistency comes from the fact that the OP is using our built in `find`.
![image](https://github.com/nushell/nushell/assets/343840/3a576b06-4a56-4aae-90f2-711cc4a97485)

Notice that `find` used this way highlights the hits.

What might not be known is that even the other characters that aren't highlighted will have ansi escape sequences. You can see them like this.
![image](https://github.com/nushell/nushell/assets/343840/2b4dd697-7390-438f-b3e6-b95f600951a8)

So, to the nake eye, this looks like a normal result
![image](https://github.com/nushell/nushell/assets/343840/4fe35284-06a0-4492-b01d-6f66614bbd9c)

When in reality, it isn't.
![image](https://github.com/nushell/nushell/assets/343840/d06eb7af-a0a6-45ba-a2d1-914804b25159)

So, the fix for this is to use our `ansi strip` command which just leaves the text.
![image](https://github.com/nushell/nushell/assets/343840/70f59441-b621-40cd-86d9-05ea97e60b73)

Now, it works normally, after you understand what's going on.
![image](https://github.com/nushell/nushell/assets/343840/83f92e2b-db94-4d0e-bc6e-28a6229b6746)

**Closed by fdncred** 2023-10-30 16:50 UTC
Labels: needs-triage
