### ISSUE TITLE
Links in `ls` output display poorly when terminal width is low (Windows Terminal)

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6775] opened 2022-10-16 16:03 UTC
### Describe the bug

The file links in `ls` output seem to get mishandled when Windows Terminal's terminal width forces them into multiple lines - they turn into unclickable doubled-up full paths which are difficult to read.

### How to reproduce

Here's an example:
```
C:\Users\Leon\TODO\A〉ls -l
╭───┬────────────┬──────┬────────┬──────────┬──────┬────────────┬────────────┬───────────╮
│ # │    name    │ type │ target │ readonly │ size │  created   │  accessed  │ modified  │
├───┼────────────┼──────┼────────┼──────────┼──────┼────────────┼────────────┼───────────┤
│ 0 │ A.txt      │ file │        │ false    │  0 B │ 20 seconds │ 20 seconds │ 20        │
│   │            │      │        │          │      │ ago        │ ago        │ seconds   │
│   │            │      │        │          │      │            │            │ ago       │
│ 1 │            │ file │        │ false    │  0 B │ now        │ now        │ now       │
│   │ //C:/Users │      │        │          │      │            │            │           │
│   │ /Leon/TODO │      │        │          │      │            │            │           │
│   │ /A/REALLYL │      │        │          │      │            │            │           │
│   │ ONGFILENAM │      │        │          │      │            │            │           │
│   │ E.BACKUP.T │      │        │          │      │            │            │           │
│   │ XTREALLYL  │      │        │          │      │            │            │           │
│   │ ONGFILENAM │      │        │          │      │            │            │           │
│   │ E.BACKUP.T │      │        │          │      │            │            │           │
│   │ XT         │      │        │          │      │            │            │           │
╰───┴────────────┴──────┴────────┴──────────┴──────┴────────────┴────────────┴───────────╯
C:\Users\Leon\TODO\A〉
```

### Expected behavior

I don't know if this is a limitation of terminal links (a feature I don't fully understand) or something else, but in that case, I kind of expect the filenames to display normally in narrow terminals, even if they can't be used as links as a result.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment] 2022-10-16 16:44
I assume this is a duplicate of https://github.com/nushell/nushell/issues/6553 or https://github.com/nushell/nushell/issues/6704 that is fixed on the development branch and should land with the next release

**Closed by sholderbach** 2022-10-16 16:44 UTC
