### ISSUE TITLE
String "é" cannot be displayed on Windows

### ISSUE THREAD

**Issue by rivten** [nushell/nushell#10337] opened 2023-09-12 16:12 UTC
### Describe the bug

On Windows, when I input the simple string "é", which is a valid UTF-8 string, I encounter the error "Windows stdio in console mode does not support writing non-UTF-8 byte sequences".

Yet, when one checks out the binary representation, all look legit. https://www.compart.com/en/unicode/U+00E9

This might be related to https://github.com/nushell/nushell/issues/7703 and https://github.com/nushell/nushell/issues/6619, also since it’s directly related to text, I thought it might be better to create another issue with this exact repro case.

As pointed out in one of those issues, the crash is in the Rust stdlib : https://github.com/rust-lang/rust/blob/7f442f8ba174fd4233a14ef4d7b577aa907db594/library/std/src/sys/windows/stdio.rs#L116

Also note that the same issue was encountered in the hurl project and was fixed here : https://github.com/Orange-OpenSource/hurl/pull/302/files

Not sure if the same can be done here.

Best.

### How to reproduce

```
~> "é"                                                                                    
Error: nu::shell::io_error

  × I/O error
  help: Error { kind: InvalidData, message: "Windows stdio in console mode does not support writing non-UTF-8 byte
        sequences" }

~> "é" | hx -f b                                            
0x000000: 0b11000011 0b10101001                                         ..
   bytes: 2
```

### Expected behavior

I expect nu to display the UTF-8 string !

### Configuration

```
~> version | transpose key value | to md --pretty                                                        09/12/2023 06:10:29 PM
Error: nu::shell::io_error

  × I/O error
  help: Error { kind: InvalidData, message: "Windows stdio in console mode does not support writing non-UTF-8 byte
        sequences" }
```

Funnily, this crashes as well. Here are the bytes:

```
~> version | transpose key value | to md --pretty | hx                                                   09/12/2023 06:10:56 PM
0x000000: 0x7c 0x20 0x6b 0x65 0x79 0x20 0x20 0x20 0x20 0x20 | key
0x00000a: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000014: 0x20 0x7c 0x20 0x76 0x61 0x6c 0x75 0x65 0x20 0x20  | value
0x00001e: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000028: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000032: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x00003c: 0x20 0x20 0x20 0x20 0x7c 0x0a 0x7c 0x20 0x2d 0x2d     |.| --
0x000046: 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d ----------
0x000050: 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x20 0x7c 0x20 0x2d ------ | -
0x00005a: 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d ----------
0x000064: 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d ----------
0x00006e: 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d ----------
0x000078: 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x2d 0x20 ---------
0x000082: 0x7c 0x0a 0x7c 0x20 0x76 0x65 0x72 0x73 0x69 0x6f |.| versio
0x00008c: 0x6e 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 n
0x000096: 0x20 0x20 0x20 0x7c 0x20 0x30 0x2e 0x38 0x34 0x2e    | 0.84.
0x0000a0: 0x30 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0
0x0000aa: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0000b4: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0000be: 0x20 0x20 0x20 0x20 0x20 0x20 0x7c 0x0a 0x7c 0x20       |.|
0x0000c8: 0x62 0x72 0x61 0x6e 0x63 0x68 0x20 0x20 0x20 0x20 branch
0x0000d2: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x7c          |
0x0000dc: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0000e6: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0000f0: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0000fa: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000104: 0x20 0x20 0x7c 0x0a 0x7c 0x20 0x63 0x6f 0x6d 0x6d   |.| comm
0x00010e: 0x69 0x74 0x5f 0x68 0x61 0x73 0x68 0x20 0x20 0x20 it_hash
0x000118: 0x20 0x20 0x20 0x20 0x20 0x7c 0x20 0x64 0x32 0x61      | d2a
0x000122: 0x62 0x62 0x38 0x36 0x30 0x33 0x61 0x62 0x61 0x62 bb8603abab
0x00012c: 0x34 0x33 0x65 0x63 0x34 0x61 0x36 0x64 0x34 0x65 43ec4a6d4e
0x000136: 0x64 0x35 0x36 0x66 0x39 0x30 0x31 0x38 0x37 0x39 d56f901879
0x000140: 0x30 0x62 0x39 0x39 0x64 0x63 0x65 0x20 0x7c 0x0a 0b99dce |.
0x00014a: 0x7c 0x20 0x62 0x75 0x69 0x6c 0x64 0x5f 0x6f 0x73 | build_os
0x000154: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x00015e: 0x20 0x7c 0x20 0x77 0x69 0x6e 0x64 0x6f 0x77 0x73  | windows
0x000168: 0x2d 0x78 0x38 0x36 0x5f 0x36 0x34 0x20 0x20 0x20 -x86_64
0x000172: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x00017c: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000186: 0x20 0x20 0x20 0x20 0x7c 0x0a 0x7c 0x20 0x62 0x75     |.| bu
0x000190: 0x69 0x6c 0x64 0x5f 0x74 0x61 0x72 0x67 0x65 0x74 ild_target
0x00019a: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x7c 0x20 0x78        | x
0x0001a4: 0x38 0x36 0x5f 0x36 0x34 0x2d 0x70 0x63 0x2d 0x77 86_64-pc-w
0x0001ae: 0x69 0x6e 0x64 0x6f 0x77 0x73 0x2d 0x6d 0x73 0x76 indows-msv
0x0001b8: 0x63 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 c
0x0001c2: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0001cc: 0x7c 0x0a 0x7c 0x20 0x72 0x75 0x73 0x74 0x5f 0x76 |.| rust_v
0x0001d6: 0x65 0x72 0x73 0x69 0x6f 0x6e 0x20 0x20 0x20 0x20 ersion
0x0001e0: 0x20 0x20 0x20 0x7c 0x20 0x72 0x75 0x73 0x74 0x63    | rustc
0x0001ea: 0x20 0x31 0x2e 0x36 0x39 0x2e 0x30 0x20 0x28 0x38  1.69.0 (8
0x0001f4: 0x34 0x63 0x38 0x39 0x38 0x64 0x36 0x35 0x20 0x32 4c898d65 2
0x0001fe: 0x30 0x32 0x33 0x2d 0x30 0x34 0x2d 0x31 0x36 0x29 023-04-16)
0x000208: 0x20 0x20 0x20 0x20 0x20 0x20 0x7c 0x0a 0x7c 0x20       |.|
0x000212: 0x72 0x75 0x73 0x74 0x5f 0x63 0x68 0x61 0x6e 0x6e rust_chann
0x00021c: 0x65 0x6c 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x7c el       |
0x000226: 0x20 0x31 0x2e 0x36 0x39 0x2e 0x30 0x2d 0x78 0x38  1.69.0-x8
0x000230: 0x36 0x5f 0x36 0x34 0x2d 0x70 0x63 0x2d 0x77 0x69 6_64-pc-wi
0x00023a: 0x6e 0x64 0x6f 0x77 0x73 0x2d 0x6d 0x73 0x76 0x63 ndows-msvc
0x000244: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x00024e: 0x20 0x20 0x7c 0x0a 0x7c 0x20 0x63 0x61 0x72 0x67   |.| carg
0x000258: 0x6f 0x5f 0x76 0x65 0x72 0x73 0x69 0x6f 0x6e 0x20 o_version
0x000262: 0x20 0x20 0x20 0x20 0x20 0x7c 0x20 0x63 0x61 0x72      | car
0x00026c: 0x67 0x6f 0x20 0x31 0x2e 0x36 0x39 0x2e 0x30 0x20 go 1.69.0
0x000276: 0x28 0x36 0x65 0x39 0x61 0x38 0x33 0x33 0x35 0x36 (6e9a83356
0x000280: 0x20 0x32 0x30 0x32 0x33 0x2d 0x30 0x34 0x2d 0x31  2023-04-1
0x00028a: 0x32 0x29 0x20 0x20 0x20 0x20 0x20 0x20 0x7c 0x0a 2)      |.
0x000294: 0x7c 0x20 0x62 0x75 0x69 0x6c 0x64 0x5f 0x74 0x69 | build_ti
0x00029e: 0x6d 0x65 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 me
0x0002a8: 0x20 0x7c 0x20 0x32 0x30 0x32 0x33 0x2d 0x30 0x38  | 2023-08
0x0002b2: 0x2d 0x32 0x32 0x20 0x32 0x31 0x3a 0x32 0x30 0x3a -22 21:20:
0x0002bc: 0x35 0x38 0x20 0x2b 0x30 0x30 0x3a 0x30 0x30 0x20 58 +00:00
0x0002c6: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0002d0: 0x20 0x20 0x20 0x20 0x7c 0x0a 0x7c 0x20 0x62 0x75     |.| bu
0x0002da: 0x69 0x6c 0x64 0x5f 0x72 0x75 0x73 0x74 0x5f 0x63 ild_rust_c
0x0002e4: 0x68 0x61 0x6e 0x6e 0x65 0x6c 0x20 0x7c 0x20 0x72 hannel | r
0x0002ee: 0x65 0x6c 0x65 0x61 0x73 0x65 0x20 0x20 0x20 0x20 elease
0x0002f8: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000302: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x00030c: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000316: 0x7c 0x0a 0x7c 0x20 0x61 0x6c 0x6c 0x6f 0x63 0x61 |.| alloca
0x000320: 0x74 0x6f 0x72 0x20 0x20 0x20 0x20 0x20 0x20 0x20 tor
0x00032a: 0x20 0x20 0x20 0x7c 0x20 0x73 0x74 0x61 0x6e 0x64    | stand
0x000334: 0x61 0x72 0x64 0x20 0x20 0x20 0x20 0x20 0x20 0x20 ard
0x00033e: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000348: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x000352: 0x20 0x20 0x20 0x20 0x20 0x20 0x7c 0x0a 0x7c 0x20       |.|
0x00035c: 0x66 0x65 0x61 0x74 0x75 0x72 0x65 0x73 0x20 0x20 features
0x000366: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x7c          |
0x000370: 0x20 0x64 0x65 0x66 0x61 0x75 0x6c 0x74 0x2c 0x20  default,
0x00037a: 0x73 0x71 0x6c 0x69 0x74 0x65 0x2c 0x20 0x74 0x72 sqlite, tr
0x000384: 0x61 0x73 0x68 0x2c 0x20 0x77 0x68 0x69 0x63 0x68 ash, which
0x00038e: 0x2c 0x20 0x7a 0x69 0x70 0x20 0x20 0x20 0x20 0x20 , zip
0x000398: 0x20 0x20 0x7c 0x0a 0x7c 0x20 0x69 0x6e 0x73 0x74   |.| inst
0x0003a2: 0x61 0x6c 0x6c 0x65 0x64 0x5f 0x70 0x6c 0x75 0x67 alled_plug
0x0003ac: 0x69 0x6e 0x73 0x20 0x20 0x7c 0x20 0x20 0x20 0x20 ins  |
0x0003b6: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0003c0: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0003ca: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20
0x0003d4: 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x20 0x7c              |
   bytes: 989
```

**Comment by ChrisDenton** [comment] 2023-09-12 16:47
I'm unable to reproduce on my machine. Can you say what version of Windows you're using?

It seems especially odd to me that `version | transpose key value | to md --pretty` is erroring. That should only output ascii text so even if there were some kind of encoding issue, it should still work.

**Comment by fdncred** [comment] 2023-09-12 16:54
@rivten Thanks for the report. I have no issues with it on Windows 10.

```nushell
❯ char -u '00e9'
é
❯ "é"
é
❯ let test = "é"
é
```

I'm assuming this is because you're not using the utf-8 code page in your terminal. You can check your code page with `chcp`. To change it to utf-8, you can do `chcp 65001`.

**Comment by rivten** [comment] 2023-09-12 17:05
Thanks for the response.
Here is the result of  `sys | get host`

name: Windows
os_version: 11 (22621)
long_os_version: Windows 11 Enterprise
kernel_version: 22621


Also, I don’t know why I did not mention that, but I am using a bepo keyboard layout. I have a French locale. I discovered the bug while piping the result of ping (which in French uses French accent) and got this error.

Finally, the weirdest of all, just relaunched a new terminal, and now everything seem to be working…

```
~> "é"                                                                                                                                                                                                                                    09/12/2023 07:03:44 PMé
~> version | transpose key value | to md --pretty                                                                                                                                                                                         09/12/2023 07:03:45 PM| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.0                                   |
| branch             |                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-08-22 21:20:58 +00:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |
```

I’m 100% positive this was not the case previously.
So, maybe I just got unlucky.

Thanks a lot for having a look into it so quickly though !

**Comment by fdncred** [comment] 2023-09-12 17:58
let's close this then. thanks for the follow-up.

**Closed by fdncred** 2023-09-12 17:58 UTC
Labels: platform-specific, needs-triage, special-characters
