### ISSUE TITLE
'ls' does not display the cumulative size of the directory content

### ISSUE THREAD

**Issue by ssahaxd** [nushell/nushell#12499] opened 2024-04-12 21:21 UTC
### Related problem

When executing the 'ls' command to list directory contents, the command only shows '4 KB' as the size for directories instead of displaying the total size of all the files and subdirectories within that directory.

### Describe the solution you'd like

Can the 'ls' command be augmented with an option to display the cumulative size of the files and subdirectories within a given directory?

**Comment by fdncred** [comment] 2024-04-12 21:59
It's working as designed. Look at the help for `ls` and you'll discover other options like `ls --du`.

**Comment by YizhePKU** [comment] 2024-04-14 14:29
Is there a reason why showing directory metadata size is more useful than disk usage? There might be an argument that `--du` should be the default.

**Comment by fdncred** [comment] 2024-04-14 19:02
I won't support making `--du` the default because it's too slow.

**Comment by sholderbach** [comment] 2024-07-13 16:56
Closing this one due to the performance concerns of having to compute the total disk usage of a directory and it being consistent with the default behavior on almost all platform. This may be not the most end-user friendly choice but is consistent with the precedent.

**Closed by sholderbach** 2024-07-13 16:56 UTC
Labels: enhancement, needs-triage
