### ISSUE TITLE
make it possible to append to a file when redirecting

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10479] opened 2023-09-23 11:04 UTC
### Related problem

we already have things like
```nushell
"foo" out> foo.txt
```
to redirect to a file, but we cannot do something like
```bash
echo "bar" >> foo.txt
```
as in Bash to append to the file when redirecting :cry: 

i think this would be great to have and make redirection even more useful :yum: 

### Describe the solution you'd like

> **Important**
> the syntax below simply uses a double `>`, i.e. `>>` do denote the *appending redirection*, but this could be discussed for sure :+1: 

make the following possible
```nushell
"i'm the first line" out> foo.txt
"no i am the first line" out> foo.txt
"just wanna be there too ^^" out>> foo.txt
```
which would give
```nushell
> open foo.txt
no i am the first line
just wanna be there too ^^
```

**Comment by sholderbach** [comment] 2023-09-26 13:39
This is a duplicate of your own #10278

**Closed by sholderbach** 2023-09-26 13:39 UTC
Labels: enhancement, redirection-pipe, needs-triage

**Comment by fdncred** [comment] 2023-09-26 13:42
it bothers me so much that i create two issues 🤣 

I'm not laughing at you, I'm laughing with you because i've done the exact same thing.

**Comment by amtoine** [comment] 2023-09-26 16:26
no way :laughing: 
good catch :scream:
