### ISSUE TITLE
`parse` panics on invalid regex

### ISSUE THREAD

**Issue by gaetanww** [nushell/nushell#1797] opened 2020-05-15 15:31 UTC
**Describe the bug**

Panics when invalid regex is inputted.

```nu
❯ echo "tests.html" | parse "{filename}[.{ext}]?"
thread 'main' panicked at 'no group at index '2'', /home/wattiau/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.3.7/src/re_unicode.rs:1021:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
`echo "tests.html" | parse "{filename}[.{ext}]?"`

**Expected behavior**

Gives an error.

**Configuration (please complete the following information):**
 - OS: Ubuntu on Windows
 - Version 0.14.0
 - Optional features: features=stable

**Comment by Yam76** [comment] 2020-05-15 22:47
Probably due to [this line](https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/commands/parse.rs#L148). Maybe needs a check to prevent out of bounds indexing in case there are more columns than captures?

**Comment by thegedge** [comment] 2020-05-16 15:50
I think that's a good candidate, @Yam76.

It's good that we deal with this panic appropriately, but we should also understand the root cause of the panic: there's a bug in how the regex is constructed.

When we have raw text, we only escape raw parentheses: https://github.com/nushell/nushell/blob/822440d5ff97f7ce4bf0d2e604726538fef40fb8/crates/nu-cli/src/commands/parse.rs#L73

What this means is that the parse arg you supplied, `"{filename}[.{ext}]?"`, would be translated into this regex:

```
(.*)[.(.*)]?
```

So you can easily see why there wasn't a second capture group (the first capture group swallowed up the entire string, because `*` is greedy).

I'd love to see one/two PRs to close this one off:

1. Prevent the panic from ever occurring. I'd recommend checking the number of capture groups against the number of column names.
2. Don't attempt to do our own escaping by making use of https://docs.rs/regex/1.3.7/regex/fn.escape.html

**Comment by gaetanww** [comment] 2020-05-16 19:26
Thanks for looking it up :) 

For reference, I triggered this panic while trying to see if I could parse the name of a file, extract the name and eventually the extension. So the difference in number of column and capture group was probably my goal. I don't know if it's something that `parse` should support.

**Comment by johnterickson** [comment] 2020-05-16 19:44
If nobody else is already digging in, I might try to a stab at this as my first contribution:
> Prevent the panic from ever occurring. I'd recommend checking the number of capture groups against the number of column names.

**Comment by johnterickson** [comment] 2020-05-16 20:12
@jonathandturner I see you just moved `parse` in #1801.  I can't seem to repro this anymore as `parse` is not found on master. Am I doing something wrong? I've tried a number of `feature` combinations.

```
C:\src\nushell>cargo run --all-features
    Finished dev [unoptimized + debuginfo] target(s) in 1.45s
     Running `target\debug\nu.exe`
Welcome to Nushell 0.14.1 (type 'help' for more info)
nushell on 📙 master is 📦 v0.14.1 via 🦀 v1.43.1
❯ echo "tests.html" | parse "{filename}[.{ext}]?"
error: Command not found
- shell:1:47
1 | echo "tests.html" | parse "{filename}[.{ext}]?"
  |                     ^^^^^ command not found

**Comment by jonathandturner** [comment] 2020-05-16 20:34
@johnterickson - now that parse is a plugin, you'll need to do two steps:

In Nu:
```
cargo build --all --features=stable; cargo run --features=stable
```

In Bash:
```
cargo build --all --features=stable && cargo run --features=stable
```

**Comment by gaetanww** [comment] 2020-05-18 11:12
I can't find any docs explaining the semantics of the pattern in `parse`. It seems to be some subset of regular expressions. Could you direct me to it, if it exists?

My concern is that PRs like #1814, would prevent optional matches, or is that expected?

**Comment by thegedge** [comment] 2020-05-18 15:24
@gaetanww https://github.com/nushell/nushell/issues/1831

**Comment by thegedge** [comment] 2020-05-18 15:26
Since https://github.com/nushell/nushell/pull/1814 is in, I'm going to close this one in favour of https://github.com/nushell/nushell/issues/1831, which can both add `--regex` and escape the current format. It should hopefully lead to less implicit behaviours.

**Closed by thegedge** 2020-05-18 15:26 UTC
Labels: bug, good first issue, panic
