### ISSUE TITLE
ls dosen't work on Windows network drive

### ISSUE THREAD

**Issue by MCoooo** [nushell/nushell#5057] opened 2022-04-01 07:31 UTC
When cd'ing into a Windows mapped network drive, the DOS UNC path is listed rather than the drive (not the issue but not what I cc'd into). Then when I run 'ls' I receive this error:

Error:
  × No matches found for ./*
  help: no matches found

**Comment by fdncred** [comment] 2022-04-01 11:29
dupe of #4863. closing in favor of it.

**Closed by fdncred** 2022-04-01 11:29 UTC
Labels: platform-specific
