### ISSUE TITLE
`to json` may convert to invalid json in some cases

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4403] opened 2022-02-10 06:38 UTC
### Describe the bug

`to json` may convert to invalid json in some cases

### How to reproduce

1. Create a toml file `c.toml`, with the following contents:
```toml
[foo]
bar = '[{"a":"b","c": 2}]'
```
2. In nu v0.43, run `open ./c.toml | to json --pretty 2` will get:
```
   1   │ {
   2   │   "foo": {
   3   │     "bar": "[{\"a\":\"b\",\"c\": 2}]"
   4   │   }
   5   │ }
```
3. However, In nu v0.59, you will get:
```json
{
  "foo":
  {
    "bar": '''[{"a":"b","c": 2}]'''
  }
}
```
which is an invalid json string

### Expected behavior

Get a valid json string as the old nu does

### Configuration

| name               | val                                                 |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | c2118e75                                            |
| commit_hash        | c2118e7505d779103bf6f6c845ea86f8a1cd70c0            |
| commit_date        | 2022-02-10 02:24:29 +00:00                          |
| build_os           | macos-x86_64                                        |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-10 12:07:35 +08:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, which, zip                      |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment] 2022-02-10 12:33
may be a dupe of #4311

**Comment by hustcer** [comment] 2022-02-15 02:36
@fdncred When will this issue be resolved? We are heavily depend on this. Thanks

**Closed** 2022-02-15 11:55 UTC
Labels: bug
