### ISSUE TITLE
The whole line of text will flash when typing. Windows Terminal

### ISSUE THREAD

**Issue by kouhe3** [nushell/nushell#7860] opened 2023-01-26 11:23 UTC
### Describe the bug

The whole line of text will flash when typing.

https://user-images.githubusercontent.com/25522053/214823116-7d35eff8-2efb-44c4-acec-97d7cec0ed2d.mp4

### How to reproduce

Windows_NT 10.0 25284 x86_64 MS/Windows

Windows Terminal
Ver: 1.15.3466.0

### Expected behavior

normal

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.0                                   |
| branch             | main                                     |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.0                                   |
| build_time         | 2023-01-10 16:21:03 -06:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment] 2023-01-26 12:27
Hi, thanks for the bug report. This is a dupe of https://github.com/nushell/nushell/issues/6214.

The underlying Windows Terminal issue (please upvote): https://github.com/microsoft/terminal/issues/13710

**Closed by fdncred** 2023-01-26 12:28 UTC
