### ISSUE TITLE
Unable to use ls when working dir is a network drive on Windows 10

### ISSUE THREAD

**Issue by ehawman** [nushell/nushell#5798] opened 2022-06-15 18:42 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/52979227/173899646-b36626b6-c4aa-4ffc-8133-263aeaea887d.png)

![image](https://user-images.githubusercontent.com/52979227/173900488-f7b10bdd-1473-41fe-8c44-a8e252d8e04f.png)

Unable to list files when connected to a mapped drive on Windows 10.

### How to reproduce

1. `cd` to remote mapped drive or full UNC path
2. Attempt `ls`

### Expected behavior

I expected the `ls` command to work (which it does on the native system, including external drives plugged in via USB)

![image](https://user-images.githubusercontent.com/52979227/173901222-57e9f40e-d8b5-472c-a8de-f481af6e39ac.png)

### Screenshots

![image](https://user-images.githubusercontent.com/52979227/173899646-b36626b6-c4aa-4ffc-8133-263aeaea887d.png)

![image](https://user-images.githubusercontent.com/52979227/173900488-f7b10bdd-1473-41fe-8c44-a8e252d8e04f.png)

![image](https://user-images.githubusercontent.com/52979227/173901222-57e9f40e-d8b5-472c-a8de-f481af6e39ac.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        | cb66d2bcad6db50a71d0accba0f76afe0ec12cac        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 16:06:21 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment] 2022-06-15 18:45
sorry, but this is a dupe of https://github.com/nushell/nushell/issues/4863. closing in favor of that. please subscribe to that issue.

**Closed by fdncred** 2022-06-15 18:45 UTC

**Comment by ehawman** [comment] 2022-06-15 21:42
@fdncred got it, thanks!
