### ISSUE TITLE
Using nu as default shell I can't start a wayland (sway) session

### ISSUE THREAD

**Issue by antoniocorbi** [nushell/nushell#4141] opened 2021-11-22 08:32 UTC
### Describe the bug

Hi all,

I don't use any graphical login manager, after login onto my text session on VT1 I type 'sway' and that's it, at least under bash or fish but not with nushell.

In the case of nushell,  sway shows this error:
 00:00:00.004 [ERROR] [wlr] [backend/wayland/backend.c:401] Could not connect to remote display: No such file or directory
 00:00:00.004 [ERROR] [sway/server.c:53] Unable to create backend

And it does not work, but I've checked that under nushell I can definitely start an Xorg session via startx and it works as expected.

Is there a solution for this?

### How to reproduce

1. Login onto vt1
2. type. sway: It doesn't work
3. type startx: It does work.

### Expected behavior

Start a wayland session and work as expected

**Comment by antoniocorbi** [comment] 2021-11-22 14:53
Hi fdncred,

> I'm just guessing but could this be because the DISPLAY environment variable isn't set 

Definitely no:
```
    grep DISPLAY .config/nu/config.toml 
    DISPLAY = ":0"
```
There must be another reason.

**Comment by fdncred** [comment] 2021-11-22 15:11
ya, that looks right as long as it's under the `[env]` section of the config.toml

**Comment by antoniocorbi** [comment] 2021-11-22 18:26
Yeah, it indeed is:

```
[env]
CMD_DURATION_MS = "25"
COLORTERM = "truecolor"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
DISPLAY = ":0"
```

**Comment by kubouch** [comment] 2021-11-30 22:56
That's strange, I'm able to run sway under Nushell no problem, and I don't have any special env vars set up, not even DISPLAY. What happens if you delete the DISPLAY env var from the config?

Perhaps, what you can do is to set your main shell to bash, log out, log in, list all environment variables (using `env`), then change the shell back to Nushell, log out, log in, list all Nushell's environment variables (`$nu.env`) and compare the two lists. That way you can figure out any settings you might have forgotten or misconfigured.

**Comment by fdncred** [comment] 2022-03-06 14:43
is this reproducible on 0.59?

**Comment by jntrnr** [comment] 2022-03-09 10:31
Since the environment stuff changed for 0.59, I'm going to go ahead and close this. Please re-open it if you're still seeing this behaviour with the newer versions.

**Closed by jntrnr** 2022-03-09 10:31 UTC
Labels: bug, investigate, external-commands, 0.60
