### ISSUE TITLE
Source login.nu before everything else

### ISSUE THREAD

**Issue by StevenDoesStuffs** [nushell/nushell#8169] opened 2023-02-22 17:08 UTC
This is consistent with the behavior of POSIX shells, and allows for greater flexibility--if someone wants to override things later based on whether they're in a login shell, they could set an environment variable in login.nu to mark that they're in a login shell. 

Here's how bash does it: 
![image](https://user-images.githubusercontent.com/13265529/220703732-020db7e5-b4dd-4d66-a4fa-e71a03cbf534.png)

I'd be happy to PR this if you'd accept such a change.

**Comment by fdncred** [comment] 2023-02-22 18:08
Sounds interesting but what exactly are you proposing? I guess I'd like to see how nushell would do something like your diagram since nushell doesn't have all those files or parameters.

**Comment by StevenDoesStuffs** [comment] 2023-02-22 21:08
The gist of how bash does things is that `bashrc` is for interactive shells, and the profile stuff is for login shells. The point of the diagram was to show that bash sources profile stuff first then bashrc second. In nushell the equivalent would be to source `login.nu` (equivalent to profile stuff in bash) first, then `env.nu` and `config.nu` (equivalent to bashrc).

**Comment by fdncred** [comment] 2023-02-22 22:22
I thought that's how it worked today if you have nushell set as your login shell

**Comment by StevenDoesStuffs** [comment] 2023-02-23 01:45
Currently, login.nu is sourced after config and env.

https://www.nushell.sh/book/configuration.html#configuration-with-login-nu
> The file login.nu is sourced after env.nu and config.nu, so that you can overwrite those configurations if you need.

Just to reiterate, if we instead source login.nu before, people can still override stuff later since they could set an env-var in login.nu and use that to customize their behavior in env and login.

**Comment by fdncred** [comment] 2023-02-23 14:49
> Just to reiterate, if we instead source login.nu before, people can still override stuff later since they could set an env-var in login.nu and use that to customize their behavior in env and login.

It seems odd that it was done this way. I thought it was sourced first. IMO, login.nu should be sourced first.

**Comment by StevenDoesStuffs** [comment] 2023-02-24 07:39
Seems like the whole point was this:

https://github.com/nushell/nushell/pull/5714#issuecomment-1146805495
> At the moment the login.nu will be sourced after config/env.nu, since I assumed it should be possible to change some of the config variables set in config/env.nu in case of a loginshell.

**Comment by jokeyrhyme** [comment] 2024-01-07 21:46
@StevenDoesStuffs have you tried using `if $nu.is-login { }` in your env.nu to customise variables the way you want?

**Comment by suimong** [comment] 2024-06-24 02:36
@fdncred Do you and the rest of the core team still feel like sourcing `login.nu` first is the desired behavior? I have a small PR ready but since this is a breaking change (and not a trivial one), I'd like to consult you first beforehand.

**Comment by jokeyrhyme** [comment] 2024-06-24 02:47
I don't speak for the nushell folks, but I wonder if much else besides $nu.is-login ought to be exposed

Given how unreliable/inconsistent the concept is, perhaps it'd be better to discourage folks from using it: https://github.com/zellij-org/zellij/issues/1434#issuecomment-2185391816

**Comment by fdncred** [comment] 2024-06-24 12:46
> @fdncred Do you and the rest of the core team still feel like sourcing `login.nu` first is the desired behavior? I have a small PR ready but since this is a breaking change (and not a trivial one), I'd like to consult you first beforehand.

Let me see if I can get people's attention. We're about to do a release (tomorrow) so it may be a few days.

**Comment by fdncred** [comment] 2024-06-24 15:35
Looks like we may not want to make this change since, according to @IanManske's research:

> I'll comment later today, but I actually think bash and zsh load login config last.

https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html#implementation

and from the [Arch wiki on Zsh](https://wiki.archlinux.org/title/Zsh#Startup/Shutdown_files), the login config is listed last:

> $ZDOTDIR/.zlogin Used for executing user's commands at ending of initial progress, will be read when starting as a login shell. Typically used to autostart command line utilities.

**Comment by suimong** [comment] 2024-06-24 15:58
Thanks @fdncred for the quick response and @IanManske for the research! Seems like I misunderstood the (historically) intended behavior of a "login" script, as I was misappropriating it for loading system-wide configurations eg `/etc/profiles` etc. As such, a simple `if $nu.is-login` block, as suggested by @jokeyrhyme, should suffice.

**Comment by fdncred** [comment] 2024-06-24 17:12
`$nu.is-login` is already exposed. Is there something else needed?

**Comment by suimong** [comment] 2024-06-25 00:08
No, all good. Maybe we could close this?

**Closed** 2024-06-25 00:20 UTC
Labels: enhancement, configuration, POSIX-expectations
