### ISSUE TITLE
nushell interferes with 'git commit -m"message"'?

### ISSUE THREAD

**Issue by rimathia** [nushell/nushell#1667] opened 2020-04-26 18:51 UTC
**Describe the bug**
in nushell:
/Users/mathiasritzmann/Library/nushell(master)> git add example.json
/Users/mathiasritzmann/Library/nushell(master)> git commit -m"test commit"
error: pathspec 'commit' did not match any file(s) known to git

but if I exit nushell, the following works (in the same directory):

git commit -m"test commit"

versions and other information:

nushell: local build (cargo build) from master (80025ea684db049601cfa1917202500ed4d7fbea)

which git
─────────┬────────────────────
 arg     │ git 
 path    │ /usr/local/bin/git 
 builtin │ No 
─────────┴────────────────────

git --version
git version 2.26.1

**To Reproduce**
1. open nushell in a git repository
2. "git add test_file"
3. 'git commit -m"test commit"'

**Expected behavior**
I expected the same to happen as in the default bash shell.

**Configuration (please complete the following information):**
 - OS: macOS
 - Version Catalina 10.15.2
 - Optional features (if any)

**Comment by rimathia** [comment] 2020-04-26 18:53
I'll be happy to have a look at it myself but it is likely I won't get around to doing so before 30.4.2020 (and I'll probably have to find out how to run nushell in a debugger, but that's something I should do anyway).

**Comment by jonathandturner** [comment] 2020-04-27 02:06
@rimathia - if you do `git commit -m "test commit"` instead of `git commit -m"test commit"` does it work? It's possible this is parser-related

**Comment by quebin31** [comment] 2020-04-27 15:56
I can't reproduce this on Arch Linux with the latest version of `master`, did someone fixed it?

**Comment by thegedge** [comment] 2020-04-27 16:28
@quebin31 nope, it's still broken on my end.

**Comment by rimathia** [comment] 2020-04-27 18:42
@jonathandturner indeed both `git commit -m "test commit"` and `git commit -m"test"` work as expected

**Comment by jonathandturner** [comment] 2020-04-27 19:04
@rimathia - if both work as expected, can you describe what the issue here is?

**Comment by rimathia** [comment] 2020-04-27 19:08
@jonathandturner  sorry, I should have been more precise. git commit `-m"test commit"` does not work, it just seems that I need both no space between `-m` and the commment and a comment which contains a space to hit the problem

**Comment by jonathandturner** [comment] 2020-04-27 19:15
@rimathia - thanks, that helps a lot. Definitely sounds parser related. For anyone interested in fixing it: run `nu -l trace` and look to see if the lite-parse of the code contains the right token `-m"test commit".  If not, fixing the liteparser to include the whole token should help fix the issue.

**Comment by thegedge** [comment] 2020-04-28 00:57
Looks like this is resulting in the following parse:

```
built command "sh" "-c" "git commit \"-m\"this is a test\"\""
```

This would be the same as running this on the command line:

```
git commit "-m"this is a test""
```

So we'll need to drop those quotes around the entire thing.

**Comment by thegedge** [comment] 2020-04-28 01:05
Looks like the problem is here: https://github.com/nushell/nushell/blob/c704157bc8aec542a2afc5170b13d863d84ec59e/crates/nu-cli/src/commands/classified/external.rs#L221

So we need to be smarter here.

**Comment by quebin31** [comment] 2020-04-28 14:20
I would like to try too, where exactly can I start to understand how this is failing?

**Comment by thegedge** [comment] 2020-04-29 18:28
@quebin31 I think @jonathandturner is landing some things to simplify how we expand `$it` which could potentially impact this, so let's wait for him to get everything in. After that, here are my thoughts:

1. If we're expanding a var in the context of something passed to an external, we need to escape any special character. Surrounding with quotes is insufficient, for example, if we had the value `this "is a" string`.
2. If we're just feed it in something directly from the parse, feed it as is. The user would have done the necessary level of quoting. For example, the `git commit` example from the original description in this PR.

**Comment by jonathandturner** [comment] 2020-04-29 21:32
I've finished landing the $it-expansion work, so everything in master should be a good place to start from.

**Comment by thegedge** [comment] 2020-05-01 02:56
Looks like this may have been fixed by https://github.com/nushell/nushell/pull/1687. I'm not experiencing issues on a8de619. Please reopen if you're still having problems.

**Closed by thegedge** 2020-05-01 02:56 UTC
Labels: bug, parser
