### ISSUE TITLE
`std assert` commands are very sensitive to how their inputs are given

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#12999] opened 2024-05-29 21:01 UTC
### Describe the bug

it looks like, when having a variable in a compound data structure such as a list, doing `$l.0` and `($l.0)` changes the span of the _thing_ you get :open_mouth: 
let's see an example with the `std assert` commands :blush: 

### How to reproduce

- run the following two snippets, the first one will show a proper error, the second one will give an interesting error
```nushell
use std assert

let a = 1
let b = [2]

assert equal $a ($b.0)
```
```
Error:   × Assertion failed.
   ╭─[entry #11:6:14]
 5 │
 6 │ assert equal $a ($b.0)
   ·              ────┬────
   ·                  ╰─┤ These are not equal.
   ·                    │         Left  : '1'
   ·                    │         Right : '2'
   ╰────
```

```nushell
use std assert

let a = 1
let b = [2]

assert equal $a $b.0
```
```
Error:   × invalid error format.
    ╭─[NU_STDLIB_VIRTUAL_DIR/std/assert.nu:44:16]
 43 │             msg: ($message | default "Assertion failed."),
 44 │ ╭─▶         label: ($error_label | default {
 45 │ │               text: "It is not true.",
 46 │ │               span: (metadata $condition).span,
 47 │ ├─▶         })
    · ╰──── `$.label.start` should be smaller than `$.label.end`
 48 │         }
    ╰────
  help: 235409 > 235393
```

### Expected behavior

i expected the one where `$b.0` is NOT wrapped in `(...)` to show the same error as the first one.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | ac4125f8edd5b8f3f68aa653d03d57b2d25f1da1        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-22 19:13:16 +02:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | clipboard, explore, tui_template                |

**Comment by sholderbach** [comment] 2024-08-20 11:09
Seems to be a duplicate of #10666

**Closed** 2024-08-20 14:34 UTC
Labels: std-library, needs-triage
