### ISSUE TITLE
How to disable line cursor blinking?

### ISSUE THREAD

**Issue by TomLebeda** [nushell/nushell#8988] opened 2023-04-25 07:44 UTC
### Question

Hello, 

I have tried reading through documentation, issues here on GitHub as well as the config files, but I couldn't find anywhere where/how to disable the line cursor blinking? The block doesn't blink, so I assume it should be possible. 

Thank you.

**Comment by hustcer** [comment] 2023-04-25 07:54
Duplicate of https://github.com/nushell/nushell/issues/6214?

**Comment by TomLebeda** [comment] 2023-04-25 08:00
I will check it out, but the #6214 seems like "flickering" is unintentional behaviour, that doesn't happen to me. What I mean is the slow blinking on/off when cursor is idle - that seems to me intentional.

**Comment by jntrnr** [comment] 2023-04-25 08:53
@TomLebeda it's possible there's an ansi sequence that does this, though I was also wondering if you could change it via your terminal settings.

**Comment by WindSoilder** [comment] 2023-04-25 09:27
I think you can just change `cursor_shape` in config to underscore:
```  
cursor_shape: {
    emacs: underscore # block, underscore, line (line is the default)
  }
```

**Comment by TomLebeda** [comment] 2023-04-25 09:44
@jntrnr I have blinking disabled in terminal itself (both wezterm and alacritty), but when I enter nushell, it overrides it (at when I exit nushell, it stays overriden and doesn't return back to original). Could you please elabore how/where should I add/remove the ansi sequence?

**Comment by TomLebeda** [comment] 2023-04-25 09:45
@WindSoilder Yeah, but I like the vertical line cursor, I am used to underscore being "replace" mode.

**Comment by fdncred** [comment] 2023-04-25 11:23
I don't believe nushell makes cursors blink. That is a terminal thing. I've looked and don't see it anywhere. This explains all we do right now. https://github.com/nushell/nushell/issues/8452#issuecomment-1468760230 and also shows the ansi escape sequences that could change your cursor.

However, if you have it set in your terminal, the ansi escape sequences probably won't make a difference. This makes your cursor a solid block `echo "\e[2 q"` but in WezTerm, I have it set to
```
default_cursor_style = "BlinkingBar", -- SteadyBlock, BlinkingBlock, SteadyUnderline, BlinkingUnderline, SteadyBar, and BlinkingBar
```
which overrides that escape.

**Comment by WindSoilder** [comment] 2023-04-25 11:32
I found that in the latest main, default with be a line cursor without blinking...

**Comment by TomLebeda** [comment] 2023-04-25 12:06
@fdncred Thank you, it worked! You were right, the blinking was done by wezterm. However, I was using block cursor in wezterm with plain bash, so it wasn't visible. When I explicitly disabled the blinking in wezterm, it stopped in nushell as well.

**Closed** 2023-04-25 13:27 UTC
Labels: question
