### ISSUE TITLE
screen flicker when type character every time

### ISSUE THREAD

**Issue by lost22git** [nushell/nushell#8454] opened 2023-03-15 01:48 UTC
### Describe the bug

screen flash when type character every time

|env|version|
|:----:|:----:|
|os|win11|
|windows terminal|v1.16.220921001-preview|
|nushell|v0.77.0 installed by `cargo install ...`|

### How to reproduce

open nushell in windows terminal

### Expected behavior

No screen flicker, protect my eyes

### Screenshots

![cc](https://user-images.githubusercontent.com/65008815/225182434-94a81978-94ae-4973-b054-8e1b76ce17b4.gif)

### Configuration

```shell
~> version | transpose key value | to md --pretty                                  03/15/2023 09:35:42 上午| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.77.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | windows-x86_64                              |
| build_target       | x86_64-pc-windows-msvc                      |
| rust_version       | rustc 1.69.0-nightly (f77bfb733 2023-03-01) |
| rust_channel       | nightly-x86_64-pc-windows-msvc              |
| cargo_version      | cargo 1.69.0-nightly (9880b408a 2023-02-28) |
| build_time         | 2023-03-15 08:21:41 +08:00                  |
| build_rust_channel | release                                     |
| features           | default, zip                                |
| installed_plugins  |                                             |
```

**Comment by rgwood** [comment] 2023-03-15 04:48
Duplicate of https://github.com/nushell/nushell/issues/6214 (it's a Windows Terminal issue)

**Closed by rgwood** 2023-03-15 04:48 UTC

**Comment by rgwood** [comment] 2023-03-15 05:14
Please do not bother everyone subscribed to that Windows Terminal issue with "any update?" comments.
