### ISSUE TITLE
Replace Right Arrow key auto complete with Tab key

### ISSUE THREAD

**Issue by MarioGK** [nushell/nushell#3984] opened 2021-09-02 20:05 UTC
### Describe the solution you'd like

When NuShell suggests something like this
![image](https://user-images.githubusercontent.com/8379079/131908717-5e63be3b-bc24-487a-b7fb-1985865c8642.png)
I wanted to press Tab instead of Right Arrow to complete it, searched on config and there is nothing similar

### Describe alternatives you've considered

Maybe this feature/config option would break the Autocomplete of commands?

**Comment by fdncred** [comment] 2021-09-02 20:29
dupe of https://github.com/nushell/nushell/issues/3959, closing in favor of it. if you disagree, please re-open.

**Closed by fdncred** 2021-09-02 20:29 UTC
