### ISSUE TITLE
Alias executed on shell load if it contains 'doas'

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#10858] opened 2023-10-28 06:15 UTC
### Describe the bug

If i add an alias to `config.nu` like `alias clock = chronyc -N 'sources -v' ; echo ; doas chronyc -N 'selectdata -v' ; echo ; chronyc tracking ; echo ; chronyc rtcdata` then it gets executed immeadiately upon shell load without user interaction.

Another alias where this happens is `alias nn = doas cp -u ~/Dokumente/Install/Linux/Nixos/*.nix /etc/nixos/ ; doas nixos-rebuild switch --upgrade-all`

### How to reproduce

1. enter something like `alias clock = chronyc -N 'sources -v' ; echo ; doas chronyc -N 'selectdata -v' ; echo ; chronyc tracking ; echo ; chronyc rtcdata` into `config.nu`
2. start nushell by executing `nu` in a terminal

### Expected behavior

The alias is accepted as usual and not run on shell start.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.86.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (built from a source tarball) |
| cargo_version      | cargo 1.72.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

This is at the top of my `config.nu` with the problematic lines commented out. As soon as i uncomment one of the lines with `doas` in them and restart `nu` the problem arises:
```
### NixOS
# alias nboot = doas cp -u ~/Dokumente/Install/Linux/Nixos/*.nix /etc/nixos/ ; doas nixos-rebuild boot --upgrade-all ; reboot
# alias nswitch = doas cp -u ~/Dokumente/Install/Linux/Nixos/*.nix /etc/nixos/ ; doas nixos-rebuild switch
# alias ntest = doas cp -u ~/Dokumente/Install/Linux/Nixos/*.nix /etc/nixos/ ; doas nixos-rebuild test --upgrade-all
# alias ndry = doas cp -u ~/Dokumente/Install/Linux/Nixos/*.nix /etc/nixos/ ; doas nixos-rebuild dry-build --upgrade-all
# alias nn = doas cp -u ~/Dokumente/Install/Linux/Nixos/*.nix /etc/nixos/ ; doas nixos-rebuild switch --upgrade-all
# alias nroot = nix-store --gc --print-roots
# alias ngarb = nix-collect-garbage -d ; doas nix-collect-garbage -d
# alias ngenconf = doas nixos-generate-config
# alias np = nox
# alias npkgs = realpath $(which $argv)

alias ne = neofetch kernel packages distro uptime
alias nt = nix-tree
def nver [input] { ls -l /run/current-system/sw/bin/ | where target =~ $input | select target }
# alias nc = doas nano /etc/nixos/configuration.nix
# alias compsize = doas echo -e \n/ ; doas compsize -x / ; echo -e \n/home ; doas compsize -x /home ; echo -e \n/mnt/backup256 ; doas compsize -x /mnt/backup256/
```

**Comment by amtoine** [comment] 2023-10-28 11:28
this is expected :wink: 

`config.nu` is a regular Nushell script, thus
```nushell
alias clock = chronyc -N 'sources -v' ; echo ; doas chronyc -N 'selectdata -v' ; echo ; chronyc tracking ; echo ; chronyc rtcdata
```
is equivalent to
```nushell
alias clock = chronyc -N 'sources -v'
echo
doas chronyc -N 'selectdata -v'
echo
chronyc tracking
echo
chronyc rtcdata
```
and thus the alias `clock` is defined, `doas` runs once, `chronyc` runs twice and `echo` runs three times, all of that on startup :open_mouth: 

here you want to use either a `do` block or a [custom command](https://www.nushell.sh/book/custom_commands.html)
```nushell
alias clock = do { chronyc -N 'sources -v' ; echo ; doas chronyc -N 'selectdata -v' ; echo ; chronyc tracking ; echo ; chronyc rtcdata }
```
```nushell
def clock [] { chronyc -N 'sources -v' ; echo ; doas chronyc -N 'selectdata -v' ; echo ; chronyc tracking ; echo ; chronyc rtcdata }
```

**Comment by amtoine** [comment] 2023-10-28 11:29
because this is expected behaviour in `config.nu`, again because this is just a regular Nushell script and thus `;` is a command separator, i'll close this issue :+1: 

please feel free to reopen if there is something extra to discuss :wink: :relieved:

**Closed by amtoine** 2023-10-28 11:29 UTC
Labels: needs-triage

**Comment by Schweber** [comment] 2023-10-28 13:17
I see, sorry for the trouble and thank you for the explanation. I'm just transitioning to `nushell`.

**Comment by amtoine** [comment] 2023-10-28 17:17
> I see, sorry for the trouble and thank you for the explanation. I'm just transitioning to `nushell`.
>
of course, no worries at all :wink: 

feel free to drop in [our Discord](https://discord.gg/ajjDjBX8) if you have little questions like this :relieved:
