### ISSUE TITLE
Go Test path gets interpreted wrongly

### ISSUE THREAD

**Issue by tsukinoko-kun** [nushell/nushell#14236] opened 2024-11-02 15:47 UTC
### Describe the bug

Go uses a path like `./...` for tests to run all tests in the directory. `go test ./internal/...` means: run all tests in the `internal` directory.  
This path `./...` gets treated as two directories up in the hierarchy.

### How to reproduce

1. In a go project run `go test ./...`
2. I get an error like `no Go files in /Users/frank`

### Expected behavior

Runs all tests

I get the expected behavior when running `go test './...'`

### Configuration

I have nushell installed using Nix on my Macbook. Configured using Nix Home Manager.

```
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.99.1                                                            |
| major              | 0                                                                 |
| minor              | 99                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (built from a source tarball) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |
```

**Comment by fdncred** [comment] 2024-11-02 16:29
This is a dupe of https://github.com/nushell/nushell/issues/13303, closing.

**Closed by fdncred** 2024-11-02 16:29 UTC
Labels: needs-triage
