### ISSUE TITLE
Bashism !$ uses last token to previous command, rather than the last argument to previous command 

### ISSUE THREAD

**Issue by 132ikl** [nushell/nushell#14256] opened 2024-11-05 02:10 UTC
### Describe the bug

`!$` is a bashism provided by reedline which allows you to autofill the last value passed to the last command. Example:

```nushell
mkdir hello
cd !$ # when you press enter here, !$ will be replaced with "hello", like so:
cd hello
```

However, `!$` pulls only the last _token_, not the last _argument_, which isn't always correct:

```nushell
mkdir `hello world`
cd !$ # on enter, this will be replaced with:
cd world`
```

This differs from bash's behavior in a way which is bad for UX:

```bash
mkdir "hello world"
cd !$ # on enter, this will be evaluated as 'cd "hello world"' and immediately executed 
```

I'm filing this as a nushell issue rather than a reedline issue since I don't think the concept of arguments exists for reedline, and this seems to be a nushell UX issue rather than a reedline specific issue. I can move this to the reedline repo if others disagree though. Because we handle this at the readline level, rather than the shell level like bash, a solution might be somewhat involved, but I'm not familiar enough with either codebase to know for certain.

The relevant reedline code can be found [here](https://github.com/nushell/reedline/blob/main/src/engine.rs#L1641-L1650).

### How to reproduce

1. Pass a string with spaces to a command as the last argument, ex. `echo "foo bar"`.
2. Type !$ and press enter

### Expected behavior

Use the whole last parameter instead of splitting against the space.

### Configuration

| key                | value                                                                                                                                                            |
| ------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.99.2                                                                                                                                                           |
| major              | 0                                                                                                                                                                |
| minor              | 99                                                                                                                                                               |
| patch              | 2                                                                                                                                                                |
| branch             | makepkg                                                                                                                                                          |
| commit_hash        | 8b19399b1336798197088b90dd8b6a97f4261509                                                                                                                         |
| build_os           | linux-x86_64                                                                                                                                                     |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                         |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)                                                                                                                              |
| rust_channel       | 1.80.1-x86_64-unknown-linux-gnu                                                                                                                                  |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                                                                                                                              |
| build_time         | 2024-11-04 09:00:06 +00:00                                                                                                                                       |
| build_rust_channel | release                                                                                                                                                          |
| allocator          | mimalloc                                                                                                                                                         |
| features           | default, sqlite, trash                                                                                                                                           |
| installed_plugins  | custom_values 0.1.0, example 0.98.0, explore 0.99.1, formats 0.98.0, gstat 0.98.0, inc 0.98.0, jwalk 0.8.0, polars 0.98.0, query 0.98.0, stress_internals 0.98.0 |

**Comment by fdncred** [comment] 2024-11-05 02:47
Agreed. I've known this for a while. There may be an issue for it somewhere. I'm pretty sure this is a reedline issue vs nushell though.

**Comment by sholderbach** [comment] 2024-11-05 15:02
Ah found on further digging: 
- Duplicate of this particular problem with `!$` https://github.com/nushell/nushell/issues/6971
- And the issues of it being generally syntax unaware like around quotes in #13577

**Closed** 2024-11-05 21:24 UTC
Labels: line editor, needs-triage, duplicate
