### ISSUE TITLE
Corruption of history.txt on Windows

### ISSUE THREAD

**Issue by AaronErhardt** [nushell/nushell#4494] opened 2022-02-16 08:15 UTC
### Describe the bug

When using Nu for a while, it might happen that the history file just explodes with huge amount of backslashes added to random commands.

Let's say you have `cd Dir` in your history. This might eventually end up as `cd \\\\\\\\\\\\\\\\\\Dir\\\\\\\\\\\\\\`, just a lot worse. In fact, it gets so bad that Windows Terminal crashes when I type `cd` because the autocomplete suggestion pastes over 200 kB of backslashes.

[An example from my history](https://github.com/nushell/nushell/files/8077915/part_of_history.txt)

### How to reproduce

1. Install Nu (from chocolatey) with basically no configuration changes
2. Use Nu for a couple of days (I sometimes use quite a few instances in parallel)

### Expected behavior

Nu doesn't change paths in old commands. No backslashes are randomly added.

### Configuration

> I don't have the transpose command for some reason, so here's the output without

| version | short_commit | commit_hash                              | commit_date                | build_os       | rust_version                        | rust_channel                  | cargo_version                       | pkg_version | build_time                 | build_rust_channel | features                                                            | installed_plugins                                                                                                                                                       |
| ------- | ------------ | ---------------------------------------- | -------------------------- | -------------- | ----------------------------------- | ----------------------------- | ----------------------------------- | ----------- | -------------------------- | ------------------ | ------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 0.44.0  | a660720b     | a660720b6889eab2fa3153854b0a367172c3821d | 2022-02-08 01:15:46 +00:00 | windows-x86_64 | rustc 1.58.1 (db9d1b20b 2022-01-20) | stable-x86_64-pc-windows-msvc | cargo 1.58.0 (f01b232bc 2022-01-19) | 0.44.0      | 2022-02-08 01:49:18 +00:00 | release            | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by kubouch** [comment] 2022-02-16 08:27
We had history problems before but I think they should be resolved in the latest main since we switched to another line editor.

**Comment by fdncred** [comment] 2022-02-16 12:16
@AaronErhardt if you have a way to reproduce this on 0.44.0 we could try and see if it still happens on 0.59.0.

**Comment by AaronErhardt** [comment] 2022-02-16 13:33
Since this is a quite noticeable bug that existed for me since 0.39 and it seems like nobody else has reported this, I assume it could be hard to reproduce. Or maybe there just aren't a lot of Windows users...

Reproducing should only require installing Nu with no configuration changes and using it a bit. Unfortunately, I can't say when this happens, but it seems like the backslashes are inserted gradually and become more over time.

Btw. the terminals I used were Windows Terminal and the terminal inside VSCode.

However, I can install the latest version from git and then report back if the bug still happens or not.

**Comment by fdncred** [comment] 2022-02-16 15:27
Thanks. I think 0.59 uses a different location for the history.txt so they shouldn't clobber each other. I would say though, that on 0.44, once your history.txt gets corrupted it's best to either delete it or edit it so it doesn't have garbage in it.

**Comment by fdncred** [comment] 2022-03-06 14:38
I think we should close this as it hasn't been reported in 0.59.

**Closed by fdncred** 2022-03-06 14:38 UTC
Labels: bug, engine-q, 0.60
