### ISSUE TITLE
Prompt is bold by default

### ISSUE THREAD

**Issue by ShinyZero0** [nushell/nushell#9123] opened 2023-05-06 23:41 UTC
### Describe the bug

Set any prompt
```js
$env.PROMPT_COMMAND = {|| (ansi { fg: '#fafafa' attr: 'n'}) + $env.PWD }
```
and it's bold if you don't `ansi reset` at the start. Very confusing

### How to reproduce

1. Wish to make a non-bold prompt

### Expected behavior

Don't set any default attributes to user's prompt

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.78.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.68.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

0.79 `nu -n` same behaviour

**Comment by fdncred** [comment] 2023-07-31 15:43
I did more diagnostics and found that `starship` seems to be rendering the ansi codes correctly, seen here (and also in discord)
```
\n
\u{1b}[38;2;102;2;217m
\u{e0b6}
\u{1b}[48;2;102;2;217;38;2;255;255;255m
fdncred 
\u{1b}[48;2;219;86;116;38;2;102;2;217m
\u{e0b0}
\u{1b}[38;2;255;255;255m
 …/nushell 
\u{1b}[48;2;250;150;110;38;2;219;86;116m
\u{e0b0}
\u{1b}[38;2;35;33;54m 
\u{f418} 
 main 94bec72 
\u{1b}[48;2;255;232;120;38;2;250;150;110m
\u{e0b0}\u{1b}[38;2;35;33;54m  
\u{1b}[48;2;95;204;207;38;2;255;232;120m
\u{e0b0}\u{1b}[38;2;35;33;54m 
\u{e7a8} v1.69.0 
\u{1b}[48;2;11;110;184;38;2;95;204;207m
\u{e0b0}
\u{1b}[1;38;2;252;154;157m <-- This is bold RGB 252, 154, 157
 95% 
\u{f125d}  
\u{1b}[0m\u{1b}[48;2;11;110;184;38;2;255;255;255m
♥ 10:21 500ms 
\u{1b}[0m\u{1b}[38;2;11;110;184m
\u{e0b0} 
\u{1b}[0m\n
\u{1b}[1;38;2;255;92;111m <-- This is bold RGB 255, 92, 111
654321 
\u{f467} 
❯
\u{1b}[0m 
\n
```

Tested in `kitty` on WSL and was able to reproduce the problem with @LeoniePhiline's starship.toml seen here with it rendereing as the prompt and then just calling starship.
![image](https://github.com/nushell/nushell/assets/343840/2ae9bf86-2e5e-470b-bb1f-1f78906a1db9)

I think this could be a reedline/crossterm issue but I haven't been able to narrow it down. I also can't pinpoint the error with a more simplistic prompt like this. You can see that `green_bold` and `green` look the same.
![image](https://github.com/nushell/nushell/assets/343840/2b7a54e8-8c7a-4ecb-a517-bf5bad0ec488)
Although if you look closely at the escapes, nushell is passing the escapes correctly. The top one is `green_bold` aka `1:32m` and the bottom is `green` aka `32m`
![image](https://github.com/nushell/nushell/assets/343840/68a4d410-1938-477c-8be7-9d8ff0f666f0)

**Comment by fdncred** [comment] 2023-07-31 18:23
If we can get the reedline PR 615 landed, I believe it'll fix this.

**Closed** 2023-07-31 19:39 UTC
Labels: :bug:  bug, configuration

**Comment by LeoniePhiline** [comment] 2023-07-31 19:52
Thanks for digging all the way down!
