### ISSUE TITLE
Tab-completed filenames aren't sorted

### ISSUE THREAD

**Issue by YaLTeR** [nushell/nushell#8023] opened 2023-02-09 23:35 UTC
### Describe the bug

Tab-completed filenames appear to not be sorted. Or rather, they are sometimes sorted, but sometimes not. Maybe it's based on file ids or something?

### How to reproduce

1. Open some folder, write `cd ` and hit Tab

### Expected behavior

The filenames in tab complete are always sorted alphabetically.

### Screenshots

Compare to fish on the right (note that fish goes by columns whereas nu goes by rows):

![image](https://user-images.githubusercontent.com/1794388/217962522-57fd5dda-144a-474e-9074-b9e90d66fede.png)

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.75.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.67.0 (fc594f156 2023-01-24)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.67.0 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.75.0                               |
| build_time         | 2023-02-09 15:10:05 -08:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

### Additional context

I frequently use the fact filenames are sorted in fish to tab-complete the last file. E.g. all videos recorded from OBS or screencasts recorded from GNOME Shell will have the same filename format for which alphabetic sorting is equal to sorting by date, so a quick Tab-Shift Tab lets me run an ffmpeg command on the latest recording.

**Comment by ryand67** [comment] 2023-02-12 02:09
I'll take this one!

**Comment by amtoine** [comment] 2023-07-12 17:44
according to some users, this issue has be addressed and i cannot reproduce either :open_mouth: 
i'll close this issue, please feel free to request reopening if the feature falls down again :relieved:

**Closed by amtoine** 2023-07-12 17:44 UTC
Labels: good first issue, polish, completions
