### ISSUE TITLE
Background streams

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#1329] opened 2020-02-01 20:46 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes you want to set up a pipeline to run at a certain time or just to process in the background. 

**Describe the solution you'd like**
Something as simple as a command that takes the pipeline as an argument (like a block)

**Describe alternatives you've considered**
Alternately, you could leverage a task system and create new tasks in that.

**Comment by thegedge** [comment] 2020-02-02 18:24
Okay, I see a few features I'd like in backgrounded pipelines:

1. Results buffering.
2. Status requests.
3. Cancellation/kill requests.
4. Bringing the pipeline to the foreground (first gives me the buffered results, then continues processing).

Here's what that could potentially look like:

```
$ background my_backgrounded_pipeline { pipeline | ... }
$ 
$ echo $my_backgrounded_pipeline.status
$ read_background my_backgrounded_pipeline | ...
$ cancel $my_backgrounded_pipeline
```

Not sure about the names of these, just for show. If no name is given, the pipeline simply runs in the background, with an expectation that it is set up in some way to communicate to the end user its results (e.g., `save`).

**Comment by koenaad** [comment] 2020-02-02 19:50
Could these background pipelines be implemented as a 'shell'? So you could cycle through them using the `n` and `p` commands. It would tie it all together for me.

I really like the flow of opening a couple of shells and cycling between them. But it's use is limited now since you can't cycle anymore when a program is running. So it only makes sense to have shells in different directories to avoid `cd`'ing all the time.

I think it would be great if you could start a program (i.e. `ng serve`) and then switch to the next shell using some shortcut. Then I could easily cycle back-and-forth to check on the running program.

**Comment by brasilikum** [comment] 2021-06-25 14:02
Is there any workaround for now? 
Or would you need to run a whole no instance of nu?

**Comment by dumblob** [comment] 2021-07-11 21:23
Isn't this actually a duplicate of https://github.com/nushell/nushell/issues/247 ?

If not, then I'd still propose what I did in #247 - namely the [Nursery pattern](https://en.wikipedia.org/wiki/Structured_concurrency ) (aka "structured concurrency") as the MVP and a very solid foundation for this issue.

**Comment by jntrnr** [comment] 2023-08-09 17:41
This is closely related to #247

**Closed** 2023-08-09 17:42 UTC
Labels: enhancement, needs-design, delight, exempt
