### ISSUE TITLE
Panic when completing with `only_buffer_difference: true` and a non-empty line buffer

### ISSUE THREAD

**Issue by epbuennig** [nushell/nushell#9006] opened 2023-04-26 11:45 UTC
### Describe the bug

I had the following completion menu from some default config back when I first installed `nu`, after fixing because of some breaking updates I tried out this completion menu. I encountered a panic when completing and using a navigation key.

```nu
let config = {
  # ...
  menus: [
    {
      name: commands_with_description
      only_buffer_difference: true
      marker: "# "
      type: {
        layout: description
        columns: 4
        col_width: 20
        col_padding: 2
        selection_rows: 4
        description_rows: 10
      }
      style: {
        text: green
        selected_text: green_reverse
        description_text: yellow
      }
      source: { |buffer, position|
        $nu.scope.commands
        | where name =~ $buffer
        | each { |it| { value: $it.name description: $it.usage } }
      }
    }
  ]
  # ...
}
```

### How to reproduce

1. type at least one character into the line buffer
2. run the completion menu given above
3. complete some command, accepting the completion to drop out of the menu
4. press `arrow-up` (or I assume `k` in vi mode)

### Expected behavior

It rejects the current line and moves up the command history as if the line was empty and `arrow-up` (`k`) was pressed.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.78.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) |
| cargo_version      | cargo 1.68.2                                                     |
| build_time         | 2023-04-05 02:09:35 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

### Additional context

I, unfortunately, am too lazy to build with debug symbols to get a better stack trace, but it contains the line number and is reproducible.
```
~
❯ taliasthread 'main' panicked at 'byte index 7 is out of bounds of `talias`', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.18.0/src/core_editor/line_buffer.rs:647:10
stack backtrace:
   0:     0x562dd845f29e - <unknown>
   1:     0x562dd6e5124e - <unknown>
   2:     0x562dd8457ff5 - <unknown>
   3:     0x562dd845f075 - <unknown>
   4:     0x562dd8460e1f - <unknown>
   5:     0x562dd8460b94 - <unknown>
   6:     0x562dd84614c1 - <unknown>
   7:     0x562dd8461256 - <unknown>
   8:     0x562dd845f7cc - <unknown>
   9:     0x562dd8460f92 - <unknown>
  10:     0x562dd6a9d833 - <unknown>
  11:     0x562dd6e55585 - <unknown>
  12:     0x562dd6a9de77 - <unknown>
  13:     0x562dd832133b - <unknown>
  14:     0x562dd83408b5 - <unknown>
  15:     0x562dd83411a2 - <unknown>
  16:     0x562dd833fc46 - <unknown>
  17:     0x562dd6f565bb - <unknown>
  18:     0x562dd6f12fd1 - <unknown>
  19:     0x562dd6f23d07 - <unknown>
  20:     0x562dd6f1f50b - <unknown>
  21:     0x562dd6f13383 - <unknown>
  22:     0x562dd844fe4c - <unknown>
  23:     0x562dd6f242dc - <unknown>
  24:     0x7f213ca3c790 - <unknown>
  25:     0x7f213ca3c84a - __libc_start_main
  26:     0x562dd6b02855 - <unknown>
  27:                0x0 - <unknown>
```

I am using [starship](https://github.com/starship/starship) for my prompt, not sure if this meddles with the line buffer position because of the different prompt.

**Comment by fdncred** [comment] 2023-04-26 11:53
I can reproduce on 0.79.0. I'm not sure it's about the menu but perhaps the history? It's kind of a weird issue.

```
'hello' | str upcasethread 'main' panicked at 'byte index 30 is out of bounds of `'hello' | str upcase`', /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/core_editor/line_buffer.rs:647:10
stack backtrace:
   0:        0x104b189e0 - std::backtrace_rs::backtrace::libunwind::trace::h74af4446853d6729
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104b189e0 - std::backtrace_rs::backtrace::trace_unsynchronized::hbbdfd4ef476b857c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104b189e0 - std::sys_common::backtrace::_print_fmt::h5439e990fc83de1b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x104b189e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7f563e99e08996c8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x104b392b4 - core::fmt::write::h828d1a1d9994c0d4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:        0x104b10d78 - std::io::Write::write_fmt::h5f89acb1837ba600
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:        0x104b187f4 - std::sys_common::backtrace::_print::h13f47e65a1f035c2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x104b187f4 - std::sys_common::backtrace::print::h840392abbac6ee51
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x104b1a6f4 - std::panicking::default_hook::{{closure}}::h4759ed42ee25f714
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:        0x104b1a44c - std::panicking::default_hook::h0e3a71e8a2850720
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:        0x102548260 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he999ae396c9f0783
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:2001:9
  11:        0x10254704c - nu::main::{{closure}}::hfe862b7009c34ac2
                               at /Users/fdncred/src/nushell/src/main.rs:40:9
  12:        0x104b1ad58 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc4cb6d0cd0ce8d2b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:2001:9
  13:        0x104b1ad58 - std::panicking::rust_panic_with_hook::h7210718e7f3b5517
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:692:13
  14:        0x104b1ab40 - std::panicking::begin_panic_handler::{{closure}}::h783370b8bddac8b4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
  15:        0x104b18e48 - std::sys_common::backtrace::__rust_end_short_backtrace::h33a0191324141f1f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  16:        0x104b1a894 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  17:        0x104b7cae4 - core::panicking::panic_fmt::h8c7962154a272fe6
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  18:        0x104b3dbe0 - core::str::slice_error_fail_rt::he7fb66b2c91bf1bd
  19:        0x104b7cdfc - core::str::slice_error_fail::hb8e64bb8a9ddd940
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/str/mod.rs:86:9
  20:        0x104812e88 - core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index::h48c768bee1c0a1a1
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/str/traits.rs:218:21
  21:        0x104813914 - core::str::traits::<impl core::ops::index::Index<I> for str>::index::h5d58f512b039f454
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/str/traits.rs:65:9
  22:        0x10365d634 - reedline::core_editor::line_buffer::LineBuffer::is_cursor_at_first_line::h84081eeee2df2881
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/core_editor/line_buffer.rs:647:10
  23:        0x1036467b8 - reedline::core_editor::editor::Editor::is_cursor_at_first_line::h7893fc7a0f9687bd
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/core_editor/editor.rs:158:9
  24:        0x1036330cc - reedline::engine::Reedline::up_command::h5f60140b7e1bb7e1
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/engine.rs:1313:12
  25:        0x10362f6c4 - reedline::engine::Reedline::handle_editor_event::h4f585c36bb6e6ab3
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/engine.rs:1081:17
  26:        0x10362fe04 - reedline::engine::Reedline::handle_editor_event::h4f585c36bb6e6ab3
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/engine.rs:1123:27
  27:        0x10362ea20 - reedline::engine::Reedline::handle_event::he3f50b37c121a7f4
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/engine.rs:696:13
  28:        0x10362e690 - reedline::engine::Reedline::read_line_helper::h79cfefdb397cdc93
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/engine.rs:673:23
  29:        0x10362d94c - reedline::engine::Reedline::read_line::hbbd5cd42aa75660f
                               at /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.19.0/src/engine.rs:534:22
  30:        0x1025ae070 - nu_cli::repl::evaluate_repl::haa2cf8add3aa0ce4
                               at /Users/fdncred/src/nushell/crates/nu-cli/src/repl.rs:443:21
  31:        0x102536380 - nu::run::run_repl::h7b90cd334be4f5e4
                               at /Users/fdncred/src/nushell/src/run.rs:245:19
  32:        0x1025308cc - nu::main::h0e3c7dd25c5b8229
                               at /Users/fdncred/src/nushell/src/main.rs:269:9
  33:        0x1025462e4 - core::ops::function::FnOnce::call_once::h93c439b9c90aad0d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
  34:        0x102551540 - std::sys_common::backtrace::__rust_begin_short_backtrace::hacdd0849155db4b4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:121:18
  35:        0x102536ea4 - std::rt::lang_start::{{closure}}::hdfbb65f36f7bc229
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:166:18
  36:        0x104b0a518 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b53062eab6199a4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:286:13
  37:        0x104b0a518 - std::panicking::try::do_call::h17d3b9ed3583552a
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
  38:        0x104b0a518 - std::panicking::try::h2d654c437390750a
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
  39:        0x104b0a518 - std::panic::catch_unwind::h0860f5037be189c4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
  40:        0x104b0a518 - std::rt::lang_start_internal::{{closure}}::hac5a1bfdb95d5868
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:48
  41:        0x104b0a518 - std::panicking::try::do_call::h6244e1d5ff64380f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
  42:        0x104b0a518 - std::panicking::try::h05734b1779c06a48
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
  43:        0x104b0a518 - std::panic::catch_unwind::h01f5b06b20d00263
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
  44:        0x104b0a518 - std::rt::lang_start_internal::h54d26558116c1823
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:20
  45:        0x102536e6c - std::rt::lang_start::h7a1a81fe70a4883c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:165:17
  46:        0x102532820 - _main
```

**Comment by sholderbach** [comment] 2023-10-15 18:24
Appears to be a duplicate of #8091, will copy the repro over if there is a detail worth differentiating.

**Closed by sholderbach** 2023-10-15 18:24 UTC
Labels: :bug:  bug, line editor, panic
