### ISSUE TITLE
`$nothing` in `match` matches everything

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#9198] opened 2023-05-14 18:21 UTC
### Describe the bug

It seems that `$nothing` does not work just like `null` in `match`, but matches with everything.

### How to reproduce

```sh
> match 1 {
∙ $nothing => true,
∙ 1 => false,
∙ _ => 1
∙ }
true
> match 1 {
∙ null => true,
∙ 1 => false,
∙ _ => 1
∙ }
false
```

Same for any other type of data, string, list, record, etc.

### Expected behavior

The documentation said `null` is a.k.a. `$nothing` so I believe they should work in the same way :smile: 

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.79.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.68.1 (8460ca823 2023-03-20)                                             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.68.1 (115f34552 2023-02-26)                                             |
| build_time         | 2023-04-27 06:27:42 +08:00                                                      |
| build_rust_channel | release                                                                         |
| features           | default, zip                                                                    |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

**Comment by fdncred** [comment] 2023-05-14 18:25
That's odd. If you do `null == $nothing` it should come back as true since they both evaluate to `Value::Nothing`. Maybe there's a bug in the `match` command?

**Comment by mksinicus** [comment] 2023-05-14 18:35
I also see neither `$nothing` nor `null` can be the "value to check" in `match`, otherwise the result would always be that of the fallback block:

```sh
> match null {
∙ null => true,
∙ _ => false
∙ }
false
> match $nothing {
∙ null => true,
∙ _ => false
∙ }
false
> # But again, `$nothing` will match
> match null {
∙ $nothing => true,
∙ _ => false
∙ }
true
```

I don't know if it is intended behavior (seems not). Maybe they grew out of the same bug in the `match` command?

**Comment by tesla232** [comment] 2023-05-17 00:55
I've found that this bug occurs whenever a variable is used in a match statement. For example:
```
let a = 221;
match 1 {
$a => 1,
_ => 0
}
```
returns 1. I believe this is caused by
https://github.com/nushell/nushell/blob/8695b575848d5eb4d688087aa9e906b4d9e7c8d8/crates/nu-protocol/src/engine/pattern_match.rs#L43-L47
I'm not sure why variables return true for a pattern match, though if I had to guess it would be so
```
let $a=32
```
is valid.

**Comment by mksinicus** [comment] 2023-05-17 05:13
> I've found that this bug occurs whenever a variable is used in a match statement. For example:
> 
> ```
> let a = 221;
> match 1 {
> $a => 1,
> _ => 0
> }
> ```
> 
> returns 1. 

That's part of the pattern matching feature I think. A standalone variable is also a "pattern" (cf. value in list or record), like `Some(x)` in Rust's `match`.

```sh
> let a = 100
> match 1 {$a => $a, _ => 0}
1
```

However `$nothing` and `$in` are "builtin variables", so normally if you try to `let`-bind one of them you'll get a warning. I've constructed a case to test `$in`:

```sh
> # `$in` would match, but won't be re-assigned in the conditional block
> 1 | match ($in + 1) {$in => $in, 2 => 3, _ => 0}
1
> # The "indefinite variable" pattern would take precedence over actual values:
> 1 | match ($in + 1) {$a => $a, 2 => 3, _ => 0}
2
```

The case of `$nothing` is similar to the case of `$in` I think,

```sh
> match 1 {$nothing => $nothing, 1 => 1, _ => 0} # returns null
```

So maybe the cause is, in a `matchblock`, variable identifiers-looking token are not evaluated before it is recognized as such (to have them assigned the matched values,  so that they can be used in the conditional block). Perhaps an exception should be made for builtin variables like `$in` and `$nothing`.

And parentheses can't be used to force-evaluate in advance (in fact they seem to match nothing. Is it intended behavior?):

```sh
> match 2 { (1 + 1) => 2, _ => false }
false
> match '(1 + 1)' { (1 + 1) => 2, _ => false }
false
> # compare matching against a string
> match 'foo' { foo => true, _ => false }
true
```

**Comment by Mehrbod2002** [comment] 2023-05-17 05:23
@fdncred 
On March command there is handler , when it reaches to it as any variable,  it will return true, 
Suppose have to evaluate it , but `Variable`there is not method to retrieve a any value,  I check stack and engine_stack too , do you know how can evaluate the Variable ?

**Comment by ysthakur** [comment] 2024-05-22 23:38
Closing because `$nothing` was removed in 0.87 and it seems like matching on `null` works fine now. Let us know if you come across problems matching on `null`.

**Closed by ysthakur** 2024-05-22 23:38 UTC
Labels: :bug:  bug, semantics, pattern-matching
