### ISSUE TITLE
Calling `vi filename` now gives warning

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1173] opened 2020-01-08 16:57 UTC
**Describe the bug**
Calling out to an interactive external, we are now in an unexpected state

**To Reproduce**
1. Run `vi Cargo.toml` with the latest master

**Expected behavior**
This should work as before, where the external works like it would in other shells

**Screenshots**

![Screenshot from 2020-01-09 05-55-30](https://user-images.githubusercontent.com/547158/71998575-c3d89d80-32a4-11ea-8413-d10f2304e15f.png)

**Configuration (please complete the following information):**
 - OS: Linux
 - Version: Master from 2020-01-09 NZ
 - Optional features: stable

cc @thegedge

**Comment by thegedge** [comment] 2020-01-08 17:54
Yeah, this is from https://github.com/nushell/nushell/pull/1056, since we moved to always establishing a pipe for stdin. I don't have an immediate solution, but likely it would be fixed by the "optimization pass" idea we discussed in Discord.

**Comment by thegedge** [comment] 2020-01-08 17:56
Actually, I have an idea. If we have a peekable stream, we could peek at the first item in the stream. If it's a `Nothing` value, we know we're first in the pipeline and don't need to set up a stdin pipe.

**Comment by thegedge** [comment] 2020-01-10 00:49
Caused by https://github.com/nushell/nushell/pull/1056.

**Closed** 2020-01-10 06:31 UTC
