### ISSUE TITLE
Cannot cd into ~/

### ISSUE THREAD

**Issue by Nate-Watts** [nushell/nushell#475] opened 2019-08-26 22:44 UTC
Maybe I have something setup incorrectly with my environment, but currently ~/ isn't recognized.
```
/Users/nwatts> cd ~
error: Parse Error
- shell:1:3
1 | cd ~
  |    ^
/Users/nwatts> 
```

**Comment by twe4ked** [comment] 2019-08-26 23:07
Dupe of https://github.com/nushell/nushell/issues/340.

**Comment by jonathandturner** [comment] 2019-08-27 00:51
Closing as dupe of #340

**Closed by jonathandturner** 2019-08-27 00:51 UTC

**Comment by jonathandturner** [comment] 2019-08-27 06:10
(basic support now in https://github.com/nushell/nushell/pull/479)
