### ISSUE TITLE
nu 0.60 beta cannot `ls` in a UNC share

### ISSUE THREAD

**Issue by anisoptera** [nushell/nushell#4863] opened 2022-03-17 15:50 UTC
### Describe the bug

This works on 0.44.0 (released non-beta). If you `cd` to a UNC share in the 0.60.0 beta, `ls` doesn't work. Instead of listing files I get an error about `./*: not found`.

I can still `cd` to directories I know exist, but listing files fails no matter what directory I'm in on the share.

### How to reproduce

1. `cd` to a UNC share (\\servername\sharename)
2. type `ls`

### Expected behavior

List files in a fancy table

**Comment by fdncred** [comment] 2022-03-17 16:40
this seems to work
```
> ls \\localhost\admin$ 
╭─────┬──────────────────────────────────────────────────────────────────┬──────┬──────────┬────────────────╮
│  #  │                               name                               │ type │   size   │    modified    │
├─────┼──────────────────────────────────────────────────────────────────┼──────┼──────────┼────────────────┤
│   0 │ \\localhost\admin$\AppReadiness                                  │ dir  │      0 B │ 44 minutes ago │
│   1 │ \\localhost\admin$\Boot                                          │ dir  │   4.1 KB │ 9 months ago   │
│   2 │ \\localhost\admin$\Branding                                      │ dir  │      0 B │ 9 months ago   │
│   3 │ \\localhost\admin$\BrowserCore                                   │ dir  │      0 B │ 9 months ago   │
│   4 │ \\localhost\admin$\CSC                                           │ dir  │      0 B │ 2 years ago    │
│   5 │ \\localhost\admin$\CbsTemp                                       │ dir  │   4.1 KB │ a week ago     │
│   6 │ \\localhost\admin$\Containers                                    │ dir  │      0 B │ 9 months ago   │
```

**Comment by fdncred** [comment] 2022-03-17 17:17
I think this is the problem. Our glob crate doesn't know what to do with VerbatimUNC paths.
https://github.com/nushell/nushell/blob/6e69d40bb9f5602cf110e75c3cdd27be9d1d15ca/crates/nu-glob/src/lib.rs#L226-L239

unc path
```
root=[Some("\\\\?\\UNC\\localhost\\admin$\\")]
```
path components
```
p=PrefixComponent { raw: "\\\\?\\UNC\\localhost\\admin$", parsed: VerbatimUNC("localhost", "admin$") }
```

**Comment by MCoooo** [comment] 2022-06-08 18:16
Hi, this issue is caused by the PWD using UNC. If PWD is set to drive format, e.g. let-env PWD = "L:\\Scripts" ,  all is well.

![nushell-pwd](https://user-images.githubusercontent.com/68328255/172687976-ba9eb178-cb74-4f32-95a0-9caa43f8cfc3.PNG)

**Comment by anisoptera** [comment] 2022-06-08 19:35
Yes, the bug is specifically about the pwd being a UNC path. I don’t want to have to map a drive letter to use a share. I can’t switch away from powershell without feature parity :)

**Comment by MCoooo** [comment] 2022-06-10 09:37
Ah sorry - reading helps! I raised a similar issue but for drive map use case but didn't pick up on this distinction (folded into here as dup).

While being very much on at the start of my Rust (and GitHub) journey *and* without understanding the implication, but wishing to use nu on a daily basis, I've forked and and swapped \\\\?\\UNC\\ to \\\\ in cwd in env.rs.

Hasn't broken yet. If of any use...

https://github.com/MCoooo/nushell_hack

Hopefully get time to understand what's going on more fully

**Comment by MCoooo** [comment] 2022-06-13 10:50
After removing the condition
_'if root_len > 0
        && check_windows_verbatim(root.expect("internal error: already checked for len > 0"))'_

and using a verbatim path, nu ls does generate a contents list but not as expected. When change directory uses a verbatim path some auto correction takes place where needed (device to unc and case for example). When ls is used directly against a verbatim, there is no autocorrection, however it does generate a list.

However verbatim paths currently do no just display the files but some of the path, so I assume the 'name' object is incorrect for use in piped commands.

Not sure of the QA benchmarks for changes, but I would argue its better to promote adoption in the Windows (Enterprise) space with this limitation / rough edge. Unless of course more is broken...

<img width="443" alt="allow_verbatim" src="https://user-images.githubusercontent.com/68328255/173338112-c85d3f18-2dc3-4f9d-8859-b3e4414c45a5.png">

**Comment by charlesroper** [comment] 2022-08-13 14:23
I came across this issue trying to CD into WSL. My Ubuntu WSL instance is mapped to U: but the path gets converted to a UNC path.

![2022-08-13_01](https://user-images.githubusercontent.com/176/184498276-53c20a67-0415-41aa-b7d7-ea0a2c79d814.png)

There's an open issue about this for `zoxide`: https://github.com/ajeetdsouza/zoxide/issues/162

Which leads to a problem with `dunce`: https://gitlab.com/kornelski/dunce/-/issues/2

Could this be the problem?

**Comment by fdncred** [comment] 2022-08-13 22:02
`cd` is not the same as `ls`, of course, but this problem could be related. we use dunce as well but switching from dunce to crate x may not solve the problem this issue states (but it may solve the cd'ing issue). I spelled out above what I thought the issue was with verbatimunc paths.

**Comment by charlesroper** [comment] 2022-08-14 22:02
Sorry, I wasn't clear! cd'ing works. The error you see in my screenshot is Zoxide failing (maybe because of `dunce`). I can, however, still type commands. If I invoke `ls`, it gives me the error this issue is about.

![2022-08-14_01](https://user-images.githubusercontent.com/176/184556097-9dd5bb01-88be-4873-bb9a-0ffd1055794e.png)

Not sure if these things are related or not, but seemed worth mentioning.

**Comment by fdncred** [comment] 2022-08-15 14:25
i'm guessing they're related but someone would have look at the ls code and debug it probably.

**Comment by ehawman** [comment] 2022-09-03 20:03
Wanted to chime in by saying that recently I've been getting a more aggressive error message. 

![image](https://user-images.githubusercontent.com/52979227/188286074-15af830e-d872-4014-a282-16966e62b3ec.png)

Not sure if this is due to some third-party application or if there are just more debug options in Nu now.

I should note here that I have pwd as

``` nush
def pwd [] {
    echo $env.PWD | sd \\ /
}
```

Hence the forward slashes, but both manual entry and `cd pwd` results in the same gobbledygook.

**Comment by fdncred** [comment] 2022-09-03 22:37
@ehawman That's weird. Those look like dotnet errors. nushell doesn't have any dotnet but on Windows it may call into the Windows API that is dotnet.

**Comment by rgwood** [comment] 2022-10-23 05:07
Good news, UNC issues should be fixed by https://github.com/nushell/nushell/pull/6824. The fix will be released in Nushell v0.71.

**Closed by rgwood** 2022-10-23 05:07 UTC
Labels: :bug:  bug, help wanted

**Comment by MCoooo** [comment] 2022-10-23 08:08
Fantastic. Great work all.

**Comment by charlesroper** [comment] 2022-10-23 17:12
Thank you so much folks! Especially @ChrisDenton for `omnipath`. 🙏
