### ISSUE TITLE
Conflict between "export extern" and "export def"

### ISSUE THREAD

**Issue by j-xella** [nushell/nushell#13184] opened 2024-06-20 10:29 UTC
### Describe the bug

I have a nu-shell wrapper around some external command, which parses the output and converts it into a table. The wrapper has the same name as the external command, and is in a module.

However, sometimes I want to access the external command directly too (^command), but in style. For that, I want to define extern for it. 

When I do this, I get `Error: nu::parser::duplicate_command_def`

### How to reproduce

1. Create a module `test.nu`
2. In the module, define a wrapper `export def aaa [] {}`
3. In the same module, define extern `export extern aaa []`
4. `use test.nu *`

```
Error: nu::parser::duplicate_command_def

  × Duplicate command definition within a block.
    ╭─[/path/to/test.nu:15:15]
 14 │ export def aaa [] {}
 15 │ export extern aaa []
    ·               ─┬─
    ·                ╰── defined more than once
 16 │
    ╰────
```

### Expected behavior

1. There are no errors
2. When I write `aaa`, `export def` is used, as usual
3. When I write `^aaa` external aaa is called, but with help, argument completion etc... as defined in `export extern`

### Configuration

| key                | value                                                                |
| ------------------ | -------------------------------------------------------------------- |
| version            | 0.94.2                                                               |
| major              | 0                                                                    |
| minor              | 94                                                                   |
| patch              | 2                                                                    |
| branch             |                                                                      |
| commit_hash        | be8c1dc0066cd1034a6b110a622f47b516bfe029                             |
| build_os           | linux-x86_64                                                         |
| build_target       | x86_64-unknown-linux-musl                                            |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                  |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                      |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                  |
| build_time         | 2024-06-03 19:20:40 +00:00                                           |
| build_rust_channel | release                                                              |
| allocator          | mimalloc                                                             |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  | polars, query                                                        |

**Comment by kubouch** [comment] 2024-06-20 17:37
This works as intended, if we allowed both have the same name, if you called `aaa`, Nushell wouldn't be able to know what to do. `extern` creates a command definition same as `def`, just without the body. The `^aaa` calls the external directly without going through the `extern` definition.

**Comment by j-xella** [comment] 2024-06-20 23:28
I guess I misunderstood the [documentation](https://www.nushell.sh/book/externs.html) then. It says:

> This is where extern comes in. The extern keyword allows you to write a full signature for **the command that lives outside of Nushell**

And `^command` means invoking external command, so I decided that `export extern` will be used there...

**Comment by kubouch** [comment] 2024-06-23 09:35
`extern` defines a command with a signature internally. When you call it, the flags etc. get parsed and typechecked same as with normal commands, but it automatically calls the external (hence no need for the command body, like in `def`). `^command` bypasses the signature parsing altogether.

I'll close this since it seems to be working as ecpected.

**Closed by kubouch** 2024-06-23 09:35 UTC
Labels: needs-triage
