### ISSUE TITLE
nu -c "# '" fails

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#5175] opened 2022-04-13 07:24 UTC
### Describe the bug

`nu -c "# '"` gives an error of `expected closing '`. However, the opening `'` is commented out, so this error should not be occurring.

### How to reproduce

In `bash` or `nu`, run ` nu -c "# '"`.

### Expected behavior

Expected: no error.

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             | nushell                               |
| tag                |                                       |
| build_os           | macos-aarch64                         |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 2022-04-12 20:38:15 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by fdncred** [comment] 2022-04-13 13:54
I noticed that the error provides a hint, everything is single quotes in the error.
```
./target/debug/nu -c "# '"
Error: nu::parser::unexpected_eof (link)

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ nu -c '# ''
   ·            ▲
   ·            ╰── expected closing '
   ╰────
```

**Comment by uasi** [comment] 2022-04-29 14:46
Now `` nu -c '# `' `` fails.

**Comment by ajeetdsouza** [comment] 2022-04-29 18:40
@jntrnr can this be reopened?

**Comment by jntrnr** [comment] 2022-04-30 04:27
Can we change the issue to the example that's currently broken?

Also, can you walk me through when this happens in practice? It reads like we're just trying corner cases but would be good to know that this fixes a real world issue.

**Comment by uasi** [comment] 2022-04-30 04:59
This is certainly a real world issue. Currently (1fc7abcc383c2f8ec2fea24ebf9990b81bff69ad) any one-liner containing backticks fail or misbehave.

```
bash-3.2$ target/debug/nu -c 'mkdir "./my_dir_with_`_in_name"'
Error: nu::parser::unexpected_eof (https://docs.rs/nu-parser/0.61.1/nu_parser/enum.ParseError.html#variant.UnexpectedEof)

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ nu -c `mkdir "./my_dir_with_`_in_name"`
   ·                                        ▲
   ·                                        ╰── expected closing "
   ╰────
```

```
bash-3.2$ target/debug/nu -c 'echo `hello world`'
`echo `hello
```

**Comment by uasi** [comment] 2022-04-30 05:27
Also, `nu -c "#'"` still fails (note the lack of the whitespace between `#` and `'`).

**Comment by uasi** [comment] 2022-04-30 05:42
The above issues are due to the following lines not escaping backticks in `arg` and not escaping `arg` containing no whitespace:

https://github.com/nushell/nushell/blob/1fc7abcc383c2f8ec2fea24ebf9990b81bff69ad/src/main.rs#L85-L89

**Comment by jntrnr** [comment] 2022-04-30 06:44
@uasi - agreed, that seems like the cause.

If you have fixes, we'd happily take a PR for them.

**Comment by uasi** [comment] 2022-04-30 17:58
@jntrnr unfortunately this issue doesn't seem to be easily fixed.

``format!("`{}`", arg) `` and `` format!("'{}'", arg) `` are insufficient. ``format!("\"{}\"", arg.replace('\\', r"\\").replace('"', r#"\""#)`` should work, but `nu -c` misparses escaped double quotes as described in https://github.com/nushell/nushell/issues/5383.

**Comment by jntrnr** [comment] 2022-05-01 21:56
With @uasi's help, I think this is now fixed in the latest main.

**Closed by jntrnr** 2022-05-01 21:56 UTC
Labels: bug

**Comment by ajeetdsouza** [comment] 2022-05-01 22:00
@jntrnr the real world use case is that I'm using `nu -c` in CI for [zoxide](https://github.com/zoxide)'s nushell plugin. The use case is to test for syntax errors in the generated init script.
