### ISSUE TITLE
Indicate (like fish) if the command/executable would be valid before running. 

### ISSUE THREAD

**Issue by kaifastromai** [nushell/nushell#8775] opened 2023-04-06 17:43 UTC
### Related problem

Say I try typing ``poetry`` because I am certain I added it to the path. But when I press enter, ERR! 

### Describe the solution you'd like

 It would be useful (although not particularly urgent) to indicate whether or not the executable can be found/is valid before I ever press enter. Fish (the shell I migrated from) does and it's quite convenient. I am fairly avid rust developer myself, so I could potentially help out with this, with the proper guidance. 

### Describe alternatives you've considered

Just pressing enter and waiting for the error message.

### Additional context and details

None?

**Comment by rgwood** [comment] 2023-04-09 03:53
How does Fish indicate this?

**Comment by sholderbach** [comment] 2023-04-17 12:58
Duplicate of #4134 and #5612

**Closed by sholderbach** 2023-04-17 12:58 UTC
Labels: enhancement
