### ISSUE TITLE
Slashes are not supported as path separators on windows

### ISSUE THREAD

**Issue by Sympatron** [nushell/nushell#2513] opened 2020-09-08 09:06 UTC
At the moment it is not possible to use slashes as a path separator in windows.

For example autocompletion does not work if you use a slash instead of a backslash (`cd ../<tab>` does nothing).

I don't know if this is expected behaviour, but the only why to run any file is to write `.\<file>`. `./<file` and just `program.exe` do not work ("error: Command not found"). The latter could be deliberately not working, because it would be consistent with other shells like bash (although unfamiliar on windows).

Slash is a perfectly valid path separator on windows in almost all cases (except as the start of a UNC path) and should be treated as such in my opinion.

It is also kind of odd that `cd .\<dir>` leads to nushell reporting `C:\<whatever>\.\<dir>` as the current path in the next line. Although I don't know if this is a related or a different issue.

I am currently using version 0.19.0.

**Comment by thegedge** [comment] 2020-09-16 00:48
Duplicate of https://github.com/nushell/nushell/issues/2535

A little slowly, but I'm trying really hard to improve paths and completions 🙂

**Closed by thegedge** 2020-09-16 00:48 UTC
