### ISSUE TITLE
Release notes for 0.4.0 have wrong link

### ISSUE THREAD

**Issue by wagenet** [nushell/nushell#850] opened 2019-10-18 17:02 UTC
It should be http://www.jonathanturner.org/2019/10/nushell-0_4_0.html, with a dash between nushell and 0.

**Comment by jonathandturner** [comment] 2019-10-18 17:37
Dupe of #841 

Unfortunately, we're still waiting for github to fix the bug so we can update it

**Closed by jonathandturner** 2019-10-18 17:37 UTC

**Comment by wagenet** [comment] 2019-10-21 12:34
Whoops, sorry for the duplicate!
