### ISSUE TITLE
Custom nerdfont prompt breaks prompt into two lines

### ISSUE THREAD

**Issue by wingertge** [nushell/nushell#4374] opened 2022-02-08 18:22 UTC
### Describe the bug

When using a custom nerdfont prompt the prompt gets broken from one line into to, with the right prompt in the first and the left in the second. This happens even when the right prompt is set to an empty string, so it's clearly not spacing issues.

### How to reproduce

1. Set up oh-my-posh or starship (both have the same issue)
2. Open nushell
3. The prompt is now two lines

### Expected behavior

The prompt should be one line regardless of whether the left prompt is custom or not.

### Screenshots

![image](https://user-images.githubusercontent.com/1058083/153051112-59861c75-3b30-4cf4-89a2-0d4f9ae80c25.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | master                                   |
| short_commit       | 19caef26                                 |
| commit_hash        | 19caef260d0a18b226a32f7a76976d38503f964a |
| commit_date        | 2022-02-08 16:21:17 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-08 18:03:56 +01:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, which, zip           |
| installed_plugins  |                                          |

**Comment by fdncred** [comment] 2022-02-08 18:36
@wingertge can you post your oh-my-posh json or starship config for us to test with?

**Comment by fdncred** [comment] 2022-02-08 18:56
I reproduced it like this.
1. launch nushell
2. `hide PROMPT_COMMAND_RIGHT` <-- this should now show your default ticking reedline right prompt
3. `let-env PROMPT_INDICATOR = " "`
4. `let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS }`
5. you may need this too `let config = ($config | update animate_prompt $true)`
6. now you should see the bug where the right prompt is one line higher than your left prompt

The solution for this was to trim the left prompt like this:
`let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS | str trim }`

I'm not sure i'd consider this a bug. it's just how nushell works, unless we want it to work differently.

**Comment by wingertge** [comment] 2022-02-08 18:58
I've now figured out it can be fixed with an explicit `add_newline = false` in `starship.toml`. Seems this interacts strangely with the right prompt. This makes successive prompts "stick together" if no output is between them, but probably better than a newline in between every command.

**Comment by fdncred** [comment] 2022-02-08 19:13
I removed the `bug` label since I think this is just an interoperability item. I documented these findings in #4375. I also think we can close this because I don't believe any further code is going to be written to change this. If anyone disagrees, feel free to re-open and comment.

**Closed by fdncred** 2022-02-08 19:13 UTC
