### ISSUE TITLE
Dmenu stopped working after the shell was changed from bash to nu

### ISSUE THREAD

**Issue by s1n7ax** [nushell/nushell#4929] opened 2022-03-24 10:00 UTC
### Describe the bug

I'm using https://tools.suckless.org/dmenu/ and after changing the shell to nu, launching applications through dmenu is not working.

### How to reproduce

1. Clone the demenu project, build and install dmenu
2. run dmenu_run script
3. select a GUI application

### Expected behavior

Application should be launched

**Comment by hustcer** [comment] 2022-05-07 14:11
dupe of https://github.com/nushell/nushell/issues/5002, Please view that for more detail

**Closed by hustcer** 2022-05-07 14:11 UTC
