### ISSUE TITLE
Piping output into vim no longer works

### ISSUE THREAD

**Issue by crides** [nushell/nushell#11295] opened 2023-12-11 19:36 UTC
### Describe the bug

As title. Piping any output into vim will produce an error like:
```
rror: nu::shell::io_error

  × I/O error
  help: Os { code: 35, kind: WouldBlock, message: "Resource temporarily
        unavailable" }
```
And stop the display from updating. I can still, however, send commands to vim and quit.

### How to reproduce

```
ls | nvim
```

### Expected behavior

no errors are produced, vim receives the output and functions normally

### Screenshots

<img width="860" alt="Screenshot 2023-12-11 at 11 29 55" src="https://github.com/nushell/nushell/assets/15631555/03d2e115-fbc6-45f5-8c32-54da51676eba">

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.87.2                                                            |
| branch             | main                                                              |
| commit_hash        | 310c905f3ae5326dc1ebe79f5c5eac8f02a6ddde                          |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-12-01 14:46:41 -08:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, extra, sqlite, trash, which, zip                         |
| installed_plugins  | from plist, hist, plot, xyplot                                    |

### Additional context

This used to work (just like in POSIX shells), but it doesn't work now. After bisecting for a bit, this changed in roughly this range of commits:
```
8386bc091 Convert more ShellError variants to named fields (#11173)
182b0ab4f add echo_env_mixed testbin to reduce windows only tests (#11172)
fa83458a6 Add metadata to some filters (#11160)
54398f954 Bump `sysinfo` to 0.29.11 (#11166)
077d1c812 Support `o>>`, `e>>`, `o+e>>` to append output to an external file (#10764)
1ff8c2d81 Cp target expansion (#11152)
d77f1753c add shape `ExternalResolved` to show found externals via syntax highlighting in the repl (#11135)
85c6047b7 fix the link to the `nu_scripts` in `std clip` deprecation (#11150)
d37893cca (HEAD) Add more descriptive error message when passing list to from_csv (#10962)
95ac436d2 Fix release and nightly build workflow (#11146)
c2a46070a Exit the release job if creating binary package failed (#11145)
57808ca7c Redirect: support redirect stderr with piping stdout to next commands. (#10851)
6cfe35eb7 enable to pass switch values dynamically (#11057)
b2734db01 Move more commands to opaque `Record` type (#11122)
823e578c4 Spread operator for list literals (#11006)
```
Note: this is a [non-upstream branch](https://github.com/crides/nushell). I didn't bisect further because the behaviour got a bit weird around here. I'd suspect it's one of the redirection commits, though I haven't looked to see which one would cause this

**Comment by nibon7** [comment] 2023-12-12 00:34
try `ls | vim -`?

**Comment by nibon7** [comment] 2023-12-12 00:44
`ls | nvim` and `ls | nvim -` both work in my system.

nushell: v0.87.0 or d717e8faeb5a7e842b47de20fe573ba05a628f26
nvim: v0.9.4

**Comment by crides** [comment] 2023-12-12 00:51
I rebased onto `b3a52a247` and tested, still doesn't work

nvim: v0.9.1, though I don't think that'd make a difference, cuz this works fine in `zsh`

**Comment by crides** [comment] 2023-12-12 01:02
No idea yet, but this _could_ be a mac thing. I'll test this on a Linux once I get back today

**Comment by amtoine** [comment] 2023-12-12 14:26
i think there is an issue in `0.87.2` :thinking: 
it does work on `0.87.1` but behaves stangely with the nightly builds :thinking:

**Comment by amtoine** [comment] 2023-12-12 14:27
i don't get an error but the terminal gets all messed up :open_mouth:

**Comment by RGBCube** [comment] 2023-12-12 20:22
As a temporary workaround - use vipe from moretools

**Comment by amtoine** [comment] 2023-12-13 11:54
## i just opened https://github.com/nushell/nushell/issues/11312 which is a duplicate of this

i'll bisect the two releases to find the culprit... :recycle:

**Comment by amtoine** [comment] 2023-12-13 12:05
ok i found the culprit:
- 57808ca and https://github.com/nushell/nushell/pull/10851

@WindSoilder any ideas? :innocent:

**Comment by amtoine** [comment] 2023-12-13 12:34
> Oh...That's really unexpected... Sorry for introducing such issue, I'll try to take a look into this
>
no worries at all :wink: 
when you get a moment would be perfect, this all is quite subtle afaik :scream:

**Closed** 2023-12-13 19:16 UTC
Labels: regression, needs-triage

**Comment by crides** [comment] 2023-12-13 19:26
Yep, the fix works, thanks!

**Comment by fdncred** [comment] 2023-12-13 19:59
We're thinking about doing a hotfix for this. Hopefully we'll decide today.
