### ISSUE TITLE
`cp` cannot find source file in the  `cd`ed directory in script

### ISSUE THREAD

**Issue by TD-Sky** [nushell/nushell#10832] opened 2023-10-25 05:57 UTC
### Describe the bug

```nushell
def main [stem: string] {
    let in_dir = $env.PWD

    cd '~/Templates/dev'
    # let template = ^ls -1
    #     | sk -i --ansi -c 'fd {}' --preview 'bat -pp --color=always {}'
    #     | str trim -r
    let template = 'foo.rs'

    echo $template

    let extension = $template | path parse | get extension
    let dest = $in_dir | path join $"($stem).($extension)"

    cp $template $dest
}
```

This is a script to copy my template file to the specified location. I'm sure that the file $template exists. But I got an $template not found error when running the script.

Strangely, it works fine under interactive mode via typing line by line.

### How to reproduce

```bash
# 1.
$ mkdir -p ~/Templates/dev

# 2.
$ touch ~/Templates/dev/foo.rs

# 3.
$ script bar
```

Then you will get an file not found error.

### Expected behavior

It should create an file named `bar.rs` with the content of `foo.rs` in the current directory.

### Screenshots

![image](https://github.com/nushell/nushell/assets/44722470/81ceda7e-3686-436e-943c-09ff6188aa79)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.86.1                                      |
| branch             | makepkg                                     |
| commit_hash        | cb754befe91d6ba3e853004fe90ff3a1af7caa9b    |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.75.0-nightly (1c05d50c8 2023-10-21) |
| cargo_version      | cargo 1.75.0-nightly (8eb8acbb1 2023-10-17) |
| build_time         | 2023-10-24 21:55:19 +00:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, trash, which, zip          |
| installed_plugins  |                                             |

**Comment by amtoine** [comment] 2023-10-25 11:35
i've been able to reproduce this :+1: 

the bug disappears when you already are in `~/Templates/dev/` :open_mouth:

**Comment by fdncred** [comment] 2023-10-25 11:43
But I'm not convinced it's a bug with `cp`. It's more likely something going on with `cd` right?

**Comment by amtoine** [comment] 2023-10-25 11:45
> But I'm not convinced it's a bug with `cp`. It's more likely something going on with `cd` right?
>
exactly, looks it's from `cd` from what i'm seeing :+1:

**Comment by TD-Sky** [comment] 2023-10-25 11:49
> > But I'm not convinced it's a bug with `cp`. It's more likely something going on with `cd` right?
> 
> exactly, looks it's from `cd` from what i'm seeing 👍

But `$env.PWD` is indeed the directory after `cd`.

**Comment by fdncred** [comment] 2023-10-25 11:56
But then again `cp` shouldn't be giving that error since it's not a ShellError.

Also, I put debug messages in the ucp code and they're never printing. I'm so confused.

@dmatos2012 Do you have time to look into why `cp` is failing here? Is it `cp`? Is it `cd`?

**Comment by fdncred** [comment] 2023-10-25 11:58
oh, i know why it's not printing my debug messages, that's because i'm doing `nu tpl.nu bar` and it's calling a different version of nushell, duh.

**Comment by fdncred** [comment] 2023-10-25 12:03
I think it's some weird `cp` issue. Here's my debug messages. Notice the `PWD from ucp` message. It's in the right folder. So, it's `ucp` failing somehow. Then you can see the parameters. Maybe it's weird that `foo.rs` is in brackets?
![image](https://github.com/nushell/nushell/assets/343840/0ca28816-8424-4454-8226-ac6b6ad802c2)

**Comment by fdncred** [comment] 2023-10-25 13:40
I'm wondering now if this could've broken with @bobhy's latest changes?

**Comment by dmatos2012** [comment] 2023-10-25 18:57
No, its not related to @bobhy's PR since I checked out that commit~1, and the error still persists. Before bobhys PR was merged,  it errors out on the file coming out of globbing coming out as empty and errors out on `$template file not found`. Particularly here

snippet 1
```
match nu_glob::glob_with(&expanded_src.to_string_lossy(), GLOB_PARAMS) {
  Ok(files) => {
      let f = files.filter_map(Result::ok).collect::<Vec<PathBuf>>();
      dbg!(&f); // &f = [] thus crashes on following line
      if f.is_empty() {
              return Err(ShellError::FileNotFound(p.span));
      }

```

Now, going back to current `main` on nushell,  it errors out on `uutils::cp()` rather than our own code handling(see snippet 1), thus something related with globbing I believe. For example, looking at these cases

```
cargo r --  tpl.nu bar
[crates/nu-command/src/filesystem/ucp.rs:204] &sources = [
    "foo.rs", # note relative path
]
```
debug line  corresponding to sources PathBuf in [code](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/filesystem/ucp.rs#L201) 

However, if you do 
`touch a`

```
>cp a b
[crates/nu-command/src/filesystem/ucp.rs:204] &sources = [
    "/home/david/Documents/oss/nushell/a", #note full path
]
```
It succeeds but its always the full path specified in `sources` not relative like `foo.rs` above. So not sure but hope this helps :)

**Comment by fdncred** [comment] 2023-10-25 19:33
very weird. maybe it would help to bring @tertsdiepraam in to see if he's heard of this weirdness?

**Comment by tertsdiepraam** [comment] 2023-10-25 19:57
uutils service desk here, how can I help you today? 😉

This _feels_ like something that's not entirely on the uutils side, but rather something about the integration of `uu_cp` into nushell. My guess is that the `PWD` that `nu` stores is somehow different from the `PWD` that `uu_cp` operates in. @fdncred how did you get the `PWD` in those debug messages? I'll try to add a debug print in on both the nushell and the uutils side to see what's going on.

**Comment by dmatos2012** [comment] 2023-10-25 19:58
No, its not on the `uutils` side. If you swap `cp` to `uutils cp` it succeeds!. Sorry @tertsdiepraam I tried to write this before you showed up but welp too late :( haha

**Comment by tertsdiepraam** [comment] 2023-10-25 20:08
So, there's a stack, which contains env vars right? And possibly, the same var appears in multiple stack frames. uutils just takes the PWD from the environment variables it gets, not the environment variables in the stack. The old cp solved this by getting the PWD from the stack:
```

**Comment by bobhy** [comment] 2023-10-25 20:17
The cp error you're getting may be due to the *dest* path including a folder that doesn't exist.

There's something strange with expansion of `~`,  at least for me on Windows.  Folder `cd ~/Templates/dev` didn't put you in the directory you specified, and there's no guarantee it even exists.

```
> cd ~
|> $env.PWD
C:\Users\bobhy_b2jfqo9
> cd ~/Templates/dev
> $env.PWD
C:\Users\bobhy_b2jfqo9\AppData\Roaming\Microsoft\Windows\Templates\dev
> cd ~
> $env.PWD
C:\Users\bobhy_b2jfqo9
```

I don't recognize the AppData\Roaming\Microsoft\Windows prefix.  It's not the value of any of the usual environment variables.  I don't have access to Linux to see what happens there, either.

Here's my version info, for comparison
```
╭────────────────────┬──────────────────────────────────────────╮
│ version            │ 0.86.1                                   │
│ branch             │ main                                     │
│ commit_hash        │ 878f0cf6e1353dab8cab9a2ccdcd1ed109c07621 │
│ build_os           │ windows-x86_64                           │
│ build_target       │ x86_64-pc-windows-msvc                   │
│ rust_version       │ rustc 1.71.1 (eb26296b5 2023-08-03)      │
│ rust_channel       │ 1.71.1-x86_64-pc-windows-msvc            │
│ cargo_version      │ cargo 1.71.1 (7f1d04c00 2023-07-29)      │
│ build_time         │ 2023-10-20 18:48:27 -07:00               │
│ build_rust_channel │ release                                  │
│ allocator          │ mimalloc                                 │
│ features           │ default, sqlite, trash, which, zip       │
│ installed_plugins  │                                          │
╰────────────────────┴──────────────────────────────────────────╯
```

**Comment by fdncred** [comment] 2023-10-25 21:36
> uutils service desk here, how can I help you today? 😉

LOL, Thanks for jumping in.

@tertsdiepraam This is how I got the path in my screenshots.
```rust
        eprintln!("ucp here");
        eprintln!(
            "PWD from ucp = {:?}",
            nu_engine::env::current_dir(engine_state, stack)
        );
```
and then before uu_cp::copy
```rust
        eprintln!(
            "about to call uu_cp::copy {:?} {:?}",
            &sources, &target_path
        );
```

**Comment by tertsdiepraam** [comment] 2023-10-25 22:31
Right, so here's the issue I think.

If I run this with some `dbg!`s:
```nu
def main [] {
   cd '~/Programming/uutils/nushell/crates/nu-command'

   cp Cargo.toml Cargo2.toml
}
```

I get this:

```
[crates/nu-command/src/filesystem/ucp.rs:99] std::env::current_dir() = Ok(
    "/home/terts/Programming/uutils/nushell",
)
[crates/nu-command/src/filesystem/ucp.rs:100] nu_engine::env::current_dir(engine_state, stack) = Ok(
    "/home/terts/Programming/uutils/nushell/crates/nu-command",
)
```

So the `PWD` in the environment (that uutils relies on) is not the same as the `PWD` according to the nu engine.

**Comment by fdncred** [comment] 2023-10-25 22:52
Right. We're always supposed to use the `nu_engine::env::current_dir()` in nushell. We're never supposed to use `std::env::current_dir()`. So, can't we just pass the appropriate paths to `uu_cp::copy()` or does uutils do something with `std::env::current_dir()`?

**Comment by fdncred** [comment] 2023-10-25 23:24
I've tried a couple things like doing this in the `cd` command and in the `cp` command but it doesn't seem to work. Not sure where to go from here.
```rust
   std::env::set_var("PWD", &path_value);
```

**Comment by tertsdiepraam** [comment] 2023-10-25 23:41
`cp` doesn't use it explicitly, but the current working directory is used by the syscalls that performs under the hood. These syscalls use the something like `getcwd()` to resolve the current directory, which is also why setting `PWD` doesn't work, because that then goes out of sync with `getcwd()`. To set it correctly, you can do `std::env::set_current_dir`. I think it makes sense to add that to `cd`.

We should also think about the other environment variables, but that's a lower priority.

**Comment by fdncred** [comment] 2023-10-26 12:00
Thanks for the advice @tertsdiepraam. That fixed it for me. I put up a PR with the fix.

**Comment by fdncred** [comment] 2023-11-16 13:22
After the team meeting yesterday, @kubouch volunteered to fix this by passing fully qualified paths to uu_cp. We hope to have this resolved soon.

**Closed** 2023-11-16 23:30 UTC
Labels: :bug:  bug, coreutils-uutils
