### ISSUE TITLE
Path not conditionally modifiable

### ISSUE THREAD

**Issue by your-local-developer** [nushell/nushell#6703] opened 2022-10-11 09:59 UTC
### Describe the bug

I want to append certain files only to my PATH if the directory exists.
It's the same way as my `.profile` is configured.
After modifying my `env.nu` to conditionally include `~/.local/bin`, it won't appear in the output of `$env.PATH`.
Done without condition, it does show appear, tho.

### How to reproduce

1. Append the following lines to your `~/.config/nushell/env.nu `
2. Log out
3. Log on
4. Check the terminal if _"Gets executed"_ gets printed
5. Check $env.PATH if it includes `/home/<YOUR_USER>/.local/bin`

```nu
# ~/.config/nushell/env.nu
# ...

let home_bin = ([$env.HOME '.local' 'bin'] | path join)
if ($home_bin | path exists) {
    print "Gets executed"
    let-env PATH = ($env.PATH | prepend $home_bin)
}

# EOF
```

### Expected behavior

I expect the output of `$env.PATH` to include `/home/jan/.local/bin`.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             | makepkg                                         |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (Arch Linux rust 1:1.64.0-1)       |
| cargo_version      | cargo 1.64.0                                    |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 03:30:35 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment] 2022-10-11 10:57
With the current design of nushell the environment is also scoped although mutable compared to regular variables which are considered immutable: https://www.nushell.sh/book/thinking_in_nu.html#nushell-s-environment-is-scoped

To accomplish what you describe you currently need to follow an expression oriented pattern
``` shell
let home_bin = ([$env.HOME '.local' 'bin'] | path join)
let-env PATH = (if ($home_bin | path exists) {
    print "Gets executed"
    $env.PATH | prepend $home_bin
} else { $env.PATH })
```

It is definitely a common pattern and we are considering as part of the language evolution process to make this easier or more intuitive.

**Comment by your-local-developer** [comment] 2022-10-12 12:40
Thank you, for your help! 😄

**Comment by atahabaki** [comment] 2023-10-29 17:03
@your-local-developer you could use `in` operator. Below is the perfect example in your case:

```nu
let home_bin = ([$env.HOME '.local' 'bin'] | path join)
if not ($home_bin in $env.PATH) {
    print "Gets executed"
    $env.PATH = ($env.PATH | prepend $home_bin)
}
```

**Comment by amtoine** [comment] 2023-10-29 17:48
actually, if i update the repro script above to the new syntax, i.e. with `$env.PATH` instead of `let-env PATH`,
```nushell
let home_bin = ([$env.HOME '.local' 'bin'] | path join)
if ($home_bin | path exists) {
    print "Gets executed"
    $env.PATH = ($env.PATH | prepend $home_bin)
}
```
because `$home_bin` exists on my system, i see my `$env.PATH` growing :yum: 

i'll close this issue then :relieved: 
feel free to reopen if some part of the original issue is still reproducable :wink:

**Closed by amtoine** 2023-10-29 17:48 UTC
Labels: polish, engine-r
