### ISSUE TITLE
Newlines in string comprehension

### ISSUE THREAD

**Issue by yourealwaysbe** [nushell/nushell#3980] opened 2021-08-31 15:15 UTC
### Describe the bug

When using `$"(cmd1)(cmd2)"` newlines are inserted between the command output. This makes things like

    mv $file $"(dirname $file)/newname"

break because the new name has a newline before the /.

### How to reproduce

1. run `echo $"(dirname hey/ho)/ho"`
2. observe output is

    hey
    /ho

### Expected behavior

`echo $"(dirname hey/ho)/ho"` outputs `hey/ho`

### Configuration

|key|value|
|-|-|
|version|0.35.0|
|short_commit|bc682066|
|commit_hash|bc682066d8eb756727c38d98ae58a34dd9cb3b38|
|commit_date|2021-08-03 08:01:09|
|build_os|linux-x86_64|
|rust_version|rustc 1.54.0 (a178d0322 2021-07-26)|
|rust_channel|stable-x86_64-unknown-linux-gnu (default)|
|cargo_version|cargo 1.54.0 (5ae8d74b3 2021-06-22)|
|pkg_version|0.35.0|
|build_time|2021-08-03 08:30:50|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment] 2021-08-31 16:16
How about this?
`> echo $"(dirname hey/ho)/ho" | str trim --all`
hey/ho

You can see the problem more visible here
```
echo $"(dirname hey/ho)/ho" | debug --raw
Value {
    value: Primitive(
        String(
            "hey\n/ho",
        ),
    ),
    tag: Tag {
        anchor: None,
        span: Span {
            start: 461,
            end: 483,
        },
    },
}
```

**Comment by yourealwaysbe** [comment] 2021-08-31 16:22
That works -- i usually avoid spaces in filenames :)

It's not a general workaround though:

    > echo $"(dirname 'dir with spaces/ho')/ho" | str trim --all
    dirwithspaces/ho

**Comment by fdncred** [comment] 2021-08-31 17:23
You can also trim only a specific character.

**Comment by kubouch** [comment] 2021-09-03 11:59
@yourealwaysbe You can also use `path` subcommands to construct paths, e.g., `"hey/ho" | path dirname | path join -a "ho"`

I believe this is not a bug. The `dirname` Unix command outputs a newline by default, so the behavior is correct. You can pass a `-z` to `dirname` to not append the newline. This works as expected: `echo $"(dirname -z hey/ho)/ho"`.

You can test this by wrapping it into single quotes for example:
```
❯ $"'(dirname hey/ho)'"
'hey
'

❯ $"'(dirname -z hey/ho)'"
'hey'
```

**Comment by yourealwaysbe** [comment] 2021-09-03 13:45
@kubouch thanks for the tips.

The newline might only be to separate multiple arguments. The man page examples for me show

       dirname /usr/bin/
              -> "/usr"

       dirname dir1/str dir2/str
              -> "dir1" followed by "dir2"

which is a bit ambiguous, but neither bash nor zsh append a newline when there's only a single path argument.

**Comment by kubouch** [comment] 2021-09-04 15:53
@yourealwaysbe You're right, it's indeed Nushell who's appending the newline.

Bash: 
```
> echo "--$(dirname /usr/bin)--"
--/usr--
```

Nushell
```
> $"--(dirname /usr/bin)--"
--/usr
--

> build-string '--' (dirname /usr/bin) '--'
--/usr
--
```

It seems like a bug. I noticed that sometimes Nushell appends two newlines instead of one on my Linux. I'm wondering if it's the same issue.

**Comment by fdncred** [comment] 2022-03-06 15:02
I don't think this is a nushell issue. with 0.59 you can see that dirname is appending a new line.
```
dirname /usr/bin | debug -r
String {
    val: "/usr\n",
    span: Span {
        start: 83988,
        end: 83995,
    },
}
```
you can also see this outside of nushell. this is from fish.
```
dirname /usr/bin | xxd 
00000000: 2f75 7372 0a                             /usr.
```

bash's `echo` seems to eat the newline from `dirname`.

Since we're probably not going to try to reproduce the bash experience, I vote that we close this issue.

**Closed** 2022-11-23 03:51 UTC
Labels: :bug:  bug
