### ISSUE TITLE
Pressing tab twice on alias causes nushell to panic and crash the terminal

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#8026] opened 2023-02-10 10:20 UTC
### Describe the bug

if I declare an alias in the config.nu file and try to use it in the terminal autocomplete

like `alias = foo_bar baz `

If i try to autocomplete the command and press tab twice `nu shell` panics and crashes the terminal. This is not a serious bug just encountered it when I accidentally pressed `Tab` key twice when doing autocomplete on the alias

I am on  KDE Neon (Ubuntu 22.04).

I tried it on `Konsole` (default KDE terminal) and it panics with an error and crashed the terminal

I also tried it on alacritty terminal app and it panics with error message
`thread 'main' panicked at 'Can't create a Span whose end < start, start=18446744073709523827, end=8', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.15.0/src/completion/base.rs:18:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

but it does not crash alacritty terminal

### How to reproduce

1. Create an alias in config.nu file  `alias = foo_bar baz `
2. Restart terminal / nu
3. type `foo_` and press `Tab` key to autocomplete
4. Press `Tab` key again after autocomplete is done

### Expected behavior

I expected nu not to crash

### Configuration

Sorry this returns an error, maybe I am missing a plugin or something

```sh
to: command not found
version: command not found
transpose: command not found
```

**Comment by sholderbach** [comment] 2023-02-10 12:09
Thanks for the detailed report! Weird that the version command etc. are not found. I have to look up if we have similar issues already, because I remember both panics around the aliases and panics after pressing `TAB` twice.

**Comment by henryjetmundsen** [comment] 2023-02-18 23:41
The failure happens at [completer.rs line 401](https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/completions/completer.rs#L401). The failure specifically happens when the alias name is longer than value it is aliased to. In the linked code, `line_vec` is the vector of ascii values representing the value of the alias, and `input_vec` is the vector of ascii values representing the name of the alias. Since `alias_offset` is of type `Vec<u8>`, we encounter an error when trying to push a negative value to it.

**Comment by sholderbach** [comment] 2023-02-18 23:47
Thanks for digging into that @henryjetmundsen! I think there have been some debugging efforts in that direction of completion panics due to aliases. @kubouch has been fighting around with a bug fix as one fix of a panic accidentally removed the important subcommand completion functionality. (#8102)

It seems to me that this issue could be a dupe of #7648 based on your investigation.

**Comment by kubouch** [comment] 2023-02-19 10:25
I can't reproduce the issue because `alias = foo_bar baz` is not a valid syntax. Seems like you meant `alias foo_bar = baz` which indeed crashes Nushell.

We're currently figuring out a better alias implementation because the current one made the completions code overly complex and unmaintainable.

**Closed** 2023-02-27 08:12 UTC
Labels: :bug:  bug, completions

**Comment by charleschege** [comment] 2023-03-20 07:44
The new alias implementation breaks if an alias command has an equal sign `=` for example if I add an alias in the `config.nu` file of the git command with env variable
```
alias foo_git = GIT_SSH_COMMAND="ssh -i /home/foo_user/path/to/other/ssh/key/.ssh/id_ed25519" git
```
If I try executing the `git` command aliased as `foo_git` 
```sh
foo_git push -u origin master
```
I get the error below
```sh
Results in the error
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ foo_git push -u origin master
   · ───┬───
   ·    ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

This is in both nu `0.77.0` and `0.77.1`  running on ubuntu 22.04

**Comment by kubouch** [comment] 2023-03-20 09:32
Can you please open a new issue with the environment shorthand issue?

**Comment by charleschege** [comment] 2023-03-20 10:42
I have filed the issue here - https://github.com/nushell/nushell/issues/8541
