### ISSUE TITLE
`datetime` deserialization from `nuon` records is broken

### ISSUE THREAD

**Issue by crides** [nushell/nushell#10985] opened 2023-11-07 02:08 UTC
### Describe the bug

`datetime` types somehow can't survive the de/serialization round trip in nuon, but only for records.

```
> {d: (date now)} | to nuon | from nuon
Error:   × error when parsing nuon text
   ╭─[entry #64:1:1]
 1 │ {d: (date now)} | to nuon | from nuon
   ·                             ────┬────
   ·                                 ╰── could not parse nuon text
   ╰────

Error:   × error when parsing
```

but it's fine for tables:
```
> [{d: (date now)}] | to nuon | from nuon
╭───┬─────╮
│ # │  d  │
├───┼─────┤
│ 0 │ now │
╰───┴─────╯
```

### How to reproduce

`{d: (date now)} | to nuon | from nuon`

### Expected behavior

return the same thing (or close to, cuz time) as `{d: (date now)}`

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.86.1                                                            |
| branch             | main                                                              |
| commit_hash        | 8560b9b90e078974f908c0a49ea8fedd3ab2ded4                          |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-11-06 09:49:47 -08:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by crides** [comment] 2023-11-07 05:48
Oh, so [this is a lexing problem](https://github.com/nushell/nushell/blob/main/crates/nu-parser/src/parser.rs#L5104). `:` is treated as a top level token, which definitely doesn't play well with the embedded colons within the `datetime`

**Comment by crides** [comment] 2023-11-07 08:44
looking at the parsing code, technically for a janky patch we could just chain colon-delimited tokens (which don't contain spaces) together and try to recognize that as a datetime, as that would just fail to parse anyway?

**Comment by sholderbach** [comment] 2023-11-07 21:07
Duplicate of 
- #10889 
- #8257

**Closed** 2024-08-28 20:53 UTC
Labels: :bug:  bug, nuon-format, duplicate
