### ISSUE TITLE
Permit combining stdout/stderr as streams to external command behind pipe

### ISSUE THREAD

**Issue by x10an14** [nushell/nushell#9684] opened 2023-07-14 12:54 UTC
### Related problem

See #9673 

### Describe the solution you'd like

See https://github.com/nushell/nushell/issues/9673#issuecomment-1635488819

### Describe alternatives you've considered

See #9673 

### Additional context and details

https://github.com/nushell/nushell/issues/9673#issuecomment-1635750733

**Comment by fdncred** [comment] 2023-07-14 13:19
maybe we should call this dupe of #9673 and just close it?

**Comment by amtoine** [comment] 2023-07-14 13:28
i think we can just modify the content of #9673 to make it a feature request :yum: 
having two issues for that doesn't seem that useful :relieved:

**Closed by amtoine** 2023-07-14 13:28 UTC
Labels: enhancement, needs-triage
