### ISSUE TITLE
About the table's autocomplete in new nushell

### ISSUE THREAD

**Issue by chen244** [nushell/nushell#4372] opened 2022-02-08 16:22 UTC
### Related problem

In the 0.44 ,It can do this action
![image](https://user-images.githubusercontent.com/60290287/153029774-966941da-8fb7-4b67-9021-da07bc86c100.png)
But In the engine-q which is pull ,it cannot

### Describe the solution you'd like

If in new nushell such action can be reserved？

**Comment by kubouch** [comment] 2022-02-08 16:28
The issue is that hitting tab does not complete the `b.bin.name`?

**Comment by herlon214** [comment] 2022-04-30 19:50
Probably fixed by https://github.com/nushell/nushell/pull/5204

**Comment by fdncred** [comment] 2022-04-30 21:58
@herlon214 that is so cool!

**Closed by fdncred** 2022-04-30 21:58 UTC
Labels: enhancement, completions
