### ISSUE TITLE
SambaShare navigation not as expected

### ISSUE THREAD

**Issue by Zethtren** [nushell/nushell#6812] opened 2022-10-19 16:09 UTC
### Describe the bug

This error is on Windows 11. I have not tested on other OS's. I have a sambashare with a static IP mounted to the T: directory. When I switch directories using T: It will switch although the displayed name shows the connection type, ip and folder path for the shared folder "\\?\UNC\REDACTED_IP_ADDR\sambashare" instead of "T:".

Further, when using ls in cmd prompt it lists the contained folders. In nu, instead, I get this error "Error:  × No matches found for ./*
  help: no matches found"
  
Everything works as expected on this drive in CMD.

### How to reproduce

1. Install nu with winget.
2. Run nu from cmd
3. cd into sambashare with mounted path
4. run ls

### Expected behavior

I expected nu to list the files and directories contained within the sambashare.

### Screenshots

From C: drive behaviour is normal

![image](https://user-images.githubusercontent.com/56445354/196745116-f3ecd155-c549-433c-b9c8-5f4072848e46.png)

From T: it does not work:

![image](https://user-images.githubusercontent.com/56445354/196745488-f698ea4d-bb2d-4b9c-a9e7-a478933ac357.png)

Action works on base CMD terminal 
![image](https://user-images.githubusercontent.com/56445354/196745725-03c721b6-807a-4829-8b65-172f6b55ec77.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment] 2022-10-19 17:15
UNC shares are not supported by one of nushell's crates. It would be nice if someone fixed it. You can find more documentation on this by searching for UNC in our issue list like #6461, #4863, #686, etc. So, this is really a dupe of those.

**Comment by Zethtren** [comment] 2022-10-19 17:30
I see. Thanks for the quick insight!

**Comment by fdncred** [comment] 2022-10-19 23:36
closing due to being a dupe

**Closed by fdncred** 2022-10-19 23:36 UTC
Labels: platform-specific, file-system
