### ISSUE TITLE
Break out of long running command with CTRL+C

### ISSUE THREAD

**Issue by schoetbi** [nushell/nushell#1898] opened 2020-05-26 14:06 UTC
I did `open 200MbFile.dat`. It ran very long and pressing Ctrl+C did not work. I did not find a way to get back to the command prompt.

For me pressing CTRL+C would be the most natural way.

**Comment by thegedge** [comment] 2020-05-26 14:16
Yeah, we have Ctrl-C in some places and not in others. We probably want it everywhere, ideally in a way that Just Works™ for most commands (that lazily compute values in the pipeline).

**Comment by JosephTLyons** [comment] 2020-05-27 05:17
I just finished working on adding ctrl+c support for the `du` command here, https://github.com/nushell/nushell/issues/1844, so since its fresh in my mind, I could probably take this one.

**Comment by jonathandturner** [comment] 2020-05-27 08:04
This is related to https://github.com/nushell/nushell/issues/1448

The issue is that the current open is synchronous and does not stream blocks of data through the pipeline.  Ideally, `open`, `fetch`, and `post` would all stream their contents into the pipeline just like external commands do.  This would allow use to not only process them incrementally, but also to allow for ctrl-c breaking.

**Comment by JosephTLyons** [comment] 2020-05-28 01:04
> This is related to https://github.com/nushell/nushell/issues/1448
> 
> 
> 
> The issue is that the current open is synchronous and does not stream blocks of data through the pipeline.  Ideally, `open`, `fetch`, and `post` would all stream their contents into the pipeline just like external commands do.  This would allow use to not only process them incrementally, but also to allow for ctrl-c breaking.

Ahhh, I didn’t realize the issue was more involved, I suppose I should leave this one for someone who knows what they are doing here.

**Comment by jonathandturner** [comment] 2021-07-07 18:32
I've seen this recently, so I believe it's still an issue. While we have some ctrl+c checking, we don't have it everywhere we need to fully support it.

**Comment by raboof** [comment] 2021-10-04 08:40
Perhaps we should open separate issues under this 'umbrella issue' for particular commands?

I noticed `ls **/*foo.bar` on a huge directory could not be aborted with ^C

**Comment by rgwood** [comment] 2022-12-02 16:03
This should be fixed for `open` and anything else that uses `RawStream` by https://github.com/nushell/nushell/pull/7314

Feel free to raise new issues (or reopen this one) if you run into more ctrl+c problems.

**Closed by rgwood** 2022-12-02 16:03 UTC
Labels: enhancement, polish, signal-cancel
