### ISSUE TITLE
Piping binary data into external commands should pass the binary data directly

### ISSUE THREAD

**Issue by CyborgSquirrel** [nushell/nushell#7615] opened 2022-12-27 17:57 UTC
### Question

If I run this: `0x[DEADBEEF] | hexdump -C`, then nushell just pipes the text representation of the data into the command, and the result is this:
```
00000000  4c 65 6e 67 74 68 3a 20  34 20 28 30 78 34 29 20  |Length: 4 (0x4) |
00000010  62 79 74 65 73 20 7c 20  1b 5b 31 3b 33 36 6d 70  |bytes | .[1;36mp|
00000020  72 69 6e 74 61 62 6c 65  20 1b 5b 31 3b 33 32 6d  |rintable .[1;32m|
00000030  77 68 69 74 65 73 70 61  63 65 20 1b 5b 31 3b 33  |whitespace .[1;3|
00000040  35 6d 61 73 63 69 69 5f  6f 74 68 65 72 20 1b 5b  |5mascii_other .[|
00000050  31 3b 33 33 6d 6e 6f 6e  5f 61 73 63 69 69 1b 5b  |1;33mnon_ascii.[|
00000060  30 6d 0a 1b 5b 33 36 6d  30 30 30 30 30 30 30 30  |0m..[36m00000000|
00000070  1b 5b 30 6d 3a 20 20 20  1b 5b 31 3b 33 33 6d 64  |.[0m:   .[1;33md|
00000080  65 1b 5b 30 6d 20 1b 5b  31 3b 33 33 6d 61 64 1b  |e.[0m .[1;33mad.|
00000090  5b 30 6d 20 1b 5b 31 3b  33 33 6d 62 65 1b 5b 30  |[0m .[1;33mbe.[0|
000000a0  6d 20 1b 5b 31 3b 33 33  6d 65 66 1b 5b 30 6d 20  |m .[1;33mef.[0m |
000000b0  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
*
000000d0  20 20 20 20 20 20 20 20  20 1b 5b 31 3b 33 33 6d  |         .[1;33m|
000000e0  c3 97 1b 5b 30 6d 1b 5b  31 3b 33 33 6d c3 97 1b  |...[0m.[1;33m...|
000000f0  5b 30 6d 1b 5b 31 3b 33  33 6d c3 97 1b 5b 30 6d  |[0m.[1;33m...[0m|
00000100  1b 5b 31 3b 33 33 6d c3  97 1b 5b 30 6d 0a        |.[1;33m...[0m.|
0000010e
```

Is there any way for nushell to pipe just the binary data? So that if I pipe it into `hexdump -C`, the result is:
```
00000000  de ad be ef                                       |....|
00000004
```

### Additional context and details

nushell version 0.72.1

**Comment by sholderbach** [comment] 2022-12-27 19:11
Mhh that doesn't seem like the right behavior and in my mind shouldn't require extra flags or contortions to work.

**Comment by henryjetmundsen** [comment] 2023-02-05 09:09
If we run `0x[DEADBEEF] | cat ` we can see the problem is that the output of a Binary to an external command is
```
Length: 4 (0x4) bytes | printable whitespace ascii_other non_ascii
00000000:   de ad be ef                                          ××××
```

I'm guessing the desired input to an external command would be `"\xde\xad\xbe\xef` which would produce the expected output.

**Comment by fdncred** [comment] 2023-02-05 13:30
I think this is as close as we can get.
```
> 0x[DEADBEEF] | debug
[222, 173, 190, 239]
```
```
> 0x[DEADBEEF] | debug | hexdump -C 
00000000  5b 32 32 32 2c 20 31 37  33 2c 20 31 39 30 2c 20  |[222, 173, 190, |
00000010  32 33 39 5d                                       |239]|
00000014
```

**Comment by henryjetmundsen** [comment] 2023-02-05 21:08
To achieve the desired output, we would need to write the values in `[222, 173, 190, 239]` as unformatted bytes instead of a formatted string. A rust program that simply does the following would produce the desired output if piped into `hexdump -C`.
```
use std::io::stdout;
use std::io::Write;

fn main() {
    let mut stdout = stdout();
    stdout.write_all(&[222, 173, 190, 239]);
}
```

**Comment by henryjetmundsen** [comment] 2023-02-05 21:44
Can someone assign this issue to me? It looks like the problem is that in `run_external.rs` we render input as a table before passing to an external command. For hex values, this causes `pretty_hex` output to be written to stdout. I think the correct behavior for external commands would be to simply pass the `vec<u8>` representation of the binary. We will need to modify `table.rs` to know whether stdout is going to an external command or not so that it can decide whether to use pretty print for hex or `Vec<u8>`.

**Comment by sholderbach** [comment] 2023-02-05 21:47
Thanks for picking up this one @henryjetmundsen !

**Comment by fdncred** [comment] 2023-02-05 21:47
Stefan beat me to it. It's yours @henryjetmundsen

**Closed** 2023-02-24 20:39 UTC
Labels: :bug:  bug, good first issue, external-commands, type-system, semantics
