### ISSUE TITLE
Flag to print default `env.nu` or `config.nu`

### ISSUE THREAD

**Issue by lilyball** [nushell/nushell#9716] opened 2023-07-17 07:31 UTC
### Related problem

The `nu` binary knows what the default [`env.nu`](https://github.com/nushell/nushell/blob/48271d8c3e1f83723f005ae1809ebd5026783f8a/crates/nu-utils/src/sample_config/default_env.nu) and [`config.nu`](https://github.com/nushell/nushell/blob/48271d8c3e1f83723f005ae1809ebd5026783f8a/crates/nu-utils/src/sample_config/default_config.nu) are, as it uses them if the files aren't found on disk. I'd like to be able to ask `nu` to tell me what those defaults are, so I can easily see if they've changed (by comparing them to a saved copy) or even scripting the inclusion of them prior to my modifications when building my home environment.

### Describe the solution you'd like

Having a flag to the `nu` binary that prints these files would work well. Either one flag per file, or a flag that is parameterized with `env` or `config` to select the file (as both files can't be printed simultaneously).

### Describe alternatives you've considered

There could be some built-in command that prints it, such as `config default` command that returns a `record<config: string, env: string>` so I could use `nu -c 'print (config default).config'` to see the default `config.nu`.

The drawback to having this be built-in like this is that would then suggest that it should be possible to source this default config/env as well without having to write it to a file first.

I don't have enough experience with Nu yet but maybe this could be exposed as a module that I could `use <module> *` to get the defaults? The only behavioral change I see offhand is the `$dark_theme` and `$light_theme` variables would no longer be exposed, though they could always be moved into the environment instead.

### Additional context and details

I'm currently building my Nu environment with Nix. I've copied the default config/env files from v0.82.0 into my Nix config, but I'd like to know if the default config gets updated, and I'd like a way to layer my modifications onto it.

**Comment by sholderbach** [comment] 2023-07-17 09:59
The `$nu` variable/constant has: `$nu.default-config-dir`, `$nu.config-path`, and `$nu.env-path` for the configs (and others for the rest of the primary locations nu looks up.

**Comment by sholderbach** [comment] 2023-07-17 10:39
Ah I probably slightly misread your request based on the title.

Currently only the `config reset` command will output the default files embedded into the binary. Notably there may be differences between what nushell with a config file similar to it provides and the fall-back defaults that are directly implemented in the source code. #9676 tries to reconcile some of this.

I think there are two possible avenues. Store the embedded files in the `$nu` variable to access (and rewrite the `config reset` command in terms of that) or have either a flag on `config reset` or a new command `config default` as you propose. From a consistency perspective the `$nu` solution seems slightly favorable but dealing with more or larger fields on those magic variables/constant has been a problem in the past. (See the recent move of the `$nu.scope` fields into their own `scope` commands)

**Comment by fdncred** [comment] 2023-07-17 11:44
Another option is to load the default_config.nu and default_env.nu when nushell initially loads before everything else. That would make it available in `view files` which would enable one to use `view span <start> <end>` to view the file. Maybe that's too hackish?

**Comment by amtoine** [comment] 2023-07-17 16:36
> Another option is to load the default_config.nu and default_env.nu when nushell initially loads before everything else. Then we overwrite it when a config.nu and env.nu are found. That would make it available in `view files` which would enable one to use `view span <start> <end>` to view the file. Maybe that's too hackish?
>
depends on whether this would require parsing the two files :thinking: 
if it needs parsing them, i think that's a no-go in terms of startup performance :cry:

**Comment by cumber** [comment] 2023-08-18 05:12
While we're at it, it would be very convenient to be able to print the default config and/or output the default config files to a desired location, instead of `config reset`'s approach of hardwiring that we're writing them to the "live" config location.

I'm also building my home environment with nix, and what *actually* lives at `~/.config/nushell/{config.nu,env.nu}` are symlinks to the build output. When I'm checking for updates to the default config I want to output into my *source* location. I can do that by moving files around after `config reset`, but it's a bit more hassle.

And if I was doing some sort of automated process (e.g. checking to see if there have been differences in the default config), it's definitely not ideal for it to clobber my config as part of running the test! I should be able to run it in a sandbox dir (or just get it as structured output and not require side effects at all).

**Comment by fdncred** [comment] 2023-08-18 13:39
I could see someone adding a new optional parameter like `config reset --location /some/new/folder` That wouldn't be too tricky, I think. Probably just get the config path and check for this new parameter to see if it should be overridden. And then also taked into account the without_backup flag.
https://github.com/nushell/nushell/blob/2e0fb7c1a606aa1917734d9231dbe7a9721db39a/crates/nu-command/src/env/config/config_reset.rs#L51-L63

Looking at the rest of the code is confusing because the options are double negatives. like `if !no_backup` vs `if backup`.

**Comment by lilyball** [comment] 2023-08-20 00:52
Being able to specify an alternative directory for `config reset` does not seem like it adds anything over just giving me access to the text of the default scripts and letting me save that to a file if I wish.

**Comment by tad-lispy** [comment] 2023-10-10 18:21
I just run into a problem with Carapace integration with Nushell. The issue is discussed here: <https://github.com/rsteube/carapace-bin/issues/1897>. I do have a temporary workaround (not very elegant though), and I am not yet sure what an elegant solution would look like, but perhaps having the command proposed by @lilyball could play a role.

**Comment by sholderbach** [comment] 2023-10-10 18:41
Closed by https://github.com/nushell/nushell/pull/10480 that adds `config nu --default` or `config env --default` with the output in text form. (nightly only at the moment)

**Closed by sholderbach** 2023-10-10 18:41 UTC
Labels: enhancement, configuration
