### ISSUE TITLE
`select 0 0` hangs Nushell

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#8145] opened 2023-02-21 08:15 UTC
### Describe the bug

See title.

### How to reproduce

1. `ls | select 0 0`

### Expected behavior

This should work the same as `select 0 1`, except that the duplicate 0 causes the 1st row to be repeated in the output. (Compare `get 0 0`)

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.75.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | windows-x86_64                       |
| build_target       | x86_64-pc-windows-msvc               |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)  |
| rust_channel       | stable-x86_64-pc-windows-msvc        |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)  |
| pkg_version        | 0.75.0                               |
| build_time         | 2023-02-02 01:15:47 +10:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by dmatos2012** [comment] 2023-02-21 10:08
I would like to work on this issue :)

**Comment by fdncred** [comment] 2023-02-21 12:54
> I would like to work on this issue :)

I just assigned it to you @dmatos2012. Thanks.

@webbedspace Good to see you back again! Thanks for the issue.

**Comment by dmatos2012** [comment] 2023-02-23 21:32
So while trying to debug, I found out the problem is that when input is `PipelineData::ListStream(stream, ..)`, and you loop over it, it loops forever due to way the iterator is built [here](https://github.com/nushell/nushell/blob/3fb1e37473ce998b223844f2ae0275a4ebe3672f/crates/nu-command/src/filters/select.rs#L284-L287), which basically increases the current count in iterator but the `row` is always 0, going on forever. (or any other input # repeated (e.g `ls | select 1 1`). 

So, there are two possibilities:
1) Fix that loop by adding an extra condition. Problem: The iterator is consumed, so once it `input.next()` on `0th` index, then it cant never consume that index again, thus making it impossible to output same thing twice.
2) Just deduplicate the 0 so that `ls | select 0 0` becomes `ls | select 0`, and it works fine.  If I do that, I get:
```
❯ ls | select 0 0
╭───┬────────────────────┬──────┬────────┬──────────────╮
│ # │        name        │ type │  size  │   modified   │
├───┼────────────────────┼──────┼────────┼──────────────┤
│ 0 │ CODE_OF_CONDUCT.md │ file │ 3.4 KB │ 8 months ago │
```

Problem is that then behavior would differ from that of `ls | get 0 0`. 

Most probably im missing maybe something obvious, or "better" way of doing it. So, some input ideas would be very welcomed :)

**Comment by alesito85** [comment] 2023-02-23 22:01
I think that `get` serves it's purpose by allowing to fetch data from same row multiple times because one can then kind of transpose the data if you want. But select only returns a limited subset of either rows or columns when working with tables. I think `dedup` would be a good solution to this as you've suggested.

**Comment by fdncred** [comment] 2023-02-24 13:34
> Just deduplicate the 0 so that ls | select 0 0 becomes ls | select 0, and it works fine. If I do that, I get:

I'm leaning in the dedup direction but it would be interesting for `select 0 0` to work like `get 0 0` like
```
ls | get 0 0
╭───┬────────┬──────┬──────┬──────────────╮
│ # │  name  │ type │ size │   modified   │
├───┼────────┼──────┼──────┼──────────────┤
│ 0 │ .cargo │ dir  │  0 B │ 3 months ago │
│ 1 │ .cargo │ dir  │  0 B │ 3 months ago │
╰───┴────────┴──────┴──────┴──────────────╯
```
```
ls | select 0 0
╭───┬────────┬──────┬──────┬──────────────╮
│ # │  name  │ type │ size │   modified   │
├───┼────────┼──────┼──────┼──────────────┤
│ 0 │ .cargo │ dir  │  0 B │ 3 months ago │
│ 0 │ .cargo │ dir  │  0 B │ 3 months ago │
╰───┴────────┴──────┴──────┴──────────────╯
```
But I really don't know what the use case is for that, especially since they're identical outputs. So, maybe it's just better to have select not hang?

> Problem is that then behavior would differ from that of ls | get 0 0. 

The behavior already differs. `ls | get 0 0` works, `ls | select 0 0` hangs. :)

Let's see what others say.

**Comment by alesito85** [comment] 2023-02-24 13:58
> But I really don't know what the use case is for that, especially since they're identical outputs. So, maybe it's just better to have select not hang?
The difference is that with get you can also select a different column with each row, while with select you can only do the same combination of rows/columns (they're not required at the same time).
```
ls | get 0.name 1.type                     
╭───┬──────────────────────────╮
│ 0 │ 29.11.2022 20.32.44.pklg │
│ 1 │ file                     │
╰───┴──────────────────────────╯
```

**Comment by webbedspace** [comment] 2023-02-24 14:26
Maybe, for the sake of coherence, supplying the same cell path twice to `select` should just be an error.

**Comment by dmatos2012** [comment] 2023-02-24 21:16
@fdncred do you also agree on erroring out rather than just `dedup`? Otherwise, its all different opinions hehe. If so, I can proceed with a PR.

**Comment by fdncred** [comment] 2023-02-24 21:30
> @fdncred do you also agree on erroring out rather than just `dedup`? Otherwise, its all different opinions hehe. If so, I can proceed with a PR.

Sure, I'm good with erroring out. I tried to solicit some other feedback but the best I got was, "that's weird".

**Closed** 2023-02-27 02:14 UTC
Labels: :bug:  bug
