### ISSUE TITLE
`LS_COLORS` not used when `ls` inside parenthesis 

### ISSUE THREAD

**Issue by pseudoparenchymatous** [nushell/nushell#7137] opened 2022-11-15 06:20 UTC
### Describe the bug

I first noticed that my `alias la = (ls -a | sort-by type)` doesn't display colors when run. Then I tried just running `(ls)` in the shell and it still didn't display colors. A bit problematic because my aliases for the `ls` command are piped and pipes in aliases must be inside parentheses. 

### How to reproduce

Run `(ls)` in the shell

### Expected behavior

Display colors when `ls` run inside parentheses. 

### Screenshots

![IMG_20221115_142405](https://user-images.githubusercontent.com/105337186/201842676-c7ef8a88-3b15-4230-b2ff-6bcf3f707fd3.jpg)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | aarch64-linux-android                           |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | 1.63.0-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-09 02:23:14 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

I'm using Termux in Android

**Comment by fdncred** [comment] 2022-11-15 11:58
Thanks for reporting this but it's a dupe of #4501. Closing this in favor of that one, which has more information.

**Closed by fdncred** 2022-11-15 11:58 UTC
