### ISSUE TITLE
Support switching Ruby versions using RVM or similar

### ISSUE THREAD

**Issue by mackinleysmith** [nushell/nushell#1960] opened 2020-06-10 15:41 UTC
**The problem**

I am loving nushell and would very much like to use it as my default shell. One of the final barriers in my way is that I cannot seem to get the RVM installation on my machine to work within nushell.

When I run `rvm list`, I can see my installed Rubies:
```
❯ rvm list
   ruby-2.4.3 [ x86_64 ]
   ruby-2.5.0 [ x86_64 ]
=* ruby-2.5.1 [ x86_64 ]
   ruby-2.5.5 [ x86_64 ]
   ruby-2.5.7 [ x86_64 ]
   ruby-2.6.0 [ x86_64 ]
   ruby-2.6.3 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

Ruby 2.5.1 is clearly selected when I open a fresh terminal with nushell:
```
❯ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

❯ which ruby
─────────┬──────────────────────────────────────────────────
 arg     │ ruby
 path    │ /Users/mackinley/.rvm/rubies/ruby-2.5.1/bin/ruby
 builtin │ No
─────────┴──────────────────────────────────────────────────
```

However, if I try to _set_ my current Ruby version to something else, RVM spits this out:
```
❯ rvm use 2.6.0

RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.

❯ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
```

**The solution I'd like**
The way this works in bash, zsh and fish for me is that RVM basically stays out of my way. I only need to touch it when setting up a project on some Ruby version that isn't installed to my machine yet, or when trying to upgrade a project to some new version of Ruby. When I `cd` into a Ruby project directory with any of the aforementioned shells, it reads the `Gemfile` and/or the `.ruby-version` file in that directory and chooses an installed Ruby automatically. This is also important for my IDE, Rubymine, to open up with the correct Ruby interpreter already selected.

**Alternatives considered**
I am not married to RVM and would definitely be open to jumping ship to some other Ruby version management system like rbenv, if any other such tool is easier to support.

**Additional context**
I did not see any Github issues specifically regarding Ruby or RVM, but I did see a few that seem linked to the underlying situation that nushell does not seem to, in the words of RVM's error message, "allow login shell". Therefore, I believe that this issue may be loosely connected to a few other open issues, though I do not believe it is a duplicate.

I have a hunch that the comment about nvm (a similar utility for NodeJS) not working may share the same root cause: https://github.com/nushell/nushell/issues/1469#issuecomment-596526637

I also am under the impression that this user's trouble with ssh may have originally been related to my issue: https://github.com/nushell/nushell/issues/1654

I am a developer who is not yet well versed in Rust, but excited by the chance to get my hands a little dirty to try to figure out an ideal solution to this issue. Any direction on where to start would be much appreciated, and in the meantime, I would like for this issue to be visible to any others who would like to control their Ruby version inside of nushell.

Thanks!

**Comment by smit1625** [comment] 2020-06-10 23:19
Okay I think you're onto something there, @sollyucko.

Trying to follow the instructions to set up per-directory environment variables, I think the guide may be missing an ending square bracket for its example command, `config --set [nu_env_dirs ["/home/sam", "/home/sam/github", "/home/sam/github/test"]`. However, even with that square bracket in place and some manual adjustments made, I still cannot seem to get my project-level `.nu-env` to be respected.

My `config.toml` contains this:
```
nu_env_dirs = ["/Users/mackinley", "/Users/mackinley/Projects", "/Users/mackinley/Projects/coldbox-identification-training-ui"]
```

I created a file at `/Users/mackinley/Projects/coldbox-identification-training-ui/.nu-env` containing this:
```
[env]
rvm_ruby_string = "ruby-2.6.0"
SOMETHING_NEW = "yo"
```

But still, `$rvm_ruby_string` is set to `ruby-2.5.7` which is configured in my `config.toml`, and `$SOMETHING_NEW` is not defined.
```
❯ config --get env | get rvm_ruby_string
ruby-2.5.7

❯ config --get env | get SOMETHING_NEW
error: Unknown column
- shell:1:36
1 | config --get env | get SOMETHING_NEW
  |                        ^^^^^^^^^^^^^ There isn't a column named 'SOMETHING_NEW'
```

This led me to another discovery, though. The reason I had my default rvm ruby loaded when starting a nushell is that when I followed the instructions for `chsh`, namely `config --set [path $nu.path]`, some path additions that rvm set up were copied into my `config.toml`. It turns out this is all you really need! I can switch ruby versions by changing the version numbers for a new path entries in `config.yoml`. Janky, sure, but workable at least.

So, now what I think I need to do is get this `nu_env_dirs` thing working. Does it support changing my `$nu.path`, or just regular env vars?

**Comment by jonathandturner** [comment] 2020-06-10 23:24
@smit1625 to see into the values of the current environment, use `$nu.env` instead of `config`.  The former is the current variables and their values, and the latter is the environment that's been saved into the permanent storage via `config`.

In theory, you should be able to do:

```
> echo $nu.env.SOMETHING_NEW
```

And see the new value.

**Comment by smit1625** [comment] 2020-06-10 23:55
@jonathandturner that's pretty slick, but still unfortunately does not find `SOMETHING_NEW`.

```
❯ echo $nu.env.SOMETHING_NEW
error: Unknown column
- shell:1:26
1 | echo $nu.env.SOMETHING_NEW
  |              ^^^^^^^^^^^^^ did you mean 'GEM_HOME'?
```

**Comment by smit1625** [comment] 2020-06-11 15:37
Okay, here's a few more discoveries to throw onto the pile.

I hadn't realized how new this per-directory environment stuff is (released 3 days ago). I was previously on 0.14.0, and have now upgraded to 0.15.0 which is the one with the per-directory env feature.

Upon upgrading, I found that my `config --path` changed from `/Users/mackinley/Library/Application\ Support/nu/config.toml` to `/Users/mackinley/Library/Preferences/org.nushell.nu/config.toml`, without copying over my config for me. Starting `nu` after upgrading gave me a blank config, which was a little confusing. I was able to just paste the contents of my old `config.toml` into the new one, so no harm really done, but I wanted to make sure to call this out in case y'all weren't aware yet. I didn't see the change to the `config.toml` location documented anywhere, but perhaps I just missed it.

Unfortunately, even after upgrading, I still can't seem to get it to find `$nu.env.SOMETHING_NEW`. I tried re-running the commands from https://www.nushell.sh/blog/2020/06/09/nushell_0_15_0.html#per-directory-environment-variables-samhedin, to no avail.

I'm going to repeat my earlier concern about the command to set `nu_env_dirs` being potentially wrong. Here's what running the command as written in the documentation gets me:
```
❯ config --set [nu_env_dirs ["/Users/mackinley", "/Users/mackinley/Projects", "/Users/mackinley/Projects/coldbox-identification-training-ui"]
```
Resulting change to `config.toml`:
```
nu_env_dirs = "[\"/Users/mackinley\", \"/Users/mackinley/Projects\", \"/Users/mackinley/Projects/coldbox-identification-training-ui\""
```

Here's what I _think_ that command should be:
```
config --set [nu_env_dirs [/Users/mackinley /Users/mackinley/Projects /Users/mackinley/Projects/coldbox-identification-training-ui]]
```
Resulting change to `config.toml`:
```
nu_env_dirs = ["/Users/mackinley", "/Users/mackinley/Projects", "/Users/mackinley/Projects/coldbox-identification-training-ui"]
```

Does the latter `config.toml` change look correct to everybody, or is it supposed to be a string with escaped brackets and commas?

**Comment by jonathandturner** [comment] 2020-06-11 18:12
@smit1625 - admittedly a bit confusing, the current list syntax will not properly handle the commas. We really should fix that.

So yeah, the last thing you show is correct, without using any commas.  That looks right to me.

With that, are you able to us a .nu-env in those directories to get further?

**Comment by smit1625** [comment] 2020-06-11 22:13
Unfortunately no. Here's my `.nu-env`:
```
❯ cat /Users/mackinley/Projects/coldbox-identification-training-ui/.nu-env
[env]
SOMETHING_NEW = "yo"
something_else_new = "sup"
rvm_ruby_string = "ruby-2.6.0"
```

And still,
```
❯ cd ..; cd /Users/mackinley/Projects/coldbox-identification-training-ui
❯ echo $nu.env.SOMETHING_NEW
error: Unknown column
  ┌─ shell:1:14
  │
1 │ echo $nu.env.SOMETHING_NEW
  │              ^^^^^^^^^^^^^ did you mean 'GEM_HOME'?

```

**Comment by jonathandturner** [comment] 2020-06-11 22:34
@smit1625 - just to verify. After you added directories to the allowed list in the config, did you also restart `nu`?

**Comment by smit1625** [comment] 2020-06-12 00:03
Yes, that was from a fresh shell.

**Comment by jonathandturner** [comment] 2020-06-13 19:18
@samhedin - do you know what might be causing this issue?

@smit1625 - you're using a macOS setup? Trying to guess from the paths, but not 100% sure

**Comment by samhedin** [comment] 2020-06-13 20:17
I am also thinking that this might be a macOS thing. Do we know if anyone has been able to run this on mac?

If you set an environment variable through the env var in the config file, the one listed here: https://www.nushell.sh/book/en/configuration.html - does it work?

Maybe we can make this into a separate issue and try to figure out when it happens? I sadly have no way to access a mac, so I can't rule that option out myself.

**Comment by pka** [comment] 2020-06-13 20:20
I'm having the same problem on Linux. I'll debug a bit.

**Comment by samhedin** [comment] 2020-06-13 20:20
Exciting times!

**Comment by jonathandturner** [comment] 2020-06-13 20:23
For folks helping us debug what's going on:

Key logic lives in: https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/env/directory_specific_environment.rs

Specifically, is this .nu-env file opened correctly, and can the variables be seen?  Here's where the variables are read in: https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/env/directory_specific_environment.rs#L121

And here's where we see if the file is allowed to be opened: https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/env/directory_specific_environment.rs#L103

**Comment by samhedin** [comment] 2020-06-13 20:29
Advice if you want to try some things out, inside `environment.maintain_directory_environment` there are three main sections - one to delete vars, one to restore vars, and one to add vars. 
If your issue is vars not being added, I suggest commenting out the other two sections.

Also for good measure, you can hardcode a call to add an environment variable in that function.
`self.add_env("test_env_var", "alive")` or something along those lines 

I am working on a nicer version of this code, but I don't expect that this bug will have disappeared in it as environment variables are still being set in the same way as now.

**Comment by pka** [comment] 2020-06-13 20:55
`env_vars_to_add` is not called when I `cd` to my test dir . `sync_env_vars` gets called, but `environment.env()` (line 47) seems to be None.

**Comment by pka** [comment] 2020-06-13 21:25
@samhedin are there other infos that would help you?

**Comment by smit1625** [comment] 2020-06-15 18:10
Sorry for going dark there, I was traveling this weekend. It is indeed happening on macOS for me and I'm happy to test things on this machine.

@samhedin yes, my config.toml specifies several env vars inside the `[env]` section and those get loaded just fine. It's just the per-directory ones that don't get set.

**Comment by samhedin** [comment] 2020-06-15 18:47
@smit1625 @pka
If you have tho time, could you open `environment_syncer.rs` and change `new()` to look like this:

``` rust
impl EnvironmentSyncer {
    pub fn new() -> EnvironmentSyncer {
        let mut env = EnvironmentSyncer {
            env: Arc::new(Mutex::new(Box::new(Environment::new()))),
            config: Arc::new(Box::new(NuConfig::new())),
        };
        env.load_environment();
        env
    }
    ...
}
```

Try again with that version installed. Does it work now?

**Comment by pka** [comment] 2020-06-15 19:17
@samhedin: environment.env() in sync_env_vars still None for me.

**Comment by pka** [comment] 2020-06-15 19:18
@samhedin : I would be available for a debgging session for the next hour...

**Comment by samhedin** [comment] 2020-06-15 19:20
Are you on the nushell discord https://discord.com/invite/NtAbbGn ? 
Send me a message there and we can talk, both over voice and chat. I'm JustSam

**Comment by samhedin** [comment] 2020-06-16 17:17
@pka seems to have figured out the reason for this.
It happens if there is no env-section in `.config/nu/config.toml`.
This results in 
``` rust
impl Env for Environment {
    fn env(&self) -> Option<Value> {
        if let Some(vars) = &self.environment_vars {
            return Some(vars.clone());
        }

        None
    }
```
returning `None`, which completely skips running the code for dealing with directory specific environment variables. I will add it to the list of things to fix. 

For now, it seems like it is enough to add `[env]` to the bottom of `config.toml` to make the program happy.

Does that solve it for you too, @smit1625?

**Comment by tionis** [comment] 2020-06-17 09:25
I'm experiencing the same problem, environment variables defined in config.toml in the [env] section work, but .nu-env doesnt. Also I tried to use an eval value in the environment variable and the shell refused to start.

**Comment by samhedin** [comment] 2020-06-17 10:37
Hmm, I am happy that we added this early version of the code - it's been good to receive feedback and issue reports.
Something this has shown me is that this really needs some better errors, so we can exclude some potential issues right from the get-go.

Until then: How does your `config.toml` look, how does a `.nu-env` file look? What is your setup?

**Comment by tionis** [comment] 2020-06-17 13:09
My .nu-env in /home/tionis looks like this:
```
[env]
test = "quak"
test2 = nope
```
My config.toml like this:
```
startup = ["alias dotfiles [a1 a2 a3 a4 a5 a6 a7 a8 a9 a10] {/usr/bin/git --git-dir=/home/tionis/.dotfiles/ --work-tree=/home/tionis $a1 $a2 $a3 $a4 $a5 $a6 $a7 $a8 $a9 $a10}", "alias git-log [] {git log --pretty=format:%h##%aN##%s##%aD | lines | split-column \"##\" sha1 committer desc merged_at | first 10}", "alias restartKDE [] {kquitapp5 plasmashell; kstart5 plasmashell}", "alias studip-update [] {studip-sync; updateStudip}", "alias brave [a1 a2 a3 a4 a5] {brave-beta $a1 $a2 $a3 $a4 $a5}"]
nu_env_dirs = ["/home/tionis", "/home/tionis/uni"]
[env]
SSH_AUTH_SOCK = "/run/user/1000/gnupg/S.gpg-agent.ssh"
```

and i would like to be able to write a .nu-env like this:
```
[env]
GPG_TTY = $(tty)
SSH_AUTH_SOCK = $(gpgconf --list-dirs agent-ssh-socket)
```

**Comment by smit1625** [comment] 2020-06-17 13:18
The format of my setup matches the above. As far as I know, I can't put a second `[env]` into the config.toml file, so I don't think that is a solution that works for me. My config.toml has contained a `[env]` line the whole time.

**Comment by samhedin** [comment] 2020-06-17 13:26
Hmm, No need to add extra `[env]` sections if there's one already there. Clearly something else is going wrong. There will be some changes to how all of this works anyway quite soon, partly because of https://github.com/nushell/nushell/issues/1965 and partly because I just re-wrote most things. 
Is it alright if we let this issue be for now, and then see if it's still here when the new version is out? 
With some luck it might just disappear by itself... might.

**Comment by samhedin** [comment] 2020-06-17 13:33
No need to add an extra `[env]` section if it's already there. I am working on a new version, partly because of https://github.com/nushell/nushell/issues/1965, so maybe some of these issues will disappear by itself... Maybe. Is it ok if we let this rest for now, and then we can revisit it in the PR for the new version?

I hadn't even considered that you might want to evaluate vars like that in the .nu-file. It sounds like a cool feature. What do you think @jonathandturner?

**Comment by tionis** [comment] 2020-06-17 13:37
Yeah, I've been using this in ssh for a long time, as my ssh keys are encrypted and managed by gpg.
This is also very useful in combination with gnu/pass (or in my case gopass) to set environment variables without saving them in the clear somewhere.
Together with the .nu-env implementation this would make environment variables very dynamic and secure.

**Comment by samhedin** [comment] 2020-06-24 13:42
@smit1625 there is a new PR up: https://github.com/nushell/nushell/pull/2034
Could you give it a try and see if your problem is still there?

I've been thinking about scripting. We can probably do what @tionis suggested. In addition I thought that there should be a section for general scripts to run when you enter a directory. There could also be an on-exit section where people can create clean-up scripts. Does this sound reasonable?

As soon as I made the basic version of this, it became apparent that people are using similar functionality for much more advanced things than I ever would have considered. I keep telling myself that I should try out direnv myself, since this is so heavily inspired by it, but it might be even more useful to get some comments from people who actually use it for real things.

**Comment by tionis** [comment] 2020-06-24 14:24
I tried the code in the pull request and can report that it works on my machine.  
I really like @Samboy218 suggestions, this could come in quite handy!   
Some more details about the hashing algorithm used would be nice, for automated script edits and such.

**Comment by samhedin** [comment] 2020-06-24 14:42
> I tried the code in the pull request and can report that it works on my machine.
Great!
> I really like @Samboy218 suggestions, this could come in quite handy!
Cool. I want to get the current PR merged first - there are some things left to do. After that, this will be my next priority.
> Some more details about the hashing algorithm used would be nice, for automated script edits and such.
It is unspecified: https://doc.rust-lang.org/std/collections/hash_map/struct.DefaultHasher.html
I suppose there should be no issues with changing it to something more concrete.

**Comment by tionis** [comment] 2020-06-24 14:59
It would also be very helpful if the error message of the .nu-env parser were a bit more explicit about where the parsing failed.

**Comment by rrichardson** [comment] 2020-06-25 05:41
What about setting a default filename in a script for the specified dirs?  Maybe even default it to .envrc and bash as the scripts that are run by default.  Otherwise, we could rely on the `#!` at the top of a file in order to execute the file with the appropriate interpreter. 

Or if the file specified in the config is a binary in a directory, then execute it directly. Then we can collect its environment variables via  `/proc/<pid>/environ`

Also, in the dirs array... if the path ends in a file, then that file is the environment file.. if it ends in a directory, then we execute the default file. 

e.g.

```config.toml
[env]
default-env-file = ".nu_env"
env_dirs = ["dir-a","dir-b/.my-env"]
```

**Comment by samhedin** [comment] 2020-06-25 12:21
> What about setting a default filename in a script for the specified dirs? 

I assume that this is fine, but isn't it easier to just have a section in the already existing `.nu-env` and run the scripts listed there? Less configuration, and one less file per directory. I would guess that many people already have scripts ready, and the major use of this "nu script" file would be to just call out and run some other scripts.

>Otherwise, we could rely on the #! at the top of a file in order to execute the file with the appropriate interpreter.

Yeah, for sure. The scripts would be unmanaged by design - nushell runs them and then it's up to the user to make sure they work or make sense.

> Or if the file specified in the config is a binary in a directory, then execute it directly. Then we can collect its environment variables via `/proc/<pid>/environ`

If someone runs a program which sets certain environment values, how do we know when those values should be unset? At the moment this logic would be set when the user leaves a directory, but if the program is still running at that point maybe the variables still need to be there.
If you need some cleanup after a script has been run, you could use the exit-script to do it 

> 
> Also, in the dirs array... if the path ends in a file, then that file is the environment file.. if it ends in a directory, then we execute the default file.
> 
> e.g.
> 
> ```toml
> [env]
> default-env-file = ".nu_env"
> env_dirs = ["dir-a","dir-b/.my-env"]
> ```

In the new PR, this system was replaced and there is no longer an `env_dirs` array. Right now, there really isn't much configuration to do except run `autoenv trust` on whatever file or directory you want. I kind of like it that way, because some of this code is run often, so there is a high incentive to keep the code simple and lean.

**Comment by smit1625** [comment] 2020-06-25 14:02
This is probably a silly question... but what is the best way to try out someone's pull request for this project? Docker?

**Comment by thegedge** [comment] 2020-06-25 14:22
There's two options:

1. You'll see a Gitpod check under PRs. If you click the details link, it'll take you to an online editor where you can also build and run the code. I haven't used it, but I think it should work 🙂 
2. Locally, you need to take a few steps:
   - `git remote add` the PR author's fork (let's assume you call the remote `myremote`)
   - `git fetch myremote`
   - `git checkout myremote/<pr branch name>`
   - Build/run nushell like normal

For (2), I use a script I built to automate everything: https://gist.github.com/thegedge/76c9922a07a654d267335c80944da205.

**Comment by samhedin** [comment] 2020-06-25 14:44
> It would also be very helpful if the error message of the .nu-env parser were a bit more explicit about where the parsing failed.

I tried to make it a bit better now. The actual line it fails on is available, but in the short time I spent looking at it I could not find a way to show it as a nice user-facing error. Only a more programmer-oriented "failed on Some(<line>) expected" etc..

I'll look more into it.

**Comment by samhedin** [comment] 2020-06-25 18:59
@tionis it now uses sha256 https://docs.rs/sha2/0.9.1/sha2/ for hashing. Is this satisfactory for your use case?

**Comment by tionis** [comment] 2020-06-25 19:23
With those two problems addressed the only thing remaining would be evaluation of environment variables as stated above and I could port all my workflow to nu! 
Awesome!  - I'm stoked to see this merged!

**Comment by samhedin** [comment] 2020-06-30 04:55
New PR is up, more changes and scripting added: https://github.com/nushell/nushell/pull/2083
Give it a try, I would love to hear your opinions!

**Comment by pkondzior** [comment] 2020-08-03 10:40
Whats the status of this issue ? It doesn't seems that either rvm or rbenv works with nushell right now.

**Comment by pkondzior** [comment] 2020-08-03 11:09
I've went through nushell plugin system and it feels that it should be easy enough to write rbenv support using it. 

The idea for plugin would be:
1. Detect .ruby-version file in directory subtree
2. Detect if rbenv ruby shims exists in ~/.rbenv/shims/<ruby-version>
3. Scan all the shims and register them as possible external commands

This way nushell would leverage all the rbenv ruby environment installation and directory structure system. What I am missing right now is, am I really able to run  any external commands from plugin ?

**Comment by taylorthurlow** [comment] 2021-07-07 16:14
!unstale

**Comment by jokeyrhyme** [comment] 2021-09-10 23:00
Howdie folks!

I've just read through this issue, https://www.nushell.sh/blog/2020-06-09-nushell_0_15_0.html#per-directory-environment-variables-samhedin , https://github.com/nushell/nushell/pull/2083 , https://github.com/nushell/nushell/issues/2117 , and https://github.com/nushell/nushell/issues/2130, https://github.com/nushell/nushell/issues/3872

Figured it was worth linking these all together so others can keep up with related conversations

**Comment by jntrnr** [comment] 2021-09-10 23:02
There's also the work for python virtual environments going on here: https://github.com/nushell/nu_scripts/tree/main/virtual_environments

**Comment by taylorthurlow** [comment] 2022-03-22 21:39
Fingers crossed this sort of thing is able to make it into 1.0.

**Comment by ahmed1107** [comment] 2022-04-20 14:24
> Fingers crossed this sort of thing is able to make it into 1.0.

that would be amazing

**Comment by smithjoelt** [comment] 2022-07-06 06:08
I love NuShell and am wanting to use rbenv because it's more direct implementation of virtual environments. Same issues. Please include in 1.0

I'll miss working in nushell until then. :(

**Comment by fuzzygroup** [comment] 2022-07-17 18:23
I'm still impressed by NuShell but support for version managers like RVM is pretty damn important.

**Comment by joshjordan** [comment] 2022-09-17 18:43
@andrasio @jntrnr I'll volunteer to implement this (and `avn` etc) & coordinate with the virtual env work, if someone can give me a detailed spec for implementation

**Comment by hut8** [comment] 2023-02-05 06:02
Here is a Nushell integration for `asdf`, which uses `$PATH` modifications to do its job and works with a lot of interpreters: https://github.com/asdf-vm/asdf/blob/master/asdf.nu

There's also `rbenv` integration directly in the `nu_scripts` repo: https://github.com/nushell/nu_scripts/blob/main/rbenv/rbenv.nu

So, it looks like it is actually already possible.

**Comment by jntrnr** [comment] 2023-08-09 17:54
Looks like this is possible. At the very least, Nushell has matured to the point where someone could build the support using what Nushell provides.

Closing - thanks for helping Nushell grow in this direction.

**Closed by jntrnr** 2023-08-09 17:54 UTC
Labels: enhancement
