### ISSUE TITLE
Parse Error when command argument contains equal sign

### ISSUE THREAD

**Issue by cdhunt** [nushell/nushell#487] opened 2019-08-27 13:02 UTC
I'm trying to pass an argument to `terraform` and the argument syntax uses `=` which appears to trip up nu.

```
error: Parse Error                                                                   
- shell:1:23                                                                         
1 | terraform init -backend=false                                                
  |                        ^^^^^^                                                   
 ```

**Comment by jankoprowski** [comment] 2019-08-30 08:00
Same with `make test TESTS=my_test`

**Comment by jonathandturner** [comment] 2019-09-13 23:03
Recently @wycats landed some changes to external command support in the parser. It seems this is now fixed.

I'll close the issue, but please re-open if the issue is still happening with the latest code in master.

**Closed by jonathandturner** 2019-09-13 23:03 UTC
Labels: bug, external-commands, needs-design
