### ISSUE TITLE
0.60 tanks performance on WSL

### ISSUE THREAD

**Issue by jquesada2016** [nushell/nushell#5048] opened 2022-03-31 16:33 UTC
### Describe the bug

Previously, Nu had terrible performance on WSL when trying to tab complete with the `cd` command. However, it seems now, this is the case for every command when I run it.

For example, running:
```nushell
echo hello
```

returns the output almost immediately, but then stalls the terminal for about 4 seconds before showing the prompt again.

The reason I mention the `cd` issue from before, is because I suspect it is due to the same issue.

I also know the current workaround for this is to remove the Windows path, but I actually need it in my case, so that's not really an option for me.

### How to reproduce

1. Start a WSL session under Ubuntu
2. Run `echo hello`
3. Notice the output and a lack of command prompt for about 4 or so seconds.

### Expected behavior

I expect the command prompt to be available almost immediately after executing the command.

### Screenshots

N/A

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.60.0                                      |
| build_os           | linux-x86_64                                |
| rust_version       | rustc 1.61.0-nightly (1d9c262ee 2022-03-26) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.61.0-nightly (109bfbd 2022-03-17)   |
| pkg_version        | 0.60.0                                      |
| build_time         | 2022-03-30 11:56:50 -05:00                  |
| build_rust_channel | release                                     |
| features           | dataframe, default, trash, which, zip       |
| installed_plugins  |                                             |

### Additional context

N/A

### Edit
> I also know the current workaround for this is to remove the Windows path, but I actually need it in my case, so that's not really an option for me.

I meant I know the current workaround for the `cd` tab completion and not the time delay after every command, as I am not sure it's the same bug.

**Comment by jquesada2016** [comment] 2022-03-31 16:43
Ah yes, thank you very much!

**Comment by hustcer** [comment] 2022-04-02 02:25
dupe of https://github.com/nushell/nushell/issues/4914. closing in favor of it.

**Closed by hustcer** 2022-04-02 02:25 UTC
Labels: duplicate
