### ISSUE TITLE
Zsh path completion

### ISSUE THREAD

**Issue by suhr** [nushell/nushell#1805] opened 2020-05-16 08:36 UTC
When you enter (for example) `~/P/wo`<kbd>Tab</kbd> in zsh, it completes it to `~/Projects/work/`. It would be nice to have a similar feature in nushell.

**Comment by thegedge** [comment] 2020-05-16 16:08
Definitely! Since completion is such a huge task without good specifics, we're trying to consolidate the effort here into one issue.

Duplicate of https://github.com/nushell/nushell/issues/290

**Closed by thegedge** 2020-05-16 16:08 UTC
Labels: delight, enhancement
