### ISSUE TITLE
Buitlin commands such as `ls`, `cp` do not respect `--flag=false`

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#11456] opened 2023-12-31 15:49 UTC
### Describe the bug

Awhile ago, `--flag=true` / `--flag=false` was added to fix the [combinatorial explosion when making wrappers](https://github.com/nushell/nushell/issues/7260). This works great on user-defined scripts. Although the parser appears to also understand this syntax with respect to builtin commands, it doesn't actually seem to respect what the syntax is saying.

### How to reproduce

1. `ls --long=false`

2. \*ls is long\* :c

|name|type|target|readonly|mode|num_links|inode|user|group|size|created|accessed|modified|
|-|-|-|-|-|-|-|-|-|-|-|-|-|
|bar|file||false|rw-r--r--|1|24217229|root|root|0 B|2023-12-31 08:45:31 (Sun, Dec) -0700|2023-12-31 08:45:31 (Sun, Dec) -0700|2023-12-31 08:45:31 (Sun, Dec) -0700|
|foo|file||false|rw-r--r--|1|24217228|root|root|0 B|2023-12-31 08:45:31 (Sun, Dec) -0700|2023-12-31 08:45:31 (Sun, Dec) -0700|2023-12-31 08:45:31 (Sun, Dec) -0700|

### Expected behavior

`--flag=false` should disable `flag` for the command.

### Configuration

| key                | value                                                                                              |
| ------------------ | -------------------------------------------------------------------------------------------------- |
| version            | 0.88.1                                                                                             |
| branch             |                                                                                                    |
| commit_hash        |                                                                                                    |
| build_os           | linux-x86_64                                                                                       |
| build_target       | x86_64-unknown-linux-gnu                                                                           |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (built from a source tarball)                                  |
| cargo_version      | cargo 1.74.0                                                                                       |
| build_time         | 1980-01-01 00:00:00 +00:00                                                                         |
| build_rust_channel | release                                                                                            |
| allocator          | mimalloc                                                                                           |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                               |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, net, query, query json, query web, query xml, regex |

**Comment by NotLebedev** [comment] 2024-01-06 17:15
The issue is the [has_flag](https://github.com/nushell/nushell/blob/6f59abaf4310487f7a6319437be6ec61abcbc3b9/crates/nu-protocol/src/ast/call.rs#L204C5-L212C6) method. It is used in commands to check if flag is set, but in reality it checks if a named argument is present (without evaluating its argument if it exists)

I think I can fix it. I will rename existing `has_flag` method to `has_named` and replace usages in parser with `has_named`. I will move the `has_flag` command to [CallExt](https://github.com/nushell/nushell/blob/6f59abaf4310487f7a6319437be6ec61abcbc3b9/crates/nu-engine/src/call_ext.rs#L10C9-L10C9) and change body to something like this:
```rust
    fn has_flag(
        &self,
        engine_state: &EngineState,
        stack: &mut Stack,
        flag_name: &str,
    ) -> Result<bool, ShellError> {
        for name in self.named_iter() {
            if flag_name == name.0.item {
                return if let Some(expr) = &name.2 {
                    // Check --flag=false
                    let result = eval_expression(engine_state, stack, expr)?;
                    match result {
                        Value::Bool { val, .. } => Ok(val),
                        _ => Err(ShellError::CantConvert {
                            to_type: "bool".into(),
                            from_type: result.get_type().to_string(),
                            span: result.span(),
                            help: Some("".into()),
                        }),
                    }
                } else {
                    Ok(true)
                };
            }
        }

        Ok(false)
    }
```

which will additionally evaluate expression of flag if it exists and check if it is true. Unlike `get_flag` it will return `Result<bool, ShellError>` and produce an error if result of expression evaluation is not a bool.
I tried it in ls only and it seems to work so I'll try replacing it in all commands and see if it works

**Comment by WindSoilder** [comment] 2024-01-15 08:49
Is it resolved? @NotLebedev

**Comment by NotLebedev** [comment] 2024-01-15 08:54
> Is it resolved? @NotLebedev 

Yes

**Comment by WindSoilder** [comment] 2024-01-15 08:57
Thanks for resolving it!  It highly improves user experience when using builtin commands :)

**Closed by WindSoilder** 2024-01-15 08:57 UTC
Labels: needs-triage
