### ISSUE TITLE
Paths containing [ break commands like rm

### ISSUE THREAD

**Issue by Aarkon** [nushell/nushell#10997] opened 2023-11-08 11:56 UTC
### Describe the bug

When working in directories that have (at least) the first half of the list literal in them, I noticed that very common commands don't work the way I expect them to. For instance, I've got my music collection organized like this: `$artist/[$year] $album_title/$track_no - $title`  
Deleting the content of an album's content failed in a (to me) very surprising manner:

```
Music/Numenorean/[2019] Adore
❯ : rm *
Error:   × File(s) not found
   ╭─[entry #9:1:1]
 1 │ rm *
   ·    ┬
   ·    ╰── File(s) not found
   ╰────
```
This happens even if I target a specific file rather than a glob like `*`.  
The issue appears to be that the `[` character isn't properly escaped automatically. Below, I've collected simple steps on how to reproduce the problem in a minimal fashion

### How to reproduce

1.     mkdir `test[foo`
2.     cd `test[foo`
3.     touch test
4.     rm test
        Error:   × Pattern syntax error near position 9: invalid range pattern
           ╭─[entry #38:1:1]
         1 │ rm test
           ·    ──┬─
           ·      ╰── Pattern syntax error near position 9: invalid range pattern
           ╰────

### Expected behavior

IMHO, nu and its commands should just exhibit the behavior here I'd expect when doing the same in bash.

### Configuration

 | key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.85.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29) |
| build_time         | 2023-10-09 11:25:12 +02:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

### Additional context

The problem is not entirely limited to the list literal, but is present to some extent when the path contains other literals like `{`. I haven't checked for others though.

**Comment by amtoine** [comment] 2023-11-08 17:30
looks like a duplicate of
- https://github.com/nushell/nushell/issues/10211
- https://github.com/nushell/nushell/issues/10211

also related to
- https://github.com/nushell/nushell/issues/10364

i'll close this one in favor of the ones linked above :relieved:

**Closed by amtoine** 2023-11-08 17:30 UTC
Labels: needs-triage

**Comment by Aarkon** [comment] 2023-11-08 21:14
Ah, sorry for the duplicate. I didn’t know what to look for. Thrilled about the next release!

**Comment by amtoine** [comment] 2023-11-08 21:20
> Ah, sorry for the duplicate. I didn’t know what to look for. Thrilled about the next release!
>
no worries at all :wink: 
we have so many issues and the GitHub issue search engine is not always... super great :eyes: :laughing:
