### ISSUE TITLE
`ls -s /usr` somehow strips `LS_COLORS`

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4319] opened 2021-12-23 22:24 UTC
regular `ls /usr`
<img width="632" alt="Screen Shot 2021-12-23 at 4 23 03 PM" src="https://user-images.githubusercontent.com/343840/147296183-ac97e595-4803-4563-a7dc-cfe845faf868.png">

`ls /usr -s`
<img width="582" alt="Screen Shot 2021-12-23 at 4 23 22 PM" src="https://user-images.githubusercontent.com/343840/147296197-3060e097-b567-4e93-945d-fef4532d25a8.png">

**Comment by hustcer** [comment] 2022-03-28 12:02
This issue seems to be fixed on latest main, by https://github.com/nushell/nushell/pull/5009

**Comment by fdncred** [comment] 2022-03-28 12:07
the original issue still isn't fixed `ls /usr -s`

**Comment by hustcer** [comment] 2022-03-28 12:09
![Screen Shot 2022-03-28 at 20 08 32](https://user-images.githubusercontent.com/1161607/160394660-9a7449e9-ec3a-4fb4-a9bd-016a5c61c2ab.png)
The colors may be different, but `ls /usr -s` does has colors

**Comment by hustcer** [comment] 2022-03-28 12:28
It's weird that `ls -s` works well for some folders, but some others don't

![Screen Shot 2022-03-28 at 20 27 13](https://user-images.githubusercontent.com/1161607/160397827-e0e374ff-bdf7-419a-aa25-f31564cd7a57.png)

**Comment by fdncred** [comment] 2022-03-28 13:07
ya, i'm wondering if it's just because you're inside of the nushell directory versus doing `ls /usr -s`. i think it has to do with the `-s` in remote folders makes the files just strings and not filepaths. ls_colors doesn't really even need files, it can be made to color strings if the strings are wrapped in filepaths like "Path::new(some_string)" or maybe it's "PathBuf::new(some_string)".

**Comment by jaeheonji** [comment] 2022-03-28 16:02
After debugging, I found out the exact reason for this problem. The problem is that it cannot bring information about the `symlink_metadata`.

https://github.com/nushell/nushell/blob/1aef3a730a21ef0b4048c6cd2db8df6592831592/crates/nu-command/src/viewers/table.rs#L222-L224

This happens not only in the `/usr` directory, but everywhere the directory path is used with the `-s` option. for example, `ls -s $HOME/project/nushell`

This doesn't matter if you look up the current directory like just `ls -s`

When calling the `symlink_metadata` function, **absolute path** is required to obtain files or directory information outside the current directory, but the `-s` option removes all paths and returns only the file name or folder name.

To solve this problem, I think a different approach for the `-s` option is needed.

**Comment by fdncred** [comment] 2022-03-28 19:17
> To solve this problem, I think a different approach for the -s option is needed.

or either fake it and after this just say `Path::new(&path)`

**Closed** 2023-08-09 19:40 UTC
Labels: pipeline-metadata

**Comment by fdncred** [comment] 2023-08-13 12:56
I figured out how to make this work in #9994. Let's see if it lands or not.
