### ISSUE TITLE
can't `save out.ndjson` anymore

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#12655] opened 2024-04-24 20:37 UTC
### Describe the bug

`from ndjson` and `to ndjson` are commands defined in the standard library that enables to convert from Nushell values to NDJSON, i.e. one JSON object per line, and vice versa.

for free, Nushell allows to run `open in.ndjson` and `save out.ndjson` instead of `open --raw in.ndjson | from ndjson` and `to ndjson | save --raw out.ndjson`

however, this does not work anymore :scream:

### How to reproduce

1. `use std formats "to ndjson"`
2. `ls | save out.ndjson` gives
```
Error:   × Internal error: can't run custom
  │ command with 'run', use block_id
```

### Expected behavior

i expected the above command to output a file `out.ndjson` containing something like
```json
{"name":"LICENSE","type":"file","size":35076,"modified":"2023-12-04 19:36:37.245796502 +01:00"}
{"name":"README.md","type":"file","size":10451,"modified":"2023-12-04 19:36:37.249129844 +01:00"}
{"name":"documents","type":"dir","size":4096,"modified":"2024-02-14 18:47:04.025187609 +01:00"}
{"name":"downloads","type":"dir","size":4096,"modified":"2024-04-03 22:31:09.225909543 +02:00"}
{"name":"media","type":"dir","size":4096,"modified":"2023-11-06 12:24:48.945149373 +01:00"}
```

but i have to add `to ndjson` before `save` to fix that, i.e.
```bash
ls | to ndjson | save out.ndjson
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.92.3                                          |
| major              | 0                                               |
| minor              | 92                                              |
| patch              | 3                                               |
| branch             | main                                            |
| commit_hash        | 2595f31541554c6d8602ebebc9dffbc4dd29dd89        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77-x86_64-unknown-linux-gnu                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-04-24 22:07:38 +02:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | clipboard, explore                              |

**Comment by sholderbach** [comment] 2024-05-02 13:00
This reminds me of the test failures you had to deal with when adding them in https://github.com/nushell/nushell/pull/10519 and seems to be a duplicate of https://github.com/nushell/nushell/issues/10429

**Comment by sholderbach** [comment] 2024-05-03 11:16
Closing in favor of #10429

**Closed by sholderbach** 2024-05-03 11:16 UTC
Labels: needs-triage

**Comment by amtoine** [comment] 2024-05-04 08:55
another episode of "me filling twice the same issue" :rofl:
