### ISSUE TITLE
Making `alias` a command instead of a keyword

### ISSUE THREAD

**Issue by mon-jai** [nushell/nushell#7880] opened 2023-01-27 15:18 UTC
### Related problem

Currently `alias` is a parser keyword. It is not possible to create alias programmatically.

The following command does nothing.

```
["foo", "bar"] | each {|command_name| alias $command_name = $"($command_name).ps1" }
```

### Describe the solution you'd like

Making alias a command instead.

Therefore, something like this would legit.

```
let foo = "bar";
alias $foo = $"/bin/($foo)"
```

### Describe alternatives you've considered

Running `source` with a dynamically generated `.nu` file.

it seems to be not possible as "sourced files need to be available before your script is run".

### Additional context and details

Originally proposed at #7753

**Comment by kubouch** [comment] 2023-01-27 18:20
It doesn't work like that by design, see here for example https://www.nushell.sh/book/how_nushell_code_gets_run.html.

If we ever decide to add eval, then it would be possible to do all of this dynamically but it would require a serious redesign that we're not considering right now.

**Comment by mon-jai** [comment] 2023-01-27 19:26
I found a work around.

[Nushell load `env.nu` and `config.nu` separately](https://www.nushell.sh/book/configuration.html#nushell-configuration-with-env-nu-and-config-nu), so we can write a new script to filesystem in `env.nu` and then source the file in `config.nu`.

`env.nu`

```diff
+ ["foo", "bar"] | each {|command_name| $"alias ($command_name) = ($command_name).ps1" } | str join "\n" | save --force ~/.config/nushell/env-generated.nu
```

`config.nu`

```diff
+ ~/.config/nushell/env-generated.nu
```

---

To make it more easy to bypass these restriction, maybe we can let user config which script to run on startup?

**Comment by kubouch** [comment] 2023-04-06 19:09
You can set which scripts to run in config.nu. We might also be able to do conditional sourcing/module import at some point, which should help. But that's a separate problem, I'll close this one.

**Closed by kubouch** 2023-04-06 19:09 UTC
Labels: enhancement, alias
