### ISSUE TITLE
Make internal->external protocol configurable

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#778] opened 2019-10-03 03:32 UTC
Eg) https://twitter.com/saulfp/status/1179595380352147457?s=19

It would be helpful to be able to configure how values are serialized from internal commands to external ones. Eg you may want to configure it to use json if you predominantly user json-parsing externals.

**Comment by saulpw** [comment] 2019-10-03 04:06
I don't know about the internals of nushell, but would it be straightforward to check the environment for something like `NUTO=tsv`?

Also what is the `^echo $it`?

**Comment by andrasio** [comment] 2019-10-03 04:09
@jonathandturner Interesting.

@saulpw please see [escaping commands](https://book.nushell.sh/en/escaping)

**Comment by ajkerrigan** [comment] 2019-10-04 02:02
This seems related to #412, but I can't tell if these are two separate concerns or just two pieces of the same question:

- How do we send data directly from an internal command to the stdin of an external one?
- How do we control the serialization/formatting along the way?

For VisiData specifically, I was wondering if it'd be useful to have a plugin that would let you do this:

```<internal command that produces a table> | vd --format json```

As a replacement for:

```<internal command that produces a table> | to-json | ^echo $it | vd -f json```

But wasn't sure if that was a fundamentally broken/too narrow way to think about it.

**Comment by andrasio** [comment] 2019-11-02 21:20
#900

**Comment by thegedge** [comment] 2020-01-06 00:57
Related idea: https://github.com/nushell/nushell/issues/451

**Comment by thegedge** [comment] 2020-02-23 19:11
Duplicate of https://github.com/nushell/nushell/issues/451

I'm going to close this in favour of #451, which mentions configuring both input and output marshalling of externals. In other words, it's a superset of functionality.

**Closed by thegedge** 2020-02-23 19:11 UTC
Labels: enhancement
