### ISSUE TITLE
Underlined filename in table incorrectly displayed in narrow terminal window

### ISSUE THREAD

**Issue by dandavison** [nushell/nushell#6553] opened 2022-09-13 03:06 UTC
### Describe the bug

.zip and .tgz files are displayed with an underline font in the `ls` table output by default:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/52205/189798447-a02a2034-ad34-4516-aa88-49a5636601f8.png">

But when the terminal window is narrow, they are displayed incorrectly

<img width="366" alt="image" src="https://user-images.githubusercontent.com/52205/189798472-d1b93ee0-57f4-42de-9397-ada4a8dfb25b.png">

Quick googling suggests that 24m might be [SGR Not underlined](https://en.wikipedia.org/wiki/ANSI_escape_code). It seems likely that what's going on is that nushell is making an attempt to remove the underline font (since it has to break the file name across lines), but the ANSI 24m technique it's using to do that isn't working out.

### How to reproduce

1. `touch aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip`
2. Make your terminal window narrow
3. `ls`

### Expected behavior

I expected nu to display the filename without extraneous characters or strange font decorations, even when the table is narrow.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.68.2                                   |
| branch             |                                          |
| commit_hash        | 12c5054c5bd9e30791ca3167df3a633ccda42fe2 |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)      |
| rust_channel       | 1.61.0-x86_64-apple-darwin               |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)      |
| pkg_version        | 0.68.2                                   |
| build_time         | 2022-09-11 20:12:48 -04:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

### Additional context

Originally reported by Sommermorgentraum in [discord](https://discord.com/channels/601130461678272522/614593951969574961/1019074488815603732).

**Comment by zxkmm** [comment] 2022-09-13 03:09
Reproduced on me.

**Comment by dandavison** [comment] 2022-09-13 11:07
Actually, this bug is not specifically related to underline, it seems to involve other ANSI escapes and non-ASCII characters. E.g. here there seems to be bad handling of the non-ASCII characters, and a number from an ASCI color code is appearing (39, which is related to setting foreground color).

<table>
  <tbody>
      <tr>
          <td><img width="913" alt="image" src="https://user-images.githubusercontent.com/52205/189883909-652abfc3-3d77-489e-ac26-c3bf44c1b548.png">
</td>
      </tr>
  </tbody>
</table>



<table>
  <tbody>
      <tr>
          <td><img width="745" alt="image" src="https://user-images.githubusercontent.com/52205/189884592-ad729932-ac50-460b-ad0c-4397779f2e8f.png">
</td>
      </tr>
  </tbody>
</table>


@zhiburt do you happen to know where this bug is (is it in tabled's wrap.rs?)

The file names I'm using there are (and these align correctly thanks to @zhiburt!)

```
│ README.release.txt                                                                      │ file │     132 B │ 3 minutes ago  │
│ VOF NGS rådata og behandling.docx                                                       │ file │       0 B │ 37 minutes ago │
│ Yanling NUC-C3 Lüfterloser Firewall-Mini-PC mit viermal GBit - Ethernet im Test.pdf.txt │ file │       0 B │ 17 minutes ago │
│ Yanling NUC-C3 Lüfterloser Firewall-Mini-PC mit viermal GBit - Ethernet im Testüüü.pdf  │ file │       0 B │ 16 minutes ago │
```

**Comment by zhiburt** [comment] 2022-09-13 11:22
Hi @dandavison
your research is correct the reason is in `wrap.rs`.

The actual cause is that `tabled` yet doesn't support terminal links when doing wrap.
(That's something I am working on currently).

```
│\u{1b}[39m \u{1b}[37m\u{1b}[38;5;203m\u{1b}[4m\u{1b}]8;;file:///home/maxim/trash/nushell/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip\u{1b}\\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip\u{1b}]8;;\u{1b}\\\u{1b}[0m\u{1b}[0m \u{1b}[35m│
```

ref: #6443

**Comment by dandavison** [comment] 2022-09-13 11:37
Hi @zhiburt, great! I don't know if this is helpful, but just in case: [delta](https://github.com/dandavison/delta/blob/master/src/ansi/iterator.rs#L45) contains a library for parsing ANSI escape sequences and OSC terminal hyperlinks: you give it a string, and it returns a Rust iterator of parsed ANSI sequences/hyperlinks or intervening text. I'm the author of delta, but I (thankfully, or I certainly wouldn't recommend it) didn't write the parser: it uses the [vte](https://github.com/alacritty/vte) terminal emulator library from the Alacritty project, so I believe it may be pretty robust. When I wrote it, competing Rust crates such as https://github.com/mitsuhiko/console did not handle hyperlinks (and are based on Regex parsing). Anyway, perhaps there is a solution for this now in the Rust crates ecosystem. But if not, I'd be happy to work with you to pull `AnsiIterator` out of delta into a crate. (I'm dd7 in nushell discord). But no worries at all if none of that is relevant.

**Comment by zhiburt** [comment] 2022-09-13 23:09
It would interesting to compare https://github.com/dandavison/delta/blob/master/src/ansi/iterator.rs#L45 and https://lib.rs/crates/ansitok which relays on `nom`.

They have a similar interface.
But the former doesn't handles links (not sure if it should).

`tabled` uses it to parse colors.

**Comment by dandavison** [comment] 2022-09-13 23:51
> It would interesting to compare https://github.com/dandavison/delta/blob/master/src/ansi/iterator.rs#L45 and https://lib.rs/crates/ansitok which relays on nom.

Ah, nice you've written an ANSI parser library. Definitely, I'll have a go at making that comparison and see if the vte-based parser solves the hyperlink problems.

**Comment by dandavison** [comment] 2022-09-14 03:42
I've put up a fix for this as a patch against tabled v0.8.0, using the ANSI parser library from Alacritty, which handles OSC8 hyperlinks (code taken from delta): https://github.com/zhiburt/tabled/pull/223 The OSC8 parser code is currently a crate on github; we could vendor it temporarily in tabled, or continue installing from github, or get the crate documented and published to crates.io.

**Comment by zhiburt** [comment] 2022-09-14 06:30
> Definitely, I'll have a go at making that comparison and see if the vte-based parser solves the hyperlink problems.

I meant a few benchmarks actually :)

![image](https://user-images.githubusercontent.com/20165848/190076415-0772ce93-6908-44f6-a27b-75764bd793bd.png)

Seems like vte::AnsiElementIterator is faster.

Need to investigate it a bit more.
If it is we could switch to it I think.

**Comment by dandavison** [comment] 2022-09-14 10:21
Excellent, thanks for working on the benchmarking! I'd be interested to see the benchmarking code at some point.

**Comment by zhiburt** [comment] 2022-09-14 11:17
> I'd be interested to see the benchmarking code at some point.

Well I was just comparing `.next()` calls on iterators.

```rust
use ansitok::{parse_ansi, parse_ansi_sgr, AnsiSequence, Output};
use criterion::{black_box, criterion_group, criterion_main, BenchmarkId, Criterion};
use vte_ansi_iterator::AnsiElementIterator;

pub fn asd(c: &mut Criterion) {
    let mut group = c.benchmark_group("asd");

    for size in [1, 8, 32, 128, 512] {
        let text = std::iter::repeat("\x1b[31;1;4mHello World\x1b[0m")
            .take(size)
            .collect::<Vec<_>>()
            .join("\n");

        group.bench_with_input(BenchmarkId::new("ansitok", size), &size, |b, _size| {
            b.iter(|| {
                for a in parse_ansi(&text) {
                    if let Output::Escape(AnsiSequence::SelectGraphicRendition(sgr)) = a {
                        for output in parse_ansi_sgr(sgr) {
                            black_box(output);
                        }
                    }

                    black_box(a);
                }
            });
        });

        group.bench_with_input(BenchmarkId::new("vte", size), &size, |b, _size| {
            b.iter(|| {
                for a in AnsiElementIterator::new(&text) {
                    black_box(a);
                }
            });
        });
    }

    group.finish();
}

criterion_group!(benches, asd);
criterion_main!(benches);

```

I'd like also to point out that seems like you parse SGR right away.
`ansitok` requires second call.

It gets us to

![image](https://user-images.githubusercontent.com/20165848/190139838-7317ee9b-6282-4d50-8042-a9b2552c581c.png)

**Comment by IwateKyle** [comment] 2022-10-01 00:41
just wanted to add that I'm getting the same wrapping anomaly. Somehow, it looks like the previous entry name data is getting merged with succeeding entries.
 
![image](https://user-images.githubusercontent.com/658799/193376167-6d2f4652-0ff1-4342-852e-c10c65dc2126.png)

**Comment by zhiburt** [comment] 2022-10-01 09:41
Hi @IwateKyle could you try to do the same on https://github.com/nushell/nushell/pull/6286?

**Closed** 2022-10-03 16:42 UTC
Labels: :bug:  bug, tabled
