### ISSUE TITLE
Type mismatch with "where size > 4kb"

### ISSUE THREAD

**Issue by peterdolland** [nushell/nushell#5578] opened 2022-05-18 16:00 UTC
### Describe the bug

I have just installed the nushell 0.62.0 under Linux Mint 20. I am calling nu from a terminal and following the introduction https://www.nushell.sh/book/ . The third command is "ls | where size > 1kb" which is leading to a "type mismatch" error.

### How to reproduce

1. Install nushell under Linux Mint 20.
2. Start nu
3. ls | where size > 1kb

### Expected behavior

as described in the introduction on https://www.nushell.sh/book/ .

### Screenshots
```
/home/peter〉ls                                           05/18/2022 05:19:09 PM
╭────┬────────────────────────────────────┬──────┬───────────┬───────────────╮
│ #  │                name                │ type │   size    │   modified    │
├────┼────────────────────────────────────┼──────┼───────────┼───────────────┤
│  0 │ B0                                 │ dir  │   4.0 KiB │ a year ago    │
│  1 │ Bilder                             │ dir  │   4.0 KiB │ 3 months ago  │
│  2 │ Dokumente                          │ dir  │   4.0 KiB │ 2 months ago  │
│  3 │ Downloads                          │ dir  │   4.0 KiB │ a week ago    │
│  4 │ Gramps                             │ dir  │   4.0 KiB │ 4 months ago  │
│  5 │ Musik                              │ dir  │   4.0 KiB │ 2 months ago  │
│  6 │ Python-3.10.0                      │ dir  │   4.0 KiB │ 5 months ago  │
│  7 │ Python-3.10.0.tgz                  │ file │  23.8 MiB │ 7 months ago  │
│  8 │ Saxonica                           │ dir  │   4.0 KiB │ a year ago    │
│  9 │ Schreibtisch                       │ dir  │   4.0 KiB │ 6 months ago  │
│ 10 │ Videos                             │ dir  │   4.0 KiB │ a year ago    │
│ 11 │ Vorlagen                           │ dir  │   4.0 KiB │ a year ago    │
│ 12 │ audacity_proj                      │ dir  │   4.0 KiB │ a year ago    │
│ 13 │ b..bash_history                    │ file │ 279.0 KiB │ 7 months ago  │
│ 14 │ digraphtable                       │ dir  │   4.0 KiB │ 9 months ago  │
│ 15 │ easytranscript                     │ dir  │   4.0 KiB │ a month ago   │
│ 16 │ exc                                │ dir  │   4.0 KiB │ 3 months ago  │
│ 17 │ fam                                │ dir  │   4.0 KiB │ a week ago    │
│ 18 │ gap-4.11.1                         │ dir  │   4.0 KiB │ 10 months ago │
│ 19 │ get-pip.py                         │ file │   2.1 MiB │ 5 months ago  │
│ 20 │ graphviz                           │ dir  │   4.0 KiB │ 10 months ago │
│ 21 │ haskell                            │ dir  │   4.0 KiB │ a year ago    │
│ 22 │ lit                                │ dir  │   4.0 KiB │ 4 months ago  │
│ 23 │ log-general                        │ dir  │   4.0 KiB │ a year ago    │
│ 24 │ mypipe                             │ pipe │           │ 6 months ago  │
│ 25 │ nu_0_62_0_linux                    │ dir  │   4.0 KiB │ 2 weeks ago   │
│ 26 │ nu_0_62_0_linux.tar.gz             │ file │  18.5 MiB │ 2 weeks ago   │
│ 27 │ peter20211228-2022-04-25-17-26-51. │ file │ 211.7 KiB │ 3 weeks ago   │
│    │ gramps                             │      │           │               │
│    │ gramps                             │      │           │               │
│ 29 │ peter20211228_det_descendant_repor │ file │ 204.5 KiB │ 3 weeks ago   │
│    │ t.pdf                              │      │           │               │
│ 30 │ postgre                            │ dir  │   4.0 KiB │ a year ago    │
│ 31 │ privMath                           │ dir  │   4.0 KiB │ 2 years ago   │
│ 32 │ prj                                │ dir  │   4.0 KiB │ 2 months ago  │
│ 33 │ prl                                │ dir  │   4.0 KiB │ 9 months ago  │
│ 34 │ py                                 │ dir  │   4.0 KiB │ 3 months ago  │
│ 35 │ rl                                 │ dir  │   4.0 KiB │ 10 months ago │
│ 36 │ sav211017_.bashrc                  │ file │   2.9 KiB │ 7 months ago  │
│ 37 │ svgpy                              │ dir  │   4.0 KiB │ 7 months ago  │
│ 38 │ t                                  │ dir  │   4.0 KiB │ a week ago    │
│ 39 │ texex                              │ dir  │   4.0 KiB │ a year ago    │
│ 40 │ texmf                              │ dir  │   4.0 KiB │ a year ago    │
│ 41 │ tmpsave                            │ dir  │   4.0 KiB │ a year ago    │
│ 42 │ vs                                 │ dir  │   4.0 KiB │ a week ago    │
│ 43 │ x                                  │ file │       6 B │ 3 months ago  │
│ 44 │ xmltry                             │ dir  │   4.0 KiB │ 10 months ago │
│ 45 │ Öffentlich                         │ dir  │   4.0 KiB │ a year ago    │
├────┼────────────────────────────────────┼──────┼───────────┼───────────────┤
│ #  │                name                │ type │   size    │   modified    │
╰────┴────────────────────────────────────┴──────┴───────────┴───────────────╯
```
```
/home/peter〉ls | where size > 4kb                        05/18/2022 05:19:22 PM
Error: nu::shell::type_mismatch (link)

  × Type mismatch
   ╭─[entry #2:1:1]
 1 │ ls | where size > 4kb
   ·                 ┬
   ·                 ╰── needs compatible type
   ╰────

/home/peter〉                                             05/18/2022 05:20:58 PM
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | da104050                                        |
| commit_hash        | da104050e6dcf7fbffd41bfd4bdeae1285b7a48c        |
| commit_date        | 2022-05-03 21:50:33 +00:00                      |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)               |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-03 22:01:03 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by merelymyself** [comment] 2022-05-18 16:13
This isn't reproducible on my end. I'm on the latest commit - maybe it's already fixed?

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.62.1                                   |
| branch             | main                                     |
| commit_hash        | 2c58beec1329eedfb9aa126520b061671cdadbeb |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.62.1                                   |
| build_time         | 2022-05-18 23:53:29 +08:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by hustcer** [comment] 2022-05-18 16:26
Guess maybe a dupe of this one: https://github.com/nushell/nushell/issues/4975

**Comment by hustcer** [comment] 2022-05-18 16:32
I see, there is a pipe file in your dir named `mypipe`, can you show me the size of it? @peterdolland

**Closed** 2022-05-20 14:27 UTC
Labels: bug
