### ISSUE TITLE
Unable to set alias from a record with a loop

### ISSUE THREAD

**Issue by aadi58002** [nushell/nushell#8657] opened 2023-03-29 04:17 UTC
### Question

Why is this loop not setting alias according to the record defined
```
let-env aliases = {
     pacu : "paru -Syu",
     pacs : "paru -Ss",
     paci : "paru -S",
     pacr : "paru -Rns",
     pacl : "paru -Qs",
}

$env.aliases | transpose key value | each { |val| print (alias $val.key = bash -c ("\"" + $val.value + "\"" )) }
```
After running these both there are no alias set with above names

### Additional context and details
I am nu shell version 0.77.1 and running arch linux

**Comment by kubouch** [comment] 2023-03-29 06:01
This can't work for two reasons:
1. You can't define aliases dynamically (e.g., name from a variable).
2. Aliases (like almost everything in Nushell) are scoped, so the alias would be visible only inside the `each` closure.

The underlying reason for both is that we don't have "eval" functionality, by design.

You can check our documentation for more explanation, especially https://www.nushell.sh/book/thinking_in_nu.html (and if you want more in-depth https://www.nushell.sh/book/how_nushell_code_gets_run.html).

I'll close it now but feel free to ask more questions.

**Closed by kubouch** 2023-03-29 06:01 UTC
Labels: question
