### ISSUE TITLE
Running `ls | where type == File and size > 10 KB` in my home directory crashes nushell

### ISSUE THREAD

**Issue by stephanemagnenat** [nushell/nushell#599] opened 2019-09-04 19:06 UTC
```
/home/steph> ls | where type == File and size > 10 KB
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShellError { error: CoerceError { left: Tagged { tag: Tag { origin: None, span: Span { start: 28, end: 32 } }, item: "string" }, right: Tagged { tag: Tag { origin: None, span: Span { start: 35, end: 37 } }, item: "int" } }, cause: None }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x5565d44c0ca2 - backtrace::backtrace::libunwind::trace::h18f90dc074cdeff3
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x5565d44c0ca2 - backtrace::backtrace::trace_unsynchronized::h27ef0203f88f7ab3
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x5565d44c0ca2 - std::sys_common::backtrace::_print::h67261d2f8a7a2d49
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5565d44c0ca2 - std::sys_common::backtrace::print::h659c07e17322713f
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5565d44c0ca2 - std::panicking::default_hook::{{closure}}::h535865fabc88f114
                               at src/libstd/panicking.rs:200
   5:     0x5565d44c0986 - std::panicking::default_hook::hade01f1414caaa82
                               at src/libstd/panicking.rs:214
   6:     0x5565d44c13f5 - std::panicking::rust_panic_with_hook::h2afd8ba2d470937f
                               at src/libstd/panicking.rs:477
   7:     0x5565d44c0f92 - std::panicking::continue_panic_fmt::ha9436eec374093a8
                               at src/libstd/panicking.rs:384
   8:     0x5565d44c0e86 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5565d44e2eaa - core::panicking::panic_fmt::ha4df8a24069b4b5e
                               at src/libcore/panicking.rs:85
  10:     0x5565d44e2fa7 - core::result::unwrap_failed::h7d8c11e627c07c08
                               at src/libcore/result.rs:1084
  11:     0x5565d3ff36d7 - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h19756347b7cbf9d1
  12:     0x5565d3f343e7 - <futures_util::stream::flatten::Flatten<St> as futures_core::stream::Stream>::poll_next::hbff15e541d53f124
  13:     0x5565d3ff2d25 - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h0cdbbef46be0657d
  14:     0x5565d3f1d6f5 - std::future::poll_with_tls_context::hba0d09cd381e9765
  15:     0x5565d3f1a3aa - nu::cli::cli::{{closure}}::h3a0f2a87dfbb16bc
  16:     0x5565d3f00b08 - futures_executor::local_pool::block_on::hf67dd8e6da9c8d73
  17:     0x5565d3f0889c - nu::main::h1f2c6ca9b7db4f9a
  18:     0x5565d3f0c9f7 - std::rt::lang_start::{{closure}}::h3b97c38d552ddf2a
  19:     0x5565d44c0e23 - std::rt::lang_start_internal::{{closure}}::h015d4c17e77088f5
                               at src/libstd/rt.rs:49
  20:     0x5565d44c0e23 - std::panicking::try::do_call::hec38da4a4422da84
                               at src/libstd/panicking.rs:296
  21:     0x5565d44caa7a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  22:     0x5565d44c19ad - std::panicking::try::h841396757fc5079e
                               at src/libstd/panicking.rs:275
  23:     0x5565d44c19ad - std::panic::catch_unwind::hc772ff53db32b5fc
                               at src/libstd/panic.rs:394
  24:     0x5565d44c19ad - std::rt::lang_start_internal::he96efc45dc6ada61
                               at src/libstd/rt.rs:48
  25:     0x5565d3f089e2 - main
  26:     0x7f7bb8581b97 - __libc_start_main
  27:     0x5565d3ef349a - _start
  28:                0x0 - <unknown>
```

**Comment by stephanemagnenat** [comment] 2019-09-04 19:08
Versions are:
- nu v0.2.0
- rustc 1.39.0-nightly (b9de4ef89 2019-09-03)

**Comment by stephanemagnenat** [comment] 2019-09-04 19:13
I guess this issue is an instance of #294. As a user, is it worth reporting such issues or is it better to wait for #294 to be fixed? I do not want to create unnecessary noise.

**Comment by jonathandturner** [comment] 2019-09-04 21:02
I believe this is a general parser issue, as `and` is not supported by nu.

**Comment by wycats** [comment] 2019-09-10 01:18
The `and` feature is a dupe of #502 

It's good to report crashes, but I'm generally merging them into #438.

This particular issue seems like a dupe of #454, which said that it was no longer panicking, but rather just behaving poorly. I tested and that seems true to me.

**Closed by wycats** 2019-09-10 01:18 UTC
