### ISSUE TITLE
Wrong infer type when passing flag with var (maybe when combine with mut)

### ISSUE THREAD

**Issue by wdv4758h** [nushell/nushell#9206] opened 2023-05-16 08:55 UTC
### Describe the bug

I think nushell has wrong infer type in this case. Causing script can't be run.

### How to reproduce

```nu
def func [
  --timeout(-t) = 3sec
] {
  []
}

def main [
  --timeout(-t) = 1sec
] {
  mut data = []
  $data = (func -t $timeout)  # this failed
  # $data = (func -t 1sec)  # this works
  # $data = (func -t $timeout | inspect)  # this works
}
```

### Expected behavior

Works without error.

### Screenshots

![image](https://github.com/nushell/nushell/assets/2716047/6c5e0b70-10b2-43ca-a31f-53fb9348c780)

### Configuration

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.79.0                                                                                      |
| branch             | makepkg                                                                                     |
| commit_hash        | a1b72611215dbfca257351003204a80c83859e05                                                    |
| build_os           | linux-x86_64                                                                                |
| build_target       | x86_64-unknown-linux-gnu                                                                    |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (Arch Linux rust 1:1.69.0-2)                            |
| cargo_version      | cargo 1.69.0                                                                                |
| build_time         | 2023-04-27 07:32:56 +00:00                                                                  |
| build_rust_channel | release                                                                                     |
| features           | default, zip                                                                                |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

**Comment by wdv4758h** [comment] 2023-05-16 09:01
I think it's the last flag that passing with var will become the infered return type. Adding extra flags behind it with passing via literal won't change the behavior.

**Comment by fdncred** [comment] 2023-05-16 11:16
I can't test because 0.79.1 won't allow this type of definintion. This part looks like a bug but I'm not sure.
![image](https://github.com/nushell/nushell/assets/343840/126cb67b-44de-48f9-ba0b-24782175fb9f)

**Comment by bobhy** [comment] 2023-05-16 12:04
I can confirm there's something wrong here.  I think it has to do with recognizing Filesize or Duration constants as defaults in the function definition, other types work OK.  Title might be changed to say "some constants not recognized when defining function"
```
〉def f [ --foo=3day ] { [] }
Error: nu::parser::non_constant_default_value

  × Default values should be constant expressions.
   ╭─[entry #28:1:1]
 1 │ def f [ --foo=3day ] { [] }
   ·               ──┬─
   ·                 ╰── expected a constant value
   ╰────
〉def f [ --foo = 23b ] { [] }
Error: nu::parser::non_constant_default_value

  × Default values should be constant expressions.
   ╭─[entry #29:1:1]
 1 │ def f [ --foo = 23b ] { [] }
   ·                 ─┬─
   ·                  ╰── expected a constant value
   ╰────

〉def f [ --foo = 23 ] { [] }
# no error

〉def f [ --foo = 23. ] { [] }
〉help f
Usage:
  > f {flags} 

Flags:
  --foo <Number> -  (default: 23)
  -h, --help - Display the help message for this command
```


And I think this might be a recent regression, I was playing with durations as defaults last week and didn't notice this problem.

**Comment by wdv4758h** [comment] 2023-05-16 13:20
I think the duration can't be default is different issue. What I metioned can reproduce with int too.

I just build from latest commit and reproduce it:

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.79.1                                                                                      |
| branch             | main                                                                                        |
| commit_hash        | bf86cd50a5928d86dce0e9b5b52a269cec35595f                                                    |
| build_os           | linux-x86_64                                                                                |
| build_target       | x86_64-unknown-linux-gnu                                                                    |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)                                                         |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu                                                             |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)                                                         |
| build_time         | 2023-05-16 21:14:31 +08:00                                                                  |
| build_rust_channel | debug                                                                                       |
| features           | default, zip                                                                                |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

Code:

```nu
def func [
  --foo = 3
] {
  []
}

def main [] {
  mut data = []
  let x = 1
  $data = (func --foo $x)  # this failed
  # $data = (func --foo 1)  # this works
  # $data = (func --foo $x | inspect)  # this works
}
```

![image](https://github.com/nushell/nushell/assets/2716047/a3899d34-298d-4a0a-adaf-fb01bbc77679)

**Comment by fdncred** [comment] 2023-05-16 13:49
@wdv4758h I think the problem is how you're defining your mutable variable and your function. This works.

With data as a list
```
def func [--foo = 3] { [] }
def main [] {
  mut data = []
  let x = 1
  $data = [(func --foo $x)]
  echo $data
}
```
With data as an int
```
def func [--foo = 3] { $foo }
def main [] {
  mut data = 0
  let x = 1
  $data = (func --foo $x)
  echo $data
}
```
In your example, your function is returning a list and data is a list but you're assigning an int to it incorrectly.

**Comment by wdv4758h** [comment] 2023-05-16 14:23
> In your example, your function is returning a list and data is a list but you're assigning an int to it incorrectly.

Unfortunately, I can't agree with this comment at the moment.

1. my function is returning a list
2. my data is a list
3. I'm assiging my function return (which should be as list since 1.) to my data (which is a list since 2.)

How to explain the reason of int return type?

---

For your first example:

```
def func [--foo = 3] { [] }
def main [] {
  mut data = []
  let x = 1

  $data = [(func --foo $x)]  # <- why is this one needs to be included with [] when the function return is already a list
  # also, this makes type list<list<any>> instead of list<any>

  echo $data
}
```

---

Let's modify your int version a little bit:

```
# here we modify the foo from int to string, and the implementation return the string length
def func [--foo = "a"] { $foo | str length }
def main [] {
  mut data = 0
  let x = "ab"
  $data = (func --foo $x)  # now this will fail
  echo $data
}
```

![image](https://github.com/nushell/nushell/assets/2716047/acb4db1d-62cc-4191-a9d8-9e8b718ecc70)

**Comment by bobhy** [comment] 2023-05-16 14:24
Aha!  Then I think there are 2 issues!  I'll open the other one separately

**Comment by wdv4758h** [comment] 2023-05-16 14:41
Besides adding `| inspect`. There is another workround I found. Using `(do { ... })` instead of `(...)` will make it happy.

For example, this works:

```
def func [--foo = "a"] { $foo | str length }
def main [] {
  mut data = 0
  let x = "ab"
  $data = (do { func --foo $x })
  echo $data
}
```

**Comment by fdncred** [comment] 2023-05-16 15:10
I agree that there's a bug.
Expects a string as input and int as output
```
def func [--foo = "a"] { $foo | str length }
```
You can see that the input is set right here (but the output is set to any - not sure why)
```
$nu.scope.commands | where name == func | get signatures.0.any                                                                     79  10:06:36 AM
╭───┬────────────────┬────────────────┬──────────────┬─────────────┬────────────┬─────────────┬───────────────────┬───────────────────╮
│ # │ parameter_name │ parameter_type │ syntax_shape │ is_optional │ short_flag │ description │ custom_completion │ parameter_default │
├───┼────────────────┼────────────────┼──────────────┼─────────────┼────────────┼─────────────┼───────────────────┼───────────────────┤
│ 0 │                │ input          │ any          │ false       │            │             │                   │                   │
│ 1 │ foo            │ named          │ string       │ true        │            │             │                   │ a                 │
│ 2 │                │ output         │ any          │ false       │            │             │                   │                   │
╰───┴────────────────┴────────────────┴──────────────┴─────────────┴────────────┴─────────────┴───────────────────┴───────────────────╯
```
Then you can just do your other function things in the repl to try and reduce the footprint.
```
mut data = 0
let x = "ab"
```
We see that `func` is returning correctly here.
```
func --foo $x | debug -r
Int {
    val: 2,
    span: Span {
        start: 267670,
        end: 267680,
    },
}
```
We can see that `$data` is an int with
```
$data | describe
int
```
So, we should be able to do 
```
$data = (func --foo $x)
Error: nu::parser::type_mismatch

  × Type mismatch during operation.
   ╭─[entry #20:1:1]
 1 │ $data = (func --foo $x)
   ·         ───────┬───────
   ·                ╰── expected int, found string
   ╰────
```
but we get an error, which I think is a bug.

**Comment by WindSoilder** [comment] 2023-11-15 01:59
I can't reproduce it on latest main....It may be fixed by an unknown pr...
@wdv4758h Would you please verify if the issue is still exists?

**Comment by wdv4758h** [comment] 2023-11-15 05:27
@WindSoilder I can verify that the original issue is gone. Not sure since when though.

**Comment by WindSoilder** [comment] 2023-11-15 06:16
Thanks for your verify!  It's handled by a secret power -.-  I'll close the issue for now, feel free to reopen it if the issue is still exists

**Closed by WindSoilder** 2023-11-15 06:16 UTC
Labels: type-system, needs-triage
