### ISSUE TITLE
Allow defaults for `to json` and similar commands.

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#2190] opened 2020-07-15 17:58 UTC
I'd like to set a default for `to json` to always use `-p 4`, I can't seem to find a way to accomplish this with configs I know I could just alias the command, but I am wondering if there is another way I am not aware of.

**Comment by thegedge** [comment] 2020-07-15 19:13
Duplicate of https://github.com/nushell/nushell/issues/1885

> I can't seem to find a way to accomplish this with configs I know I could just alias the command, but I am wondering if there is another way I am not aware of.

Aliases are the way to go. One problem we have currently is that you can't create an alias that overrides a builtin command. For example, in another shell I may override `ls` to always use colors:

```
alias ls='ls -G'
```

We have https://github.com/nushell/nushell/issues/1885 for that though, so subscribe to that one and hopefully we'll have something for you soon 🙂

**Closed by thegedge** 2020-07-15 19:13 UTC

**Comment by ryanpcmcquen** [comment] 2020-07-15 19:26
Thanks!
