### ISSUE TITLE
Completer issue when command is alias of a builtin.

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#9301] opened 2023-05-26 22:39 UTC
### Describe the bug

"ERR" showing up after I enter `<command><space>TAB`, but (apparently) only when `<command>` is an alias matching name of a built-in command *and* the alias expansion includes a switch.

### How to reproduce

`alias uniq = ls`
![image](https://github.com/nushell/nushell/assets/1971300/0ef2c865-d605-4284-9e78-8fa22e7dc104)

`alias uniq = ls -l`

![image](https://github.com/nushell/nushell/assets/1971300/5cde1993-b88e-4201-916a-f6a46314abbb)

### Expected behavior

Completer shouldn't fail because the expansion was different.  The characters preceeding TAB on the command line are the same in both cases.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.1                                   |
| branch             | main                                     |
| commit_hash        | 6481bf272c8a407aacddf91c171ebf78c0531889 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-26 07:05:33 -04:00               |
| build_rust_channel | release                                  |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by bobhy** [comment] 2023-05-26 22:41
It doesn't fail if the alias name does not match a built-in command...

![image](https://github.com/nushell/nushell/assets/1971300/d2cb33d4-2a1c-4bae-b1bb-6b432e14d31f)

**Comment by ysthakur** [comment] 2024-05-22 23:16
@bobhy Can you still reproduce this? I can no longer do so on the latest main ([64afb52](https://github.com/nushell/nushell/commit/64afb52ffaa68ac761b5f5d05d51d3fb1547084b) at the time of writing).

![image](https://github.com/nushell/nushell/assets/45539777/58032523-bde8-4c44-bcf4-e43202644ace)

I'm closing this issue because I assume it was fixed at some point, but let me know if you can still reproduce it.

**Closed by ysthakur** 2024-05-22 23:16 UTC
Labels: :bug:  bug, completions, alias

**Comment by bobhy** [comment] 2024-05-25 04:18
I can no longer repro this either, on 0.93.1
