### ISSUE TITLE
7z is a 'string' despite 7z.exe being on my path

### ISSUE THREAD

**Issue by BatmanAoD** [nushell/nushell#5109] opened 2022-04-06 15:10 UTC
It appears that #3934 still affects me on Windows in version 0.60.0.

```
❯ : nu --version
0.60.0

~
❯ : which 7z
╭───┬─────┬─────────────────────────────────────────┬──────────╮
│ # │ arg │                  path                   │ built-in │
├───┼─────┼─────────────────────────────────────────┼──────────┤
│ 0 │ 7z  │ C:\Users\Kyle.Strand\scoop\shims\7z.EXE │ false    │
╰───┴─────┴─────────────────────────────────────────┴──────────╯

~
❯ : 7z | describe
string

~
❯ : 7z
7z
```

Note that 7z is provided by Scoop. I'm not sure if this is part of the problem.

I'm using Windows 11; please let me know what other environment info I can provide.

_Originally posted by @BatmanAoD in https://github.com/nushell/nushell/issues/4606#issuecomment-1089466373_

**Comment by fdncred** [comment] 2022-04-06 15:16
Can you try the latest main branch instead of installng from scoop or choco?

**Comment by fdncred** [comment] 2022-04-06 17:09
ok, we're partly in agreement. haha :)

Any shell in WSL that accesses `/mnt/c/blah` will have a performance hit, no matter what. That's just the nature of coming from linux's ext4 from a vm going through the network to get to a mount point, translating that to ntfs, and accessing those files. 

Where we agree is that nushell is doing its look-for-externals-in-the-path-that-look-like-numbers too much and maybe the wrong way. See my most recent suggestion here https://github.com/nushell/nushell/issues/5106#issuecomment-1090488080 - not sure if it's a good idea but i'm warming up to it since it could fix the problem i think.

Trust me, i about fell over when I started up WSL the other day, in a new instance and had 10 linux path entries and 60 windows path entries. It took a solid 15 seconds to do anything. Part of that is what we're talking about, another part to consider is that having 70 path entries was ridiculous for wsl (thank you windows).

i'm not trying to be argumentative with you - just trying to find common ground. i also think we're kind of saying a lot of the same thing but different ways. thanks for your input.

**Comment by jntrnr** [comment] 2022-04-06 17:42
@BatmanAoD - I think it's a combination of a couple factors. Something like `7mb` would be treated as a filesize, which can be part of a math expression, but `7z` isn't. What if there was a binary on the system called `7mb`? The way the system works now, we give it priority over the filesize value when in the command position.

**Comment by BatmanAoD** [comment] 2022-04-06 18:13
@jntrnr Okay, that clears up a _lot_ of confusion for me; I wasn't aware that there were any valid alphanumeric (but not strictly numeric) strings that were "math-like". Thanks.

I think it does make sense that an executable called `7mb` would take precedence, though I can also see an argument for treating it more like `open`, i.e., something that the user should configure an exception for if they want to be able to use the non-`nu`-like behavior.

If `nu` did adapt the default that "math-like expressions won't trigger a search for an external command, unless they match a specific override", I think that a sufficiently conservative check for whether an expression is "math-like" would still be sufficient for most cases. In particular, I doubt `7z` will ever be a valid math-expression, and it _is_ a popular tool, so it shouldn't be treated as a math expression (whether or not it's on the path).

**Comment by jntrnr** [comment] 2022-04-07 02:02
Can you see if https://github.com/nushell/nushell/pull/5115 fixes the issue? There may be a couple related issues, but hopefully this improves some aspects.

**Comment by jntrnr** [comment] 2022-04-08 07:54
Going to go ahead and close this one, but please re-open it if the issue is still present in the latest main.

**Closed by jntrnr** 2022-04-08 07:54 UTC

**Comment by BatmanAoD** [comment] 2022-04-15 22:01
Can confirm it's fixed now!
