### ISSUE TITLE
ls -s to a different directory colors folders/files as symlinks if there is a symlink with the same name in pwd

### ISSUE THREAD

**Issue by 1256-bits** [nushell/nushell#10561] opened 2023-09-30 18:45 UTC
### Describe the bug

If in the current directory you're in you have a symlink
![image](https://github.com/nushell/nushell/assets/104160323/0a9d7b79-ce03-4c54-9f8f-d5c7fd516db3)
and you call ls -s to a different directory that has a file/folder with the same name (doesn't matter if it links to this exact file/folder or not), the aforementioned file/folder will be colored as a symlink
![image](https://github.com/nushell/nushell/assets/104160323/ba777a6f-d9da-437e-9b80-d7b4bb1c9b29)

### How to reproduce

1. Create a symlink, e.g.
```
  cd ~/test
  ls -s ~/Downloads Downloads
 ```
2. Call ls -s to a directory where the file/folder with identical name is located
```
ls -s ~
```

### Expected behavior

Color the folder/file according to LS_COLORS

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.84.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (Arch Linux rust 1:1.71.1-1) |
| cargo_version      | cargo 1.71.1                                                     |
| build_time         | 2023-08-23 02:21:39 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment] 2023-09-30 18:51
This is a dupe of #4319 and probably others and is the reason I wrote https://github.com/nushell/nushell/pull/9994. But I'm not sure that'll ever land since it changes some internal things.

**Comment by amtoine** [comment] 2023-10-01 11:40
closing in favor of #4319 :wink: 

feel free to reopen and tweak the issue a bit if there is more to this duplicate :relieved:

**Closed by amtoine** 2023-10-01 11:40 UTC
Labels: needs-triage
