### ISSUE TITLE
Gaps in 

### ISSUE THREAD

**Issue by 0x4d6165** [nushell/nushell#10148] opened 2023-08-29 23:25 UTC
### Describe the bug

Hi I'm not sure if this is a bug in foot or nushell but this only happens in nushell. If the window size changes while the shell is running a large gap appears between the last and current prompt.

### How to reproduce

1. Set default shell in .config/foot/config.ini
2. Open foot terminal and thus, nushell
3. Resize window

### Expected behavior

No strange gap between the prompts. the new prompt should appear right under the old prompt.

### Screenshots

![shows the bug](https://i.imgur.com/7vE7SEX.png)

### Configuration

| key                | value                                         |
| ------------------ | --------------------------------------------- |
| version            | 0.84.0                                        |
| branch             |                                               |
| commit_hash        |                                               |
| build_os           | linux-x86_64                                  |
| build_target       | x86_64-unknown-linux-gnu                      |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23)           |
| rust_channel       | stable-x86_64-unknown-linux-gnu               |
| cargo_version      | cargo 1.72.0 (103a7ff2e 2023-08-15)           |
| build_time         | 2023-08-29 13:37:30 -07:00                    |
| build_rust_channel | release                                       |
| allocator          | standard                                      |
| features           | dataframe, default, sqlite, trash, which, zip |
| installed_plugins  |                                               |

**Comment by fdncred** [comment] 2023-08-29 23:33
dupe of https://github.com/nushell/nushell/issues/8213

**Closed by fdncred** 2023-08-29 23:33 UTC
Labels: needs-triage
