### ISSUE TITLE
feat: add `trap` command for handling signals

### ISSUE THREAD

**Issue by WieeRd** [nushell/nushell#10724] opened 2023-10-15 16:06 UTC
### Related problem

Following the example in the [cookbook](https://www.nushell.sh/cookbook/ssh_agent.html), I added a snippet that launches `ssh-agent` in my `env.nu`.
The problem is that `ssh-agent` does not automatically kill itself when nushell terminates.
It needs to be explicitly killed with `ssh-agent -k` or `kill $env.SSH_AGENT_PID`.
If not, it can lead to a bunch of "dangling" `ssh-agent` processes accumulating over time.
(try `ps | where name == ssh-agent`)

### Describe the solution you'd like

An addition of `$env.config.hooks.pre_termination` would be an elegant solution to this.
I think what it does is pretty clear from the name.

```nu
$env.config = {
    hooks: {
        pre_termination: [
            { ssh-agent -k }
        ]
    }
}
```

### Describe alternatives you've considered

`$ man ssh-agent`
> The agent starts a command under which its environment variables are exported, for example **ssh-agent xterm &**.  When the command terminates, so does the agent.

Running nushell with `ssh-agent nu` will automatically inherit the required environment variables, and the agent will terminate when nushell does. I changed the shell command of my terminal config to this and using it as a workaround for now.

**Comment by sholderbach** [comment] 2023-10-15 17:21
Design wise there is a question how much code we want to execute when you try to force the shell to terminate, to not stall the system. Should there be a timeout or immediate abort for any unhandled error?

**Comment by WieeRd** [comment] 2023-10-15 23:48
I think we can just leave it up to the users with extra config key to decide for themselves, depending on how important the cleanup job is. Default timeout of `1sec` sounds reasonable to me.

**Comment by amtoine** [comment] 2023-10-16 16:29
either way, with or without timeout, i love this idea and would definitely kill my *SSH agent* with this kind of hook :muscle:

**Comment by WieeRd** [comment] 2023-10-17 12:59
I did some more research, and came across the `trap` command.
It's a POSIX standard command, and I can confirm it works on both Bash and Zsh.

Basically, it's a shell command that can add handler to each signal with `trap 'command' SIGNAL`.
The exact usage is described in the [man page] and `trap --help` on Bash.

![image](https://github.com/nushell/nushell/assets/59733058/313d36e1-27dc-4290-b4d7-e3344e2afb45)

I added a handler `echo 42` to an interrupt signal and as you can see, Bash prints out 42 when I press Ctrl+C.
Similarly, the `EXIT` signal can be used as the `pre_termination` hook I initially requested.

```nu
trap 'ssh-agent -k' EXIT
```

## How about implementing `trap` as an internal command of Nushell?

We have closures, so we can use it instead of command string to make it more nu-style and easier to add complex handlers.

```nu
trap { ssh-agent -k } EXIT
```

[`$ man trap`][man page]
> The trap command with no operands shall write to standard output a list of commands associated with each condition.

```text
$ trap
╭───┬────────┬────────────────╮
│ # │ signal │    handler     │
├───┼────────┼────────────────┤
│ 0 │ SIGINT │ echo 42        │
│ 1 │ EXIT   │ <Closure 1696> │
╰───┴────────┴────────────────╯
```

[man page]: https://man7.org/linux/man-pages/man1/trap.1p.html

**Comment by amtoine** [comment] 2023-10-17 16:31
i like this idea too, it's probably even better because more powerful and versatile :open_mouth:

**Comment by sholderbach** [comment] 2023-10-18 21:28
With the pivot in the issue this becomes a duplicate of #8360

**Closed** 2024-01-02 15:55 UTC
Labels: enhancement, needs-design, configuration, hooks, duplicate, new-command
