### ISSUE TITLE
[Alacritty/Windows] `ctrl-c` a process launched in `nushell` kills the terminal

### ISSUE THREAD

**Issue by midnightexigent** [nushell/nushell#3937] opened 2021-08-18 12:26 UTC
### Describe the bug

Interestingly, when `nu` is spawned from a parent shell (eg. `powershell`), the problem doesn't occur  

### How to reproduce

1. in `alacritty.yml`, set the shell to `nu`
2. open an alacritty window
3. start any process (eg. `sleep 10sec`)
4. `ctrl-c` to interrupt it

### Expected behavior

I expect the process to stop without killing the parent terminal 

### Configuration

```
version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                      Column1
────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.35.0
  1 │ short_commit       │ bc682066
  2 │ commit_hash        │ bc682066d8eb756727c38d98ae58a34dd9cb3b38
  3 │ commit_date        │ 2021-08-03 08:01:09
  4 │ build_os           │ windows-x86_64
  5 │ rust_version       │ rustc 1.54.0 (a178d0322 2021-07-26)
  6 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
  7 │ cargo_version      │ cargo 1.54.0 (5ae8d74b3 2021-06-22)
  8 │ pkg_version        │ 0.35.0
  9 │ build_time         │ 2021-08-03 08:46:53
 10 │ build_rust_channel │ release
 11 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
 12 │ installed_plugins  │
────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

**Comment by fdncred** [comment] 2021-08-18 13:40
Is `ctrlc_exit` set to `false` in your `config.toml`? If not, try it to see if it changes the behavior. You'll have to quit out of nushell and restart to get the config change to apply. The config file is at `$nu.config-path`.  I'm not sure right now what our defaults are. LOL.

**Comment by midnightexigent** [comment] 2021-08-18 13:48
it didn't change the behavior 

```
~
❯ config
───┬────────────┬─────────────────
 # │ ctrlc_exit │     prompt
───┼────────────┼─────────────────
 0 │ false      │ starship prompt
───┴────────────┴─────────────────
```

**Comment by fdncred** [comment] 2021-08-18 21:36
I'm not sure then. We've had people report similar issues before but it's usually what I said with the ctrlc_ext. You might search the issues repo to see what others have found.

**Comment by midnightexigent** [comment] 2021-09-11 15:26
This might be due to the fact that **nushell doesn't create a new process group when spawning a process**

There was a similar [issue](https://github.com/zellij-org/zellij/commit/e477f3b5cd0653155845eb80f923090bccf6249e) when using the [zellij multiplexer](https://github.com/zellij-org/zellij) with `nushell`

**Comment by hunger** [comment] 2022-01-03 12:05
Same issue here, but with nushell 0.42.0 build with `--features extra`.

For me `ctrlc` is actually listed as a feature, but I can not spot it in `config`.

**Comment by fdncred** [comment] 2022-01-03 13:25
does the same problem exist in `engine-q`?

**Comment by hunger** [comment] 2022-01-04 12:00
How do I test that?

**Comment by fdncred** [comment] 2022-01-04 12:23
you try out our new [engine](https://github.com/nushell/engine-q) by compiling it and running it and then trying to reproduce the problem.

**Comment by hunger** [comment] 2022-01-05 10:18
I narrowed down the problem a bit: It happens only when using nu as a shell in a systemd-nspawn container directly!

`machinectl shell /path/to/machine/dir /usr/bin/nu` has the Ctrl-C problem. Doing `machinectl shell /path/to/machine/dir /usr/bin/bash` and then starting `nu` in bash works fine.

`engine-q` has exactly the same behavior as `nu` in this regard: It works fine when any other shell has been launched in the nspawn container before but quits when `Ctrl-C` is sent to it and it is the first shell in that container.

**Comment by midnightexigent** [comment] 2022-01-20 10:34
This is no longer happening in 0.43.0

```console
❯ version | pivot
────┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                       Column1
────┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.43.0
  1 │ short_commit       │ 4e8e0386
  2 │ commit_hash        │ 4e8e03867c87307d536369a20dbe81491666ee51
  3 │ commit_date        │ 2022-01-18 17:51:21 +00:00
  4 │ build_os           │ windows-x86_64
  5 │ rust_version       │ rustc 1.58.0 (02072b482 2022-01-11)
  6 │ rust_channel       │ stable-x86_64-pc-windows-msvc
  7 │ cargo_version      │ cargo 1.58.0 (7f08ace4f 2021-11-24)
  8 │ pkg_version        │ 0.43.0
  9 │ build_time         │ 2022-01-18 18:21:27 +00:00
 10 │ build_rust_channel │ release
 11 │ features           │ ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
 12 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post,
    │                    │ ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
────┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────

```

**Comment by hustcer** [comment] 2022-03-10 11:50
@hunger Can you try again on the latest main branch? Seems fine for me.

**Comment by hunger** [comment] 2022-03-10 12:35
I stil, have that issue with nu at version 44.

I run nu in a systemd-nspawn container, start gitk and hit Ctrl-C. Nu quits, the container quits and I am in the shell I ran systemd-nspawn in.

**Comment by fdncred** [comment] 2022-03-10 12:47
what about in version 0.59.1? I don't think we're going to fix 0.44 since we're so close to releasing 0.60.

**Comment by hustcer** [comment] 2022-03-10 12:48
latest main will be nu 0.59.1

**Comment by hunger** [comment] 2022-03-10 13:41
Sorry for that, I just did `cargo install --force nu`and that installs version 0.44. I'll check the website for instructions on how to get a newer version

**Comment by fdncred** [comment] 2022-03-10 13:47
no worries - the newest version is in beta. You can read about it here https://www.nushell.sh/blog/2022-03-01-nushell_0_59.html. You can also compile it from the latest main branch of our repo.

**Comment by hunger** [comment] 2022-03-10 14:37
I grabbed the binaries from the blog post you linked to: Exactly the same behavior:-/

```
Connected to machine barfoo. Press ^] three times within 1s to exit session.
/home/dev〉version | transpose                                                                                                                                                                                            03/10/2022 03:35:50 PM
╭────┬────────────────────┬──────────────────────────────────────────╮
│ #  │      column0       │                 column1                  │
├────┼────────────────────┼──────────────────────────────────────────┤
│  0 │ version            │ 0.59.0                                   │
│  1 │ branch             │ main                                     │
│  2 │ short_commit       │ 42f1874a                                 │
│  3 │ commit_hash        │ 42f1874a3aae2e3bc3c669cb0aac0132a586ea24 │
│  4 │ commit_date        │ 2022-03-01 13:05:29 +00:00               │
│  5 │ build_os           │ linux-x86_64                             │
│  6 │ rust_version       │ rustc 1.59.0 (9d1b2106e 2022-02-23)      │
│  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu          │
│  8 │ cargo_version      │ cargo 1.59.0 (49d8809dc 2022-02-10)      │
│  9 │ pkg_version        │ 0.59.0                                   │
│ 10 │ build_time         │ 2022-03-01 13:31:35 +00:00               │
│ 11 │ build_rust_channel │ release                                  │
│ 12 │ features           │ dataframe, default, trash, which, zip    │
│ 13 │ installed_plugins  │                                          │
╰────┴────────────────────┴──────────────────────────────────────────╯
/home/dev〉gitk                                                                                                                                                                                                           03/10/2022 03:36:00 PM
^C
Connection to machine barfoo terminated.
tobias@foobar:~ ➜ 
```

**Comment by hunger** [comment] 2022-03-14 08:32
It does _not_ happen when I run bash inside the container and start nu in that bash shell. It behaves as espected then: Ctrl-C kills gitk and returns me into nu.

That's why I suspect (without any understanding of the problem space:-) that this might be some terminal setup issue or something: If the terminal is set up correctly (by some other shell) then it works.

**Comment by fdncred** [comment] 2022-03-14 19:49
I have alacritty for windows v10.1 with nu.exe set as the shell and don't have any exit issues. I can hit ctrl-c a dozen times in rapid succession without exiting. It doesn't stop the propmt scripts from running, because i'm hitting ctrl-c so fast but it comes back on the next enter.

![image](https://user-images.githubusercontent.com/343840/158249639-4645e751-7e01-4872-af1d-978c44b29cb7.png)

**Comment by hunger** [comment] 2022-03-14 22:04
I have no clue about shells and terminal, but I suspect that is "just" a "set up the terminal" issue.

Windows and Linux are two very different beasts in that regard. I am not surprised that it works in windows. It also works in Linux -- provided it is started inside another shell like bash or fish, even in a container. Started in a container without bash and fish? Nope, it does not work there.

Is there anything I can do to help reproduce the issue?

**Comment by fdncred** [comment] 2022-03-14 22:47
I don't have a way really to test this on Linux. I could try on WSL2 but I'm not sure that would be the same.

**Comment by midnightexigent** [comment] 2022-03-14 23:10
@fdncred does nushell create a new process group when spawning a new process ? If not, then all processes are in the same foreground group, so ctrlc sends the signal to every member of the group -- the behavior is normal

**Comment by midnightexigent** [comment] 2022-03-14 23:12
> This might be due to the fact that **nushell doesn't create a new process group when spawning a process**
> 
> There was a similar [issue](https://github.com/zellij-org/zellij/commit/e477f3b5cd0653155845eb80f923090bccf6249e) when using the [zellij multiplexer](https://github.com/zellij-org/zellij) with `nushell`

Up

**Comment by fdncred** [comment] 2022-03-14 23:45
> @fdncred does nushell 0.59 create a new process group when spawning a new process ? If not, then all processes are in the same foreground group, so ctrlc sends the signal to every member of the group -- the behavior is normal

No, I don't believe nushell creates a process group as it is starting.

**Comment by midnightexigent** [comment] 2022-03-14 23:58
sooo I guess that's what's causing the problem.. ?

**Comment by fdncred** [comment] 2022-03-15 00:44
I'd like to be able to reproduce the problem before saying that's the diagnosis.

**Comment by midnightexigent** [comment] 2022-03-15 09:53
idk about reproducing it with @hunger's setup, but, you might be able to reproduce with zellij 0.14, more details: https://github.com/zellij-org/zellij/issues/615#issue-941281441

**Comment by fdncred** [comment] 2022-03-15 17:25
i can't reproduce it on linux either
![image](https://user-images.githubusercontent.com/343840/158435784-d5acdab0-7975-41ce-8196-c3b4afce1345.png)

**Comment by hunger** [comment] 2022-03-16 08:05
Did younuse zellij during your test? Or a container?

Nu works fine in a bog-standard terminal on Linux for me as well.

**Comment by fdncred** [comment] 2022-03-16 11:26
As I said above, I used WSLg.

**Comment by midnightexigent** [comment] 2022-03-16 13:43
hmm, very much not expert here, but if understand correctly, nushell rather needs to create a pid group for every process it spawns, that way ctrlc doesn't propagate to nushell itself. 

From the explanation of the folks at zellij when dealing with the issue

> nushell doesn't create a new process group when spawnning a process,
so all processes including the ones spwanned by us are in the same
foreground group. So if kernel will send signal to every member of this
group.

I am not at all familiar with the internals, but if a core developer directs me to the crate/module that handles that, I can try to submit a PR

**Comment by midnightexigent** [comment] 2022-03-16 21:51
I am very much spitballing, this is solely based on my understanding of the small explanation by the zellij contributor (aka paragraph I quoted in my previous comment)

My understanding is that zellij 0.14 spawned a pane and shell as part of the same process group. Since nushell doesn't create a process group for its child processes, any command spawned by nushell is part of the same foreground group as nushell itself as well as its parent zellij pane. `ctrlc`ing that command propagates the interruption signal to the zellij pane that holds the nushell session. 

To circumvent that, they made it so the shell is part of its own process group, separating the parent pane from its shell. 

> Point me to how other shells do this and I'll take a look

idk... the same explanation by the zellij contributor makes it sound like other shells do it "nushell doesn't create a new process group when spawnning a process"

**Comment by midnightexigent** [comment] 2022-03-16 23:08
just did some testing, here's what I found

- zellij 0.14 & nu 0.44
```console
# launch nu in zellij and make it sleep 
$ env SHELL=nu zellij setup --clean
Welcome to Nushell 0.44.0 (type 'help' for more info)
/home/midnightexigent> ^sleep 8000

# on a separate console

$ pgrep -a sleep
57217 sleep 8000

# find the group id of the sleep process
$ ps -o pid,ppid,pgid,sid,cmd 57217
    PID    PPID    PGID     SID CMD
  57217   57069   57068   57068 sleep 8000

# list the processes associated with that group id
$ pgrep --pgroup=57068 -a
57068 /home/midnightexigent/.cargo/bin/zellij --server /run/user/1000/zellij/0.14.0/ubiquitous-addition
57069 /usr/bin/nu
57217 sleep 8000
```

process spawned by nushell finds itself in the same foreground group as the zellij session and nushell itself

- zellij 0.26.1 & nu 0.44 
```console
# launch nu in zellij and make it sleep 
$ env SHELL=nu zellij setup --clean
Welcome to Nushell 0.44.0 (type 'help' for more info)
/home/midnightexigent> ^sleep 8000

# on a separate shell
$ pgrep -a sleep
57534 sleep 8000

$ ps -o pid,ppid,pgid,sid,cmd 57534
    PID    PPID    PGID     SID CMD
  57534   57478   57478   57478 sleep 8000

$ pgrep --pgroup=57478 -a
57478 /usr/bin/nu
57534 sleep 8000
```

this time nu and zellij session are in seperate process groups

-  zsh 
```console
# put zsh to sleep
$ sleep 9000

# on a separate console
$ pgrep -a sleep
57968 sleep 9000
$ ps -o pid,ppid,pgid,sid,cmd 57968
    PID    PPID    PGID     SID CMD
  57968   51484   57968   51484 sleep 9000
$ pgrep --pgroup=57968 -a
57968 sleep 9000
```

**zsh isn't in the same process group as the process it spawned**

**Comment by midnightexigent** [comment] 2022-03-18 15:23
Yeah so my last comment is no too far off from what other shells do. From [tutorial on how to write a shell in C](https://brennan.io/2015/01/16/write-a-shell-in-c/)

>  First, an existing process forks itself into two separate ones. Then, the child uses `exec()` to replace itself with a new program. The parent process can continue doing other things, and it can even keep tabs on its children, using the system call `wait()`.

```c
int lsh_launch(char **args)
{
  pid_t pid, wpid;
  int status;

  pid = fork();
  if (pid == 0) {
    // Child process
    if (execvp(args[0], args) == -1) {
      perror("lsh");
    }
    exit(EXIT_FAILURE);
  } else if (pid < 0) {
    // Error forking
    perror("lsh");
  } else {
    // Parent process
    do {
      wpid = waitpid(pid, &status, WUNTRACED);
    } while (!WIFEXITED(status) && !WIFSIGNALED(status));
  }

  return 1;
}
```

**Comment by hunger** [comment] 2022-03-18 16:12
I am not an expert when it comes to writing shells, but this is so low level that I would be seriously surprised if there was a good cross-platform solution for this:-/

**Comment by midnightexigent** [comment] 2022-03-18 16:57
I'd leave it untouched on windows since the problem is no longer happening there. I don't think the concepts of process group or kernel signals translate from unix to windows very well either way

**Comment by ErichDonGubler** [comment] 2022-04-15 20:24
I'm reproducing this issue (or one very similar) with Windows Terminal and the `sleep` command; if I hit <kbd>CTRL</kbd> + <kbd>C</kdb> during a `sleep 10sec` invocation, then it ends up terminating the entire shell:

![image](https://user-images.githubusercontent.com/658538/163628649-97627cb5-a275-4a6d-b49e-27216f05ec02.png)

Is this the same issue? Should I create another one?

**Comment by fdncred** [comment] 2022-04-16 15:42
No issues in WezTerm on Mac.
<img width="585" alt="Screen Shot 2022-04-16 at 10 41 10 AM" src="https://user-images.githubusercontent.com/343840/163681487-2317f3a9-b50f-4cac-8fbb-f39357b63bfd.png">

**Comment by rgwood** [comment] 2022-10-23 06:02
> I'm reproducing this issue (or one very similar) with Windows Terminal and the sleep command

I can't reproduce this in Windows Terminal on v0.70.1, guessing it's been fixed.

Is anyone still having issues with `ctrl+c` crashing?

**Comment by ChrisDenton** [comment] 2023-03-22 21:11
I think the [HandlerRoutine callback](https://learn.microsoft.com/en-us/windows/console/handlerroutine) is relevant here. Specifically, using [SetConsoleCtrlHandler](https://learn.microsoft.com/en-us/windows/console/setconsolectrlhandler) to set one.

**Comment by rgwood** [comment] 2023-03-27 22:43
I still can't reproduce this on Windows, unfortunately. `sleep 5sec` then `ctrl+c` does not terminate Nu for me in Windows Terminal (1.17.1023) or Alacritty (0.11.0). Launching Nu from PowerShell does not seem to make a difference.

@ChrisDenton I believe we're already calling `SetConsoleCtrlHandler` indirectly using the `ctrlc` crate: https://github.com/nushell/nushell/blob/7ec5f2f2eb33e517d2390b1009bae76b5dbb9666/src/signals.rs#L12-L14

**Comment by jntrnr** [comment] 2023-08-09 18:40
This issue is quite strange. Seemingly, no one on the nushell team has been able to reproduce this, which is leading me to think that there are other configuration components involved.

As no one on the team has been able to reproduce this, I'm going ahead and closing. If folks who are experiencing this are able to come up repro steps, please re-open and post the repro steps.

**Closed by jntrnr** 2023-08-09 18:40 UTC
Labels: :bug:  bug, investigate, signal-cancel

**Comment by kouhe3** [comment] 2023-08-24 03:06
```
version | transpose                                                                           08/24/2023 10:48:51 AM
╭────┬────────────────────┬──────────────────────────────────────────╮
│  # │      column0       │                 column1                  │
├────┼────────────────────┼──────────────────────────────────────────┤
│  0 │ version            │ 0.83.1                                   │
│  1 │ branch             │                                          │
│  2 │ commit_hash        │ bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd │
│  3 │ build_os           │ windows-x86_64                           │
│  4 │ build_target       │ x86_64-pc-windows-msvc                   │
│  5 │ rust_version       │ rustc 1.69.0 (84c898d65 2023-04-16)      │
│  6 │ rust_channel       │ 1.69.0-x86_64-pc-windows-msvc            │
│  7 │ cargo_version      │ cargo 1.69.0 (6e9a83356 2023-04-12)      │
│  8 │ build_time         │ 2023-07-30 18:18:41 +00:00               │
│  9 │ build_rust_channel │ release                                  │
│ 10 │ allocator          │ standard                                 │
│ 11 │ features           │ default, sqlite, trash, which, zip       │
│ 12 │ installed_plugins  │                                          │
╰────┴────────────────────┴──────────────────────────────────────────╯

```


https://github.com/nushell/nushell/assets/25522053/1ef79b38-b3a5-4647-a613-968acf860f52

**Comment by jupjohn** [comment] 2024-01-12 01:16
I've been experiencing this for the past few months, and might have a solution for anyone who installed via a package manager like chocolatey or scoop (assuming scoop will do the same thing).

My alacritty config was pointing at `C:\ProgramData\chocolatey\bin\nu.exe` which it turns out isn't the nu binary - it's a shim that then executes the real binary at `C:\Program Files\nu\bin\bu.exe`. After I changed alacritty to use the real binary, the problem disappeared 🎉 

Chocolatey generates these shims and I suspect they do some funky stuff around spawning that shell (although I'm not going to dig into it).
