### ISSUE TITLE
nushell has no way to provide multi-line commands with error handling

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#10856] opened 2023-10-27 21:57 UTC
### Describe the bug

I just got bit quite hard by wrapping a multiline external command with `()` only to find out that suppresses error handling.

Take this gist: https://gist.github.com/colemickens/bbee4161334849669b60e6db9e06a511

It produces different results from `run1` and `run2`. This was quite unexpected.

But worse, I don't see any other way of running mult-line commands in nushell without wrapping them in parenthesis, which prevents errors from bubbling up. 

To me, this is a grave, fatal flaw, as it stands. I need to be able to author scripts where I call external programs, and be able to format it across lines. The example I've provided is trivial and contrived, but I have many scripts where I'm inadvertently breaking error handling my using multi-line commands right now.

### How to reproduce

1. Take a long line of an external command.
2. Try to split it across lines.
3. Use the only facility I see available, wrapping the lines in `()`
4. Notice that it suppresses the error from bubbling.

### Expected behavior

Nushell provides a way to enter multiline commands that does not suppress error bubbling.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.86.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (built from a source tarball) |
| cargo_version      | cargo 1.73.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by colemickens** [comment] 2023-10-27 22:02
Hmm, @fdncred points out, indeed there might be a "better way to hold it". By making a list of the args, and then calling `./inner.sh $args`.

**Comment by colemickens** [comment] 2023-10-27 22:06
As @fdncred also points out, this only applies to external commands. But, also, I have never seen myself calling an internal command with so many args that I would care. Though, it still feels like something of a mental disparity. Though I have used the arglist, $args construction before, this one still threw me for a bit of a loop. Maybe that's my mistake for reaching for the parenthesis too quickly.

**Comment by amtoine** [comment] 2023-10-28 11:22
ooh actually, this is a good catch @colemickens :open_mouth: 

here are maybe clearer steps to reproduce :wink: 
> **Note**
> these commands should be run outside of a Git repo
- run without parentheses
```nushell
> git fetch --all --prune; print "ok"
fatal: not a git repository (or any of the parent directories): .git
```
- the error bubbles up and `ok` is not printed
- run without parentheses, not even on multiple lines
```nushell
> (git fetch --all --prune); print "ok"
fatal: not a git repository (or any of the parent directories): .git
ok
```
- the error does not bubble up and `ok` is printed

**Comment by colemickens** [comment] 2023-10-28 17:33
another case, similar, maybe just the same or very related bug:

```
╭ zeph  ~/code/nixcfg  823ms
╰─▶ ssh $"cole@(tailscale ip --4 thishostdoesnotexist)"
error looking up IP of "thishostdoesnotexist": lookup thishostdoesnotexist on 127.0.0.53:53: server misbehaving
ssh: Could not resolve hostname : Name or service not known
```

it fell through to ssh even though the inner command failed.

**Comment by tv42** [comment] 2023-12-11 21:16
This might be related to / duplicate of #10633

**Closed** 2024-09-07 06:44 UTC
Labels: :bug:  bug, external-commands, error-handling
