### ISSUE TITLE
Aliases not working as described in book

### ISSUE THREAD

**Issue by medakk** [nushell/nushell#3032] opened 2021-02-08 21:38 UTC
**Describe the bug**
I'm trying to use [aliases](https://www.nushell.sh/book/aliases.html), but the commands on that page do not work.

**To Reproduce**
```
/home/karthik/Documents/projects/nushell(main)> alias ls-names [] { ls | select name }
error: Type Error
   ┌─ shell:34:16
   │
34 │ alias ls-names [] { ls | select name }
   │                ^^ Expected =, found []
```

```
/home/karthik/Documents/projects/nushell(main)> alias e [msg] { echo $msg }
error: Type Error
   ┌─ shell:35:9
   │
35 │ alias e [msg] { echo $msg }
   │         ^^^^^ Expected =, found [msg]
```

```
/home/karthik/Documents/projects/nushell(main)> config path | vi $it
error: Variable not in scope
   ┌─ shell:36:18
   │
36 │ config path | vi $it
   │                  ^^^ missing '$it' (note: $it is only available inside of a block)
```

Just `alias`:

```
/home/karthik/Documents/projects/nushell(main)> alias
error: Type Error
  ┌─ shell:1:1
  │
1 │ alias
  │ ^^^^^ Expected alias, found alias
```

**Expected behavior**
Either the doc is wrong, or the command. I tried `help commands | where name =~ alias` but I guess alias is not a "command"?

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                      Column1                                       
────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.26.1                                                                             
  1 │ branch             │ main                                                                               
  2 │ short_commit       │ 233161d5                                                                           
  3 │ commit_hash        │ 233161d56ed909e1666b05cdbef5c1e165d0c13d                                           
  4 │ commit_date        │ 2021-02-07 15:10:06                                                                
  5 │ build_os           │ linux-x86_64                                                                       
  6 │ rust_version       │ rustc 1.49.0 (e1884a8e3 2020-12-29)                                                
  7 │ rust_channel       │ stable (default)                                                                   
  8 │ cargo_version      │ cargo 1.49.0 (d00d64df9 2020-12-05)                                                
  9 │ pkg_version        │ 0.26.1                                                                             
 10 │ build_time         │ 2021-02-07 19:17:24                                                                
 11 │ build_rust_channel │ release                                                                            
 12 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip 
────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by fdncred** [comment] 2021-02-08 21:52
Dupe of #3020

**Comment by medakk** [comment] 2021-02-08 23:13
I see that #3020 is closed. Should this issue remain open?

**Comment by fdncred** [comment] 2021-02-09 13:35
ya, we should probably close it. we're close to getting the docs updated.

**Closed by fdncred** 2021-02-09 13:35 UTC
