### ISSUE TITLE
Piping and alias, which contains arguments or flags and then using tab for autocompletion causes panic

### ISSUE THREAD

**Issue by supericqicq3** [nushell/nushell#8220] opened 2023-02-26 09:43 UTC
### Describe the bug

I am using aliases to commands with flags basically in every shell I use, everywhere it worth nothing to make alias to command with arguments (here as example of reproduction I use `ls -la` as a command). But if I use pipe and then try to get autocompletion for commands what I can use here, it just panics

### How to reproduce

1. Create an alias, example: alias la = ls -la
2. Use pipe here: la | 
3. Press tab
4. See panic message

### Expected behavior

Showing list of builtin or external commands

### Configuration

# This error persists in both builds

## First: I built it myself from crates.io
| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-02-25 00:28:45 +03:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

## Second: from archlinux repo
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

### Additional context

Panic message:

thread 'main' panicked at 'Can't create a Span whose end < start, start=8, end=5', /home/ljdswer/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.16.0/src/completion/base.rs:18:9
stack backtrace:
   0:     0x55eacdf9a2fe - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
   1:     0x55eacd454e5e - core::fmt::write::h032658c119c720d7
   2:     0x55eacdf92ea5 - std::io::Write::write_fmt::h299fc90dfae41c0d
   3:     0x55eacdf9a0d5 - std::sys_common::backtrace::print::had745c0a76b8b521
   4:     0x55eacdf9bdef - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
   5:     0x55eacdf9bb64 - std::panicking::default_hook::h1cc3af63455a163c
   6:     0x55eacdf9c494 - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
   7:     0x55eacdf9c226 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
   8:     0x55eacdf9a82c - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
   9:     0x55eacdf9bf62 - rust_begin_unwind
  10:     0x55eacd3ebfd3 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
  11:     0x55eacde51f66 - reedline::completion::base::Span::new::h5e96c9b3cf0b9d20
  12:     0x55eacd579208 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::he64efae89bfc7fde
  13:     0x55eacd5a87a2 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold::hc681fc40a86a5cf1
  14:     0x55eacd565d03 - alloc::vec::Vec<T,A>::extend_trusted::h41d7a3a00be9566c
  15:     0x55eacd563a2f - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::hdf1cfe697d424602
  16:     0x55eacd57ce11 - nu_cli::completions::command_completions::CommandCompletion::complete_commands::h99ea8996c9956e6c
  17:     0x55eacd57dad4 - <nu_cli::completions::command_completions::CommandCompletion as nu_cli::completions::base::Completer>::fetch::h8d91eaf8e4a92464
  18:     0x55eacd5a09f5 - nu_cli::completions::completer::NuCompleter::process_completion::h00ef404790f0cbfc
  19:     0x55eacd5a2510 - nu_cli::completions::completer::NuCompleter::completion_helper::h00c4d865a0fa617c
  20:     0x55eacd5a3d4c - <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete::hf4bc74828e9a803b
  21:     0x55eacde5ddd5 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values::h7248981e9e8b5b7b
  22:     0x55eacde58f7d - reedline::engine::Reedline::handle_editor_event::h7d37ec06369a484e
  23:     0x55eacde58ad2 - reedline::engine::Reedline::handle_editor_event::h7d37ec06369a484e
  24:     0x55eacde57572 - reedline::engine::Reedline::read_line::h6734a3e6aba0eb1f
  25:     0x55eacd58fc3c - nu_cli::repl::evaluate_repl::h62aa1c132c4c65c3
  26:     0x55eacd54fe64 - nu::run::run_repl::hc0789aaf110898b7
  27:     0x55eacd55d273 - nu::main::h2acc5f7771725870
  28:     0x55eacd55da71 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbf7ee8a60bd89994
  29:     0x55eacd55ea9f - std::rt::lang_start::{{closure}}::h4fe8959a342e83fa
  30:     0x55eacdf8c9dc - std::rt::lang_start_internal::hd16e6ff7bf05a444
  31:     0x55eacd55d885 - main
  32:     0x7f8568354790 - <unknown>
  33:     0x7f856835484a - __libc_start_main
  34:     0x55eacd411fb5 - _start
  35:                0x0 - <unknown>

**Comment by fdncred** [comment] 2023-02-26 12:52
dupe of #7648

**Comment by sholderbach** [comment] 2023-02-27 10:23
Thanks for the detailed report with backtrace.

Should be resolved by #8123

**Closed by sholderbach** 2023-02-27 10:23 UTC
