### ISSUE TITLE
setting nu 0.60 as default shell (on linux) somehow breaks dmenu_run script

### ISSUE THREAD

**Issue by midnightexigent** [nushell/nushell#5002] opened 2022-03-28 05:21 UTC
I just tried `chsh -s /bin/nu`, after logging out/in, when I try to run the `dmenu_run` script (via keybinding) my entire desktop (X11 session) freezes

However, when default shell is something else (eg. zsh) and I try to run `dmenu_run` from a `nushell` prompt, everything works fine

**Comment by fdncred** [comment] 2022-03-28 11:26
I'm not familiar with `dmenu_run` but since it creates some type of menu, I wonder if it's interfering with crossterm and the menus we create with it or maybe line editing all together?

**Comment by midnightexigent** [comment] 2022-03-28 15:48
when the problem occurs nushell isn't being ran inside of a terminal. it's a keybinding which invokes an external command (the `dmenu_run`). so the window manager tries to spawn a headless nushell, which in turn runs `dmenu_run`

**Comment by fdncred** [comment] 2022-03-29 11:51
what does a headless nushell look like? is that like `nu -c ^dmenu_run`?

**Comment by midnightexigent** [comment] 2022-04-27 12:01
Actually scratch that, the display manager I am using spawns the `dmenu_run` uses the system `sh`. 

https://github.com/leftwm/leftwm/blob/eaf531d1943a6a90edc1876c7bca0627247a65f1/leftwm-core/src/utils/child_process.rs#L300-L313

I think there's a bug on their side, I need to take a closer look at this

**Comment by lokegustafsson** [comment] 2022-05-04 21:53
I have the same issue. Not sure why it happens, but it can have an easy minimal example. `dmenu_run` is is a shell script, essentially
```
#!/bin/sh
dmenu_path | dmenu "$@" | ${SHELL:-"/bin/sh"} &
```
I can reproduce this without dmenu by
1. Running `sh` interactively (within `nu`?).
2. Here doing `sh ./foo.sh` or `./foo.sh` (running `sh -c './foo.sh' does NOT reproduce)
3. Where `foo.sh` is a shell script like
```
echo foobar | ${SHELL:-"/bin/sh"} &
```
This results in `Error: Os { code: 5, kind: Uncategorized, message: "Input/output error" }` being printed in an infinite busy loop.
I cannot strictly connect this to nu, but I cannot imagine another rust program being involved in a headless shell running a command (which is what happens when dmenu_run is run by the window manager).

My window manager was started by bash, which was started by lightdm, which was started by systemd. I cannot see any way for nu being involved in program launching other than through being my login shell.

With `ctrl-d`, one can exit the shell even though the infinite printing is running. When running not just `sh`, but many nested shells, I still have to `ctrl-d` all the way until the terminal (alacritty) closes. At that point, the printing process exists (and stops using its whole cpu). I assume the same cannot really happen for a headless wm-launched shell, so it spins until logout.

Finally, this did not happen to me on 0.44. I am not sure about 0.60, but on 0.61 it happens.

**Comment by lokegustafsson** [comment] 2022-05-04 22:08
Oh, how ironic is it that what I though was a bug in nushell was really just me not being able to read posix shell :rofl:

`${SHELL:-"/bin/sh"}` is `$SHELL`, but equal to `/bin/sh` if this is not set. Since `$SHELL=nu`, this runs nu:
```
echo foobar | nu &
```
This works when run interactively, but not when run though a file. I don't know why, but the obvious workaround is to not use nu.

I should sleep now, I am clearly not thinking straight :)

**Comment by lokegustafsson** [comment] 2022-05-04 22:24
I am now launching
```
dmenu_path | dmenu -fn 'monospace:size=11' -nb '#eee8d5' -nf '#586e75' -sb '#fdf6e3' -sf '#002b36' | sh &
```
from my wm, and everything is working.

**Comment by midnightexigent** [comment] 2022-05-07 09:58
Oh nice catch @lokegustafsson ! 

I solved my problem by changing the command to `SHELL=/bin/sh dmenu_run`

**Comment by hustcer** [comment] 2022-05-07 09:59
So can we close this issue?

**Comment by midnightexigent** [comment] 2022-05-07 10:08
fine by me

**Closed** 2022-05-07 12:09 UTC

**Comment by cosineblast** [comment] 2024-02-19 18:07
As a sidenote, another alternative is patching dmenu_run so it uses bash for the program lookup instead of nushell.

Running `sed -ri -e 's#\$\{SHELL:-"/bin/sh"\}#"$(which bash)"#g' /path/to/dmenu_run` is usually enough.

If you have dmenu installed through nix, you can do something like the following to get this modified version of dmenu.

```nix
      (pkgs.dmenu.overrideAttrs (oldAttrs: {
          pname = "dmenu-bash";
          postPatch = oldAttrs.postPatch + ''
          sed -ri -e 's#\$\{SHELL:-"/bin/sh"\}#"$(which bash)"#g' dmenu_run
          '';
          }))
```
