### ISSUE TITLE
Filenames with square brackets cause errors

### ISSUE THREAD

**Issue by takac** [nushell/nushell#10244] opened 2023-09-05 20:26 UTC
### Describe the bug

File names with square brackets are treated as globs and cannot be literally referenced as far as I can tell.

```
touch '[hello].txt'
```
```
ls '[hello].txt'
```
```
Error:   × No matches found for [hello].txt
   ╭─[entry #14:1:1]
 1 │ ls '[hello].txt'
   ·    ──────┬──────
   ·          ╰── Pattern, file or folder not found
   ╰────
  help: no matches found
```

### How to reproduce

1. `touch '[hello].txt'`
2. `ls '[hello].txt'`

### Expected behavior

I expect to be able to `ls` a file with square brackets with escapes (e.g. `\[ \]`) or otherwise and that the completion uses the "right" string to reference the file.

### Configuration

```
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |
```

### Additional context

Other ways to get the same error:
```
ls $'[hello].txt'
ls '\[hello\].txt'
ls \[hello\].txt
```

There is a slightly different error when not in quotes:
```
ls [hello].txt
```
```
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #42:1:1]
 1 │ ls [hello].txt
   ·    ─────┬─────
   ·         ╰── expected non-[] value
   ╰────
```

**Comment by fdncred** [comment] 2023-09-05 20:41
Here's what we can do on the latest main branch. Not sure it works on the version you're using.
```
❯ touch '[hello].txt'
❯ ls '[[]hello[]].txt'
╭#┬───name────┬type┬size┬──modified──╮
│0│[hello].txt│file│16 B│a minute ago│
╰─┴───────────┴────┴────┴────────────╯
❯ open '[[]hello[]].txt'
now is the time
```
`[` and `]` are known glob patterns, so I think they currently have to be escaped this way.

**Comment by takac** [comment] 2023-09-05 20:52
Thanks! That does work on `main`. The completer/menu probably needs updating to use the right escape sequence.

There are so other oddities with `open` and the json which need exploring. Should I open a separate bugs for those in the comment above?

**Comment by fdncred** [comment] 2023-09-05 21:02
I'd like a more holistic solution myself. This escaping is just ugly and no one will really know to do it. Not sure what to do here exactly myself.

**Comment by amtoine** [comment] 2023-09-06 16:34
this looks possibly a duplicate of https://github.com/nushell/nushell/issues/9310, can you have a look @takac? :yum:

**Comment by takac** [comment] 2023-09-08 16:20
Yes they are related, or even duplicate. Seems like a more general issue than just `ls` or any other command as it's about globs.

**Closed** 2023-09-25 08:09 UTC
Labels: duplicate
