### ISSUE TITLE
Cannot abort long running commands

### ISSUE THREAD

**Issue by bmurphy1976** [nushell/nushell#641] opened 2019-09-11 02:10 UTC
If I'm running a command such as the following to scan a large number of folders:

```
ls **/*
```

I cannot abort the command by hitting ^C. I have to kill the entire nu process (usually by hitting ^Z and then killing it by pid).

**Comment by jonathandturner** [comment] 2019-09-11 02:11
This seems to be a duplicate of https://github.com/nushell/nushell/issues/403, but please reopen if it's not.

**Closed by jonathandturner** 2019-09-11 02:11 UTC
