### ISSUE TITLE
`ls | format '{name:'` produces infinitely long error message

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7211] opened 2022-11-23 14:33 UTC
### Describe the bug

See title. This message continues printing and prevents all Ctrl-C input from letting you regain control of the terminal, necessitating a restart of Nushell.

### How to reproduce

1. Enter `ls | format '{name:'`

### Expected behavior

Functional error message for incorrect format.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:03:36 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by Kangaxx-0** [comment] 2022-12-01 00:47
Do you have screenshot for the infinitely long error message? This is what I saw 

<img width="594" alt="image" src="https://user-images.githubusercontent.com/85712372/204938663-fdb6bd5d-e9e0-4d43-a984-ecbdcccef67c.png">

Also, Ctrl+C does not work if `nu` is default terminal/shell, I believe this is an ok behavior because the app panicked ?

**Comment by webbedspace** [comment] 2022-12-01 05:28
Here's some footage:
https://user-images.githubusercontent.com/83939/204973031-916e0666-1cf1-4a7d-a687-98c89bdc090c.mp4

**Comment by Kangaxx-0** [comment] 2022-12-01 06:24
Hard to see, what is your shell/terminal app? Is it native window ENV? I tried [Windows Terminal](https://learn.microsoft.com/en-us/windows/terminal/install) + Windows 11

**Comment by webbedspace** [comment] 2022-12-01 06:32
It's just Windows Terminal + Win 10…

**Comment by Kangaxx-0** [comment] 2022-12-01 16:50
If you use Powershell or cmd, then type `nu` and try to reproduce, will it be the different behavior, can terminal fall back instead of giving you infinite error ?

**Comment by webbedspace** [comment] 2022-12-01 16:57
https://user-images.githubusercontent.com/83939/205113374-c8fce34f-7355-4ea5-9fdd-cd94b756f116.mp4

**Comment by Kangaxx-0** [comment] 2022-12-01 17:42
It is super weird.. I do not have Windows 10, but if you provide me OS info, I could create an Azure VM and see what's going on
<img width="439" alt="image" src="https://user-images.githubusercontent.com/85712372/205122756-d11dd8f6-6ebb-4528-8918-e64df192b4fb.png">

**Comment by rgwood** [comment] 2022-12-01 17:59
I was also able to reproduce this.

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             | main                                     |
| commit_hash        | f71a45235a14e426410c079cd25347539731de41 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-01 09:23:26 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment] 2022-12-19 12:10
Should be fixed by #7522

**Closed by sholderbach** 2022-12-19 12:10 UTC
Labels: :bug:  bug, unhelpful-error
