### ISSUE TITLE
Second bar in closure literal parameter list is incorrectly highlighted as a pipe

### ISSUE THREAD

**Issue by 132ikl** [nushell/nushell#13183] opened 2024-06-20 01:09 UTC
### Describe the bug

When typing a closure on the command line, the closing bar/pipe character for the parameter list is highlighted as a bar (pink in my config) instead of in the closure color like the opening bar/pipe character is.

### How to reproduce

1. Type a closure literal with a parameter list with a non-zero number of parameters into the CLI

### Expected behavior

Highlight the closing bar/pipe character in the closure color

### Screenshots

![image](https://github.com/nushell/nushell/assets/8751613/14314a3b-e3ea-4564-8a25-7b9e47edf463)
from @fdncred:
![image](https://github.com/nushell/nushell/assets/8751613/6f8dc9cd-4598-4eb5-8383-3047fbbd29a7)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.94.3                                   |
| major              | 0                                        |
| minor              | 94                                       |
| patch              | 3                                        |
| branch             | makepkg                                  |
| commit_hash        | 34f2bcff8971898e54b35e5b691ad49b4a94248c |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-06-15 18:42:20 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  | clipboard                                |

**Comment by weirdan** [comment] 2024-08-26 04:18
Possible duplicate of #9562 (or least very likely related to).

**Comment by fdncred** [comment] 2024-08-26 11:30
Agreed. I put the images in #9562 for reference. Let's close this one.

**Closed by fdncred** 2024-08-26 11:30 UTC
Labels: :bug:  bug, syntax-highlighting, needs-triage
