### ISSUE TITLE
"error: External command failed" on compilation errors with gcc or nodejs in Windows 11

### ISSUE THREAD

**Issue by shans10** [nushell/nushell#4625] opened 2022-02-24 08:44 UTC
### Describe the bug

I am currently working with nodejs and gcc and whenever there is any compilation error thrown by gcc or node then at the end of the output nushell throws the error "error: External command failed". Infact it happens with all the commands/programs if they give an error or failure status. I have set `nonzero_exit_errors = false` in my config.toml but still there is no change in status. 

**PS:** I installed nushell with "winget".

### How to reproduce

-  Try to compile a C/C++ program with errors in it.

### Expected behavior

Even though the compiler throws an error, since the execution of the program was successfull and as expected nushell shouldn't throw this error.

### Screenshots

<img width="960" alt="Screenshot 2022-02-24 135028" src="https://user-images.githubusercontent.com/28944997/155485842-879db53c-81ef-438d-874d-718beb2048a2.png">

### Configuration

-  **version :**             0.44.0
-  **short_commit :**        a660720b
-  **commit_hash :**         a660720b6889eab2fa3153854b0a367172c3821d
-  **commit_date :**         2022-02-08 01:15:46 +00:00
-  **build_os :**            windows-x86_64
-  **rust_version :**        rustc 1.58.1 (db9d1b20b 2022-01-20)
-  **rust_channel :**        stable-x86_64-pc-windows-msvc
-  **cargo_version :**       cargo 1.58.0 (f01b232bc 2022-01-19)
-  **pkg_version :**         0.44.0
-  **build_time :**          2022-02-08 01:49:18 +00:00
-  **build_rust_channel :**  release
-  **features :**            ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
-  **installed_plugins :**   binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath

**Comment by fdncred** [comment] 2022-02-24 12:34
I think this is working as intended. Is there a way to tell whether the command is an expected failure vs an unexpected failure? I think maybe they both return non-zero exit codes, which are supposed to indicate some type of failure.

If you set `nonzero_exit_errors = true` does it do the same thing?

**Comment by shans10** [comment] 2022-02-24 13:16
> I think this is working as intended. Is there a way to tell whether the command is an expected failure vs an unexpected failure? I think maybe they both return non-zero exit codes, which are supposed to indicate some type of failure.
> 
> If you set `nonzero_exit_errors = true` does it do the same thing?

Yes it does the same thing in both cases, there is no difference in the output whether `nonzero_exit_errors` is `true` or `false` . Futhermore, the same thing happens when executing `explorer.exe` from nushell even though Windows Explorer opens up succesfully without any issues but still nushell  gives "external command failed" error.

**Comment by fdncred** [comment] 2022-02-24 13:43
ya, something is broken somewhere because `explorer .` returns a 0 as an exit code in this situation. luckily for us, this doesn't occur in the latest main version 0.59.0, which will soon be released. i'm not sure we'll look into this much more deeply since we're a week away from a beta.

**Comment by shans10** [comment] 2022-02-25 07:15
> ya, something is broken somewhere because `explorer .` returns a 0 as an exit code in this situation. luckily for us, this doesn't occur in the latest main version 0.59.0, which will soon be released. i'm not sure we'll look into this much more deeply since we're a week away from a beta.

I noticed something today while fiddling with my nushell config, although setting `nonzero_exit_errors` to either `true` or `false` doesn't change the behaviour, but completely removing or commenting it out fixes the both the gcc/node as well as Windows Explorer issues for me.

**Comment by fdncred** [comment] 2022-02-25 12:03
that's interesting. I guess that's a good work-around.

**Comment by hustcer** [comment] 2022-06-06 10:58
> 
> I noticed something today while fiddling with my nushell config, although setting `nonzero_exit_errors` to either `true` or `false` doesn't change the behaviour, but completely removing or commenting it out fixes the both the gcc/node as well as Windows Explorer issues for me.

So can we close this issue? Thx

**Comment by shans10** [comment] 2022-06-06 11:32
> > I noticed something today while fiddling with my nushell config, although setting `nonzero_exit_errors` to either `true` or `false` doesn't change the behaviour, but completely removing or commenting it out fixes the both the gcc/node as well as Windows Explorer issues for me.
> 
> So can we close this issue? Thx

Yes, please do, the above fix worked for me and I haven't faced this issue since then so you can close it now. Thank you!

**Closed** 2022-06-06 11:32 UTC
