### ISSUE TITLE
unable to register (python) plugins

### ISSUE THREAD

**Issue by Jan9103** [nushell/nushell#7014] opened 2022-11-05 15:23 UTC
### Describe the bug

register raises `Plugin failed to load: Error spawning child process: No such file or directory (os error 2)`

## Simple
```
> wget https://raw.githubusercontent.com/nushell/nushell/main/crates/nu_plugin_python/nu_plugin_python_example.py
> nu -c $'register "($env.PWD)/nu_plugin_python_example.py"; version'
Error: 
  × Error getting signatures
   ╭─[source:1:1]
 1 │ register "/home/shae/tmp/nu_plugin_python_example.py"; version
   · ────┬───
   ·     ╰── Plugin failed to load: Error spawning child process: No such file or directory (os error 2)
   ╰────
```

## In a docker
Dockerfile:
```
FROM debian:stable-slim    
    
RUN apt-get update && \    
    apt-get install -y --no-install-recommends curl tar jq ca-certificates && \    
    update-ca-certificates && \    
    rm -rf /usr/share/doc /usr/share/man /usr/share/locale /usr/share/info /var/cache/apt /var/lib/apt/lists /var/log /var/lib/dpkg/*-old
    
RUN curl -L -o nu.tar.gz "$(curl -L "https://api.github.com/repos/nushell/nushell/releases" | jq -r '.[0].assets | .[] | select(.name|test("x86_64-unknown-linux-gnu.tar.gz$")) | .browser_download_url')" && \ 
    tar -xf nu.tar.gz nu && \
    rm nu.tar.gz && \
    mv nu /bin

ENTRYPOINT ["nu"]
```
then:
```
> docker build -t nushell .
> docker run --rm -it nushell

> # let nu create default configs
> fetch -r https://raw.githubusercontent.com/nushell/nushell/main/crates/nu_plugin_python/nu_plugin_python_example.py | save -r nu_plugin_python_example.py
> nu -c $'register "/nu_plugin_python_example.py"; version'
Error: 
  × Error getting signatures
   ╭─[source:1:1]
 1 │ register "/nu_plugin_python_example.py"; version
   · ────┬───
   ·     ╰── Plugin failed to load: Error spawning child process: No such file or directory (os error 2)
   ╰────
```

### Expected behavior

I expect nu to load the official example plugin and not raise errors (at least in a fresh setup in a docker)

### Configuration

In docker:

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:52:28 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

Outside docker:

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:52:28 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment] 2022-11-05 16:04
Hmm, 🤔 I just registered the python plugin without issue like this `register crates/nu_plugin_python/nu_plugin_python_example.py`.

**Comment by dmatos2012** [comment] 2022-11-06 10:17
@Jan9103 I think  the  problem is more with finding the file path. I dont know how exactly string resolution works with `nu`, but its not resolving the `$env.PWD` , so if I do 
```
/home/david〉register $env.PWD                                                               11/06/2022 11:14:08 AM
Error: nu::parser::registered_file_not_found (link)

  × File not found
   ╭─[entry #18:1:1]
 1 │ register $env.PWD
   ·          ────┬───
   ·              ╰── File not found: $env.PWD
   ╰────
  help: registered files need to be available before your script is run

```

But something like
```
cat $env.PWD
```

Works just fine, so probably something the way register handles the string.

But if use the actual raw string it works fine , so like also @fdncred  did:
`register /path/to/your/script.py`.

Thats just what I think, but if you need to resolve it for now, just use the string path.

**Comment by fdncred** [comment] 2022-11-06 14:08
Generally speaking, you can't use variables with `register`, you need a full path. The same is true for all of these type commands like `source`.

You can see this in the `help register`.
```
This command is a parser keyword. For details, check:
  https://www.nushell.sh/book/thinking_in_nu.html
```

We do show a work-around in the `register` examples but I don't use that.

**Comment by WindSoilder** [comment] 2022-11-07 14:17
I can't reproduce the issue...
The error message makes me think about that: Do you have python installed? 
And refer to your dockerfile, I'm not sure if python is installed..

**Comment by theAkito** [comment] 2022-11-13 02:30
> In the docker python is not installed, but the error pops up before any python is executed.

To register a plugin, the plugin is telling Nu about its signature.
The plugin cannot say anything, without its interpreter available.

Therefore, yes, you need the corresponding interpreter at register time.

**Comment by theAkito** [comment] 2022-11-13 15:05
> let me quote my own message:



> In the docker python is not installed, but the error pops up before any python is executed.

Therefore, Docker is not installed in your clean environment and your test was bound to be futile.



> i assume getting the signature of the official example should not be a issue if it is possible to run it via `./`.

Yes, if it's a binary compatible with the kernel's architecture, then it does not require an interpreter.



> > The plugin cannot say anything, without its interpreter available.
> 
> let me quote my own message:
> 
> > My maschiene has python3, python2, pip3 and pip2 installed via apt. (i also tested the code and it runs fine)
> 
> i assume getting the signature of the official example should not be a issue if it is possible to run it via `./`. and if it actually has anything to do with it not finding `/usr/bin/python3` (which it really should) it should be changed to output a error-message like `unable to find interpreter for file` instead of `No such file or directory (os error 2)`.

Absolutely. Wanted to open an issue about it, as soon as you confirm, that the error results from a lack of Python.

**Comment by theAkito** [comment] 2022-11-16 19:50
@Jan9103

Have you tried the Docker scenario **with** Python installed?

**Comment by theAkito** [comment] 2022-11-16 20:52
> just tried again - still does not work in a debian-slim docker on my main pc (`apt update; apt install python3; python3 --version`)

I was unable to believe that, so I tried this out myself.

```nu
> docker build -t nushell .
> docker run --rm -it nushell

> # let nu create default configs
> fetch -r https://raw.githubusercontent.com/nushell/nushell/main/crates/nu_plugin_python/nu_plugin_python_example.py | save -r nu_plugin_python_example.py
> nu -c $'register "/nu_plugin_python_example.py"; version'
```

Then, I noticed, that the error you see is completely correct and it would appear in every shell on earth.

You downloaded the file into `nu_plugin_python_example.py`, but you are trying to register `/nu_plugin_python_example.py`, which does not exist.

Another minor quirk is, that you could've downloaded it with only `fetch`, without using `save`, to begin with.

```nu
fetch -r https://raw.githubusercontent.com/nushell/nushell/main/crates/nu_plugin_python/nu_plugin_python_example.py -o nu_plugin_python_example.py
```

This issue shall be closed.

**Comment by theAkito** [comment] 2022-11-16 21:12
> it is downloaded in `/` within my docker -> its the correct filepath -- i tried absolute paths and relative paths and neither works

I just literally have a Debian container open and literally downloaded & registered the plugin. It works.

**Comment by theAkito** [comment] 2022-11-16 22:00
> * as far as i am aware debian auto-symlinks python3 to python (and if it does not the example plugin or nu should be adjusted in my opinion)

I tested it in the Docker container, as explained previously, and it works. The symlink has to be created manually, unfortunately.

That said, the original fault, in the very beginning of the mess, is Python. If Python would not create a mess, we wouldn't have this issue, right now.



> the exact example works fine on my raspberry-pi (raspian with nu 0.71), but does not work on my pc (popos with nu 0.71) and my laptop (ubuntu lts with nu 0.69.1) (on each of these its the same inside of a docker as outside of a docker)
> 
>     * this means that i am capable of entering the commands correct and have a consistent behavior, but have no idea how to replicate it

So, there must be something incorrectly or incompletely set up on your PC & Laptop. It works on my x86 64-bit computer, which I think is the same architecture your PC & Laptop use.



> * feel free to close the issue if you think its a weird edgecase

I'm 99% sure something is set up in an unexpected way on your PC & Laptop. If you would re-install the operating systems or run a live distribution or something, it would work.

If you can come up with something weird about your systems' configurations, you could investigate in that direction.

**Comment by theAkito** [comment] 2022-11-16 23:02
Can you temporarily move the entire config folder and generate a new one?

Alternatively, you could create a temporary Linux user and try with a clean configuration environment.

**Comment by theAkito** [comment] 2022-11-16 23:13
Either, we are missing something, or something is wrong with the two operating system setups. It works everywhere else, even on the same computer. Just not on the two operating systems, on your computer & laptop.

**Comment by theAkito** [comment] 2022-11-17 01:23
I've just looked at your self-created Dockerfile.

```Dockerfile
FROM debian:stable-slim    
    
RUN apt-get update && \    
    apt-get install -y --no-install-recommends curl tar jq ca-certificates && \    
    update-ca-certificates && \    
    rm -rf /usr/share/doc /usr/share/man /usr/share/locale /usr/share/info /var/cache/apt /var/lib/apt/lists /var/log /var/lib/dpkg/*-old
    
RUN curl -L -o nu.tar.gz "$(curl -L "https://api.github.com/repos/nushell/nushell/releases" | jq -r '.[0].assets | .[] | select(.name|test("x86_64-unknown-linux-gnu.tar.gz$")) | .browser_download_url')" && \ 
    tar -xf nu.tar.gz nu && \
    rm nu.tar.gz && \
    mv nu /bin

ENTRYPOINT ["nu"]
```

Specifically this part.
```
tar -xf nu.tar.gz nu && \
    rm nu.tar.gz && \
    mv nu /bin
```

I thought, this is perhaps not enough for the plugin, as all the following binaries are inside that archive.

```nu
┏━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━┓
┃ # ┃               name               ┃ type ┃   size   ┃
┣━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━╋━━━━━━━━━━┫
┃ 0 ┃ /usr/bin/nu                      ┃ file ┃ 62.9 MiB ┃
┃ 1 ┃ /usr/bin/nu_plugin_custom_values ┃ file ┃  2.6 MiB ┃
┃ 2 ┃ /usr/bin/nu_plugin_example       ┃ file ┃  2.5 MiB ┃
┃ 3 ┃ /usr/bin/nu_plugin_gstat         ┃ file ┃  5.7 MiB ┃
┃ 4 ┃ /usr/bin/nu_plugin_inc           ┃ file ┃  2.0 MiB ┃
┃ 5 ┃ /usr/bin/nu_plugin_query         ┃ file ┃  4.6 MiB ┃
┗━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━┻━━━━━━━━━━┛
```

Just to be sure, I tested your Dockerfile (more or less) and it actually worked even without all the binaries, except `nu` itself. I just had to install `apt update; apt install python3; python3 --version` & link Python `ln -s (which python3 | get path) /usr/bin/python` and the plugin was successfully registered.

Building the Dockerfile failed for me, due to the following error.

```
#7 5.463 tar: nu: Not found in archive
#7 5.463 tar: Exiting with failure status due to previous errors
```

So, I had to change the `tar` extraction a bit.

___

I don't know what is going on on your systems, but it's definitely an OS issue. It happens on two completely different pieces of hardware, yet all other hardware works, for you & me, as well.

We have also tried out mutliple operating systems and the only thing that worked for you is a live system.

All this means, it must be something in your OS setup for your PC & Laptop, if I'm not missing anything.

If this would be needed to be debugged, one would need to set up an OS from scratch and then apply all the configurations you have on your PC & Laptop, step by step, on that fresh OS. After every little step, there would be a test with the Docker container, to monitor if the plugin registration suddenly starts disobeying at some point for seemingly no reason.

What I find most curious is that it doesn't even work in Docker. Docker uses the host's kernel, but I assume you have different versions on PC & Laptop, right?

Either way, it's extremely weird. It all feels like a huge user error, though we have now iterated through the steps so many times, it should've sufficed to determine such an error.

**Comment by WindSoilder** [comment] 2022-11-18 09:28
Thanks for your detailed discussion, I think this issue can be closed and prefer https://github.com/nushell/nushell/issues/7150 for better error message

**Closed** 2022-11-19 11:12 UTC
Labels: :bug:  bug, plugins
