### ISSUE TITLE
can't work with grep --include

### ISSUE THREAD

**Issue by lafirest** [nushell/nushell#5833] opened 2022-06-20 06:53 UTC
### Describe the bug

This is a nice shell, and I often use the `grep` command, but I find if I use `grep --include` in nushell, there will output nothing, but other shells work correctly.

System: macOS Big Sur Version 11.4
Installed by: brew

### How to reproduce

1. try `grep --include=` , there will output nothing

### Expected behavior

work correctly with `grep --include`

### Screenshots

In nu:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/22971499/174541788-9f000d44-cb92-4a56-a564-f6f1f7fa7f17.png">
In bash:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/22971499/174542410-98a6b65c-f9de-41fd-802f-10efa0f350c9.png">

**Comment by elferherrera** [comment] 2022-06-20 19:00
Have you tried using backticks?

**Comment by panicbit** [comment] 2022-06-20 19:14
The issue is the quotes become part of the parameter. This should work:
```
grep -L '--include=*.erl' -ri "session.subscribed" ./
```
or even just:
```
grep -L --include=*.erl -ri session.subscribed ./
```

**Comment by elferherrera** [comment] 2022-06-20 21:26
Im testing in zsh and this works
```
grep -L --include="*.txt" -ri "*61a02*" ./
```
but this doesnt
```
grep -L --include=*.txt -ri "*61a02*" ./
```

but this aside, the issue seems to be the * in nu

**Comment by panicbit** [comment] 2022-06-20 21:40
@elferherrera I doubt the `*` is the issue. The second invocation doesn't work in ZSH because ZSH will try to expand `*.txt`. For the command to work properly it has to get passed to `grep` verbatim, i.e. it has to be quoted in bourne shells (but not in nu). Nu doesn't implicitly expand globs, instead, you can use the `glob` command.
Your latter zsh command would be equivalent to this nushell invocation:

```nu
grep -L (glob "--include=*.txt") -ri "*61a02*" ./
```

**Comment by elferherrera** [comment] 2022-06-21 00:14
I created a simple arg tester like this

```rust
use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    println!("{:?}", args);
}
```

And used it to test how the arguments are passes to the external command. This is what I found
1. Input: `./target/debug/arg_tester --include=*.ext -L -` 
    Received: `["./target/debug/arg_tester", "--include=*.ext", "-L", "-"]`
2. Input: `./target/debug/arg_tester -L --include="*.txt" -ri "*61a02*" ./`
    Received: `["./target/debug/arg_tester", "-L", "--include=\"*.txt\"", "-ri", "*61a02*", "./"]`
3. Input: `./target/debug/arg_tester -L --include=`*.txt` -ri "*61a02*" ./`
    Received: `["./target/debug/arg_tester", "-L", "--include=`*.txt`", "-ri", "*61a02*", "./"]`
4. Input: `./target/debug/arg_tester -L `--include="*.txt"` -ri "*61a02*" ./`
    Received: `["./target/debug/arg_tester", "-L", "--include=\"*.txt\"", "-ri", "*61a02*", "./"]`
6.  Input: `./target/debug/arg_tester ./...`
     Received: `["./target/debug/arg_tester", "./../.."]`

So, it seems that it is creating an escaped string as you were suspecting. With `./...` it is converting it into a filepath, which is related to a golang bug mentioned on discord. We need to figure out how to pass a raw string without the escaped quotes

**Comment by elferherrera** [comment] 2022-06-21 00:57
Even weirder, I changed the `arg tester` to check if the strings are similar like this

```rust
use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    println!("{:?}", args);

    for arg in args {
        if arg == r#"--include="*.exe""# {
            println!("match: {}", arg);
        } else {
            println!("no match: {}", arg);
        }
    }
}
```
and when I run this `target/debug/arg_tester --include="*.exe"`

it does match on the string, so I dont know why grep is not receiving the correct string

**Comment by elferherrera** [comment] 2022-06-21 01:11
it seems to be the case

**Comment by lafirest** [comment] 2022-06-21 01:25
> 

Yes, this work, thanks

**Comment by elferherrera** [comment] 2022-06-21 01:26
Im closing this issue

**Closed by elferherrera** 2022-06-21 01:26 UTC
Labels: bug, external-commands, parser
