### ISSUE TITLE
Aliases to subcommands show up in command help

### ISSUE THREAD

**Issue by ddanier** [nushell/nushell#13536] opened 2024-08-04 18:31 UTC
### Describe the bug

When you create an alias for a subcommand and then use `help ...` on the (parent) command the alias will be shown. However it will a) be shown in an unusable way, showing the same subcommand  twice and b) not make any real sense on the help page of this command anyways.

### How to reproduce

Create some command including some subcommands:
```
❯ def foo [] {}
❯ def "foo x" [] {}
❯ def "foo y" [] {}
```

Create an alias for the subcommand:
```
❯ alias fx = foo x
```

Show the help of the command:
```
❯ help foo  # or use "foo --help"
Usage:
  > foo

Subcommands:
  foo x -
  foo x - Alias for `foo x`
  foo y -

Flags:
  -h, --help - Display the help message for this command
```

Note: If you add additional aliases things will get worse, as this "foo x - Alias for `foo x`" is then repeated multiple times.

### Expected behavior

I think we have two possibilities here, either don't show the aliases at all or show them in a usable way.

Not showing the alias would mean:
```
❯ help foo
Usage:
  > foo

Subcommands:
  foo x -
  foo y -

Flags:
  -h, --help - Display the help message for this command
```

Showing the aliases in a more useful manner would mean something like this:
```
❯ help foo
Usage:
  > foo

Subcommands:
  foo x -
        - Available aliases: fx
  foo y -

Flags:
  -h, --help - Display the help message for this command
```

For the sake of simplicity I would vote for now showing the aliases at all. If the alias is shown I would expect it to at least somehow contain the alias name, which also is not the case currently.

### Screenshots

<img width="623" alt="Screenshot 2024-08-04 at 20 29 22" src="https://github.com/user-attachments/assets/cdf423fb-4c03-4283-b290-bd43ca68044c">

### Configuration

Default homebrew installation with latest nu shell version:

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.96.1                                         |
| major              | 0                                              |
| minor              | 96                                             |
| patch              | 1                                              |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-aarch64                                  |
| build_target       | aarch64-apple-darwin                           |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) (Homebrew) |
| cargo_version      | cargo 1.79.0                                   |
| build_time         | 2024-07-29 23:31:36 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | default, sqlite, system-clipboard, trash       |
| installed_plugins  |                                                |

**Comment by sholderbach** [comment] 2024-08-04 19:00
This seems to be a duplicate of 
- https://github.com/nushell/nushell/issues/11657

**Closed** 2024-08-04 19:07 UTC
Labels: alias, help-system, duplicate
