### ISSUE TITLE
Special characters not recocgnized, messing with table width

### ISSUE THREAD

**Issue by KaliPhobos** [nushell/nushell#4916] opened 2022-03-23 14:05 UTC
### Describe the bug

Special characters used in other language (in my case German) are not recognized properly:
ä / ö / ü / Ä / Ö / Ü / ...

### How to reproduce

1. run `ls` in any directory. The output should be fine
2. rename any file, adding ä,ö,ü to the file or folder name
3. run `ls`again and there will be an offset

### Expected behavior

the tables should align perfectly, no matter the used letters

### Screenshots

<img width="924" alt="grafik" src="https://user-images.githubusercontent.com/21200998/159717699-d4f66656-ff61-4177-859e-a102953c772b.png">
<img width="882" alt="grafik" src="https://user-images.githubusercontent.com/21200998/159717771-cac84aa5-37cf-426b-b35b-ee4e8fadfbcb.png">

**Comment by KaliPhobos** [comment] 2022-03-23 14:06
Default configuration, freshly installed version of 0.60.0 btw

**Comment by fdncred** [comment] 2022-03-23 14:20
> the tables should align perfectly, no matter the used letters

Trust me when I say that tables will probably never align perfectly when it comes to Unicode characters. There are several problems in this area.
1. Fonts can influence this, i.e. if it's not a Unicode font, odd things happen.
2. Unicode letters can be single byte or multi byte.
3. Measuring where the columns go with `ls` and other commands is sometimes done in a streaming fashion, so nushell is writing this line by line which means we're not buffering the output to measure where the columns go.
4. There are some Unicode characters like zero width joiners that are supposed to be 0 width and _sometimes_ they are. This type of thing is especially noticed with lists of emojis.
5. Terminals are responsible for rendering Unicode so different terminals will represent the data differently. I've seen this happen many times. I regularly use Windows Terminal, Alacritty, MacOS Terminal, Tabby, Wezterm, and others and I've see the same thing represented differently.
6. We've discussed buffering the first 1000 rows with `ls` to see if that helps but it's never been implemented. It may help a little but it won't fix the problem due to number 5.

Having said all that, we're open to new and innovative solutions. So, please let us know if you have a good idea how to handle it better, or better yet, submit a PR that demonstrates this. Thanks!

**Comment by dandavison** [comment] 2022-09-13 10:50
I suspect that this is fixed now and that this issue can be closed. The very similar issue https://github.com/nushell/nushell/issues/3229 appears to be fixed. I'm actually struggling to reproduce this one on my system: I've gone back to 0.60 (which was released at the time this issue was opened) but the file names above do align in the table for me (MacOS, Alacritty and Terminal.app).

```
│  9 │ Yanling NUC-C3 Lüfterloser Firewall-Mini-PC mit viermal GBit - Ethernet im Test.pdf.txt │ file │       0 B │ 9 minutes ago  │
│ 10 │ Yanling NUC-C3 Lüfterloser Firewall-Mini-PC mit viermal GBit - Ethernet im Testüüü.pdf  │ file │       0 B │ 9 minutes ago  │
```

**Comment by fdncred** [comment] 2022-09-13 12:00
Thanks @dandavison. I'm guessing our switch to `tabled` may be helping here.

Please re-open if the issue persists.

**Closed by fdncred** 2022-09-13 12:00 UTC
