### ISSUE TITLE
Nushell auto complete always ignore upcase

### ISSUE THREAD

**Issue by Decodetalkers** [nushell/nushell#10576] opened 2023-10-02 03:27 UTC
### Describe the bug

I know on windows upcase and lower case is the same, but on unix they are different, and nushell ignore these on unix platform

### How to reproduce

![image](https://github.com/nushell/nushell/assets/60290287/a0c6e05f-4a89-43d0-80ce-21b3dccb1ec5)

The fold name is `AndroidStudioProjects`

### Expected behavior

on Unix system, not ignore the upcase

### Screenshots

![image](https://github.com/nushell/nushell/assets/60290287/14eeb5d0-6bcb-4dfb-bb53-46f7da201ca4)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.85.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a6f62e05ae5b4e9ba4027fbfffd21025a898783e                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Arch Linux rust 1:1.72.1-1) |
| cargo_version      | cargo 1.72.1                                                     |
| build_time         | 2023-09-22 08:35:37 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment] 2023-10-02 11:22
There is a setting called `$env.completions.case_sensitive` that controls completion case sensitivity. But I think what you're showing in the screenshots is the hint. The hint comes from your history. Am I understanding what you're trying to show?

**Comment by Decodetalkers** [comment] 2023-10-02 11:26
> There is a setting called `$env.completions.case_sensitive` that controls completion case sensitivity. But I think what you're showing in the screenshots is the hint. The hint comes from your history. Am I understanding what you're trying to show?

aha, yes, I make the mistake, it ignore the case of  history , let me set the environment, and make a try

**Comment by Decodetalkers** [comment] 2023-10-02 11:27
Emm, it seems not work
![image](https://github.com/nushell/nushell/assets/60290287/9fa44f1f-a146-4e88-837b-fa230f8ce0ad)
the `cd` in history is lowcase, but then I change it to `cD`, it still give me the hint

**Comment by sholderbach** [comment] 2023-10-02 11:47
This is a duplicate of #10131

**Closed by sholderbach** 2023-10-02 11:47 UTC
Labels: needs-triage
