### ISSUE TITLE
cd autocompletion should be case-insensitive on Windows

### ISSUE THREAD

**Issue by anthonyvdotbe** [nushell/nushell#1843] opened 2020-05-19 06:09 UTC
**Describe the bug**
`cd` autocompletion is case-sensitive on Windows, even though filenames are case-insensitive on Windows. This is also contrary to how all common Windows shells (Command Prompt and both PowerShell flavors) work.

**To Reproduce**
1. type `cd C:\us` and press Tab

**Expected behavior**
Autocompletion to `cd C:\Users\`

**Screenshots**
n/a

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10
 - Nu version (you can use the `version` command to find out): 0.14.0
 - Optional features (if any): n/a

**Comment by thegedge** [comment] 2020-05-19 12:56
If https://github.com/kkawakam/rustyline/pull/387 gets merged, we can bump rustyline and get this for free.

We're also considering working our own completion engine.

**Comment by filalex77** [comment] 2020-05-21 13:20
https://github.com/kkawakam/rustyline/pull/389 was merged. Do we wait for a release?

**Comment by thegedge** [comment] 2020-05-21 13:35
I think so, @filalex77. As soon as they have a new release we can simply bump rustyline and voila ✨

**Comment by fdncred** [comment] 2020-05-21 14:24
How do we talk them into making a release? It looks like it's been a while since there has been one.

**Comment by thegedge** [comment] 2020-05-21 14:34
Looks like the last release was a month ago, which isn't too bad. @jonathandturner do we have a contact on the rustyline to look into getting a release out soon, perhaps before our next release?

**Comment by jonathandturner** [comment] 2020-06-04 21:01
We've updated to the latest rustyline, so this should be fixed now. I'll go ahead and close.

**Closed by jonathandturner** 2020-06-04 21:01 UTC
Labels: bug, good first issue, platform-support, polish

**Comment by fdncred** [comment] 2021-03-31 14:00
@Sympatron please help me understand what is not working for you. I'm on 0.29.1 and I can't make this break yet.

**Comment by Sympatron** [comment] 2021-03-31 14:12
It's exactly the same as the original issue. I updated today with `cargo install -f nu` with Rust 1.51 and case insensitive auto-completion does not work.

When I enter `cd u` and hit `TAB` in `C:\` nothing happens. When I enter `cd U` and `TAB` it auto completes to `Users`.

**Comment by Sympatron** [comment] 2021-03-31 14:55
I am using Windows 8.1. `cargo` put `nu.exe` and all `nu_plugin_*.exe` in `%USERPROFILE%\.cargo\bin`.

I just tried downloading the pre-compiled binaries for Windows, but the result is the same.

**Comment by fdncred** [comment] 2021-03-31 14:56
@andrasio @jonathandturner any ideas how to debug this?

**Comment by Sympatron** [comment] 2021-03-31 15:01
Just tested on Windows 10. Same results.

Steps to reproduce:
- Download `0.29.0` from [Github](https://github.com/nushell/nushell/releases/download/0.29.0/nu_0_29_0_windows.zip).
- Extract somewhere
- Run `nu.exe`
- Type `open l` + `TAB` + `TAB`
- nushell will only suggest `less.exe` but not `LICENSE` or `LICENSE-for-less.txt`

**Comment by fdncred** [comment] 2021-03-31 15:26
i wonder what could be going on.
![open-auto](https://user-images.githubusercontent.com/343840/113169657-6f07a680-920b-11eb-8001-7cbe2f3e71d6.gif)

**Comment by Sympatron** [comment] 2021-03-31 15:45
How do you start nushell? I tried starting it directly and from `cmd` and `powershell` and with `Cmder`, but yours looks quite different.
![nushell_capture](https://user-images.githubusercontent.com/35803463/113172175-79946100-9248-11eb-8ffd-fdf5c4ebbf33.gif)

I tried with 3 different PCs and a lot of different terminals (`Cmder` works best for me in general), but none of them behave like your version. Is it perhaps some setting? Where are nushell settings stored and where are they described?

**Comment by fdncred** [comment] 2021-03-31 16:28
very interesting.  I use Windows Terminal and Windows Terminal Preview to launch nushell directly, or I launch it from pwsh.exe. Both ways work for me. You can find the config.toml with `echo $(config path)` or `echo $nu.config-path`. I use settings that are close to the config.toml [here](https://github.com/nushell/nushell/tree/main/docs/sample_config).

**Comment by fdncred** [comment] 2021-03-31 21:53
oh ya, i have 'case-insensitive' in my config.toml. darn, i forgot about it. sorry. it's tough keeping our documentation up to date when we're moving so fast. we'll accept a pr for that update to the docs though, if you're interested? :)

**Comment by Sympatron** [comment] 2021-04-18 20:14
[Done](https://github.com/nushell/nushell.github.io/pull/121).

**Comment by sagacity** [comment] 2021-05-15 13:47
Is the updated documentation correct? It currently lists `completion_match_method` under the root key, but it should be under `line_editor`, right?

**Comment by fdncred** [comment] 2021-05-15 14:19
@sagacity yes, you're right, it should be under `line_editor`.

**Comment by adrianstaniec** [comment] 2022-05-23 09:47
what happened with this option?
I dont see it anymore in the config

**Comment by Artturin** [comment] 2022-05-28 03:15
> what happened with this option? I dont see it anymore in the config

A similar option was added back 2 days ago https://github.com/nushell/nushell/pull/5646
