### ISSUE TITLE
Fuzzy Completion crashes the shell

### ISSUE THREAD

**Issue by dbuch** [nushell/nushell#6247] opened 2022-08-06 11:49 UTC
### Describe the bug

Hi Nu community!

With below configuration i can consistently crash nushell.

[config.nu.txt](https://github.com/nushell/nushell/files/9274908/config.nu.txt)
[env.nu.txt](https://github.com/nushell/nushell/files/9274909/env.nu.txt)

notice: `alias la = do { ls -la | sort-by type | select mode name size modified }`

Backtace seen below here is recorded by one of the described steps (in _How to reproduce_ section)

```
❯ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/nu`
~/dev/rust/nushell ❯ la | sthread 'main' panicked at 'slice index starts at 64 but ends at 6', library/core/src/slice/index.rs:92:5                                                                                  06/08/2022 13:10:16
stack backtrace:
   0:     0x5598341cafcd - std::backtrace_rs::backtrace::libunwind::trace::h8e036432725b1c57
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5598341cafcd - std::backtrace_rs::backtrace::trace_unsynchronized::h4f83092254c85869
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5598341cafcd - std::sys_common::backtrace::_print_fmt::h9728b5e056a3ece3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5598341cafcd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bb4bd2928827d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5598341f5fac - core::fmt::write::h909e69a2c24f44cc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:     0x5598341c2471 - std::io::Write::write_fmt::h7f4b8ab8af89e9ef
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:     0x5598341ccb95 - std::sys_common::backtrace::_print::hff4838ebf14a2171
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5598341ccb95 - std::sys_common::backtrace::print::h2499280374189ad9
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5598341ccb95 - std::panicking::default_hook::{{closure}}::h8b270fc55eeb284e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:     0x5598341cc809 - std::panicking::default_hook::h3217e229d6e9d13c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:     0x55983222cec3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h456e2288ec746927
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1886:9
  11:     0x55983222b52a - nu::main::{{closure}}::he108ef8689ebf0bc
                               at /home/dbuch/dev/rust/nushell/src/main.rs:44:9
  12:     0x5598341cd326 - std::panicking::rust_panic_with_hook::h9acb8048b738d2e0
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
  13:     0x5598341cd127 - std::panicking::begin_panic_handler::{{closure}}::h70f3b839526af6dc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
  14:     0x5598341cb484 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ecf2cee857fbe0a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x5598341cce59 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
  16:     0x5598341f3863 - core::panicking::panic_fmt::h9f8393e7fd56d655
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
  17:     0x5598341f7ea6 - core::slice::index::slice_index_order_fail_rt::he641f87f69c29b87
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:92:5
  18:     0x5598341ed007 - core::ops::function::FnOnce::call_once::hcee061b6b1eb53dc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  19:     0x5598341f2c76 - core::intrinsics::const_eval_select::h1310152c4f2a3e3a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/intrinsics.rs:2372:5
  20:     0x5598341f7e26 - core::slice::index::slice_index_order_fail::h38516ca8870eb46f
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:87:14
  21:     0x5598340d354f - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index::h179d10082402f167
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:302:13
  22:     0x559833dca148 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h0b96fc35c728434d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:18:9
  23:     0x559833d73071 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::he1a42d4d999b1d6d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/vec/mod.rs:2591:9
  24:     0x559833d3cb1c - nu_protocol::engine::engine_state::StateWorkingSet::get_span_contents::hdcf6ff8eadb7b8b8
                               at /home/dbuch/dev/rust/nushell/crates/nu-protocol/src/engine/engine_state.rs:1290:29
  25:     0x559833356bb6 - nu_cli::completions::command_completions::CommandCompletion::complete_commands::hf1bd827c93a944cc
                               at /home/dbuch/dev/rust/nushell/crates/nu-cli/src/completions/command_completions.rs:83:23
  26:     0x559833357923 - <nu_cli::completions::command_completions::CommandCompletion as nu_cli::completions::base::Completer>::fetch::hb35e80b1cab319d3
                               at /home/dbuch/dev/rust/nushell/crates/nu-cli/src/completions/command_completions.rs:210:13
  27:     0x559833382fc6 - nu_cli::completions::completer::NuCompleter::process_completion::h56db4038f47db680
                               at /home/dbuch/dev/rust/nushell/crates/nu-cli/src/completions/completer.rs:51:13
  28:     0x55983339ddab - nu_cli::completions::completer::NuCompleter::completion_helper::h62bd20d4972725a2
                               at /home/dbuch/dev/rust/nushell/crates/nu-cli/src/completions/completer.rs:217:51
  29:     0x55983339e5c4 - <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete::hd89ac0ca18e487e9
                               at /home/dbuch/dev/rust/nushell/crates/nu-cli/src/completions/completer.rs:254:9
  30:     0x559833528ca0 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values::h3235d8b62c4ddaeb
                               at /home/dbuch/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/menu/columnar_menu.rs:543:17
  31:     0x55983352938f - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_working_details::h277bcb249f5357a3
                               at /home/dbuch/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/menu/columnar_menu.rs:627:25
  32:     0x55983358ed22 - reedline::menu::ReedlineMenu::update_working_details::h33f4432115feb285
                               at /home/dbuch/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/menu/mod.rs:209:17
  33:     0x55983356224e - reedline::engine::Reedline::buffer_paint::h7cf6d47094885f93
                               at /home/dbuch/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:1371:17
  34:     0x55983355f557 - reedline::engine::Reedline::repaint::h7edd432cc155d7e7
                               at /home/dbuch/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:1152:13
  35:     0x5598335593a3 - reedline::engine::Reedline::read_line_helper::hb6f757a4139971d2
                               at /home/dbuch/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:518:29
  36:     0x5598335581a2 - reedline::engine::Reedline::read_line::h0ab60b247f2363f9
                               at /home/dbuch/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:407:22
  37:     0x5598333be389 - nu_cli::repl::evaluate_repl::hf9f96ea14de001c9
                               at /home/dbuch/dev/rust/nushell/crates/nu-cli/src/repl.rs:308:21
  38:     0x5598322140ca - nu::main::h722472215490db86
                               at /home/dbuch/dev/rust/nushell/src/main.rs:337:31
  39:     0x55983221f94b - core::ops::function::FnOnce::call_once::h3d726d1bdb4eef2e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  40:     0x55983221d9ce - std::sys_common::backtrace::__rust_begin_short_backtrace::ha81d71ec6206bd9d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
  41:     0x5598322283a1 - std::rt::lang_start::{{closure}}::h0ca970117b1d0998
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
  42:     0x5598341bac2e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5f1ba3b861cac230
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
  43:     0x5598341bac2e - std::panicking::try::do_call::h4febfdb770eca39d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  44:     0x5598341bac2e - std::panicking::try::h8b0eac8a7d726dbf
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  45:     0x5598341bac2e - std::panic::catch_unwind::h11b83c489c0d8394
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  46:     0x5598341bac2e - std::rt::lang_start_internal::{{closure}}::h63502d2988634103
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
  47:     0x5598341bac2e - std::panicking::try::do_call::h4be475cff12d2aae
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  48:     0x5598341bac2e - std::panicking::try::h1a3b25b8eaf9ba31
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  49:     0x5598341bac2e - std::panic::catch_unwind::h224588ada67b9b0b
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  50:     0x5598341bac2e - std::rt::lang_start_internal::h2807b375c1959759
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
  51:     0x559832228370 - std::rt::lang_start::he29ea3cbfbaef552
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:144:17
  52:     0x5598322194dc - main
  53:     0x7f5587e292d0 - <unknown>
  54:     0x7f5587e2938a - __libc_start_main
  55:     0x559832211315 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  56:                0x0 - <unknown>

```

### How to reproduce

1. type `la | ` and initiate completion (in my case TAB)
2. Watch it burn :)
3. try again with: type `la | select` or something then initiate completion
4. Watch it works (sort of) but try backspace until some lesser cursor position
5. Go to step two

### Expected behavior

I wouldn't expect nushell to crash.

I guess, fuzzy completion still needs some design.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.66.3                                   |
| branch             | main                                     |
| commit_hash        | 34ab4d83600a630b9e7cc89bb25dec1259d5db59 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)      |
| pkg_version        | 0.66.3                                   |
| build_time         | 2022-08-06 11:03:09 +00:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

### Additional context

I did "solve" the crash, see my [fix-slice-indexing branch](https://github.com/dbuch/nushell/tree/fix-slice-indexing) here.

This is surely just a fire extinguisher approach where root cause isn't plugged. Not sure this is actually worth a draft pr. hence linked here in issue directly.

**Comment by kubouch** [comment] 2022-08-06 12:10
I'd say any fix is better than no fix. Have you determined the root cause?

Btw, you can try defining the alias as `alias la = (ls -la | sort-by type | select mode name size modified)` or maybe a better approach is to create a custom command.

**Comment by fdncred** [comment] 2022-08-18 10:48
@dbuch can you please confirm this is now fixed in the latest main branch?

**Comment by dbuch** [comment] 2022-08-20 07:53
@fdncred I can confirm I cannot reproduce a crash.
Also I think #6269 is potential fixed aswell, by a rough analysis of the attached stack dump.

Feel free to close this issue.

**Comment by fdncred** [comment] 2022-08-20 11:04
Thanks. I'll close these.

**Closed** 2022-08-20 11:03 UTC
Labels: bug, priority, 0.67
