### ISSUE TITLE
Can't reopen saved toml file

### ISSUE THREAD

**Issue by Yam76** [nushell/nushell#1906] opened 2020-05-27 18:07 UTC
**Describe the bug**
`open` fails to parse a toml file saved with `save`. 

**To Reproduce**
1. `ls | get modified | save temp.toml`
2. `open temp.toml`

e.g.
```
> ls | get modified
0  2 weeks ago                                                                                                          
1  4 days ago                                                                                                           
2  4 days ago                                                                                                           
3  5 mins ago
> ls | get modified | save temp.toml
> open --raw temp.toml
["2020-05-07 22:44:54.348200 UTC", "2020-05-23 17:24:45.611001900 UTC", "2020-05-23 17:21:29.400286800 UTC"]
> open temp.toml
(-- Error --)
```
**Expected behavior**
Toml file is correctly parsed.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Using WSL, Ubuntu.
 - Nu version (you can use the `version` command to find out):  0.14.0

**Comment by filalex77** [comment] 2020-05-27 20:59
As you can see with `open --raw`, an array of strings gets saved to the TOML file. TOML actually doesn't support any top-level data structure except a table, so the resulting file is not valid. 

Behaviour of `open` is thus as intended, but `save` should've given you an error trying to save a top-level array into a TOML file.

I'll create a separate issue for this fix.

**Comment by arashout** [comment] 2020-06-12 07:38
Can be closed I believe @thegedge
I addressed issue 1907, which maybe addresses the root cause of this one?

**Comment by thegedge** [comment] 2020-06-12 15:12
Error message could perhaps be improved with more specifics, but I think you're right @arashout:

```
nushell on  HEAD (3bb2c9b) is  v0.14.1 via  v1.44.0
❯ ls | get modified | save temp.toml
error: Save could not successfully save
  ┌─ shell:1:21
  │
1 │ ls | get modified | save temp.toml
  │                     ^^^^ unexpected data during text save
```

**Comment by thegedge** [comment] 2020-06-12 15:12
Closed by https://github.com/nushell/nushell/pull/1946

**Closed by thegedge** 2020-06-12 15:12 UTC
Labels: bug
