### ISSUE TITLE
remove without check path exist, `rm -f`

### ISSUE THREAD

**Issue by yanganto** [nushell/nushell#2531] opened 2020-09-10 13:31 UTC
**Is your feature request related to a problem? Please describe.**
The nu shell can not delete a file or a folder, which does not always exist.

**Describe the solution you'd like**
It may be better to delete a file with `-f` option so that the shell script will not exist if the file is nonexistent.

**Describe alternatives you've considered**
use a command to check a file is exist with if condition before executing remove

**Comment by luccasmmg** [comment] 2020-09-22 13:59
I don't think i quite understand the problem, so if someone can help me i would be happy to take this issue, if i'm understanding correctly, the issue is that if i for instance concat a "rm *" with another command (Ex: rm nonexistentfile | ls) the shell will jus show the "no valid paths" error. And the desired outcome is that if the -f is set (Ex: rm -f nonexistentfile | ls) the shell will give the output of ls with no problems? is that it?

**Comment by luccasmmg** [comment] 2020-09-22 16:24
Yes thanks for the explanation, i think i can take this issue, i can probably in two or three days get a solution, would that be ok?

**Comment by thegedge** [comment] 2020-09-22 18:18
@luccasmmg definitely ok! I'll assign it to you.

**Closed** 2020-09-22 21:11 UTC
Labels: enhancement, good first issue

**Comment by yanganto** [comment] 2020-09-23 12:00
@luccasmmg Thanks for fix on this
