### ISSUE TITLE
Sending keys on tmux does not work as expected

### ISSUE THREAD

**Issue by marcelarie** [nushell/nushell#10379] opened 2023-09-15 08:13 UTC
### Question

I have this custom bash scripts to create tmux sessions and they always work with `bash` or `fish` but not with `nushell`.

```bash
#!/usr/bin/env sh

SESSION_TYPE=$1

if [ -z "$SESSION_TYPE" ]; then
	echo "No session type provided"
	exit 1
fi

WORK_PATH="$HOME/clones/$SESSION_TYPE"
# Selecting a repository to work on
SELECTED_REPO=$(ls "$WORK_PATH" | fzy)
REPO=$(echo $SELECTED_REPO | sed 's/\//-/g' | sed 's/\./-dot-/g')
SESSION="$SESSION_TYPE-$REPO"
REPO_NAME="$WORK_PATH/$SELECTED_REPO/"
# Generating the session name using the repository
SHELL=nu
EDITOR=nvim
# CUSTOM_COMMAND=""

if ! tmux has-session -t "$SESSION" 2>/dev/null; then
	echo "Creating new session..."
	tmux new-session -d -s "$SESSION"
	tmux new-window -n $EDITOR
	tmux send-keys "$SHELL" C-m
	tmux send-keys "cd $REPO_NAME" C-m
	# tmux send-keys "$CUSTOM_COMMAND" C-m
	tmux send-keys "$EDITOR" C-m
	tmux send-keys C-l
	tmux split-window -v
	tmux select-pane -t 1
	tmux send-keys "$SHELL" C-m
	tmux send-keys "cd $REPO_NAME" C-m
	# tmux send-keys "$CUSTOM_COMMAND" C-m
	tmux send-keys C-l
	tmux resize-pane -D 80
else
	echo "Session already exists"
fi

tmux -2 attach-session -t "$SESSION"
```

The C-m key are not send and when opening the session I get the following:

<img width="877" alt="Screenshot 2023-09-15 at 10 13 25" src="https://github.com/nushell/nushell/assets/62728887/e79ee96a-1f36-444d-8a98-5d5a6850fd3b">

It shoul cd to the dir and open nvim, but it just gets the two lines together.

Do you know why this happens? The scripts runs inside bash so it is strange. Should I create a `nushell` equivalent script?

**Comment by fdncred** [comment] 2023-09-15 11:28
Nushell doesn't understand bash scripts and is not POSIX compliant. I believe you'll need to write your scripts in nushell's scripting language.

**Comment by marcelarie** [comment] 2023-09-15 11:31
Cool, I am trying that but the issue is the same, nu shell does not work properly with tmux send-keys.

I did a rewrite using nu but the error is still there:

```nu
#!/usr/bin/env nu

def main [$type: string] {
    let work_path = $env.HOME + '/clones/' + $type;
    let selected_repo = (^ls $work_path | fzy)
    let repo = $selected_repo | str replace '/' '-' | str replace '.' '-dot-'
    let session = $type + '-' + $repo
    let repo_name = $work_path + '/' + $selected_repo + "/"
    let shell = 'nu'
    let editor = 'nvim'
    let custom_command = 'yazi'

    let has_session = (tmux has-session -t $session) | str contains " can't find session"

    if not $has_session {
        print "Creating session: " $session
        tmux new-session -d -s $session
        tmux new-window -n $editor
        tmux send-keys $shell C-m
        tmux send-keys $"cd ($repo_name)" C-m
        tmux send-keys $editor C-m
        tmux send-keys C-l
        tmux split-window -v
        tmux select-pane -t 1
        tmux send-keys $shell C-m
        tmux send-keys $"cd ($repo_name); C-m"
        tmux send-keys C-l
        tmux resize-pane -D 80

    } else {
        echo "Session already exists"
    }

    tmux -2 attach-session -t $session
}
```

**Comment by fdncred** [comment] 2023-09-15 11:51
I guess you'll need to find someone that uses tmux for further help. You can drop by our [Discord](https://discord.gg/NtAbbGn) I'm sure there are a few in there.

**Comment by marcelarie** [comment] 2023-09-15 12:27
Ok I will check there, thanks!

**Comment by marcelarie** [comment] 2023-09-15 13:01
this is the thread id: 1152220493852708866

**Comment by marcelarie** [comment] 2023-11-03 13:55
Did not find any help with this, this behavior happens with all the send-keys with C-m when the command is in nushell. Anyone knows how to fix it?

**Comment by fdncred** [comment] 2023-11-03 14:01
I thought @amtoine used tmux with nushell successfully. Maybe he can jump in?

**Comment by marcelarie** [comment] 2023-11-03 14:43
Yes but my question is releated to how to send-keys from a nu shell script to a tmux session.

For example for this script:
```nu
#!/usr/bin/env nu

def main [$type: string] {
    let work_path = $env.HOME + '/clones/' + $type;
    let selected_repo = (^ls $work_path | fzy)
    let repo = $selected_repo | str replace '/' '-' | str replace '.' '-dot-'
    let session = $type + '-' + $repo
    let repo_name = $work_path + '/' + $selected_repo + "/"
    let shell = 'nu'
    let editor = 'nvim'
    let custom_command = 'yazi'

    let has_session = (tmux has-session -t $session) | str contains " can't find session"

    if not $has_session {
        print "Creating session: " $session
        tmux new-session -d -s $session
        tmux new-window -n $editor
        # tmux send-keys $shell C-m
        tmux send-keys $"cd ($repo_name)" C-m
        # tmux send-keys $shell C-m
        tmux send-keys $editor C-m
        tmux send-keys C-l
        tmux split-window -v
        tmux select-pane -t 1
        tmux send-keys $"cd ($repo_name)" C-m
        tmux resize-pane -D 80
        tmux send-keys $shell C-m
        tmux send-keys C-l

    } else {
        echo "Session already exists"
    }

    tmux -2 attach-session -t $session
}
```

if I introduce any of the lines that are commented:
```
        # tmux send-keys $shell C-m
```
The next tmux send-keys will not work correctly. But if I run the command from another nu shell, it will work. 

It is really strange.

**Comment by fdncred** [comment] 2023-11-03 14:47
I have no clue what `tmux send-keys $shell C-m` is even supposed to do. LOL. My guess is that the nushell evaluator is trying to run nushell since `$shell` = `nu`

**Comment by marcelarie** [comment] 2023-11-03 15:16
`tmux send-keys` basically sends the characters that you add as arguments to the terminal.

In this case it will send: `nu` and press C-m, that will run the command. 
It is the equivalent to open a shell, write nu and press Enter.

>  My guess is that the nushell evaluator is trying to run nushell since $shell = nu
Yes that is what I thought but if I go to an already opened shell, the send-keys commands work correctly.

**Comment by marcelarie** [comment] 2023-11-03 15:35
This will be the minimal example of this issue:

```nu
#!/usr/bin/env nu

def main [] {
    tmux new-session -d -s NU-TEST    # Creates the tmux session
    tmux new-window -n EDITOR         # Creates a tmux window
    tmux send-keys nu C-m             # Sends `nu` and presses C-m 
    tmux send-keys nvim C-m           # Send `nvim` and preses C-m <- THIS FAILS
    tmux attach-session -d -t NU-TEST # When we attach to the tmux seesion we see 
                                      # that nvim is written in the shell but it is not executed
}
```

**Comment by marcelarie** [comment] 2023-11-03 15:38
Thanks @fdncred for trying to help.

**Comment by amtoine** [comment] 2023-11-03 20:49
yeah i'm simply using https://github.com/amtoine/tmux-sessionizer and it works :yum:

**Comment by WindSoilder** [comment] 2023-12-20 10:11
I think it's answered, so I'll close the issue for now

Feel free to re-open it if you still have questions

**Comment by marcelarie** [comment] 2023-12-20 11:40
@WindSoilder tbh I think it is not resolved, the solution can be using the sessionaizer that @amtoine comments, but I want to know why if I create a tmux script some send-key commands are not send. That is the problem.

**Comment by WindSoilder** [comment] 2023-12-20 15:00
Sorry for closing it early, but actually I'm not really sure why

**Comment by saketh21v** [comment] 2024-06-17 13:22
Essentially, nushell is ignoring the "Return" key when sent from tmux if nushell isn't already open and ready to receive keycodes. 
I'm facing the same issue using tmuxinator. 

The command shows up before the prompt is ready. And once the prompt is ready, the command is shown, but the "Enter/Return" keycode is ignored.
![image](https://github.com/nushell/nushell/assets/9252678/6f1d3dac-587e-44b1-bc06-ce8e2ec0c3a0)

**Comment by marcelarie** [comment] 2024-06-19 12:05
@WindSoilder do you know about anyone that can have a good knowledge on why nushell could be ignoring tmux keys?

**Comment by NotTheDr01ds** [comment] 2024-09-27 15:26
Unless I'm wrong, this can be much more minimally reproduced just by running this command from the REPL itself:

```nu
tmux send-keys "ls" C-m
```

* In Nushell, this enters `ls` at the prompt, but does not send the Return.
* In Bash and Fish, this enteres `ls` at the prompt and executes it.

I'm guessing this is a Reedline issue?

**Comment by guigaribalde** [comment] 2024-12-01 03:54
any luck so far? having the same issue here.
if you want to try it, type ` tmux send "nvim ." ENTER` and the expected behavior is to open nvim (when in a tmux session)

**Comment by codethread** [comment] 2024-12-23 15:39
stumbled upon this yesterday after trying https://github.com/ivaaaan/smug (tmux project manager) and seems the latest [101](https://www.nushell.sh/blog/2024-12-24-nushell_0_101_0.html) release seems to have fixed for me (hope others find the same 🤞 )

**Comment by NotTheDr01ds** [comment] 2024-12-23 19:46
Yes - Works now for me as well using the [example above](https://github.com/nushell/nushell/issues/10379#issuecomment-2379544206).  Taking a bit of a wild guess here - This might be from https://github.com/nushell/reedline/pull/855

**Closed by NotTheDr01ds** 2024-12-23 19:46 UTC
Labels: question
