### ISSUE TITLE
Helix editing mode

### ISSUE THREAD

**Issue by mydumpfire** [nushell/nushell#10868] opened 2023-10-29 08:04 UTC
### Related problem

We already have edit modes for vi(m), it would be nice if we can have one for [helix](https://github.com/helix-editor/helix) too.

### Describe the solution you'd like

An editing mode that emulates the Helix editor

**Comment by amtoine** [comment] 2023-10-29 12:09
i think this is a Reedline thing and a duplicate of https://github.com/nushell/reedline/issues/639 :wink: 

closing in favor of https://github.com/nushell/reedline/issues/639

**Closed by amtoine** 2023-10-29 12:09 UTC
Labels: enhancement, needs-triage

**Comment by luccahuguet** [comment] 2024-01-23 17:45
I was in doubt whether to create the issue here or in reedline, looks like I did the right call, nice
