### ISSUE TITLE
`find` does not strip ansi escape sequences when piped to other program

### ISSUE THREAD

**Issue by B4rc1** [nushell/nushell#13104] opened 2024-06-08 19:30 UTC
### Describe the bug

After [this](https://github.com/nushell/nushell/pull/11509) PR, `find` highlights text which is really nice but it does not automatically strip ansi escape sequences when piped to other programs. 

Some of my scripts relied on this behaviour since i used it as part of a pipeline and lead me to a very curios error:
```
~> $boot_entry
0000
~> sudo efibootmgr -n $boot_entry
Invalid BootNext value0000
                        ^
~> // It does not work with $boot_entry which is 0000 but it works with the string 0000...
~> sudo efibootmgr -n 0000
BootNext: 0000
BootCurrent: 0004
Timeout: 1 seconds
BootOrder: 0004,0005,0000,0006,0007
```

Which led me to discover this behavior:
```
~> $boot_entry | into binary
Length: 9 (0x9) bytes | printable whitespace ascii_other non_ascii
00000000:   1b 5b 33 37  6d 30 30 30  30                         •[37m0000
```

### How to reproduce

1. run: `"hi" | find h | into binary`
2. Observe Output:
```
~> "hi" | find h | into binary
Length: 32 (0x20) bytes | printable whitespace ascii_other non_ascii
00000000:   1b 5b 33 37  6d 1b 5b 30  6d 1b 5b 34  31 3b 33 37   •[37m•[0m•[41;37
00000010:   6d 68 1b 5b  30 6d 1b 5b  33 37 6d 69  1b 5b 30 6d   mh•[0m•[37mi•[0m
```

### Expected behavior

Output of nushell 0.87.0: 
```
~> "hi" | find h | into binary
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   68 69                                                hi
```

### Configuration

~> version | transpose key value | to md --pretty
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.94.1                                                            |
| major              | 0                                                                 |
| minor              | 94                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) (built from a source tarball) |
| cargo_version      | cargo 1.77.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash, which                   |
| installed_plugins  |                                                                   |

### Additional context

Stripping ansi sequences when used as pipes is the default behaviour of almost any shell program i know.

For now the workaround is to pipe the output into `ansi strip`:
```
~> "hi" | find h | ansi strip | into binary
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   68 69                                                hi
```

**Comment by fdncred** [comment] 2024-06-08 19:55
Here's a work-around.
```nushell
❯ "hi" | find -r h | into binary
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   68 69                                                hi
```

**Comment by sholderbach** [comment] 2024-07-13 16:35
Duplicate of #11899

I want to change the behavior of find to use metadata for composable but contamination free highlighting.

**Closed by sholderbach** 2024-07-13 16:35 UTC
Labels: :bug:  bug
