### ISSUE TITLE
tab completion is broken on subcommands

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8008] opened 2023-02-08 19:13 UTC
### Describe the bug

> **Note**
> might be related to #5780, #5888 and #7202 but i'm not sure to what extend, so i felt a new issue would be somewhat usefull

### How to reproduce

1. type `[foo bar baz] | pat`
2. press tab
- :heavy_check_mark: `pat` gets completed as `path` 
3. type ` joi` making the full command `[foo bar baz] | path joi` so far
4. press tab 
- :x: the completion does not work and shows `NO RECORDS FOUND` and a red-highlighted "joi"

### Expected behavior

i expected `nushell` to complete `joi` into `join`, i.e. the only subcommand of `path` that starts with `joi` :yum: 

> **Note**
> the completion work on command and subcommand option
> - `help --f` is completed as `help --find`
> - `str replace --no` is completed as `str replace --no-expand`

### Screenshots

i do not have the time to take screenshots for now, and i think the code blocks above might be enough :thinking: 
if you want some, feel free to ask and i'll see if i've got some time :wink: 

### Configuration

| key                | value                                                                                                           |
| ------------------ | --------------------------------------------------------------------------------------------------------------- |
| version            | 0.75.1                                                                                                          |
| branch             |                                                                                                                 |
| commit_hash        | bea7ec33c1d0a7d64e50e42d00a941a2f84408c3                                                                        |
| build_os           | linux-x86_64                                                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                                                        |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                                                                             |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                                                                                 |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                                                                             |
| pkg_version        | 0.75.1                                                                                                          |
| build_time         | 2023-02-07 19:20:48 +01:00                                                                                      |
| build_rust_channel | release                                                                                                         |
| features           | database, default, trash, which, zip                                                                            |
| installed_plugins  | gstat, len, my_str_len, nu-example-1, nu-example-2, nu-example-3, pnet, query, query json, query web, query xml |

**Comment by kubouch** [comment] 2023-02-08 19:27
Duplicate of https://github.com/nushell/nushell/issues/7821, it's a regression caused by a bugfix PR. I'll close it in favor of the existing issue.

**Closed by kubouch** 2023-02-08 19:27 UTC

**Comment by amtoine** [comment] 2023-02-09 18:47
> Duplicate of #7821, it's a regression caused by a bugfix PR. I'll close it in favor of the existing issue.
>
woopsie missed that one :yum: 
thanks for pointing to the right issue :relieved:
