### ISSUE TITLE
let silently fails to capture output of external commands

### ISSUE THREAD

**Issue by aidalgol** [nushell/nushell#8522] opened 2023-03-19 01:18 UTC
### Describe the bug

`let` does not capture output of external commands without parenthesis, and does not produce an error.

### How to reproduce

1. Create a file `foo.nu` with the following contents
```
#!/usr/bin/env nu

export def bar [] {
  each { |it|
    let stats = stat --terse $it.name
    print $"Terse stats: ($stats)"
  }
}
```
2. In a Nushell session, run `use foo`
3. Then `ls | foo bar`

Output:
```console
foo.nu 132 10 81a4 1000 100 2f 1299446 1 0 0 1679186035 1679186033 1679186033 1679185947 512
Terse stats:
```

### Expected behavior

Output:
```console
Terse stats: foo.nu 132 10 81a4 1000 100 2f 1299446 1 0 0 1679186001 1679186033 1679186033 1679185947 512
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

A simple workaround is to wrap parentheses around the expression on the right-hand side of the equals sign.  So in this example,
```nu
let stats = stat --terse $it.name
```
Would become,
```nu
let stats = (stat --terse $it.name)
```

**Comment by IanManske** [comment] 2024-03-28 16:51
Looks like this is working as intended on version 0.91.0. (It was probably fixed on some previous version.)

**Closed by IanManske** 2024-03-28 16:51 UTC
Labels: external-commands, redirection-pipe
