### ISSUE TITLE
Tab complete current directory

### ISSUE THREAD

**Issue by nu8** [nushell/nushell#2420] opened 2020-08-26 02:24 UTC
If I have a file on my `PATH`, for example `sunday.php`, I can type `su` then
press `tab` to have the rest filled in.

If I have the same file in the current directory, I can run it with
`./sunday.php` (or `.\sunday.php` on Windows).

However I noticed that with Nushell, if I enter `./su` or `.\su` and press
`tab`, nothing happens. This differs from other shells like Bash or PowerShell,
which will complete the word.

**Comment by thegedge** [comment] 2020-08-26 02:38
Duplicate of https://github.com/nushell/nushell/issues/2393

I think this worked before I made my changes to the completion engine. Definitely something I'd like to get fixed before our next release.

**Closed by thegedge** 2020-08-26 02:38 UTC
Labels: bug, completions
