### ISSUE TITLE
Using Glob Patterns in File Operations and Dealing with No Match Found Error

### ISSUE THREAD

**Issue by atahabaki** [nushell/nushell#10673] opened 2023-10-10 16:35 UTC
### Describe the bug

Certain file operations checks glob pattern match on given parameter. But what if the file exists with that name? It fails, with 'No match(es) found'.

To solve:

We could either 
- re-implement the glob or
- check if the target(s) exists before glob check on every fs operation.

I'm implementing the second approach on [glob-prevents branch on my fork.](https://github.com/atahabaki/nushell/tree/glob-prevents) 

### How to reproduce

1. Create a file or folder that contains glob pattern symbols.
2. Use filesystem operations such as mv,rm in them.
3. File and folder exists but it is handled by glob. Therefore, there'll be no match.

## Example

```nushell
touch X[12].txt
rm X[12].txt
```

### Expected behavior

Last command should be successful. Because of glob match check it will not. I'm working

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.85.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a6f62e05ae5b4e9ba4027fbfffd21025a898783e                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Arch Linux rust 1:1.72.1-1) |
| cargo_version      | cargo 1.72.1                                                     |
| build_time         | 2023-09-22 08:35:37 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by amtoine** [comment] 2023-10-10 17:13
this might be closely related to
- https://github.com/nushell/nushell/issues/9310

**Comment by bobhy** [comment] 2023-10-10 18:54
I think this is a dupe of #10571, for which I'm working on a fix #10557.

**Comment by atahabaki** [comment] 2023-10-10 20:39
> This works right now by escaping the globbing characters.
> 
> ```nushell
> rm X[[]12].txt
> ```

escaping syntax is not covered in glob --examples. I didn't know how to escape. That's why I created a draft PR #10677 . Now, I'm gonna close it. 'Cause I'd prefer the #10557 approach.


I'd consider this issue as: the dupplication of #9310, #10571. Thanks in advance.

**Comment by fdncred** [comment] 2023-10-10 20:56
Sounds good. I just wanted to share that "trick" so you knew.

**Closed by fdncred** 2023-10-10 20:56 UTC
Labels: file-system, needs-triage, glob-expansion
