### ISSUE TITLE
Build failure related to openssl

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#5379] opened 2022-04-30 11:15 UTC
### Describe the bug

Tried to build nushell with --all-features on a recent manjaro and got:

```
error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `/home/jt/Source/nushell/target/release/build/openssl-sys-f64fd49a46343eb4/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/home/jt/Source/nushell/target/release/build/openssl-sys-6e9e106a84f143e0/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
  Configuring OpenSSL version 1.1.1n (0x101010efL) for linux-x86_64
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL file first)         ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/jt/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.18.0+1.1.1n/src/lib.rs:477:39
```

### How to reproduce

1. See above

### Expected behavior

I've got openssl installed. I'm assuming that's enough?

**Comment by jntrnr** [comment] 2022-04-30 11:26
I'm able to build if I remove the static openssl setting.

**Comment by rgwood** [comment] 2022-04-30 18:13
I tried setting up a Manjaro VM to reproduce this but got bogged down in a lot of package upgrade/conflict unpleasantness (I'm not very familiar with Arch and co.).

It looks like the problem might be that `make` is not installed on your system, I'm curious whether installing it will fix the issue.

**Comment by jntrnr** [comment] 2022-04-30 20:53
Confirmed that `make` is now required (previously wasn't)

**Comment by rgwood** [comment] 2022-05-02 17:00
@Tropid That error looks like you might need to install Perl. Alternately, try building/running without the `static-link-openssl` feature.

**Comment by rgwood** [comment] 2022-05-02 21:01
^ Looking into this... seems like `extra` already includes everything but `static-link-openssl`. We could probably change `--all-features` to `--features=extra` in the PR template and call it a day.

**Comment by justinfarrelldev** [comment] 2022-08-19 20:19
I had this issue earlier, and the solution was to simply run `sudo apt update && sudo apt-get install libssl-dev`. I had openssl in my path, but for whatever reason the installation didn't work before installing `libssl-dev` like that. 

Link to the relevant StackOverflow thread that guided me to the fix (with info on the CentOS package as well): https://stackoverflow.com/a/27551158

**Comment by sholderbach** [comment] 2022-10-10 12:40
What is the status on this one? Do we need additional documentation, better packaging on the distributor side? Or is everything fine with the static linking right now?

**Comment by rgwood** [comment] 2022-12-01 07:07
I think we can close this. Static linking hasn't been causing issues recently and the PR template no longer suggests building with `--all-features`.

I've been thinking we might want to revisit using rustls instead of OpenSSL but IMO that's a separate discussion.

**Closed by rgwood** 2022-12-01 07:07 UTC
Labels: platform-specific, build-package
