### ISSUE TITLE
`export use` does not `source-env`

### ISSUE THREAD

**Issue by Jan9103** [nushell/nushell#6973] opened 2022-11-02 00:43 UTC
### Describe the bug

`use` sources `export-env`, but `export use` does not.

### How to reproduce

```nu
> "export use b.nu" | save -r a.nu
> "export-env { let-env TEST = 'foo' }" | save -r b.nu
> use b.nu
> $env.TEST
foo
> let-env TEST = ""
> use a.nu
> $env.TEST

> # workaround:
> "export-env { source-env b.nu }" | save -r a.nu
> use a.nu
> $env.TEST
foo
```

### Expected behavior

I expect nu to recursively source the exported environments.

### Configuration

```
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:52:28 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |
```

**Comment by kubouch** [comment] 2022-11-02 07:46
Yeah, I think I overlooked that one. Should be easy to fix.

**Comment by dmatos2012** [comment] 2022-11-10 22:08
I will give this one a shot, given the "Should be easy to fix" :)

**Comment by kubouch** [comment] 2022-11-10 22:37
Yeah, should be easy, check the code for the `use` command in the `nu-commands` crate, that should give your the idea.

**Comment by kubouch** [comment] 2022-11-24 21:14
I'll close this issue because it currently works "as intended". The idea is that you're always supposed to define an `export-env` block if you want a module to export an environment.

We might want to reconsider it in the future but it would go against the current design so I would rather avoid it and see if the current system is acceptable.

**Closed by kubouch** 2022-11-24 21:14 UTC
Labels: :bug:  bug
