### ISSUE TITLE
`extern` completions for single-dash long options

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12414] opened 2024-04-05 16:22 UTC
### Related problem

Some Java CLI utilities (and I presume others, too) only support single dash long options: `plantuml -help` works, whereas `plantuml --help` doesn't.

### Describe the solution you'd like

Add a flag to `extern`, which either:

- Converts double-dashed options into single-dashed, when passing them to the underlying command
- Allows passing single-dashed long options.

**Comment by sholderbach** [comment] 2024-07-21 14:37
Duplicate of #5959

**Closed by sholderbach** 2024-07-21 14:37 UTC
Labels: enhancement, external-commands, completions, syntax
