### ISSUE TITLE
`do` does not report missing arguments properly

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10415] opened 2023-09-18 17:21 UTC
### Describe the bug

i couldn't see any other issue directly talking about this, so here i am :yum: 

i was trying to write a closure to be executed in a `do` call but got a strange "variable not found" error, even though the variable looks quite defined to me :open_mouth: 

let me simplify the problem in the following section :wink: 

### How to reproduce

1. this works fine
```nushell
> do {|x| 2 * $x} 1
2
```
2. and this does too
```nushell
> 1 | do {|| 2 * $in}
2
```
3. however, this one does not work and gives an error
```nushell
> 1 | do {|x| 2 * $x}
Error: nu::shell::variable_not_found

  × Variable not found
   ╭─[entry #55:1:1]
 1 │ 1 | do {|x| 2 * $x}
   ·                 ─┬
   ·                  ╰── variable not found
   ╰────
```

### Expected behavior

~~i think i expected either~~
- to have a clearer error, maybe something like this with an help?
```nushell
> 1 | do {|x| 2 * $x}
Error: nu::shell::variable_not_found

  × Variable not found
   ╭─[entry #55:1:1]
 1 │ 1 | do {|x| 2 * $x}
   ·                 ─┬
   ·                  ╰── variable not found
   ╰────
  help: a value of `1` is given to the closure as input but argument `$x` is being used.
```
- ~~to have it working `1 | do {|x| 2 * $x}`~~

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.1                                   |
| branch             | main                                     |
| commit_hash        | 2b77544e5887e7e03cda30d4bb141a4074a17d98 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-15 18:52:21 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, nu_plugin_explore                 |

**Comment by sholderbach** [comment] 2023-09-21 22:24
This is a duplicate of https://github.com/nushell/nushell/issues/9067

The behavior of `do` in the happy path is correct here and should not be changed. The unhelpful error should be fixed to be an explicit `MissingPostional` (or whatever necessary to describe the particular mismatch between closure signature and `do` call). #9083 trying to do something about a *variable* span location does not seem like the right thing to address this problem.

As the closure has a positional argument, it has to be passed as an *argument* to `do`.
If you want to pass by pipeline into the closure pass by pipeline into `do`.

**Comment by 1Kinoti** [comment] 2023-10-01 12:36
i think the problem here isn't particularly with `do` but with how closures are represented

```rs
Type::Closure
```

this is a very lossy repr imo and should be something like

```rs
Type::Closure {
    args: Vec<Type>,
    returns: Box<Type>,
}
```

this way, `do` can require the number of args supplied to it match `Type::Closure.args` and emit better diagnostics otherwise.

now this requires changes to the parser. specifically, we need to accept annotations for closures (like we do with tables etc).

i attempted this once but found some very fun details:
- the syntax for the annotation to include all this info 
- conversation from `Type::Closure` to `Value::Closure`
- `def` and other keywords commands that have blocks use `parse_closure` to parse these blocks. so we might need to separate `parse_cmd_block` from `parse_closure`.
```nushell
# this is the possible reason why this
# was legal nushell code the last time
# i checked
def what [] {|the| f }
```

**Comment by weirdan** [comment] 2024-08-17 22:43
The error has become clearer:

```console
$ 1 | do {|x| 2 * $x}
Error: nu::shell::missing_parameter

  × Missing parameter: x.
   ╭─[entry #68:1:5]
 1 │ 1 | do {|x| 2 * $x}
   ·     ─┬
   ·      ╰── missing parameter: x
   ╰────
```

**Closed** 2024-08-18 12:51 UTC
Labels: unhelpful-error, duplicate
