### ISSUE TITLE
color change on nushell error

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#4017] opened 2021-09-15 17:58 UTC
### Describe the bug

The colors seem to be reset in an odd way after nushell errors; link to gifs and discord chat: https://discordapp.com/channels/601130461678272522/614593951969574961/887757901253451786

### How to reproduce

`cat ~/.local/share/nu/history.txt | fzf +m | nu $it` fails, but `$in$` doesn't

### Expected behavior

Color theme would remain the same.

**Comment by jntrnr** [comment] 2021-09-15 18:03
My suspicion here that we'd need to test:

* fzf uses ansi sequences to control the screen and possibly it also controls raw mode. it may also use ansi sequences to read the position and/or dimensions from the terminal
* the error message created by `nu $it` generates additional ansi sequences
* it's possible that fzf, running in the background thread, is still exiting when the error occurs
* this may leave the terminal in a state where it hasn't been properly reset to defaults (including not getting reset from raw mode)

**Comment by fdncred** [comment] 2021-09-15 19:16
I wonder if this change needs to be not only for Windows. I have experienced some odd behaviors of externals horking anis colors.
https://github.com/nushell/nushell/blob/8bcbc8eeb3f8f9cf90d65441616cb85b09dbb3e4/crates/nu-command/src/commands/platform/run_external.rs#L122-L125

**Comment by jntrnr** [comment] 2021-09-15 19:22
@fdncred yeah could be. another defensive change we could try would be for the line editor to do an ansi reset before it begins, which should clear out any pre-existing styles (both fg and bg I believe)

**Comment by fdncred** [comment] 2021-09-15 19:49
ya, sending `\x1b[0m`, which is what is mapped out our `ansi reset` command, definitely turns off all attributes and resets text to "normal" going forward. I don't think it would hurt things happening from prompt to prompt. in fact, one could probably put `prompt = (ansi reset);(regular prompt stuff)` in the prompt line to test it out, since the prompt line runs every time.

**Comment by fdncred** [comment] 2022-03-06 15:08
I can't reproduce this in 0.59 using `$in` - `$it` isn't even supported this way any longer. so, I'm closing this issue. if it reoccurs we can reopen it.

**Closed by fdncred** 2022-03-06 15:08 UTC
Labels: bug
