### ISSUE TITLE
make the "External command failed" error more descriptive

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8313] opened 2023-03-04 12:19 UTC
### Related problem

i often use the `fzf` fuzzy finder in `nushell` pipelines but i have a problem when not piping its output to `str trim`

according to @fdncred, the behaviour in https://asciinema.org/a/564496 is expected :ok_hand: 

> **Note**
> code:
> ```bash
> >_ let var = ("yes\nno" | to text | fzf | str trim); $var
> yes
> ```
> ```bash
> >_ let var = ("yes\no" | to text | fzf); $var
> Error: nu::shell::external_command
> 
>   × External command failed
>    ╭─[entry #4:1:1]
>  1 │ let var = ("yes\no" | to text | fzf); $var
>    ·                                 ─┬─
>    ·                                  ╰── External command failed
>    ╰────
>   help:
> ```

however, i find the error in itself not very descriptive :thinking: 
because, in the end, `fzf` does not fail at all here! :open_mouth: 

### Describe the solution you'd like

i'm not sure what the issue with `fzf` without `str trim` here is, so i do not know what the message should be :thinking: 

however, i'm pretty sure the `fzf` external command did NOT fail, so the error message should probably NOT be "_External command failed_" :yum:

**Comment by fdncred** [comment] 2023-03-04 13:15
I figure the failure is because `fzf` is returning with some odd character. Maybe a newline or a \0 or a space. We could probably figure out what it's returning.

**Comment by fdncred** [comment] 2023-03-04 13:19
ok, this is what I found
1. firstly "yes\no" shows up as `o` and `yes` because double quotes interprets `\n` as an escape.
2. You can see what `fzf` is returning like this
```
"yes\no" | to text | fzf | debug -r 
String {
    val: "yes\n",
    span: Span {
        start: 198040,
        end: 198043,
    },
}
```
The `\n` is throwing things off. Having items in a list and stripping the `\n` with `str trim`

This seems to work better
```
[yes no] | to text | fzf | str trim | debug -r  
String {
    val: "no",
    span: Span {
        start: 198127,
        end: 198135,
    },
}
```

**Comment by fdncred** [comment] 2023-03-04 13:59
BTW - I agree, that 'external command failed' isn't super helpful considering what the problem is here.

**Comment by amtoine** [comment] 2023-03-04 14:20
> 1. firstly "yes\no" shows up as `o` and `yes` because double quotes interprets `\n` as an escape.
>
woopsie, i forgot the "n", that's on me :relieved:

> The `\n` is throwing things off.
>
yeah, probably

> BTW - I agree, that 'external command failed' isn't super helpful considering what the problem is here.
>
if there is an "easy" change to be made, maybe it's on this error message?

=> something that looks odd to me is that, as you can see in the recording, `fzf` does not even launch when ommiting the `str trim` :thinking: 
it just hangs and i have to kill `fzf` to see the error...

**Comment by fdncred** [comment] 2023-03-04 14:22
>  fzf does not even launch when ommiting the str trim

I don't have this issue on macos. it launches fine without str trim.

**Comment by amtoine** [comment] 2023-03-04 14:28
> I don't have this issue on macos. it launches fine without str trim.
>
oooh :thinking: 
interesting

because, i might have been unclear but yeah the real strange thing is that `fzf` does not show up at all :scream: 

i can reproduce that on my work machine, so on `ubuntu`, as well as on `arch`

**Comment by fdncred** [comment] 2023-03-04 14:31
I know that `fzf` reads env vars before/while launching. Do you have any of those set that could be affecting how it runs?

**Comment by amtoine** [comment] 2023-03-04 14:37
> I know that `fzf` reads env vars before/while launching. Do you have any of those set that could be affecting how it runs?
>
the only thing i have is `FZF_DEFAULT_OPTS` i think, but i've got the same issue with
```bash
with-env [FZF_DEFAULT_OPTS ""] { let var = ([yes no] | to text | fzf) }
```

**Comment by amtoine** [comment] 2023-03-04 14:37
and this "hanging" issue only occurs when i try to `let var = ( ... | fzf)`:grey_exclamation:

**Comment by fdncred** [comment] 2023-03-04 14:38
oh ya, i didn't try to assign it a variable. let me try that.

**Comment by fdncred** [comment] 2023-03-04 14:40
ya, it breaks without the str trim for me too when assigning to a var

**Comment by amtoine** [comment] 2023-03-04 14:46
> ya, it breaks without the str trim for me too when assigning to a var
>
aah cool, we're on the same page then :muscle: 
yep i tried to assign the result to a variable, that's the crucial part of the problem i think, and it hangs

**Comment by WindSoilder** [comment] 2023-03-04 15:29
Sorry, I believe https://github.com/nushell/nushell/pull/8204 is the one to blame..

**Closed** 2023-03-16 18:07 UTC
Labels: enhancement, external-commands, unhelpful-error
