### ISSUE TITLE
Table mode doesn't change for `nu -c 'let-env config = { table_mode: light }; ls'`

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5278] opened 2022-04-21 09:26 UTC
### Describe the bug

Table mode doesn't change for `nu -c 'let-env config = { table_mode: light }; ls'`

### How to reproduce

Run `nu -c 'let-env config = { table_mode: light }; $env.config; ls'`

### Expected behavior

The output should be the same as running: `let-env config = { table_mode: light }; $env.config; ls`

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.61.1                                         |
| branch             | main                                           |
| tag                |                                                |
| short_commit       | ded9d1ce                                       |
| commit_hash        | ded9d1cedb1808fb91b0b6f2f8dea5035b5183a9       |
| commit_date        | 2022-04-21 00:08:12 +00:00                     |
| build_os           | macos-x86_64                                   |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)            |
| rust_channel       | stable-x86_64-apple-darwin                     |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)            |
| pkg_version        | 0.61.1                                         |
| build_time         | 2022-04-21 09:48:36 +08:00                     |
| build_rust_channel | release                                        |
| features           | dataframe, default, trash, which, zip          |
| installed_plugins  | gstat, query, query json, query web, query xml |

**Comment by jntrnr** [comment] 2022-04-21 10:09
This is currently by design, as the config only changes after evaluation. It's really only intended to be used during repl as neither -c commands and script don't use the config.

If we feel like this isn't good enough, we should do a bit more design work.

**Comment by hustcer** [comment] 2022-04-21 11:11
@jntrnr Is there a workaround ? If the answer is no, maybe we have to polish it. Or make `let-env config = {...}` and `let $config = {...}` both work?
It's quite often to customize the config in scripts, and make the user experience better, too.

**Comment by fdncred** [comment] 2022-04-21 11:25
We probably won't be adding `let config` back again because it was changed due to performance related issues. If `nu -c` doesn't even read the config at all, I'm not sure how this could work. I guess it's theoretically possible to read the config file with nu -c but I'm not sure if there are an ramifications to doing that.

**Comment by panicbit** [comment] 2022-05-02 16:46
I have run into this as well when I tried to output some tabular data more nicely from a script.
Maybe a tool to explicitly format a table to a string would be useful to cover this specific use-case? Think `date format` but for tables :smile:.

**Comment by fdncred** [comment] 2022-05-02 18:00
theoretically we could also have a `--table-format` nu command line argument. I'm not sure what is better myself.

1. expose config to nu -c
2. have nu -c bah --table-format light
3. whatever date format for tables is - lol
4.

**Comment by mdfinvia** [comment] 2022-05-04 19:24
To elaborate a bit on the "date format for tables", I imagine something like:

```
> [[foo bar]; [a b] [c d]] | table format basic --corners o --hbar ~ --vbar ┋ --no-indices

o~~~~~+~~~~~o
┋ foo ┋ bar ┋
+~~~~~+~~~~~+
┋ a   ┋ b   ┋
+~~~~~+~~~~~+
┋ c   ┋ d   ┋
o~~~~~+~~~~~o
```

Just don't make me responsible for coming up with a good cli :stuck_out_tongue:.
The important point being that the command is not affected by the `table_mode` config and thus the code is in control of the exact rendering of the table.

**Comment by panicbit** [comment] 2022-05-04 19:27
To elaborate a bit on the "date format for tables", I imagine something like:

```
> [[foo bar]; [a b] [c d]] | table format basic --corners o --hbar ~ --vbar ┋ --no-indices

o~~~~~+~~~~~o
┋ foo ┋ bar ┋
+~~~~~+~~~~~+
┋ a   ┋ b   ┋
+~~~~~+~~~~~+
┋ c   ┋ d   ┋
o~~~~~+~~~~~o
```

Just don't make me responsible for coming up with a good cli :stuck_out_tongue:.
The important point being that the command is not affected by the `table_mode` config and thus the code is in control of the exact rendering of the table.

**Comment by fdncred** [comment] 2022-05-04 19:51
> To elaborate a bit on the "date format for tables"
oh, i see what you mean. it's really a user-specified table theme.

This is what table themes look like now
```rust
pub struct Theme {
    pub top_left: char,
    pub middle_left: char,
    pub bottom_left: char,
    pub top_center: char,
    pub center: char,
    pub bottom_center: char,
    pub top_right: char,
    pub middle_right: char,
    pub bottom_right: char,
    pub top_horizontal: char,
    pub middle_horizontal: char,
    pub bottom_horizontal: char,
    pub left_vertical: char,
    pub center_vertical: char,
    pub right_vertical: char,

    pub separate_header: bool,
    pub separate_rows: bool,

    pub print_left_border: bool,
    pub print_right_border: bool,
    pub print_top_border: bool,
    pub print_bottom_border: bool,
}
```
and here's an example of the `basic` theme
```rust
    pub fn basic() -> Theme {
        Theme {
            top_left: '+',
            middle_left: '+',
            bottom_left: '+',
            top_center: '+',
            center: '+',
            bottom_center: '+',
            top_right: '+',
            middle_right: '+',
            bottom_right: '+',
            top_horizontal: '-',
            middle_horizontal: '-',
            bottom_horizontal: '-',
            left_vertical: '|',
            center_vertical: '|',
            right_vertical: '|',

            separate_header: true,
            separate_rows: true,

            print_left_border: true,
            print_right_border: true,
            print_top_border: true,
            print_bottom_border: true,
        }
    }
```

i think that's a cool idea. i'm just not sure how to pass all the mess needed in the theme struct.

**Comment by panicbit** [comment] 2022-05-04 20:22
I could see this passed as a single record parameter, especially since this would not be intended to be used in a REPL context, however, even in a script context, that structure looks very verbose (albeit flexible).

**Comment by hustcer** [comment] 2022-05-11 10:48
Can anyone fix this issue first? Thx

**Closed** 2022-05-11 21:15 UTC
Labels: enhancement, priority
