### ISSUE TITLE
`glibc` version too damn high?

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#7282] opened 2022-11-29 19:42 UTC
### Describe the bug

```
nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by nu)
nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by nu)
nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by nu)
```

The `glibc` version on current Debian 11 Bullseye (stable) is [2.31](https://packages.debian.org/bullseye/libc6).

Which means, the most recent version of `nu` cannot be installed through the officially recommended ways without unrecommended & potentially risky hacks to the system.

I've seen other issues like this before.

https://github.com/nushell/nushell/issues/3825
https://github.com/nushell/nushell/issues/3737

Usually, they could be fixed by upgrading the system's packages.
In this case, it does not seem possible, without issues.

### How to reproduce

1. Run Debian 11 Bullseye (stable, as of now).
2. `apt update && apt upgrade -y`
3. Still, `nu` won't run.

### Expected behavior

Continues to run on popular GNU/Linux distribution, even after an upgrade.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:00:26 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | partial                                         |

### Additional context

**Platform**
Debian GNU/Linux 11 (bullseye) in WSL2 on Windows 10

**Terminal software**
Windows Terminal

Nushell is running "natively" as a login shell.

____

I don't know, whether this is acceptable or not. Though, I had the impression that support for major operating systems in their currently most popular/recent edition is significant to this project's goals.

**Comment by rgwood** [comment] 2022-11-29 20:39
Hmm, not ideal. I suspect the root cause is that [GitHub changed their `ubuntu-latest` runners to use Ubuntu 22.04](https://github.com/actions/runner-images/issues/6399).

It looks like our 0.71 release was built on Ubuntu 20.04.5 and 0.72 was built on 22.04.1.

I'm not an expert in this area and I'm not sure what the best course of action is. We could pin our GitHub runners to `ubuntu-20.04` but maybe there's a better way?

**Comment by sholderbach** [comment] 2022-11-29 20:42
From which source did you pull this build?

I can still build and run on Ubuntu 20.04 LTS with `cargo install nu` 

```
> ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

**Comment by theAkito** [comment] 2022-11-29 20:44
I always do a `fetch` from Github and just `mv nu* /usr/bin`. I usually do it anyway, but for this project, the official documentation says, that this is the build with all or at least most features enabled, which means I must be using the recommended way of installation.

**Comment by rgwood** [comment] 2022-11-29 20:45
@sholderbach I _think_ the problem occurs when building on 22.04 and then running the binaries on 20.04.

Over on Discord someone reported the same issue https://discord.com/channels/601130461678272522/614593951969574961/1047245388068950026

**Comment by theAkito** [comment] 2022-11-29 20:46
That should be it. It's linked with a recent version on build and then it possibly might not run on older versions. Especially Debian is known for being slow.

**Comment by sholderbach** [comment] 2022-11-29 20:48
Ah that's a bummer. Thanks for sleuthing @rgwood. I was following the red herring of the recent minimum [glibc bump for the core rustc defaults](https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html) but they only increased to 2.17.

**Comment by rgwood** [comment] 2022-11-29 20:54
For now I think the easiest workarounds is to use the precompiled musl build. Or [compile Nu locally using Cargo](https://www.nushell.sh/book/installation.html#build-using-crates-io).

**Comment by rgwood** [comment] 2022-11-29 21:11
`extra` no longer does anything meaningful ([just merged the docs update](https://github.com/nushell/nushell.github.io/pull/679)).

If you want dataframe commands you can do `--features=dataframe`. If you want to statically link OpenSSL you can do `--features=static-link-openssl`. For both you can do `--all-features`.

**Comment by hustcer** [comment] 2022-11-30 07:51
[setup-nu](https://github.com/hustcer/setup-nu) failed for nu v0.72: 
https://github.com/hustcer/setup-nu/actions/runs/3581284227/jobs/6024177325
```
Run $'Nu version info:(char nl)'; version
  $'Nu version info:(char nl)'; version
  shell: /opt/hostedtoolcache/nushell/0.7[2](https://github.com/hustcer/setup-nu/actions/runs/3581284227/jobs/6024177325#step:4:2).0/x64/nu {0}
/opt/hostedtoolcache/nushell/0.72.0/x64/nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.[3](https://github.com/hustcer/setup-nu/actions/runs/3581284227/jobs/6024177325#step:4:3)[4](https://github.com/hustcer/setup-nu/actions/runs/3581284227/jobs/6024177325#step:4:5)' not found (required by /opt/hostedtoolcache/nushell/0.72.0/x64/nu)
/opt/hostedtoolcache/nushell/0.72.0/x64/nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/hostedtoolcache/nushell/0.72.0/x64/nu)
/opt/hostedtoolcache/nushell/0.72.0/x[6](https://github.com/hustcer/setup-nu/actions/runs/3581284227/jobs/6024177325#step:4:7)4/nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/hostedtoolcache/nushell/0.[7](https://github.com/hustcer/setup-nu/actions/runs/3581284227/jobs/6024177325#step:4:8)2.0/x64/nu)
Error: Process completed with exit code 1.
```

**Comment by hustcer** [comment] 2022-12-01 02:02
"so the easiest solution here is to explicitly specify ubuntu-20.04" 
REF: https://github.com/actions/runner-images/issues/6647

**Closed** 2022-12-01 02:44 UTC
Labels: build-package

**Comment by hustcer** [comment] 2022-12-01 02:45
Feel free to open if this issue still exists in the next nu release: v0.73
