### ISSUE TITLE
nushell requires a too recent glibc for Ubuntu 18.04

### ISSUE THREAD

**Issue by dckc** [nushell/nushell#1786] opened 2020-05-14 20:14 UTC
I just tried to install and use nushell but dynamic linking with libc fails.

1. install nu_0_14_0_linux.tar.gz (I also tried nu_0_13_0_linux.tar.gz): download, unpack
2. try to start: `./nu_0_14_0_linux/nushell_0_14_0/nu`
3. blammo:

```
$ ./nu_0_13_0_linux/nushell_0_13_0/nu
./nu_0_13_0_linux/nushell_0_13_0/nu: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./nu_0_13_0_linux/nushell_0_13_0/nu)
./nu_0_13_0_linux/nushell_0_13_0/nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./nu_0_13_0_linux/nushell_0_13_0/nu)
```

**Expected behavior**
nushell starts

**Configuration (please complete the following information):**
 - OS: ubuntu linux
 - Version 18.04
 - Optional features (if any)

seems to be a known issue with building rust: https://github.com/rust-lang/rust/issues/57497
"you'll need to build things on an older distro, and that's what we do for rustup"

**Comment by dckc** [comment] 2021-06-24 20:18
On behalf of the 5 others who endorsed this issue, please keep it open.

**Comment by fdncred** [comment] 2021-07-23 13:09
I'm going to close this in favor of #3737 just because there is more info there too. it's a dupe of this issue.

**Closed by fdncred** 2021-07-23 13:09 UTC
Labels: bug, platform-support
