### ISSUE TITLE
Flickering command prompt when using Windows Terminal (Windows 10)

### ISSUE THREAD

**Issue by konsuko** [nushell/nushell#7714] opened 2023-01-10 08:50 UTC
### Describe the bug

I am on Windows 10, using the latest version of Windows Terminal (1.15.3465.0)
When in nushell and inputting any characters, the entire command prompt line flickers on each input.

[Here is a video (imgur.com) that illustrates the issue
](https://imgur.com/ZWEgVmH)

### How to reproduce

1. Start Windows Terminal on Windows 10
2. Enter nushell
3. Input any characters

### Expected behavior

I expected nu to not flicker on every input.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             | fix_wix_save                             |
| commit_hash        | cbb812bda6e249c8a106428039501a0157c5a1ea |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-21 07:39:03 -06:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by rgwood** [comment] 2023-01-10 09:22
Hi, thanks for the bug report. This is a dupe of https://github.com/nushell/nushell/issues/6214.

The underlying Windows Terminal issue (please upvote): https://github.com/microsoft/terminal/issues/13710

**Closed by rgwood** 2023-01-10 09:22 UTC
