### ISSUE TITLE
The history is not persisted upon `kill -TERM`

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#8083] opened 2023-02-15 11:45 UTC
### Describe the bug

If `config.history.sync_on_enter == false`, the shell must be closed only via `C-d` for the history to persist. All other ways to terminate the shell abandon the history:
1. Closing the terminal window (running nu in alacritty)
2. Killing via `^kill -HUP`
3. Killing via `^kill -TERM`
4. Terminating a tmux/zellij session (I suspend they both send TERM)

### How to reproduce

1. Launch the shell
2. Terminate the shell in a way other than `C-d`

### Expected behavior

The history should be updated when the shell terminates in a way other than SIGKILL

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by sholderbach** [comment] 2023-02-15 12:06
Duplicate of #7790

**Closed** 2023-02-15 12:47 UTC
