### ISSUE TITLE
Built-in `rm` and `mv` cannot handle files with `[` in their name without escaping

### ISSUE THREAD

**Issue by kik4444** [nushell/nushell#9790] opened 2023-07-24 13:07 UTC
### Describe the bug

Built-in `rm` cannot delete files with `[` in their name. Doesn't matter if I use double, single quotes or backticks.  Meanwhile `mkdir`, `rmdir`, `touch` do not have a problem with brackets.

However if a file only has a closing bracket `]` there's no problem with `rm`.

### How to reproduce

```
touch `[hello]` # both brackets
rm `[hello]` # fails
rm '[hello]' # fails
rm "[hello]" # fails

Error:   × File(s) not found
   ╭─[entry #36:1:1]
 1 │ rm `[hello]` 
   ·    ────┬────
   ·        ╰── File(s) not found
   ╰────
```
```
touch `[hello` # left bracket
rm `[hello` # fails
rm '[hello' # fails
rm "[hello" # fails

Error:   × Pattern syntax error near position 81: invalid range pattern
   ╭─[entry #38:1:1]
 1 │ rm `[hello` 
   ·    ────┬───
   ·        ╰── Pattern syntax error near position 81: invalid range pattern
   ╰────
```
```
touch `hello]` # right bracket
rm `hello]` # works
```

```
mkdir `[hello` # directory
rmdir `[hello` # works
```

### Expected behavior

`rm` should work consistently 

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.82.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | ecdb023e2f6cb17445ae799206e464b2daef3d71                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1) |
| cargo_version      | cargo 1.70.0                                                     |
| build_time         | 2023-06-28 05:27:55 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

Also autocompleting with tab on a file with brackets does not quote it with backticks, but that may be a separate issue.

**Comment by fdncred** [comment] 2023-07-24 13:39
This is because most of our file io commands can use glob patterns and `[]` are valid glob patterns. We'd love to have this fixed. It may be as easy as switching out `glob_with` here 
https://github.com/nushell/nushell/blob/9db0d6bd34a99805c6da296688aa186778be5a86/crates/nu-command/src/filesystem/rm.rs#L266-L267
to use `glob_from` in a similar way that `ls` does, but I'm not positive.
`ls`
https://github.com/nushell/nushell/blob/9db0d6bd34a99805c6da296688aa186778be5a86/crates/nu-command/src/filesystem/ls.rs#L165-L166

**Comment by mengsuenyan** [comment] 2023-07-29 08:30
@kik4444 

This is not the bug, just glob pattern is not valid, the file `[hello]` can be deleted by the `rm '[[]hello[]]'`. The `?`/`*`/`[`/`]` is meta characters, need to use `[meta-character]` to match these character.

The more detail documents can be referenced [nu_glob](https://docs.rs/nu-glob/latest/nu_glob/struct.Pattern.html)

@fdncred 


- ? matches any single character.
- * matches any (possibly empty) sequence of characters.
-  ** matches the current directory and arbitrary subdirectories. This sequence must form a single path component, so both **a and b** are invalid and will result in an error. A sequence of more than two consecutive * characters is also invalid.
-  [...] matches any character inside the brackets. Character sequences can also specify ranges of characters, as ordered by Unicode, so e.g. [0-9] specifies any character between 0 and 9 inclusive. An unclosed bracket is invalid.
-  [!...] is the negation of [...], i.e. it matches any characters not in the brackets.
- The metacharacters ?, *, [, ] can be matched by using brackets (e.g. [?]). When a ] occurs immediately following [ or [! then it is interpreted as being part of, rather then ending, the character set, so ] and NOT ] can be matched by []] and [!]] respectively. The - character can be specified inside a character sequence pattern by placing it at the start or the end, e.g. [abc-].


May be the glob pattern syntax need to add in the book [nushell book](http://www.nushell.sh/book/)

**Comment by fdncred** [comment] 2023-07-29 13:00
agreed, it should be added to the book. but i also agree that it's a hassle, but at least it's a way forward.

**Comment by dedebenui** [comment] 2023-08-10 07:09
The missing quotes when auto-completing is #9884 

> The more detail documents can be referenced in the [nu_glob](https://docs.rs/nu-glob/latest/nu_glob/struct.Pattern.html)

I see there already is an `escape` function. Would it be possible to use it when tab-completing file names? Tab-completion is supposed to match an exact name, so it would make sense to systematically escape glob-specific characters.

Also would it be possible to expose it as a Nu command? A quick command like

```
ls | get name | each {|| mv $in $"new_($in)"}
```

will fail on file names that contain `[` or `[]`, so this is something that might be nice:

```
ls | get name | each {|| mv ($in | escape glob) $"new_($in)"}
```

`glob escape` would not work as a command name, even though it would be somewhat more consistent with `str trim` and `ansi strip`.

**Comment by mengsuenyan** [comment] 2023-08-11 02:06
> `glob escape` would not work as a command name, even though it would be somewhat more consistent with `str trim` and `ansi strip`.

You are right. This will modify the semantics of the function interface and require confirmation from the Nullshell team.
Perhaps the following methods can be used to temporarily avoid this issue first.

```nushell
ls | get name | each {|| let x = $in; let y = ($x | str replace -a '(?<eschar>[\[\]\?\*])' '[$eschar]'); mv $y $"new_($x)"}
```

And the `$in` works weird, for example:

```nushell
> mkdir test; cd test; touch '[hello]';
> ls | get name | each {|| print $in; let x = $in; print $"($x)"} 
> [hello]
> [[hello]]
# The expected output should be as follows:
> [hello]
> [hello]
```

**Comment by hardfau18** [comment] 2023-08-16 00:59
IMO glob expansion should not be done by command, it should be done while parsing, I think bash also does that similarly. Then make literal strings or string without quotes as glob expandable.

**Comment by fdncred** [comment] 2023-08-16 01:35
We'd accept a pr to help improve this area.

**Comment by amtoine** [comment] 2023-08-18 16:19
looks like a duplicate of https://github.com/nushell/nushell/issues/9310, thanks a lot @star-szr :pray:

**Comment by amtoine** [comment] 2023-08-18 16:19
## closing in favor of https://github.com/nushell/nushell/issues/9310

**Closed by amtoine** 2023-08-18 16:19 UTC
Labels: :bug:  bug, file-system, duplicate, glob-expansion
