### ISSUE TITLE
Ctrl + Z in editor will also trigger the nushell

### ISSUE THREAD

**Issue by yanganto** [nushell/nushell#2091] opened 2020-07-02 16:34 UTC
**Describe the bug**\
A signal trigger in editor will also trigger on nushell

**To Reproduce**
1.  start in zsh
2. use nushell by following command `nu`
3. open a file with neovim by following command `nvim /tmp/test_file`
4. press `ctrl` + `Z` in neovim to suspend the editor to go back to shell
5. now in zsh but not nushell

**Expected behavior**
1.  start in zsh
2. use nushell by following command `nu`
3. open a file with neovim by following command `nvim /tmp/test_file`
4. press `ctrl` + `Z` in neovim to suspend the editor to go back to shell
5. **back to nushell**

I have tested the scenario to exchange nushell and zsh, and everything is well as expected.

**Configuration (please complete the following information):**
 - OS: Archlinux
 - Nu version:  0.15.0
 - Optional features: no

I try to use nushell daily and want to instead of zsh, and I find out some very corner case.  I am also willing to help if this issue is good for the first issue.  :)

**Comment by Knarkzel** [comment] 2020-07-02 18:12
Add `nu` in your zshrc, or zsh config file. This way, whenever zsh is launched, nu is then launched. This issue occurs with any shell launched like nushell.

**Comment by yanganto** [comment] 2020-07-03 01:28
Yup, this use case is not usual.  

I do this because I hope that if I got some trouble in nushell,  I can Ctrl + d then quick back to the shell I am familiar with.

Besides,  I test a similar scenario to call bash in zsh, then try to Ctrl + z in an editor, it will back to bash.  It works fine.

I will try to use nushell as a login shell to avoid this problem.

**Comment by Catstyle** [comment] 2022-04-09 17:04
mark, i'm facing the same issue, looking for a solution

**Comment by hustcer** [comment] 2022-05-11 10:54
Maybe a dupe of https://github.com/nushell/nushell/issues/4104

**Comment by jntrnr** [comment] 2023-08-09 18:58
Closed as dupe of https://github.com/nushell/nushell/issues/1038

**Closed by jntrnr** 2023-08-09 18:58 UTC
Labels: signal-cancel
