### ISSUE TITLE
No way to set no-color for non-ansi terminals.

### ISSUE THREAD

**Issue by AstoriaFloyd** [nushell/nushell#4096] opened 2021-10-25 19:37 UTC
### Describe the bug

On non-ansi terminals, such as 9term, the output is quite garbled, filled with ANSI escape codes. sed-ing out these escape codes almost makes it workable, making command output quite visible, but things such as any text input is completely invisible. Looking around there may be already a way to get it to function, it simply requires being a tty... which is a bit hard to do, when not a tty.

### How to reproduce

Install plan9port
Use 9term

### Expected behavior

I did not really expect this to work, but its so close to working I decided to ask about if it could be fixed.

### Additional context

9term also does not support cursor addressing, and that might be part of the problem.

**Comment by captain-yossarian** [comment] 2021-11-23 19:22
Hi, if anybody will provide me with a start point I can grab it

**Comment by fdncred** [comment] 2021-11-23 22:04
If you search for tty in the repo you'll probably see where this change was. It has to do with using ansi strip before outputting text. You may need to put something in autoview. Ping me again if you can't find it.

**Comment by captain-yossarian** [comment] 2021-11-25 20:26
@fdncred as far as I understood, I need Linux in order to reproduce this bug. If yes - unfortunately I can't do it (

**Comment by fdncred** [comment] 2021-11-25 21:32
You can reproduce without Linux. They key to the solution here is having some type of nushell switch or configuration point to disable ansi output i.e. there will be no coloring. Just white text and lines on a black background.

**Comment by captain-yossarian** [comment] 2021-11-26 19:55
>>If you search for tty in the repo you'll probably see where this change was.
@fdncred do you mean [this commit](https://github.com/nushell/nushell/commit/d3958169290eb6f35a034e84950e38cd98d36b42) ?

**Comment by captain-yossarian** [comment] 2021-11-26 20:04
@AstoriaFloyd could you please provide me with screenshot where colors need to be fixed? I'm very new to the project, I want to do all my best but for now I understand nothing :)

**Comment by fdncred** [comment] 2021-11-27 00:30
> @fdncred do you mean this d395816 ?

Yes, that's the one I was thinking of.  I'm not sure exactly what is needed to be done but I figured this was a good starting place to start looking.

> Do you mean to strip also rows and headers ?

yes, that's what i was thinking. I think it would be easier to just strip the color toward the final step than to setup everything so it doesn't draw in colors everywhere else.

**Comment by captain-yossarian** [comment] 2021-11-27 19:02
@fdncred could you please provide me with information how I can test my changes ?
For instance, I have added several logs and I dont see them. 
**Thank you for your time and patience.** 

P.S. I've read Contribution guide and book. 
 I'm not familiar with this repo, I just was looking for Rust contributions.

**Comment by fdncred** [comment] 2021-11-28 22:16
> @fdncred could you please provide me with information how I can test my changes ?

you do a `ls` and if there are no colors except black (terminal background) and gray (terminal foreground) then you probably have achieved success. I think it another thing that would work is to do `nu -c 'ls' | save foo` from inside of nushell. i think the file `foo` would not have ansi escapes, at least it doesn't in my testing. so your output should look like this output.

theoretically you can have ansi black and ansi gray and it will look right but not be right. i'm not sure how to show the escapes right now. i've done it before but can't remember how.

**Comment by captain-yossarian** [comment] 2021-12-04 09:22
I know that I need to make my changes either here: _crates\nu-table\src\main.rs_ or here: _crates\nu-table\src\table.rs_, or both.
Seems to be that I'm missing something. After making change I run `cargo build && cargo start` and I don't see my changes. What I'm doing wrong?

**Comment by fdncred** [comment] 2021-12-04 19:38
i'm not familiar with `cargo start` - I just typically do `cargo run` or `cargo build --features=extra` and then run it out of the target/debug folder.

**Comment by fdncred** [comment] 2022-03-12 16:00
We support a no color option now. You can test it out with this command `let config = ($config | update use_ansi_coloring false)`. Closing.

**Closed by fdncred** 2022-03-12 16:00 UTC
Labels: good first issue
