### ISSUE TITLE
$env does not apply in some situations where it should

### ISSUE THREAD

**Issue by dupdrop** [nushell/nushell#10175] opened 2023-08-31 17:16 UTC
### Describe the bug

The following snippet is expected to set `$env.config.table.mode = none` for the scope of the `do` block:

```nu
# either this
do { $env.config.table.mode = none; ls }

# or this
with-env {config: {table: {mode: none}}} { ls }
```

In practice `ls` here is not working as expected, it does not use the 'none' configuration.

Replacing `ls` with `print (ls)` does print the expected results, but I don't understand why.

Replacing `ls` with `echo $env.config.table.mode` does print the expected result (`none`).

In addition, but not exactly related: The output of `table --help` for `table --list` does not tell you where/how you can use the
results from `table --list`. Especially since I just wanted to test it ad-hoc and not actually change my `config.nu` (The mode setting there looks pretty obvious, but I didn't even look there)

### How to reproduce

1. Run `do { $env.config.table.mode = none; ls }`
2. See the outputted table is not shown in the expected mode/theme.

### Expected behavior

I expect nu to use the set configuration inside the `do` block.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.84.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08) |
| build_time         | 2023-08-26 17:04:51 +03:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by fdncred** [comment] 2023-08-31 17:20
ya, seems like this should work 
```nushell
with-env [ $env.config.table.mode none ] { print $env.config.table.mode }
```
We'd accept a PR to fix this.

**Comment by dupdrop** [comment] 2023-08-31 17:42
@fdncred, in your example `$env.config.table.mode` is basically treated as a single string. According to the docs, `$env` is not expected here.

```nu
> $env.config.table.mode = rounded
> with-env [ config.table.mode none ] { print $env.config.table.mode }
rounded
> with-env [ config.table.mode none ] { print $env."config.table.mode" }  # <-- notice the quotes
none
```

In my initial example using `with-env`, I set it using a dictionary to avoid this. But then there is the actual issue imo, that it didn't apply then, even when it was set.

**Comment by kubouch** [comment] 2023-08-31 18:10
Errors like this are caused by fetching the config during evaluation using `engine_config.get_config()` which is not correct because it doesn't take into account the latest environment updates. Instead, `nu_engine::env::get_config()` should be used. I fixed a similar issue in https://github.com/nushell/nushell/pull/9353.

**Comment by JordanllHarper** [comment] 2023-09-03 19:11
I'd like to pick this up

**Comment by JordanllHarper** [comment] 2023-09-03 19:30
So looking at occurrences in the code, I couldn't find any of `engine_config.get_config()` but I see occurrences regarding `engine_state.get_config()`. Is it these occurrences that need changing? 
Apologies if I'm misunderstanding, new to this codebase.

**Comment by kubouch** [comment] 2023-09-03 19:33
@JordanllHarper Cool, go ahead! Yes, I meant `engine_state.get_config()`.

Just quickly scanning, the `table` command responsible for printing the data already has the `get_config()` fix applied, but you might be able to find the cause elsewhere, perhaps https://github.com/nushell/nushell/tree/main/crates/nu-table.

**Comment by JordanllHarper** [comment] 2023-09-15 18:09
Okay been giving this a go and I can't find the issue with this. I think it might be something to do with the do command but as a newcomer to the project I can't be sure. Wondering if I can pass this on to someone else?

**Comment by fdncred** [comment] 2023-09-15 18:24
No worries @JordanllHarper. I unassigned you. Thanks for trying!

**Comment by cosineblast** [comment] 2023-11-04 14:37
I'll give it a try, sounds fun to work on

**Comment by fdncred** [comment] 2023-11-04 14:39
It's yours @cosineblast. Have fun!

**Comment by kubouch** [comment] 2023-11-04 15:27
There was some work on it and simply replacing the `get_config()` calls might incur some performance issues due to cloning the Config. See also https://github.com/nushell/nushell/pull/10483.

**Comment by cosineblast** [comment] 2023-11-05 14:48
After some debugging I'm starting to suspect that the display_output hook is just not honoring any $env modifications, I'll confirm it once I get home

**Comment by cosineblast** [comment] 2023-11-05 17:16
Alright, this is not as simple as it seems. Commands in nushell don't print things to stdout, like in other shells; they're just  functions and all they do return is data. The data itself is only printed to stdout when it reaches the repl, so something like.

```
do { ls; ls; ls; () } 
``` 

Won't actually print anything, as the return of the do statement is `()`, and the `ls` commands are just being unused.

This behavior of nushell manifests itself in `do { $env.config.table.mode = none; ls }`, because the `ls` command is not really printing anything, just returning the data. The `table` command runs *after* the closure finishes executing and after the do returns. This is not exactly a bug, just something very non intuitive. As a workaround, one can do something like

```
do { $env.config.table.mode = none; ls | cat }
```
which will convert the data returned to a table while the environment variable is still set, showing us the intended output.

I think the best thing to do in this situation is to document this 'gotcha' in the `Pipelines` chapter of the nushell book.

**Comment by amtoine** [comment] 2023-11-05 17:43
@cosineblast 
wow, that's very interesting :open_mouth: 
i could fix it as well with `| table` :+1: 

i guess the best would be to fix this issue, for sure, but at least having it mentionned somewhere might be great as a quick fix :thinking:

**Comment by cosineblast** [comment] 2023-11-08 00:35
Also, I believe this issue should not be labelled as a 'good first issue' as it involves some semantics of the language (return vs stdout).

**Comment by kubouch** [comment] 2023-11-08 11:59
True, it has some non-trivial implications that got revealed over time.

**Comment by amtoine** [comment] 2023-11-08 17:24
the question is still have is: should the following be considered a bug?
```nushell
> do { $env.config.table.mode = none; ls }
#┬──name───┬type┬─size──┬─────modified──────
0│LICENSE  │file│35.1 KB│2023-10-31 17:14:51
1│README.md│file│11.8 KB│2023-11-06 12:26:58
2│documents│dir │ 4.1 KB│2023-10-31 17:09:28
3│downloads│dir │ 4.1 KB│2023-10-31 18:26:00
4│media    │dir │ 4.1 KB│2023-11-06 12:24:48
─┴─────────┴────┴───────┴───────────────────
```

**Comment by kubouch** [comment] 2023-11-08 17:31
It feels counter-intuitive, but IMO it shouldn't. You're sending a value from the `do` block, but the config changes are applied only inside the block.

**Comment by amtoine** [comment] 2023-11-08 17:33
now that i understand what's going on, yeah i can live with that being a feature :yum: 


the one with
```nushell
with-env {config: {table: {mode: none}}} { ls }
```
sounds like it should work though :thinking:

**Comment by kubouch** [comment] 2023-11-08 20:55
It shouldn't because you're again trapping the env changes inside the block and returning a value from it, it's the same case as `do`.

**Comment by amtoine** [comment] 2023-11-08 21:04
> It shouldn't because you're again trapping the env changes inside the block and returning a value from it, it's the same case as `do`.
>
ooh yeah you're right :open_mouth: 

then we can close this issue, right? :thinking:

**Comment by kubouch** [comment] 2023-11-08 22:14
OK, let's close this. The get_config() or changing the config in general are another topics.

**Closed by kubouch** 2023-11-08 22:14 UTC
Labels: :bug:  bug, configuration, tabled
