### ISSUE TITLE
can't reproduce in script what I can do in terminal

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#7728] opened 2023-01-11 18:44 UTC
### Describe the bug

I'm doing this in a script:
```
mut new_keybinds = []

##alias
$new_keybinds = (
    $new_keybinds 
    | append ({
          name: alias_menu
          modifier: alt
          keycode: char_a
          mode: [emacs, vi_normal, vi_insert]
          event: { 
              send: menu,
              name: alias_menu 
          }
    })
)
```
That works when testing in terminal, but when I run the script I got:
```
Error: nu::shell::type_mismatch(link)                                                                                 

  × Type mismatch.
     ╭─[nu_config.nu:125:1]
 125 │         $new_keybinds 
 126 │ ╭─▶     | append ({
 127 │ │           name: alias_menu
 128 │ │           modifier: alt
 129 │ │           keycode: char_a
 130 │ │           mode: [emacs, vi_normal, vi_insert]
 131 │ │           event: { 
 132 │ │               send: menu,
 133 │ │               name: alias_menu 
 134 │ │           }
 135 │ ├─▶     })
     · ╰──── int or range
 136 │     )
     ╰────
```

### How to reproduce

already explained

### Expected behavior

it should work in both places

### Configuration

| key                | value                                                                                              |
| ------------------ | -------------------------------------------------------------------------------------------------- |
| version            | 0.74.0                                                                                             |
| branch             | main                                                                                               |
| commit_hash        | 206a6ae6c9144645119fd664e773b670c1bb8f81                                                           |
| build_os           | linux-x86_64                                                                                       |
| build_target       | x86_64-unknown-linux-gnu                                                                           |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)                                                                |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu                                                                    |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)                                                                |
| pkg_version        | 0.74.0                                                                                             |
| build_time         | 2023-01-11 10:26:33 -03:00                                                                         |
| build_rust_channel | release                                                                                            |
| features           | database, dataframe, default, trash, which, zip                                                    |
| installed_plugins  | custom-value generate, custom-value generate2, gstat, inc, query, query json, query web, query xml |

### Additional context

it was working in 0.73

**Comment by fdncred** [comment] 2023-01-11 19:28
oh, wow. if it was working, we should be able to `git bisect` it to see what PR broke it.

**Comment by fdncred** [comment] 2023-01-11 19:31
I can't reproduce this with your example. I put it in a file called `foo.nu` and i did `nu foo.nu` and there was no error. Then I did `source foo.nu` and there was no error. Any ideas?

**Comment by kurokirasama** [comment] 2023-01-11 19:32
I just realice that the error is actually later in the script, but the error message shows it there... I'm going trough it now

**Comment by fdncred** [comment] 2023-01-11 19:44
ok, let's close this for now then. please re-open it if you still have issues with mutability.

**Closed by fdncred** 2023-01-11 19:44 UTC
Labels: :bug:  bug, regression
