### ISSUE TITLE
error from alias -  "known external name not found"

### ISSUE THREAD

**Issue by PThorpe92** [nushell/nushell#11110] opened 2023-11-20 14:43 UTC
### Describe the bug

Hey guys, first just want to say thanks and I love the project!

Was attempting to reproduce an `eza` bug from an issue and needed to change my 'ls' alias. I opened my config.nu and made one small change, only to the line with my `eza` alias.
(the change was trivial and probably irrelevant to the issue)

but upon running `source ~/.config/nushell/config.nu`

and then executing `ls` I received the following error message: 
```Error: nu::shell::nushell_failed_spanned
  × Nushell failed: known external name not found.
   ╭─[entry #101:1:1]
help: this shouldn't happen, please file an issue
```

### How to reproduce

After seeing the 

`this shouldn't happen - please report an issue`

I wanted to report it even if ended up being something that was quickly fixed by running `source` again.

In fact, I changed my 'ls' alias ever so slightly again, and ran `source` and this problem went away, 
I did notice a bug in `eza` where it's not respecting an argument for the `--color-scale-mode` flag if a `=` is used in place of a ' ' between the flag and the argument. 

Although my config previously had used an `=`, (and I didn't change it) running source again caused that error show up.

It's likely that `eza` threw an error and instead of reporting the error I was presented with that `nushell` error message.

### Expected behavior

It's likely, anyway: that I expected to see the error that I am now getting:

```
eza: Option --color-scale-mode has no "--grid" setting (choices: fixed, gradient)
```

(error message is kind of irrelevant, but anyway this is the error I'm now getting when I have the argument with key=value

### Screenshots

![image](https://github.com/nushell/nushell/assets/121899304/ba57efaf-8d8d-4333-89dd-831d7481ad8d)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.86.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1) |
| cargo_version      | cargo 1.73.0                                                     |
| build_time         | 2023-10-18 08:45:09 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

Once again it seems likely that an error was thrown from `eza` from a bug that propagated when I `sourced` my config. It looks like I was given that nushell error instead of the eza error. I'm not sure why now, I'm able to get the error, and can't reproduce it.

Really only reporting because of the `this shouldn't happen, please report`.

Thanks again and lmk if there is any other info I can provide. :heart:

**Comment by amtoine** [comment] 2023-11-20 17:36
@PThorpe92 
thanks for reporthing bugs like this :pray: 

could you share the alias though? i'm not sure i see what the issue is here :thinking: 

also, could you try with Nushell 0.87.0? :innocent:

**Comment by PThorpe92** [comment] 2023-11-20 17:46
`alias ls = eza -lhA --color=always --group-directories-first --color-scale-mode=gradient --grid --icons --git --git-repos --color-scale all --no-user --no-permissions`

This was the alias before I touched it. (I have had a tmux session going for a few days now, so it's (very) possible that the new bug that causes an error from `--color-scale-mode=gradient` instead of `--color-scale-mode gradient`, hadn't manifested yet, and when I `source`'d the config, it caused the error to throw from `eza`

So the issue would essentially be that instead of having that error displayed, I was hit with that message instead of 
![image](https://github.com/nushell/nushell/assets/121899304/6c83e2b5-5b88-471c-bfb1-d1058676af02)


I tried, from another tmux window in the same session, do duplicate this.. and all I got was the above (correct) error message. So this is obv tricky to reproduce, but I will continue trying. Also I will update nushell as well.

**Comment by fdncred** [comment] 2023-11-20 18:00
I just tried the alias in the repl and it seems to work. I also put it in the last line of my config.nu and restarted without issues. I do like the way this looks too, very nice! Unfortunately, it won't work with `ls | do any pipeline thing here`.

Very weird. Thanks for reporting. It's going to be hard to nail down without a repro.

I'm using this version.
```
❯ eza --version
eza - A modern, maintained replacement for ls
v0.16.0 [+git]
https://github.com/eza-community/eza
```

**Comment by PThorpe92** [comment] 2023-11-20 18:33
@fdncred Heyy, I think you dropped by `eza` after we tried to migrate to `nu_ansi_term` if I'm not mistaken?... This is totally unrelated but do you guys have a matrix channel? I actually have been meaning to try and ask a couple questions about how you deal with width calc of ansi escape codes + unicode specifically surrounding hyperlinks which I noticed you were able to build into `nu_ansi_term`

So as far as the issue, `pacman -Syu` actually caused it so I can't even reproduce the original `eza` error. It really must have been a one-off, so this can prob just be closed.

**Comment by fdncred** [comment] 2023-11-20 19:15
> @fdncred Heyy, I think you dropped by eza after we tried to migrate to nu_ansi_term if I'm not mistaken?... 

I knew I recognized your github name. Yep, that was me dropping by.

We do not have an official matrix channel although we've been asked about it several time. It's hard enough to keep up with all the activity on discord.

> EDIT: Sorry I was hoping to be able to provide at least a little helpful information, if I would have known that both eza and nushell were behind a version I probably wouldn't have reported it, but just in case it was one of those cases where an error that shouldn't be thrown in any circumstance type of thing I figured it couldn't hurt. Thanks 👍

ya, no worries! I'm going to close this one out.

> nu-ansi-term stuff

Feel free to open a discussion or drop by our discord. I'll be around and try my best to help.

**Closed by fdncred** 2023-11-20 19:15 UTC
Labels: needs-triage
