### ISSUE TITLE
Bad `man` fallback handling in `std help`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13159] opened 2024-06-15 16:02 UTC
### Describe the bug

`std help` is pretty wonky right now when it doesn't find a result, and sometimes even when it does.

### How to reproduce

```nu
> use std help
> help ls
# happy case - Works and displays the proper help

> help asdf
Help pages from external command asdf:
No manual entry for asdf
Error:   × std::help::item_not_found
   ╭─[entry #5:1:6]
 1 │ help asdf
   ·      ──┬─
   ·        ╰── item not found
   ╰────
```

In the basic "not found" example, `std help` first tries to fallback to `man` to see if there is a man page for the requested item.  It therefore gives a bit of a "double error", with the `man` page error and the `item_not_found` error printing.

```nu
> help sed
# displays the sed man page ... then, when exiting man ...
Help pages from external command sed:
Error:   × std::help::item_not_found
   ╭─[entry #8:1:6]
 1 │ help sed
   ·      ─┬─
   ·       ╰── item not found
   ╰────
```

If it was found, even as a man page, then it shouldn't result in an error ...

```nu
> help shells
# Displays the man page for "shells" ... then, when exiting displays the alias help for shells->show
```

### Expected behavior

Not as much wonkyness.

If there are no objections, I'd like to remove the `man` page fallback code from `std help` for the moment.  While it's probably fixable, it's also platform specific and requires testing on all platforms.  It also seems like a low-value add here.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-06-10 14:29:01 -04:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | jwalk                                           |

**Comment by lpnh** [comment] 2024-06-17 16:20
Hm, I gave it a quick look, and I guess the issue is coming from the following line:

https://github.com/nushell/nushell/blob/3a6d8aac0bce6a70351fcfe860e0aa3694054a99/crates/nu-std/std/help.nu#L710

Here's what I observed while playing with it:

```
build-command-page ($found_command | get 0)
                                         ┬
                                         ╰── index too large (empty content)
```

**Comment by NotTheDr01ds** [comment] 2024-06-17 20:43
At first glance (haven't tested), that's still going to create an error on Windows, where there's no `man`, right?

**Comment by lpnh** [comment] 2024-06-17 21:37
> At first glance (haven't tested), that's still going to create an error on Windows, where there's no `man`, right?

Yes, and according to the original idea, this should indeed be an issue: https://github.com/nushell/nushell/issues/8032

However, looking at the PR that closed it, https://github.com/nushell/nushell/pull/9025, I think this would likely be considered (some sort of) expected behavior.

By the way, it seems that the "missing man" problem was discussed, but the suggestion to "check for it" never made it into the code: https://github.com/nushell/nushell/pull/9025#issuecomment-1535171021

**Comment by sholderbach** [comment] 2024-07-13 15:10
Yeah we should be more defensive here.

**Closed** 2024-11-27 01:29 UTC
Labels: :bug:  bug, good first issue, std-library, help-system
