### ISSUE TITLE
Two external commands in sequence is very slow

### ISSUE THREAD

**Issue by koenaad** [nushell/nushell#1356] opened 2020-02-07 22:25 UTC
**Describe the bug**
A chain of external commands that has to process a lot of lines is significantly slower than other shells. Each line spawns a new instance of the external command, causing a lot of overhead.

Additionally, it is not possible to kill this pipeline. I think CTRL+C kills an instance of the second command but the pipeline will just spawn a new one for the next line.

This is most likely an effect introduced by changes done in #1230.

**To Reproduce**
Run `find` in a directory of medium size, for instance `src/` of the nushell repository:

```
nushell/src on  master [$?] via 🦀 v1.41.0 
❯ find .
.
./format.rs
./stream.rs
./shell.rs
...
```
This should complete within an instant.

Now chain this with another external command:
```
nushell/src on  master [$?] via 🦀 v1.41.0 
❯ find . | grep 'from_'
./commands/from_bson.rs
./commands/from_xml.rs
./commands/from_tsv.rs
...
```

Running this pipeline with Nu, you'll see the result stream in.
Running this in another shell the result will be printed almost instantly.

**Expected behavior**
Chaining two external commands should not be significantly slower than in other shells.

So I'd propose to either:

1. Pass data between two external similar to bash: don't spawn a new process for each line, just stream it directly into the next process.
  If you wish to spawn a process per line you'd need to do this explicetely with `lines`:
  `❯ find . | lines | grep '.DS_Store'`

2. Stream data line-by-line, but offer a mechanism to avoid spawning a new process for each line

**Screenshots**
N/A

**Configuration (please complete the following information):**
Nu 0.9.0, built from master a couple of days ago.

**Comment by thegedge** [comment] 2020-02-08 00:25
We've been discussing this one a lot. We previously defaulted to the behaviour in (2), which I want to get us back to (was recently changed).

Even with (2), though, things can be very slow when there's a significant amount of data going through the pipe. We may eventually need to do something like (1), but that's an optimization we want to worry about later.

Just wanted to give you some more context before I close.

Duplicate of https://github.com/nushell/nushell/issues/1309

**Closed by thegedge** 2020-02-08 00:25 UTC

**Comment by koenaad** [comment] 2020-02-08 00:51
Ah, didn't see the other issues since I was searching for performance related stuff.

Thanks for the clarification @thegedge, this makes sense. I'll keep an eye on #1309.
