### ISSUE TITLE
parse output drops characters

### ISSUE THREAD

**Issue by jasonmader** [nushell/nushell#7071] opened 2022-11-09 20:57 UTC
### Describe the bug

On macOS Venture 13.0.1, with nushell 0.71, parse output doesn't contain all the characters.

### How to reproduce

1. tar -tvf update.tar | cut -c1-26 | parse -r '(?<mode>[ldrwx-]+)  (?<links>\d+) (?<owner>\w+)   (?<group>\w+)'

### Expected behavior

not drop characters

### Screenshots

```
╭────┬────────────┬───────┬───────┬───────╮
│  # │    mode    │ links │ owner │ group │
├────┼────────────┼───────┼───────┼───────┤
│  0 │ lrwxr-xr-x │ 0     │ root  │ wheel │
│  1 │ drwxr-xr-x │ 0     │ root  │ wheel │
│  2 │ -rw-r--r-- │ 0     │ root  │ wheel │
│  3 │ -rw-r--r-- │ 0     │ root  │ wheel │
│  4 │ -rw-r--r-- │ 0     │ root  │ wheel │
│  5 │ -rw-r--r-- │ 0     │ root  │ wheel │
│  6 │ -rw-r--r-- │ 0     │ root  │ wheel │
│  7 │ -rw-r--r-- │ 0     │ root  │ wheel │
│  8 │ -rw-r--r-- │ 0     │ root  │ wheel │
│  9 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 10 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 11 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 12 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 13 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 14 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 15 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 16 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 17 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 18 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 19 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 20 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 21 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 22 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 23 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 24 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 25 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 26 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 27 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 28 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 29 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 30 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 31 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 32 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 33 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 34 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 35 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 36 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 37 │ -rw-r--r-- │ 0     │ root  │ whee  │
│ 38 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 39 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 40 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 41 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 42 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 43 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 44 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 45 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 46 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 47 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 48 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 49 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 50 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 51 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 52 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 53 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 54 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 55 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 56 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 57 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 58 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 59 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 60 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 61 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 62 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 63 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 64 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 65 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 66 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 67 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 68 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 69 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 70 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 71 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 72 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 73 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 74 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 75 │ -rw-r--r-- │ 0     │ root  │ wh    │
│ 76 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 77 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 78 │ drwx------ │ 0     │ root  │ wheel │
│ 79 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 80 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 81 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 82 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 83 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 84 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 85 │ -rw-r--r-- │ 0     │ root  │ wheel │
│ 86 │ -rw-r--r-- │ 0     │ root  │ wheel │
├────┼────────────┼───────┼───────┼───────┤
│  # │    mode    │ links │ owner │ group │
╰────┴────────────┴───────┴───────┴───────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | macos-x86_64                                    |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:14:46 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by jasonmader** [comment] 2022-11-09 21:02
`tar -tvf update.tar | cut -c1-26 | parse -r '(?<mode>[ldrwx-]+)  (?<links>\d+) (?<owner>\w+)   (?<group>\w+)'`

**Comment by WindSoilder** [comment] 2023-01-24 01:13
Hi, I wonder is it because of `cut` rather than `parse` itself?
Create `tar` file through `touch a;tar -cvf tmp.tar a`

List tar files:
```
❯ tar -tvf tmp.tar
-rw-r--r--  0 chenhongze wheel       0 Jan 24 09:08 a
```

List with cut:
```
❯ tar -tvf tmp.tar | cut -c1-26
-rw-r--r--  0 chenhongze w
```

It's already drops characters

**Comment by WindSoilder** [comment] 2023-02-01 08:05
The issue is happened on the usage of `cut` command rather than `nu` itself, going to close it for now, feel free to reopen if you still have such issues

**Closed by WindSoilder** 2023-02-01 08:05 UTC
Labels: :bug:  bug, priority
