### ISSUE TITLE
Support legacy "single-hyphen" long argument for `extern`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13591] opened 2024-08-11 14:18 UTC
### Related problem

Just found this when working on `extern` doc. It's not really a problem for me personally right now, but it does limit some of the external commands that can be handled.

Attempting to use the Linux `find` binary as an example in the doc won't work, because `extern` can't handle its arguments, many of which use `-long` (instead of `--long`).

```nu
export extern "find" [
  -maxdepth: int
  -mindepth: int
  --help(-help)
]
```

Result:

```nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #4:2:3]
 1 │ export extern "find" [
 2 │   -maxdepth: int
   ·   ────┬────
   ·       ╰── expected short flag
 3 │   -mindepth: int
   ╰────
```

### Describe the solution you'd like

Some way to handle these (even if not standard `def` form).

**Comment by sholderbach** [comment] 2024-08-11 18:50
That's a really popular request.
Duplicate of #5959

**Closed by sholderbach** 2024-08-11 18:50 UTC
Labels: enhancement, needs-triage
